### ISSUE TITLE
Ogg recording is not supported when using AUDIO_VIDEO

### ISSUE THREAD

**Issue by v3ss0n** [collab-project/videojs-record#10]
Audio recording example in *Audio Only* works!
But at Audio-video example isChrome is become null and trows error. Tried Forced setting isChrome to True but
that makes video blank, and it gives "cant get videoblob url" Error.
 
```Request URL:http://localhost:8000/examples/null Request Method:GET Status Code:404 File not found```

**Comment by thijstriemstra** [comment]
It's only tested and working with audio-only right now. Recording both audio and video is normally done using RecordRTC, if you want to help out I suggest checking that source code and figuring out how to use an external encoder like libvorbis.js when recording audio and video.

For now I'll find out if the `isChrome` check is present in video.js as well so we can use that, and ill throw an error or log a warning when using libvorbis.js in a scenario other than audio-only.

**Comment by v3ss0n** [comment]
Thanks a lo t, i will check it how i can put that to work in RecordRTC!

**Comment by thijstriemstra** [comment]
Added an error for using libvorbis.js in any mode other than audio-only. Will release this as 0.9 now. Leaving this ticket open for discussion of audio/video mode with libvorbis.js.

**Comment by v3ss0n** [comment]
yeah that is good.

**Comment by thijstriemstra** [comment]
Since videojs-record 1.5.0 (and latest Firefox and RecordRTC.js) it should be possible to record with `audio/ogg` natively. Simply use the `audioMimeType: 'audio/ogg'` setting. Closing, please open a new ticket if it's not working.

**Comment by v3ss0n** [comment]
thanks a lot! does it work on chrome ?

**Comment by thijstriemstra** [comment]
@v3ss0n according to this page `audio/ogg` isn't supported, but opus is: https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/mediarecorder/MediaRecorder-isTypeSupported.html
