### ISSUE TITLE
Can't upload on Chrome

### ISSUE THREAD

**Issue by clavish** [collab-project/videojs-record#101]
## Description
I can't upload to server recorded video on Chrome, on Firefox is working.

## Steps to reproduce
Just try with jquery.fileupload.js or fine-uploader.js on Chrome

## About
I just got "undefined (undefined bytes)".  
When put manually some files to  <input id="fileupload" type="file" name="files[]" multiple> from computer then it's all uploaded good. 

## Additional Information
Chrome 54
Video.js 5.11.6
videojs-record v1.5.0 

It's my firs issue, so I hope that I sent all informations.

**Comment by thijstriemstra** [comment]
@clavish you resolved the issue?
