### ISSUE TITLE
Question: After enumerating devices, how to supply a selected device to recorder

### ISSUE THREAD

**Issue by erikdonohoo** [collab-project/videojs-record#102]
## Description
How do I tell the recorder which enumerated device to use?  Basically I'm trying to make my own UI instead of the supplied one.  Is there a way to access the API used by the native button this plugin supplies?

Thanks in advance

**Comment by thijstriemstra** [comment]
Good question. Check the enumerate-devices.html example on how to get aquire the `deviceId` used in the example below.

```javascript
record: {
    maxLength: 20,
    debug: true,
    audio: true,
    video: {
        // video constraints: use preset device
        optional: [{sourceId: deviceId}]
    },
}
```

I haven't tested it but more info [here](http://stackoverflow.com/a/20082861).

**Comment by thijstriemstra** [comment]
If the proposed solution doesn't work, try this constraint instead: https://github.com/samdutton/simpl/blob/gh-pages/imagecapture/js/main.js#L51
