### ISSUE TITLE
Event VIDEOJS: Finished playback

### ISSUE THREAD

**Issue by kimhongn89** [collab-project/videojs-record#105]
## Description
Do you have event ended when i play my audio recording. There is event ended for video recording but audio isn't.

## Steps to reproduce
init audio-only => startRecord => finishRecord => play my audio recording => when audio recording finished => event ended didn't call (it's called in case audio/video)
Sorry about my English.

**Comment by thijstriemstra** [comment]
I'll take a look.

**Comment by thijstriemstra** [comment]
This looks like it's related to https://github.com/collab-project/videojs-wavesurfer/issues/24. Does that event help here or do you think videojs-record needs an extra event as well @kimhongn89?

**Comment by kimhongn89** [comment]
Yes, it 's same
