### ISSUE TITLE
How can we provide flash support in this plugin?

### ISSUE THREAD

**Issue by httpamit** [collab-project/videojs-record#106]
I have problem with safari browser, getUserMedia() is not supported in safari browser. can we provide flash support in safari?

**Comment by thijstriemstra** [comment]
I was a Flash developer for many years but after Adobe ditched it the way they did I decided to never develop for a closed-source system again. As with most things in this plugin, take a look at wavesurfer.js first, does that support Flash? It seems it does with the https://github.com/laurentvd/wavesurfer.swf project. I would start there and see if you can get that plugin working with videojs-record, I haven't tested it. If you have questions, feel free to post them here, but I'm not planning on adding Flash support myself.

**Comment by omgj** [comment]
listen to Stallman - flash is malware i.e not free software.

**Comment by thijstriemstra** [comment]
Now that `getUserMedia` is (somewhat) supported in Safari (11) I think Flash became pretty much obsolete. See #181 for safari progress.
