### ISSUE TITLE
Video very dark when recording on Android phone with Chrome

### ISSUE THREAD

**Issue by MapZombie** [collab-project/videojs-record#110]
## Description
The video is very dark when using the front camera, it seems like exposure is off.  This was on Samsung Note 4, with Chrome browser.  
## Steps to reproduce
Ran the example page of videojs-record for jquery fileupload. 
## Results
Extremely dark video.
### Expected
I switched to my standard phone camera app and the front camera was very clear and bright, lighting not an issue.  I expected to see this when recording in the chrome browser.

Are there settings that can be changed on the JS side to turn exposure ON for the camera?  It is truly like night and day compared to the front camera using the standard camera app.

**Comment by MapZombie** [comment]
Update:  I believe this a know bug for Chrome on Android.  I tried Chrome Beta and it appears to be fixed.  But regular Chrome is still behind.

**Comment by thijstriemstra** [comment]
Do you have a link for this known issue?

**Comment by MapZombie** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=630266

**Comment by thijstriemstra** [comment]
thanks!
