### ISSUE TITLE
How do I convert object given in google chrome to video. 

### ISSUE THREAD

**Issue by lorddamsy1000** [collab-project/videojs-record#112]
## Description
Briefly describe the issue.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?

**Comment by thijstriemstra** [comment]
@lorddamsy1000 what?
