### ISSUE TITLE
Firefox 51.0.1 Crash

### ISSUE THREAD

**Issue by bobyper** [collab-project/videojs-record#114]
Using demo (https://collab-project.github.io/videojs-record/examples/audio-video.html), Firefox crash (memory leak) after stop record and wait few minutes.
Firefox eat memory and crash.

**Comment by thijstriemstra** [comment]
What operating system?

**Comment by bobyper** [comment]
Windows 8.1 64 bit , and Windows 10 32 bit

Firefox 50.1.0 working fine but 51.0.1 eat memory and processor time and finally crash

**Comment by thijstriemstra** [comment]
Maybe this is related: https://bugzilla.mozilla.org/show_bug.cgi?id=1338930 I also saw weird behavior on Firefox for OSX (it ate all swap memory within 10 mins). I'm not yet sure it's a firefox-specific issue (as opposed to videojs-record) but it probably is.

**Comment by thijstriemstra** [comment]
@bobyper if firefox 50.1.0 works fine than this must be a Firefox bug. Can you open a ticket in their bugzilla?

**Comment by bobyper** [comment]
I thing so, firefox 51 is buggy.
Its something specific on videojs-record.js make Firefox to crash, because recorrtc demo working on Firefox 51 (https://www.webrtc-experiment.com/RecordRTC/)

**Comment by thijstriemstra** [comment]
@bobyper it be interesting to see what the about:memory says during the leak.

**Comment by bobyper** [comment]
Here is four export of  about:memory during leak. 
[memory-report.json.gz](https://github.com/collab-project/videojs-record/files/772289/memory-report.json.gz)
[memory-report.json3.gz](https://github.com/collab-project/videojs-record/files/772287/memory-report.json3.gz)
[memory-report.json2.gz](https://github.com/collab-project/videojs-record/files/772290/memory-report.json2.gz)
[memory-report.json1.gz](https://github.com/collab-project/videojs-record/files/772288/memory-report.json1.gz)

**Comment by bobyper** [comment]
Here is four export of about:memory during leak.

[memory-report.json1.gz](https://github.com/collab-project/videojs-record/files/772313/memory-report.json1.gz)
[memory-report.json2.gz](https://github.com/collab-project/videojs-record/files/772314/memory-report.json2.gz)
[memory-report.json3.gz](https://github.com/collab-project/videojs-record/files/772315/memory-report.json3.gz)
[memory-report.json4.gz](https://github.com/collab-project/videojs-record/files/772316/memory-report.json4.gz)

**Comment by thijstriemstra** [comment]
@bobyper in the first report I notice an unknown blob reference, which is strange, on my machines I only see a single blob at anytime. Maybe you had an additional tab open with some other (getUserMedia) example?

```
2 (100.0%) -- file-blob-urls
├──1 (50.00%) ── owner unknown/blob:null/38db65b7-e624-4e34-ba26-5855081e7bab
└──1 (50.00%) ── owner(https://collab-project.github.io/videojs-record/examples/audio-video.html)/blob:https://collab-project.github.io/8b3648f7-c5b2-48df-a766-2e042724abaf
```

**Comment by thijstriemstra** [comment]
This ticket seems very related: https://bugzilla.mozilla.org/show_bug.cgi?id=1337204

**Comment by thijstriemstra** [comment]
I've not read these memory reports before but this also seems high:

```
─442 (11.16%) -- top(https://collab-project.github.io/videojs-record/examples/audio-video.html, id=8)/active/window(https://collab-project.github.io/videojs-record/examples/audio-video.html)/dom
   │    ├──428 (10.80%) ── event-listeners
   │    └───14 (00.35%) ── event-targets
```

**Comment by bobyper** [comment]
Something totally is broken in Firefox 51. Pause/Resume not working too. Pause stops only audio. Video continues recording.  
Its seems we need to wait next Firefox version.

**Comment by thijstriemstra** [comment]
Pause/resume not working on FF is a known issue unfortunately.

**Comment by bobyper** [comment]
Pause/Resume working fine on FF 50, both Windows and Mac

**Comment by thijstriemstra** [comment]
@bobyper oh man, didn't know that, FF 51 is definitely screwed then.

**Comment by thijstriemstra** [comment]
@bobyper maybe a nightly build of Firefox might be worth testing.

**Comment by bobyper** [comment]
Nighty version FF 54 is broken too

I don't know how to define issue for ticket in  bugzilla.

**Comment by cihadhoruzoglu** [comment]
I got memory leak on Mac Chrome v56. Firefox v51 works fine on my Mac.

**Comment by thijstriemstra** [comment]
@cihadhoruzoglu can you provide a memory analysis/scan? If it's leaking in Chrome as well there's something else not right, likely in this library or one of it's dependencies.

**Comment by cihadhoruzoglu** [comment]
@thijstriemstra I had 2 crash 6 days ago but then I couldn't get that error again. I think it was about another 3rd pary library.

**Comment by thijstriemstra** [comment]
There's a new firefox release, any crashes since then?

**Comment by bobyper** [comment]
Firefox 52.0 not eat memory but pause/resume not working. Can be used for record, except pause/resume

**Comment by bobyper** [comment]
Finally, Firefox 55 record/pause/resume working fine

**Comment by thijstriemstra** [comment]
@bobyper so I guess this ticket can be closed, Firefox 55 and newer do not crash (at all)?

**Comment by bobyper** [comment]
yes
