### ISSUE TITLE
Is their any method to stop video recording and download the file?

### ISSUE THREAD

**Issue by manishchauhanquovantis** [collab-project/videojs-record#115]
In my case i need to pause and resume video many times and later on i need to download it.Video is only downloaded in case of finishRecord event.Is their any other way to inform that i finished recording.

**Comment by thijstriemstra** [comment]
@manishchauhanquovantis you can call `player.recorder.saveAs({'video': 'my-video-file-name'})` at any point you want, not just in `finishRecord`. I'm afraid I don't understand your question, can you elaborate?

**Comment by manishchauhanquovantis** [comment]
I am getting this error
`Uncaught Blob object is required`
When i tried to to call `player.recorder.saveAs({'video': 'my-video-file-name'})`

**Comment by thijstriemstra** [comment]
@when are you calling saveAs?

**Comment by manishchauhanquovantis** [comment]
@thijstriemstra  hey sorry i just checked it out again i worked.Your library is awesome i just loved it :dagger:

**Comment by thijstriemstra** [comment]
Thanks!
