### ISSUE TITLE
The camera is not captured when an element in uiElements[element] is not a function

### ISSUE THREAD

**Issue by stragari** [collab-project/videojs-record#118]
## Description
The camera is not captured when the an element in the array uiElements[element] is an element extended.

## Steps to reproduce
use Chrome Version 55.0.2883.75 (64-bit), default configuration, and an Array extended functionality.

### Expected
The camera should be captured when the a element in the array is an element extended

### Actual
The camera is not captured when the a element in the array is an element extended

### Error output
device error: TypeError: uiElements[element].el is not a function at constructor.onDeviceReady (videojs.record.js:850)

## Additional Information
I review the code and I can fixed with 

```javascript
                for (element in uiElements)
                {
                    if (uiElements.hasOwnProperty(element))
                    {
                        uiElements[element].el().style.display = 'block';
                        uiElements[element].show();
                    }
                }
```

instead

```javascript
                for (element in uiElements)
                {
                        uiElements[element].el().style.display = 'block';
                        uiElements[element].show();
                }
```

**Comment by thijstriemstra** [comment]
@stragari can you show me the error message?

**Comment by stragari** [comment]
the error message en the web console

device error: TypeError: uiElements[element].el is not a function at constructor.onDeviceReady (videojs.record.js:850)

![videojsrecorder](https://cloud.githubusercontent.com/assets/390458/22942329/70a0f180-f2bf-11e6-8a33-d47c1cabc00f.png)

**Comment by thijstriemstra** [comment]
@stragari I see, you added or removed elements and they're not found. Can you make a pull request? thanks!

**Comment by stragari** [comment]
PR #119

**Comment by stragari** [comment]
Sorry the new PR  #120

**Comment by thijstriemstra** [comment]
Should be fixed in the upcoming version.
