### ISSUE TITLE
Is their any event to get user is speaking in microphone or not during recording?

### ISSUE THREAD

**Issue by manishchauhanquovantis** [collab-project/videojs-record#122]
Am trying to create demo which asks a series of questions and video is recorded while answering.I need to grab an event when user finishes to speak .Is it possible ?

**Comment by thijstriemstra** [comment]
@manishchauhanquovantis I suppose you could monitor the volume, see http://stackoverflow.com/a/21247724 for example.

**Comment by thijstriemstra** [comment]
Closing, no feedback.

**Comment by manishchauhanquovantis** [comment]
I used AudioMeter plugin for solving this issue...
