### ISSUE TITLE
Webpack can't find 'videojs'

### ISSUE THREAD

**Issue by cihadhoruzoglu** [collab-project/videojs-record#123]
## Description
There is an issue in videojs.record.js file at line 6.
`define(['videojs'], factory);` should be `define(['video.js'], factory);`
because there is no 'videojs' npm package it should be **'video.js'**

## Steps to reproduce

- Import videojs
- Import videojs-record package and error will be pop-up when you build with webpack

### Error output
> This dependency was not found in node_modules:

* videojs

#### videojs
1.5.2

**Comment by thijstriemstra** [comment]
@cihadhoruzoglu can you post the error message?

**Comment by cihadhoruzoglu** [comment]
<img width="1049" alt="screen shot 2017-02-17 at 10 34 13" src="https://cloud.githubusercontent.com/assets/1528616/23056509/7fac8fe0-f4f4-11e6-801f-e2a01364ed61.png">

**Comment by thijstriemstra** [comment]
@cihadhoruzoglu you should use this (taken from [here](https://github.com/videojs/videojs-contrib-hls/issues/600#issuecomment-273289790):

```javascript
new webpack.ProvidePlugin({
            videojs: "video.js",
            "window.videojs": "video.js"
        }),
```

or [this](https://github.com/hallelujah/videojs-webpack-example/blob/master/webpack.config.js#L90) approach:

```javascript
alias: {
      "video.js": "video.js/src/js/video.js",
      "videojs-contrib-hls": path.resolve(__dirname, "web_modules/videojs-contrib-hls/src/videojs-contrib-hls.js"),
      "videojs": path.resolve(__dirname, "web_modules/video.js"),
      "videojs-contrib-media-sources": path.resolve(__dirname, "web_modules/videojs-contrib-media-sources/src/videojs-contrib-media-sources.js")
    }
```
