### ISSUE TITLE
My video records do not play on iPhone & iPAD

### ISSUE THREAD

**Issue by OmrDemirel** [collab-project/videojs-record#124]
## Description
Please find my codes below. My problem is that while my codes work on regular PC, they do not on Safari browsers on Iphone and Ipads. I have also attached screenshots hoping that you'll be able to help me on this issue.

As a last note, I also receive the error message below whenever I download the records to the server using ffmpeg to change into mp4 (or other) formats, and have no idea why this happens.

## FFmpeg Error
![vps](https://cloud.githubusercontent.com/assets/8202906/23092153/c6bd8e16-f5d5-11e6-83d2-d5f2943b078c.jpg)

## JS
![js](https://cloud.githubusercontent.com/assets/8202906/23091938/d4275dce-f5d1-11e6-9d40-52a06acceb37.jpg)

## PHP
![php](https://cloud.githubusercontent.com/assets/8202906/23091995/f963719e-f5d2-11e6-8f31-32b8fc935f7a.jpg)

## iPhone
![iphoneobj](https://cloud.githubusercontent.com/assets/8202906/23092131/51ae2d10-f5d5-11e6-8f75-f7ea0bdf244f.jpg)

**Comment by thijstriemstra** [comment]
@OmrDemirel what browser on the ipad? What ffmpeg command? What does the `ffprobe` tool say about your file?

**Comment by OmrDemirel** [comment]
@thijstriemstra 
FFmpeg Command
`ffmpeg -i input.mp4 output.avi`
`ffmpeg -i input.mp4 -acodec copy -vcodec copy output.avi`
`ffmpeg -i input.mp4`

I keep on getting the nsame error message for all ffmpeg listed above. This is just a few examples of errors coming to my mind and I have tried others as well. 

On the other side I use Safari on Ipad and Iphone but couldnt get the record playing. I have shared with you the screenshot of the error msg I get on these.

I have never used ffprobe, would much appreciate if you could guide me a bit on how to use it.

**Comment by thijstriemstra** [comment]
@OmrDemirel what version of ffmpeg? Please paste the full text version of the ffmpeg command and version.

`ffprobe` is installed along ffmpeg, e.g. `ffprobe input.mp4`.

Make sure your ffmpeg has libopus support (you should see `--enable-libopus` in the version output).

Mine for example:

```
$ ffmpeg -version
ffmpeg version 2.8.11-0ubuntu0.16.04.1 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libavresample   2.  1.  0 /  2.  1.  0
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101
libpostproc    53.  3.100 / 53.  3.100
```

**Comment by thijstriemstra** [comment]
And finally, the `aac` codec should work on ipad (see http://superuser.com/questions/758622/improve-ffmpeg-command-for-mkv-to-mp4-for-ipad).

**Comment by OmrDemirel** [comment]
> **$ffprobe w.mp4**
FFprobe version 0.6.5, Copyright (c) 2007-2010 the FFmpeg developers
  built on Jan 29 2012 23:55:02 with gcc 4.1.2 20080704 (Red Hat 4.1.2-51)
  configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --mandir=/usr/share/man --incdir=/usr/include --disable-avisynth --extra-cflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC' --enable-avfilter --enable-avfilter-lavf --enable-libdirac --enable-libfaac --enable-libfaad --enable-libfaadbin --enable-libgsm --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libx264 --enable-gpl --enable-nonfree --enable-postproc --enable-pthreads --enable-shared --enable-swscale --enable-vdpau --enable-version3 --enable-x11grab
  libavutil     50.15. 1 / 50.15. 1
  libavcodec    52.72. 2 / 52.72. 2
  libavformat   52.64. 2 / 52.64. 2
  libavdevice   52. 2. 0 / 52. 2. 0
  libavfilter    1.19. 0 /  1.19. 0
  libswscale     0.11. 0 /  0.11. 0
  libpostproc   51. 2. 0 / 51. 2. 0
[matroska @ 0x1048520]Unknown/unsupported CodecID A_OPUS.
[matroska @ 0x1048520]Unknown entry 0x1F43B675
[matroska @ 0x1048520]Unknown entry 0xE7
[matroska @ 0x1048520]Unknown entry 0xA3
    Last message repeated 188 times
[matroska @ 0x1048520]Could not find codec parameters (Audio: 0x0000, 48000 Hz, 1 channels)
[matroska @ 0x1048520]Could not find codec parameters (Video: 0x0000, 640x480)
[matroska @ 0x1048520]Estimating duration from bitrate, this may be inaccurate
w.mp4: Operation not permitted


#########ffmpeg version

> $ffmpeg -version
FFmpeg version 0.6.5, Copyright (c) 2000-2010 the FFmpeg developers
built on Jan 29 2012 23:55:02 with gcc 4.1.2 20080704 (Red Hat 4.1.2-51)
configuration: --prefix=/usr --libdir=/usr/lib64 --shlibdir=/usr/lib64 --mandir=/usr/share/man --incdir=/usr/include --disable-avisynth --extra-cflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC' --enable-avfilter --enable-avfilter-lavf --enable-libdirac --enable-libfaac --enable-libfaad --enable-libfaadbin --enable-libgsm --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libx264 --enable-gpl --enable-nonfree --enable-postproc --enable-pthreads --enable-shared --enable-swscale --enable-vdpau --enable-version3 --enable-x11grab
	libavutil     50.15. 1 / 50.15. 1
	libavcodec    52.72. 2 / 52.72. 2
	libavformat   52.64. 2 / 52.64. 2
	libavdevice   52. 2. 0 / 52. 2. 0
	libavfilter    1.19. 0 /  1.19. 0
	libswscale     0.11. 0 /  0.11. 0
	libpostproc   51. 2. 0 / 51. 2. 0
	FFmpeg 0.6.5
	libavutil     50.15. 1 / 50.15. 1
	libavcodec    52.72. 2 / 52.72. 2

**Comment by thijstriemstra** [comment]
Yes so thats the issue; you should upgrade to a recent ffmpeg with opus support.

**Comment by liufitch** [comment]
@OmrDemirel  can you show me your server code ??? video i recived  doesnt play.i have already thought the question for 3 days. please!!!!

**Comment by andriy-kravets** [comment]
Found your posted issue on upwork. I think I can help you! Contact me via email: kravets.andr@gmail.com. Thank you!
