### ISSUE TITLE
Is there any way to show text with controls on video?

### ISSUE THREAD

**Issue by baimurzin** [collab-project/videojs-record#126]
Is there any way to display any html block with controls during recording the video on the video block?

**Comment by thijstriemstra** [comment]
What kind of controls?

**Comment by baimurzin** [comment]
@thijstriemstra  for example I recording video and server push me any data, then I display those data as html blocks with buttons and after click on this button I show next block and store time of last closed form. 
By the way, now I trying to do this with videojs-caption but the text only can show with 'startTime' and end with similiar option. But I need to show and close programable.

**Comment by thijstriemstra** [comment]
I think this is a videojs-specific question, and if I understand correctly you want to add extra elements to the player.

Check here on how to add elements to the plugin: https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L2269
