### ISSUE TITLE
Internet Explorer Edge Support?

### ISSUE THREAD

**Issue by cihadhoruzoglu** [collab-project/videojs-record#127]
IE edge supports video capture and this library also recording on IE but when record stops IE throws this error;

![captureerror](https://cloud.githubusercontent.com/assets/1528616/23215430/03ade35a-f91b-11e6-8da8-ba4f84f38db5.PNG)

**Comment by thijstriemstra** [comment]
What media playback types does Ie edge support? Did you even search? And how am I supposed to guess yoh
