### ISSUE TITLE
How can I listen timeupdate event while recording?

### ISSUE THREAD

**Issue by baimurzin** [collab-project/videojs-record#128]
Is it possible to listen `timeupdate` event and get current time while recording?

**Comment by thijstriemstra** [comment]
Sounds like a reasonable enhancement that I'll add.

**Comment by thijstriemstra** [comment]
@baimurzin I added a `progressRecord` event that you can use, e.g.:
```javascript
player.on('progressRecord', function()
{
    console.log('current time:', player.recorder.getDuration());
});
```
Let me know how it goes!
