### ISSUE TITLE
Support for audio input selection

### ISSUE THREAD

**Issue by v3ss0n** [collab-project/videojs-record#13]
https://simpl.info/getusermedia/sources/

with that , user can choose back or front camera. What do you think? If UI is going to be difficult , just an API will be fine.

**Comment by thijstriemstra** [comment]
Maybe each example could have an extra row of buttons for testing programmatic things like picking camera, stopping device, starting device.

**Comment by v3ss0n** [comment]
Oh the regular Switch camera icon on the player would be fine?

**Comment by thijstriemstra** [comment]
Looks like this is only supported in Chrome 30 and later, nothing in Firefox yet.

**Comment by thijstriemstra** [comment]
There's also the https://github.com/muaz-khan/DetectRTC library that implements many of the functionality I'm looking for. I'll probably make that an optional dependency when the new devices API is used (it's a 10kb extra).

**Comment by thijstriemstra** [comment]
unrelated but @v3ss0n, would be cool if you can add a translation for your native language(s) in https://github.com/collab-project/videojs-record/tree/master/lang :)

**Comment by v3ss0n** [comment]
Thank you , I will translate it out.

**Comment by mathabaws** [comment]
I know it has been two years but any progress or plans on implementing this feature any time soon? :)

**Comment by thijstriemstra** [comment]
No, initial v2 release is up next. Donations help make things go faster ;)

**Comment by thijstriemstra** [comment]
This is basically already possible. Use `player.recorder().enumerateDevices()` to get a list of available devices and use constraints to assign a specific device, e.g.

```javascript
var devices = player.recorder().enumerateDevices();
var device = devices[0];

var constraints = {
    audio: {
      deviceId: {exact: device.deviceId}
    },
    // and/or video
    /*video: {
      deviceId: {exact: videoDevice.deviceId}
    }*/
};
```

I'll add a working example.
