### ISSUE TITLE
Chrome recording audio-only sounds too low

### ISSUE THREAD

**Issue by cb109** [collab-project/videojs-record#130]
Recording audio only (with the demo code) in Chrome 56 sounds a lot lower/deeper when playing back.

Can not reproduce with Firefox 43, works fine there.

Any ideas how I might fix that by changing the configuration?

**Comment by cb109** [comment]
Just checked: Does not happen when recording video AND audio.

**Comment by thijstriemstra** [comment]
@cb109 can you check if it's [using the extra audio element](https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L1216) with the audio+video recording in Chrome (and not in Firefox)?

**Comment by thijstriemstra** [comment]
@cb109 no feedback, closing.
