### ISSUE TITLE
Output blob size is 0 on Chrome when recording audio

### ISSUE THREAD

**Issue by stevula** [collab-project/videojs-record#137]
## Description
When I try to record video + audio on Chrome the output blob for video has no data and there is no audio blob at all. It outputs a 2 MB blob if recording video-only, but when I set `audio: true` in the videojs `options` object, the output video blob is 0 MB. There is also no audio blob in the output.

Your [audio-video demo](https://collab-project.github.io/videojs-record/examples/audio-video.html) also seems to have the same issue:
<img width="1392" alt="screen shot 2017-03-02 at 4 23 20 pm" src="https://cloud.githubusercontent.com/assets/13430288/23533157/b80f4f9c-ff64-11e6-8ff1-cb9d4bf815a4.png">

## Steps to reproduce
This is my setup:
```
const player = videojs('video-player', {
  // video.js options
  controls: true,
  loop: false,
  width: $('#video-container').width() || 320,
  height: $('#video-container').height() || 240,
  plugins: {
    // videojs-record plugin options
    record: {
      maxLength: 5,
      debug: true,
      audio: true,  /* only works when this is false */
      video: {
        // video constraints: set resolution of camera
        mandatory: {
          minWidth: 1280,
          minHeight: 720,
        },
      },
      // dimensions of captured video frames
      frameWidth: 1280,
      frameHeight: 720
    }
  }
});

// error handling
player.on('deviceError', function() {
  console.log('device error:', player.deviceErrorCode);
});

player.on('error', function(error) {
  console.log('error:', error);
});

// user clicked the record button and started recording
player.on('startRecord', function() {
  console.log('started recording!');
});

// user completed recording and stream is available
player.on('finishRecord', function() {
  // the blob object contains the recorded data that
  // can be downloaded by the user, stored on server etc.
  debugger
  console.log('finished recording: ', player.recordedData);
});
```

### Expected
I'm expecting to see an object with a video and audio blob of an appropriate size for a 5s video/audio recording.

### Actual
The video blob has a size of 0 and there is no audio blob.

### Error output
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. `

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
videojs 5.16.0
#### browsers
Chrome 56
#### OSes
MacOS 10.12.3

**Comment by stevula** [comment]
Sorry to bother you. The problem went away when I quit and reopened my browser.

**Comment by thijstriemstra** [comment]
Cache thing?

**Comment by stevula** [comment]
This is still popping up intermittently. Clearing browser cache doesn't fix it but closing the browser completely does. So far I've only spotted the issue in Chrome, but I haven't done as much testing in Firefox to be sure.

**Comment by thijstriemstra** [comment]
@stevula can you update and add the additional Chrome and/or OS info in the ticket description?

**Comment by ox-michaelradionov** [comment]
I've encountered the same problem, and browser restart solved it. Only Chrome, only on Mac OS.

Chrome 59.0.3071.115
macOS Sierra 10.12.4

videojs-record 1.6.0
video.js 5.15.1

**Comment by maxpaj** [comment]
I can add that I've seen this as well in our live environment. But since I don't know how to reproduce it I just don't know where to begin...

**Comment by thijstriemstra** [comment]
Yea, if it's not possible to reproduce it'll be impossible to fix this..

**Comment by maxpaj** [comment]
@thijstriemstra kind of have to agree with you here... We've seen this bug appear very sporadically. 

In any case, I think this bug probably stems from RecordRTC. So for anyone interested in getting this fixed, I'd refer to the RecordRTC issues instead. https://github.com/muaz-khan/RecordRTC
