### ISSUE TITLE
Empty record data on chrome but it works in firefox

### ISSUE THREAD

**Issue by liufitch** [collab-project/videojs-record#140]
i ran your audio-video.html of examples. but it didnt work in chrome.work fine in firework.
in chrome,it shows
![Uploading chrome_record.png…]()

![Uploading debug_record.png…]()

i didnt change js  but i change js url

my chrome  57.0.2987.110 (64-bit)
video.js 5.19.0
Latest version of RecordRTC.js and videojs-record

**Comment by thijstriemstra** [comment]
Why is this closed?

**Comment by liufitch** [comment]
i misclick

**Comment by thijstriemstra** [comment]
duplicate of #141.
