### ISSUE TITLE
Empty record data on chrome but it works in firefox

### ISSUE THREAD

**Issue by liufitch** [collab-project/videojs-record#141]
i ran your audio-video.html of examples. but it didnt work in chrome.work fine in firework.
in chrome,it shows
![chrome_record](https://cloud.githubusercontent.com/assets/16552313/24332029/eb18803c-1271-11e7-8443-58b653b89abc.png)
![debug_record](https://cloud.githubusercontent.com/assets/16552313/24332034/ee73b3a0-1271-11e7-9865-5b09df6ce3ec.png)

```javascript
var player = videojs("myVideo",
{
controls: true,
width: 320,
height: 240,
plugins: {
record: {
audio: true,
video: true,
maxLength: 10,
debug: true
}
}
});

// error handling
player.on('deviceError', function()
{
console.log('device error:', player.deviceErrorCode);
});
player.on('error', function(error)
{
console.log('error:', error);
});

// user clicked the record button and started recording
player.on('startRecord', function()
{
console.log('started recording!');
});

// user completed recording and stream is available
player.on('finishRecord', function()
{
// the blob object contains the recorded data that
// can be downloaded by the user, stored on server etc.
console.log('finished recording: ', player.recordedData);

});
```
i didnt change js but i changed js url

my chrome 57.0.2987.110 (64-bit)
video.js 5.19.0
Latest version of RecordRTC.js and videojs-record

sorry
i  closed the last issues because of my carelessness so i open another issue about the same problem

**Comment by thijstriemstra** [comment]
that's strange, although I haven't tested with video.js 5.19.0 yet. @liufitch can you reproduce this with older video.js versions?

**Comment by liufitch** [comment]
i know why. because i used http not https. it  says " getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
 device error: DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."

**Comment by thijstriemstra** [comment]
Thx
