### ISSUE TITLE
Unable to run videojs-record on angular

### ISSUE THREAD

**Issue by thestrayed** [collab-project/videojs-record#143]
## Description
try setting up video element on view with external js

### Error output
The element or ID supplied is not valid. (videojs)
if i use in-line script, this error won't come up. video tag will have only volume bar instead

**Comment by thijstriemstra** [comment]
I believe the issue template asks for video.js version info, os info. Am i supposed to guess? Try to reproduce it by making my own angular example? Sigh.

**Comment by thestrayed** [comment]
### versions
#### videojs
5.19.2
#### recordrtc
5.4.1
#### videojs-record
1.6.1
#### browsers
what browser are affected?
Chrome, Safari
#### OS
MacOS 10.12.4

Note that my code is exactly the same as audio-video.html

**Comment by thijstriemstra** [comment]
if your code is exactly the same, can you reproduce it with the audio-video.html example?

**Comment by thestrayed** [comment]
Nope, I actually have working one on html. Now I'm trying to run it on Angular version 1.6.4 It get stuck when call videojs in script

**Comment by thijstriemstra** [comment]
Can you share the solution if it's useful to others working with angular?
