### ISSUE TITLE
Freezes in Chrome

### ISSUE THREAD

**Issue by redwerk** [collab-project/videojs-record#146]
## Description
We have found inexplicable freezes of video recording in Chrome.
Sometimes on the start of recording the plugin shows just static image instead of video recording.
The video doesn't exist after the stop of the recording. 

We’ve set debug to true in order to figure out additional information, but haven’t seen any errors in browser console. Library debug log write that video is recording. 

The bug could be reproduced randomly. 
It doesn’t depend on hardware, as it could be reproduced on devices with 30% of cpu usage and 40-50% of memory usage and on high loaded devices. 
It could be reproduced with built-in webcams as well as usb webcams. 
It was reproduced on Windows and Mac OS.

We tried to debug our scripts to detect the issue, but the only thing we found, is that after the start it records for 1 second and stops with static image and without errors. After calling stop recording video doesn't exist. 

After this freeze Chrome tab doesn't respond and sometimes it can't be closed. If Chrome tab is closed after that and new one is opened, recording is impossible: the camera is not found and recorder is not created. Only the browser restart helps in this situation. 
There are no errors in browser console at that moment. 

We have also noticed another issue: 
When new usb cam is connected and driver is still installing, plug-in loges in browser console that camera is found and available, but only black screen and loading image are shown. Maybe, both of issues have the same root.

## Steps to reproduce
The bug could be reproduced randomly. 

### Expected
Video is recording always.

### Actual
Inexplicable freezes of video recording in Chrome.

### Error output
No errors at all.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
videojs 5.18.4
videojs-record v1.6.1
RecordRTC v5.4.1
#### browsers
what browser are affected?
Chrome
#### OSes
what platforms (operating systems and devices) are affected?
Windows 10, Mac OS

**Comment by thijstriemstra** [comment]
Thx for the report. How this ticket will get fixed, i dont know though..

**Comment by thijstriemstra** [comment]
@redwerk what version of Chrome?

**Comment by redwerk** [comment]
57.0.2987.133 and 58.0.3029.81

**Comment by thijstriemstra** [comment]
@redwerk can you post a video? code example?

**Comment by maxpaj** [comment]
I have observed something similar, so I'll give some input on this. 

What happens is that the video freezes a second after recording starts. Then when you finish the recording with stop(), an error is produced in the console:

GET blob:https://*hidden*/8a3ab656-d7b3-4178-af86-51918dda7cca 416 (Requested Range Not Satisfiable)

This bug appears on a very unregular basis. If I can do one recording then it seems like the bug won't appear no matter how many recordings I do - until I refresh the page. But once the bug has been produced I have to close down Google Chrome entirely before I can record normally again.

**Comment by redwerk** [comment]
We can't share the code, unfortunately, and we believe that it won't be useful as this is quite an unregular bug. Are there any chances we can speed up the fixes? Maybe we can provide help or there are some other ways to do it?

**Comment by maxpaj** [comment]
Since what happens in my case is that the entire browser hangs and I have to close it down in order to make it work again - does that mean it could be bug in Chrome?

**Comment by thijstriemstra** [comment]
possibly. Probably a good idea to open a ticket for the Chrome or Chromium browser, maybe they can reproduce it.

**Comment by redwerk** [comment]
We think it's not a chrome bug, because we had this error on firefox as well (here is the screenshot https://www.dropbox.com/s/6zwcafnm0hjiucr/Screen%20Shot%202017-05-24%20at%201.46.39%20PM.png?dl=0). We have also thoroughly reviewed our code and have not found anything that could have caused the issue. Maybe this issue it's something related to one of this issues https://github.com/collab-project/videojs-record/issues/54 or https://github.com/collab-project/videojs-record/issues/114? Or probably, we can create issue for WebRTC library.

**Comment by thijstriemstra** [comment]
Maybe you can analyze the crash report generated by firefox or chrome.

**Comment by redwerk** [comment]
We also created issue for RecordRTC library, because we found issues, which looks similar to this bug (https://github.com/muaz-khan/RecordRTC/issues/269).
And, unfortunately, we can't analyze the crash report, because it was shown once and bug reproduced really randomly.

**Comment by thijstriemstra** [comment]
@redwerk have you tried the suggestions in that recordrtc ticket?

**Comment by maxpaj** [comment]
@thijstriemstra do you think it's possible to use Chrome's native MediaRecorder with videojs-record? 

I'm thinking of temporarily replacing RecordRTC with some other record engine since we're having a lot of issues with our video recorder and RecordRTC seems to be the culprit here...

**Comment by thijstriemstra** [comment]
@maxpaj that sounds like a plan. But there are many quirks (I expect) that have to be worked around for various browsers, which is the reason I choose for recordrtc in the first place, so I wouldn't have to reinvent those fixes again. But if recordrtc is buggy and we can create a better native recorder, I'm all for it. Can you work on a PR for this @maxpaj?

**Comment by maxpaj** [comment]
@thijstriemstra I'll take a look at it!

**Comment by redwerk** [comment]
@thijstriemstra We have done everything from recordrtc ticket:
1. add to logs code, that was provided by RecordRTC owner
2. tried to reproduce issue and collect all logs, that we can get and add them to ticket.
Also,  we noticed, that error, that reproduced by @maxpaj is also reproduced in our project (comment on May 14). Error looks like this:
GET blob:https://*hidden*/f635a895-341b-486d-9aa6-1414c641f716 416 (Requested Range Not Satisfiable)

**Comment by thijstriemstra** [comment]
I can imagine #154 that was recently merged could also help fix this issue..

**Comment by redwerk** [comment]
Thank you for all responses!
We found that such error occur mostly on the 57 and 58 Chrome version. And we fixed it through changing videoMimeType to 'video/webm;codecs=vp9'.
But, also we got latest update for library and we will check this issue with your update.
Also, we noticed, after update not only videojs.record.js script, but also after update video.js script, that in console we have some warnings with text "VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead". Probably, you also need some fix.
Thank you for your help!

**Comment by thijstriemstra** [comment]
That warning should be fixed with the latest videojs-record version.

**Comment by redwerk** [comment]
Ok. Then thank you for your help!

**Comment by hypatia** [comment]
I ran into this crash on the latest videojs-record with the following browser version

>Google Chrome | 59.0.3071.115 (Official Build) (64-bit)
-- | --
Revision | 3cf8514bb1239453fd15ff1f7efee389ac9df8ba-refs/branch-heads/3071@{#820}
OS | Mac OS X
JavaScript | V8 5.9.211.38
Flash | 26.0.0.137 /Users/hypatia/Library/Application Support/Google/Chrome/PepperFlash/26.0.0.137/PepperFlashPlayer.plugin

**Comment by thijstriemstra** [comment]
@hypatia any crash log files or something you can share? Would love to get this fixed somehow.
