### ISSUE TITLE
Firefox Audio issue.

### ISSUE THREAD

**Issue by aaagepard** [collab-project/videojs-record#148]
## Description
FireFox 53.0.2 (32-bit) 
Audio example dont works normally.
It see microphone but after access acception, it just horisontal line on screen, any changes on voice. Controls works as expected, but any display changes after start or stop recording.

Works great in Chrome. Thanks!

## Steps to reproduce
Used FireFox 53.0.2 (32-bit) 
Audio : https://collab-project.github.io/videojs-record/examples/audio-only.html

### Error output
VIDEOJS: wavesurfer.js microphone plugin enabled.  video.min.js:18:20838
started recording audio stream.  RecordRTC.js:54:13
Using recorderType: MediaStreamRecorder  RecordRTC.js:828:9
Passing following config over MediaRecorder API. Object { type: "audio", bufferSize: 4096, sampleRate: 44100, numberOfAudioChannels: 2, disableLogs: false, recorderType: null, mimeType: "audio/ogg", initCallback: initRecorder/config.initCallback() }  RecordRTC.js:1752:13
Initialized recorderType: MediaStreamRecorder for output-type: audio  RecordRTC.js:90:13
started recording!  audio-only.html:63:5
VIDEOJS: Resume microphone  video.min.js:18:20838
Stopped recording audio stream.  RecordRTC.js:103:13
finished recording:  Blob { lastModifiedDate: Date 2017-05-10T14:11:28.465Z, name: "1494425488465.ogg", size: 168, type: "audio/ogg" }  audio-only.html:71:5
audio/ogg -> 168 Bytes  RecordRTC.js:140:17
VIDEOJS: Pause microphone  video.min.js:18:20838
VIDEOJS: Loading object: [object Blob]  video.min.js:18:20838
VIDEOJS: ERROR: Error decoding audiobuffer

**Comment by thijstriemstra** [comment]
@aaagepard what operating system?

**Comment by thijstriemstra** [comment]
I'm not able to reproduce this on same version of Firefox on Ubuntu 16.04. Are you sure you closed the microphone/Chrome browser while testing? They cannot access the mic at the same time.

**Comment by aaagepard** [comment]
@thijstriemstra Windows 7. yes I closed all other browses. 

![audio-only example - record plugin for video js - mozilla firefox](https://cloud.githubusercontent.com/assets/25985568/25941839/82c9e3c2-3643-11e7-9eb5-b4dff5c385c5.jpg)

**Comment by thijstriemstra** [comment]
This is related to https://github.com/katspaugh/wavesurfer.js/issues/1089 @aaagepard?

**Comment by aaagepard** [comment]
@thijstriemstra yes. I this is related issues.

**Comment by thijstriemstra** [comment]
@aaagepard so you got it to work on a different machine?
