### ISSUE TITLE
Record video in 16:9 aspect ratio record in 4:3 aspect ratio

### ISSUE THREAD

**Issue by mkc110891** [collab-project/videojs-record#150]
## Description
I am trying to record video in 16:9 video, I have set aspectRatio: '16:9' but still its recording in 4:3

## Steps to reproduce
```javascript
var player = videojs(videoId,
	{
		controls: true,
		plugins: {
			record: {
				videoMimeType:"video/mp4",
				aspectRatio: '16:9',
				autoHeight: false,
				width: 640,
				height: 360,
				video: true,
				audio: true,
				frameWidth: 640,
				frameHeight: 360
			}
		}
	});
```
## Results
Its still recording video in 4:3
### Expected
It should record in 16:9

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
Video.js 5.15.1
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?

**Comment by thijstriemstra** [comment]
You can use the aspectRatio to size the player but you need to pass in the correct video constraints to actually size it in 16:9. See https://github.com/collab-project/videojs-record#media-constraints for example.

**Comment by mkc110891** [comment]
Hi, Thijs Triemstra
I got solution.
even after using proper media constraints, I am not able to get proper frame in chrome.

Here is proper script to initiate recorder for 16:9
`var player = videojs(videoId,
		{
			controls: true,
			//loop: false,
			// dimensions of video.js player
			width: 1280,
			height: 720,
			plugins: {
				record: {
					maxLength: 40,
					//debug: true,
					audio: true,
					video: { width: 1280, height: 720 },
					// dimensions of captured video frames
					frameWidth: 1280,
					frameHeight: 720
				}
			}
		});`

And for chrome , you need to include - http://webrtc.github.io/adapter/adapter-1.0.2.js
Thats all and I got proper resolution in recording.
