### ISSUE TITLE
Uncaught (in promise) DOMException: setOptions failed in Chrome Version 59.0.3071.104

### ISSUE THREAD

**Issue by AbhijitParate** [collab-project/videojs-record#153]
## Description
Not able to capture the image in Chrome Version 59.0.3071.104
I tried with this link
[Image Demo](https://collab-project.github.io/videojs-record/examples/image-only.html)

## Steps to reproduce
Just try to capture the image

### Expected
Get image blob

### Actual
Not happening

### Error output
Uncaught (in promise) DOMException: setOptions failed

## Additional Information
Please include any additional information necessary here. Including the following:
### versions 
latest
#### videojs
what version of videojs does this occur with?
latest

**Comment by thijstriemstra** [comment]
@AbhijitParate what operating system? Could not reproduce this with Chrome 60.0.3112.50 (Official Build) beta (64-bit) on Ubuntu.

**Comment by thijstriemstra** [comment]
Please reopen if you have feedback.

**Comment by oosthoek** [comment]
I am having this same problem with the latest version of chrome on windows.  I traced it down to imageCapture.takePhoto() not working.

**Comment by thijstriemstra** [comment]
can you post the error or a screenshot @oosthoek? what version of windows/chrome?

**Comment by oosthoek** [comment]
chrome: Version 59.0.3071.115 (Official Build) (64-bit)
i have windows 7 and my coworker with windows 10 pro has the same problem.

screenshot from https://collab-project.github.io/videojs-record/examples/image-only.html
![image](https://user-images.githubusercontent.com/6978789/27928211-4bd6b288-625c-11e7-83ab-85ffa7e8fa11.png)

**Comment by thijstriemstra** [comment]
This is the implementation status page for Chrome: https://github.com/w3c/mediacapture-image/blob/gh-pages/implementation-status.md

It mentions:

> No flag needed after M59 (before that, use chrome://flags/#enable-experimental-web-platform-features).

This implies Chrome version 60 and newer should work out of the box, in older browsers you need to enable the flag: chrome://flags/#enable-experimental-web-platform-features.

I thought the plugin was checking for this but probably incorrectly, let me check.

**Comment by thijstriemstra** [comment]
Using this code currently:

```javascript
// MediaCapture is only supported on:
// - Chrome 56 (https://developers.google.com/web/updates/2016/12/imagecapture)
// - Firefox behind flag (https://bugzilla.mozilla.org/show_bug.cgi?id=888177)
// importing ImageCapture can fail when enabling chrome
// flag is still required. if so; ignore and continue
if ((detected.browser === 'chrome' && detected.version >= 56) && (typeof ImageCapture === typeof Function))
```
which pins it on Chrome >= 56 which is incorrect. So the Chrome devs decided to change this (the blog post referenced in the comments was also updated on june 2nd this year).

So let me fix that.

**Comment by thijstriemstra** [comment]
@oosthoek and @AbhijitParate, I improved a version check, can you see if it works with the latest version from the master branch?

**Comment by aaagepard** [comment]
@thijstriemstra  I had the same issue in last Crome 59.0.3071.115 (64 бит) on Windows 7 . After update from your last commits it works fine.

**Comment by oosthoek** [comment]
Works for me too.  Thank you.

**Comment by thijstriemstra** [comment]
Thx for feedback.

**Comment by kbrownhbs** [comment]
I am seeing this issue in Chrome Version 64.0.3282.186 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/3537923/36965018-5ac1be2c-2026-11e8-8c3b-72774665bf17.png)

**Comment by thijstriemstra** [comment]
@kbrownhbs let me check it out

**Comment by kbrownhbs** [comment]
Windows 10

**Comment by kbrownhbs** [comment]
My bad, this issue is for a different project dealing with taking photos using using the image-capture npm module.
