### ISSUE TITLE
Frozen video stream on Chrome Android

### ISSUE THREAD

**Issue by kperdomo1** [collab-project/videojs-record#154]
Hey guys. The plug-in has worked pretty good except for Chrome Android. Once the stream starts (after clicking the device button), it's supposed to show a live streaming of what the camera is capturing.

The issue here is that, for Chrome Android, this live streaming is extremely slow, basically showing snapshots of the stream with seconds in between. Nevertheless, once you start recording this issue disappears, as the recording streaming shows very fluently (as it's supposed to do).

In fact, you can reproduce this using the video-audio demo (https://collab-project.github.io/videojs-record/examples/audio-video.html) while using Chrome Android.

Might be related to [#146](https://github.com/collab-project/videojs-record/issues/146) though as I understand, it's a different issue.

Any ideas on why is this happening?

Issue was reproduced in Android 5.1 using Chrome v 58.0.3029.83. Happens 100% of the time.
On Firefox it works flawlessly.

**Comment by kperdomo1** [comment]
After many hours I figured out what the problem is.

At the end of onDeviceReady callback, the stream is being loaded into the video element and **immediately** being played. The thing is, Chrome seems to take a moment to load such stream. As a result, the stream is not actually being played. To solve this, right after loading the stream to the video element, a loadedmetadata callback must be configured so that we can play the stream at the right time. Like this:

`           // setup preview
            if (this.getRecordType() !== this.AUDIO_ONLY)
            {
                // show live preview
                this.mediaElement = this.player().el().firstChild;
                this.mediaElement.controls = false;

                // mute incoming audio for feedback loops
                this.mediaElement.muted = true;

                // hide the volume bar while it's muted
                this.displayVolumeControl(false);

                // save stream
                if (this.streamURL !== undefined)
                {
                    URL.revokeObjectURL(this.streamURL);
                }
                this.streamURL = URL.createObjectURL(this.stream);
                // start stream
                this.load(this.streamURL);
                var self = this;
                this.player().one('loadedmetadata', function() {
                    self.mediaElement.play();
                    // forward to listeners
                    self.player().trigger('deviceReady');
                });
            } else {
                // forward to listeners
                this.player().trigger('deviceReady');
            }`

And by the way, when loadedmetadata callback is invoked, **that** is the right time to trigger the deviceReady callback, because of the reason already explained.

While we're at it, the same logic applies while starting the recording. The start function makes use of startVideoPreview function, which also loads the stream on the video element. This loading sometimes takes time, and recording should be started only after the stream has been successfully loaded into the video element. 

I've made these changes and works great. Hope this can help anybody having the same issues.

Cheers!

**Comment by thijstriemstra** [comment]
Thanks for the details, can you make a pull request?

**Comment by kperdomo1** [comment]
Sure thing. I'm swamped with work atm but I'll try to do it tomorrow.
