### ISSUE TITLE
Turning off the device between recordings

### ISSUE THREAD

**Issue by alsar** [collab-project/videojs-record#157]
I want to be able to turn off the camera when the user has pressed the stop button (for privacy reasons).
I know, there is a `stopDevice` method and it works as advertised. It turns off the recording device. So I can call this method after the user clicks the stop button.
But the problem is that if I stop the device and the user clicks record again the recorder stops working. I get an error: ` DOMException [InvalidStateError: "An attempt was made to use an object that is not, or is no longer, usable"
code: 11
nsresult: 0x8053000b`

I understand that the MediaRecorder gets destroyed after the device is turned off. But is it possible to reinitialize the recorder somehow? 
I also tried manually calling `getDevice` but it results in all kinds of strange behaviors (not being able to stop the new recording, no play button...).

So is it possible turn the device off and on again somehow between recordings?

**Comment by thijstriemstra** [comment]
Looks related to #73, #78 and #86.

**Comment by thijstriemstra** [comment]
I think you need to call `reset` and combine it with `getDevice` @alsar.

**Comment by alsar** [comment]
@thijstriemstra `reset` works but I loose the previously recorded video (I can't play it again).
Is it somehow possible to retain the previously recorded video? 

What I want to achieve is the basically the default functionality but with the possibility that the camera gets turned off after the stop button is clicked and turned on again after start is clicked.

**Comment by thijstriemstra** [comment]
> DOMException [InvalidStateError: "An attempt was made to use an object that is not, or is no longer, usable" code: 11 nsresult: 0x8053000b

@alsar with v2.0 I'm not able to reproduce that error anymore. But when I press record again, nothing happens.. I'll look into it.

**Comment by thijstriemstra** [comment]
@alsar you can do this:

- after stop record is pressed: `player.record().stopStream()` to stop the devices
- set processing to true: `player.record()._processing = true;` (this will block the start button)
- listen for record btn click once: `player.record().controlBar.recordToggle.one(['tap', 'click'],`
- and in that callback handler you call `getDevice` and set `_processing` back to `false` (after `deviceReady` event fired) so start button works again

Does that work for you? Perhaps it can be a new option, `turnOffDeviceAfterRecord` (with a better name of course).

**Comment by thijstriemstra** [comment]
I'm thinking of adding a new option:

`autoMuteDevice`: turn off the camera and the camera's light when video recording stops, and turns the camera and light on when you resume recording.

It basically toggles `stream.getAudioTracks()[0].enabled` and `stream.getVideoTracks()[0].enabled` after pressing record and stop.

Still need to test though.

**Comment by retrocausal** [comment]
@thijstriemstra , I tried adding autoMuteDevice inside the plugin config, and nothing happened. 
I also just tried your recommended [event callback](https://github.com/collab-project/videojs-record/issues/157#issuecomment-334575397). 
this works fine for the first time when the user records a video, clicks stop. 

However, when the user clicks on record again, I get an exception thrown 

```VIDEOJS: ERROR: DOMException: Failed to execute 'start' on 'MediaRecorder': The MediaRecorder failed to start because there are no audio or video tracks available.```

Also, the controls completely disappear.

**Comment by thijstriemstra** [comment]
@retrocausal what videojs-record version, operating system, browser version etc? can you try multiple browsers?

**Comment by retrocausal** [comment]
videojs-record v 3.8.0
macOS 10.14.5 mojave
browser is chrome v75.x / firefox v 67.x

Breaks the recorder on both browsers, but firefox doesn't throw an exception.

**Comment by thijstriemstra** [comment]
please open a new ticket with some code that reproduces the problem.
