### ISSUE TITLE
Videos played by web pages can be recorded

### ISSUE THREAD

**Issue by lilyxs** [collab-project/videojs-record#158]
## Description
Use the videojs plug-in to play HLS live streams on the web page with HTML5 tags. Can you use videojs-record to record live streaming videos at the end of the page? If possible, can you tell me how to use the videojs-record related steps, thank you?

**Comment by thijstriemstra** [comment]
> Use the videojs plug-in to play HLS live streams on the web page with HTML5 tags

@lilyxs what plugin are you using for that?

**Comment by lilyxs** [comment]
RecordRTC.js and Video.js

**Comment by thijstriemstra** [comment]
@lilyxs can you show some example code?

**Comment by thijstriemstra** [comment]
no feedback. @lilyxs please reopen with feedback.
