### ISSUE TITLE
Close playback and return to recording without getDevice

### ISSUE THREAD

**Issue by bennybee** [collab-project/videojs-record#159]
Using a single player instance to record multiple videos. When finished recording - in some cases I want the user to playback what they have recorded, in other cases I want it to return straight back to webcam view while file uploads.

Is there a way to do this without using getDevice()? It keeps asking permission to use the camera when testing on HTTP. I know this isn't an issue when on HTTPS but I'm concerned it might be causing some other issues in my app. Namely that when I destroy the player the browser record icon doesn't go away.

**Comment by thijstriemstra** [comment]
@bennybee getUserMedia, the browser API that provides access to the webcam, only works on HTTPS.

**Comment by bennybee** [comment]
Ah ok, was testing in Firefox which seems to allow HTTP recording.

**Comment by thijstriemstra** [comment]
> Ah ok, was testing in Firefox which seems to allow HTTP recording.

Only on localhost afaik.

**Comment by thijstriemstra** [comment]
@bennybee you can use `player.record().startVideoPreview()` (or `player.recorder.startVideoPreview()` in older videojs-record versions) to bring back the video preview instantly. Does that work for you?

Related to #163

**Comment by bennybee** [comment]
That works, thanks. But I can't seem to get rid of the controls:

Camera inits with no controls
User records
User plays back with controls
I bring back preview and controls are still there

This is my code:

```
player.record().startVideoPreview();
player.controls(false);
```

and later when I run:

```
player.record().start();
player.controls(false);
```

The controls go again

**Comment by thijstriemstra** [comment]
@bennybee what about hiding controls with `player.controlBar.hide()`?
