### ISSUE TITLE
Preview needs setTimeout

### ISSUE THREAD

**Issue by Guiladg** [collab-project/videojs-record#161]
Why I need to use setTimeout(function(){ player.play() }, 500); for watching a preview of the recorded video? If I just use player.play() after finishRecord fires, I don't get any result.

**Comment by thijstriemstra** [comment]
@Guiladg hmm haven't seen that before. You haven't told us what version of video.js/videojs-record/recordrtc though.

**Comment by thijstriemstra** [comment]
Closing, no feedback.
