### ISSUE TITLE
preview autostart

### ISSUE THREAD

**Issue by assiomatica** [collab-project/videojs-record#162]
I need to start the camera preview without click on the player just after init, it's possible?

Thanks
Antonio

**Comment by thijstriemstra** [comment]
@assiomatica no this is not possible, browsers don't allow it. It would be a privacy nightmare if every site can start you camera without giving it permission. Closing ticket, please re-open if I misunderstood your question.

**Comment by assiomatica** [comment]
Hi thanks for quick answer,
I think my question was not clear
I should like the recorder act as this:

https://simpl.info/getusermedia/

as you can see the camera preview starts without any user action.

Thanks

**Comment by thijstriemstra** [comment]
@assiomatica I see, please try this:

```javascript
player.on('ready', function()
{
    player.recorder.getDevice();
});
```

**Comment by assiomatica** [comment]
It works! Perfect, thanks.
Excellent plugin and lighting fast support! congratulations!
