### ISSUE TITLE
Adding a video preview/stream method?

### ISSUE THREAD

**Issue by jipema** [collab-project/videojs-record#163]
## Description
In video mode, how could we re-activate the preview, after a record.stop()?
It could be useful in case of a countdown before a new recording.

## Steps to reproduce
1. player.recorder.getDevice() -> camera preview
2. player.recorder.start() -> camera preview
3. player.recorder.stop() -> recorded video cover (fixed)
4. player.recorder.start() -> camera preview

### Expected result
1. player.recorder.getDevice() -> camera preview
2. player.recorder.start() -> camera preview
3. player.recorder.stop() -> recorded video cover (fixed)

**4. player.recorder.preview() -> camera preview**

5. player.recorder.start() -> camera preview

### Actual
Using recorder.stopDevice() then recorder.getDevice() works, but the browser will ask for camera access again, which is annoying.

**Comment by thijstriemstra** [comment]
> Using recorder.stopDevice() then recorder.getDevice() works, but the browser will ask for camera access again, which is annoying.

I believe this isn't the case in Chrome, once you give permission you don't have to do it again. Can you confirm this?

**Comment by jipema** [comment]
> I believe this isn't the case in Chrome, once you give permission you don't have to do it again. Can you confirm this? <

That is correct, Chrome doesnt ask twice. But firefox does, and probably others, I have to try.


> what do you mean with "recorded video cover (fixed)"? <

The player replaced the camera feed by a still image (the first image of the recorded video).

**Comment by thijstriemstra** [comment]
> But firefox does, and probably others, I have to try.

There is a Firefox pref (`media.navigator.permission.disabled`) to disable the permission check, but this is probably not an option for you?

**Comment by thijstriemstra** [comment]
Any feedback @jipema?

**Comment by thijstriemstra** [comment]
@jipema you can use `player.record().startVideoPreview()` (for audio-video or video-only mode) to show the video preview window. The state of the play/pause/record etc will be the same. Does that work for you?

In videojs-record < v2.0.0 it's `player.recorder.startVideoPreview()`.
