### ISSUE TITLE
No audio signal in Chrome Desktop

### ISSUE THREAD

**Issue by alexthewilde** [collab-project/videojs-record#164]
## Description
The recorder doesn't receive an audio-signal in Chrome Desktop.

## Steps to reproduce
Test the [audio-only demo](https://collab-project.github.io/videojs-record/examples/audio-only.html) in Chrome v60 desktop.

### Expected
After granting permission, the recorder should receive an audio signal.

### Actual
No audio signal.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Latest.
#### browsers
Chrome Desktop v60.
Works correctly in Android Chrome, Firefox, Safari 11.

#### OSes
Tested only on Mac.

**Comment by thijstriemstra** [comment]
What version of video.js @alexthewilde (latest doesn't mean much)?

**Comment by alexthewilde** [comment]
@thijstriemstra I was using the official demo from the repo README.

Anyway, the issue seems to be gone now. It tested on multiple machines, so the issue did exist for about two days. No idea what caused it nor what fixed it.

**Comment by thijstriemstra** [comment]
Thanks for the feedback, clsoing.

**Comment by thijstriemstra** [comment]
Maybe related to #137?

**Comment by alexthewilde** [comment]
@thijstriemstra yes, this sounds very much like the issue that I've encountered.
