### ISSUE TITLE
How to upload data to server (PHP) - audio works but video does not

### ISSUE THREAD

**Issue by aveeshkumar** [collab-project/videojs-record#165]
## Description
I just thought I would give an example to newbies like myself and alert to video not being sent to server but audio works fine

## Steps to reproduce
Since I couldnt get jquery file upload or the other uploader to do it and all i wanted was a way to upload recroded file to server i just implemented it in pure JS (XHR)

audio/video are recorded and can be saved locally but on XHR uploads video does NOT populate $_FILES in PHP

### Expected
```javascript
function  upload_file(file){
formData = new FormData();
            formData.append('files_varname', 'file');
            formData.append('file', File);
            formData.append('file_dest', "video.webm");
            
            var xhr = new XMLHttpRequest();
            //xhr.setRequestHeader("Content-Type","multipart/form-data");
            xhr.open('POST', "./up5server.php", true);
            xhr.onload = function (e) {
            if (xhr.readyState === 4) {
                if (xhr.status === 200) {
                  console.log("success");
                  console.log(xhr.responseText);
                  document.getElementById("xhr_result").innerHTML = xhr.responseText; 
                } else {
                  console.error(xhr.statusText);
                }
              }
            };
            xhr.onerror = function (e) {
              console.error(xhr.statusText);
            };
            xhr.send(formData); 
}

//call elsewhere
var videoFile = player.recordedData;
upload_file(videoFile);
```
### Actual
Please describe what actually happened.
it works.

In up5server.php

look at $_POST & $_FILES
other than sanity checks the heavy weight is done by
move_uploaded_file($_FILES["video"]["tmp_name"],$file_dest);

### Error output
If there are any errors at all, please include them here.
Only audio recordings save succesfully
Video recordings record but do not populate $_FILES when uploaded - in Chrome/firefox/Androind

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
- latest ver installed uning npm 
#### browsers
what browser are affected?
#### OSes
what platforms (operating systems and devices) are affected?

**Comment by thijstriemstra** [comment]
@aveeshkumar what does your player config look like?

**Comment by aveeshkumar** [comment]
Hello,

Thx for your excellent coding!

Posting the config file below. But just wanted to say that video records coz I can click the play button to hear the recording. player.recorder.saveAs({'video': 'my-video-file-name'}); works. player.recorder.saveAs({'audio': 'my-audio-file-name'}); works too

But when I upload using XHR:
formData.append('file', player.recordedData);

works for the audio instance but not for video

On serer.php - the $_FILES variable is populated for audio but NOT for video. Code snippet below..

if (record_audioonly==1){
--
  | var player = videojs("myAudio",
  | {
  | controls: true,
  | width: 320,
  | height: 240,
  | plugins: {
  | wavesurfer: {
  | src: "live",
  | waveColor: "blue",
  | progressColor: "#2E732D",
  | debug: true,
  | cursorWidth: 1,
  | msDisplayMax: 20,
  | hideScrollbar: true
  | },
  | record: {
  | audio: true,
  | video: false,
  | maxLength: 20,
  | debug: true
  | }
  | }
  | });
  | }
  |  
  | if (record_video==1){
  | var player = videojs("myVideo",
  | {
  | controls: true,
  | loop: false,
  | controlBar: {
  | // hide volume and fullscreen controls
  | volumeMenuButton: false,
  | fullscreenToggle: false
  | },
  | width: 320,
  | height: 240,
  | plugins: {
  | record: {
  | image: false,
  | audio: true,
  | video: true,
  | maxLength: 20,
  | debug: true
  | }
  | }
  | });
  |  
  | }

**Comment by thijstriemstra** [comment]
@aveeshkumar try:

```javascript
formData.append('file', player.recordedData.video);

// or

formData.append('file', player.recordedData.audio);
```

**Comment by aveeshkumar** [comment]
hello,

It WORKED ! - thank you!

however console.log(player.recordedData.audio);

or 
console.log(player.recordedData.video);

displays undefined

Thank you Thank you!

**Comment by thijstriemstra** [comment]
Cool. I think it's different in Chrome vs. Firefox, double-check in both browsers.
