### ISSUE TITLE
Support for video.js fluid option

### ISSUE THREAD

**Issue by GordonDrop** [collab-project/videojs-record#166]
## Description
Waveform is not displayed, when option fluid is enabled.

## Steps to reproduce
1. Edit options for examples/audio-only.html 
```js
{
    controls: true,
    fluid: true,
    plugins: {
        wavesurfer: {
            src: "live",
            waveColor: "black",
            progressColor: "#2E732D",
            debug: true,
            cursorWidth: 1,
            msDisplayMax: 20,
            hideScrollbar: true
        },
        record: {
            audio: true,
            video: false,
            maxLength: 20,
            debug: true
        }
    }
}
```

2. Launch in browser

### Expected
For videojs 6.1.0: Waveform is not displayed.
![screen shot 2017-09-08 at 22 52 08](https://user-images.githubusercontent.com/5079904/30222346-b431a4d2-94e8-11e7-824a-1dcb98759c99.png)

For  5.20.3: Waveform is displayed at them bottom of the player:
![screen shot 2017-09-08 at 22 57 53](https://user-images.githubusercontent.com/5079904/30222619-303bb41e-94e9-11e7-9747-aa1fa55ee7e6.png)

### Actual
Waveform should be displayed

### Error output
No errors

#### videojs 
6.1.0, 5.20.3
#### browsers
Version 60.0.3112.113
#### OSes
MacOs

**Comment by thijstriemstra** [comment]
I worked on this a while ago in videojs-wavesurfer, see https://github.com/collab-project/videojs-wavesurfer/compare/responsive-28 and https://github.com/collab-project/videojs-wavesurfer/issues/28 but haven't found the time to complete it. Any help is greatly appreciated!

**Comment by thijstriemstra** [comment]
Update: support for the `fluid` option is available in videojs-wavesurfer when videojs-wavesurfer 2.0.0 is released. See #167 for progress on compatibility with 2.0.0 with videojs-record. Once that's done `fluid` can be properly implemented in this plugin.

**Comment by thijstriemstra** [comment]
videojs-wavesurfer 2.0.0 is released and it's working properly for audio-only modes in upcoming videojs-record 2.0.0, still need to take a look at the other modes with @ikbensiep.

**Comment by thijstriemstra** [comment]
Still need to fix it in non-audio-only modes.

**Comment by thijstriemstra** [comment]
2.0.0 is now available.
