### ISSUE TITLE
time stamp doesn't work

### ISSUE THREAD

**Issue by muhamma1** [collab-project/videojs-record#168]
I am trying to get audio in real time and using the timestamp but it is not working

![issue](https://user-images.githubusercontent.com/23171384/30815796-d1279b16-a1d9-11e7-9a7d-57376d0d36a8.png)

**Comment by thijstriemstra** [comment]
@muhamma1 what version of video.js? what version of videojs-record?

**Comment by thijstriemstra** [comment]
@muhamma1 you're using the setting `timestamp: 1` but you should use `timeSlice: 1` instead.
