### ISSUE TITLE
Add React component example

### ISSUE THREAD

**Issue by Glebasty1** [collab-project/videojs-record#171]
How can i implement this component on Reactjs?

**Comment by thijstriemstra** [comment]
This should be fairly easy once #170 is merged.

**Comment by thijstriemstra** [comment]
@Glebasty1 the master branch now contains a react component example (`examples/react/index.html`), any help testing before I release 2.0.0 would be appreciated!

**Comment by thijstriemstra** [comment]
v2.0.0 was released, see https://collab-project.github.io/videojs-record/examples/react/index.html for live demo.
