### ISSUE TITLE
is there any way to get mpeg-ts segments in timestamp event?

### ISSUE THREAD

**Issue by Hayko-1** [collab-project/videojs-record#172]

**Comment by thijstriemstra** [comment]
@Hayko-1, correct me if I'm wrong but mpeg-ts segments are something used in HLS streams, e.g. using the https://github.com/videojs/videojs-contrib-hls plugin?

**Comment by Hayko-1** [comment]
@thijstriemstra, thank you for answer. Let me describe my issue )
I'm posting recorded video blobs to server in timestamp event and saving them on HDD, simultaneously generating m3u8 playlist for HLS streaming. 
Unfortunately not all of those fragments are valid video files, so neither videojs-contrib-hls plugin nor desktop players able to play them.

**Comment by thijstriemstra** [comment]
can you show some example code? inc player config etc

**Comment by Hayko-1** [comment]
@thijstriemstra 
var player = videojs("myVideo",
        {
            controls: true,
            width: 320,
            height: 240,
            controlBar: {
                volumeMenuButton: false,
                volumePanel: false
            },
            plugins: {
                record: {
                    audio: false,
                    maxLength: 100,
                    frameWidth: 320,
                    frameHeight: 240,
                    timeSlice: 1000,
                    videoMimeType: 'video/webm;codecs=H264',
                }
            }
        });

    var segmentNumber = 0;
    player.on('timestamp', function () {
        if (player.recordedData && player.recordedData.length > 0) {
            var binaryData = player.recordedData[player.recordedData.length - 1];

            segmentNumber++;

            var formData = new FormData();
            formData.append('SegmentNumber', segmentNumber);
            formData.append('Data', binaryData);

            $.ajax({
                url: '/api/Test',
                method: 'POST',
                data: formData,
                cache: false,
                processData: false,
                contentType: false,
                success: function (res) {
                    console.log("segment: " + segmentNumber);
                }
            });
        }
    });

Saving files on server. I know those files are just splitted parts of video that has to be merged for playback, so after merging I'm using ffmpeg to get transport stream segments that can be used in m3u8 playlist and the player handles it.

ffmpeg -i C:\Projects\...\live\stream.webm -codec:a copy -codec:v libx264 -r 30 -g 30 -f segment -segment_time 1 -segment_format mpegts C:/Projects/.../live/segment-%03d.ts

Now I want to get rid of ffmpeg operations on server side, because it's too expensive. 
Is there a way to get transport stream segments in timestamp event?

**Comment by thijstriemstra** [comment]
> Is there a way to get transport stream segments in timestamp event?

I'm not too familiar but there are client-side libraries like https://github.com/uupaa/M3U8.js that might be able to do it and otherwise there's this javascript version of ffmpeg: https://github.com/Kagami/ffmpeg.js

**Comment by Hayko-1** [comment]
@thijstriemstra, It's not playlist generation issue.
I've changed my server implementation, so besides collecting blobs into a file I'm passing blobs to ffmpeg as they arrive from the client. Everything's great except the 4 sec delay. 
I've dug deeper into RecordRTC and MediaRecorder API and found out that it generates WebM video with keyframes every 2 sec, so ffmpeg is waiting for keyframes to generate mpegts segments, that's why I'm getting video with 4 sec delay. Now I'm trying to reduce it.
I don't want it, but I'm about to start digging into Chromium source codes. (( 
I know that my new issue is out of scope videojs-record, but maybe you can give me some advice how can MediaRecorder API produce keyframes more often.

**Comment by thijstriemstra** [comment]
@Hayko-1 I think @muaz-khan might know some more about that.
