### ISSUE TITLE
Video is not playing in Opera on MacOS

### ISSUE THREAD

**Issue by uvytautas** [collab-project/videojs-record#174]
## Description
Video starts recording but after recording is finished error comes out: 
**The media could not be loaded, either because the server or network failed or because the format is not supported.**
## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
1. Start recording
2. Finish recording
3. Try to play record
## Results
Error, that format is not supported
### Expected
To see recorded clip

### Error output
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 

#### videojs
6.2.8
#### browsers
Opera 48.0.2685.50 
#### OSes
Mac OS X

**Comment by thijstriemstra** [comment]
@uvytautas how does your player config look like?

**Comment by uvytautas** [comment]
@thijstriemstra 
```
let player = videojs("myVideo", {
        controls: false,
        width: 160,
        height: 80,        
        fluid: true,
        controlBar: {
            volumePanel: false,
            fullscreenToggle: false
        },


        plugins: {
            record: {
                audio: false,
                video: {facingMode: 'environment'},
                maxLength: 60,
                debug: true,
                timeSlice: 500
            }
        }
    });
```

**Comment by uvytautas** [comment]
I get same error at demo page : https://collab-project.github.io/videojs-record/examples/video-only.html

**Comment by thijstriemstra** [comment]
@uvytautas I've never tested against Opera, I thought it would be similar to Chrome nowadays. Can you reproduce this error in other browsers?

**Comment by uvytautas** [comment]
@thijstriemstra  Mozilla and Chrome works perfectly.

**Comment by thijstriemstra** [comment]
I've installed Opera using https://deb.opera.com/manual.html and will take a look.

**Comment by thijstriemstra** [comment]
@uvytautas tested https://collab-project.github.io/videojs-record/examples/video-only.html with Opera:

```
48.0.2685.50
Ubuntu 16.04.3 LTS (x86_64; Unity)
```

and that works fine.

**Comment by uvytautas** [comment]
@thijstriemstra That is strange, because I get this error (https://imgur.com/a/iFGRU) when recording is completed.
Even though I am using the same version `48.0.2685.50 ` but in `Mac OS X 10.12.6`

**Comment by thijstriemstra** [comment]
@uvytautas I will take a look and test on OSX Opera at some point. What error does the browser console display for you?

**Comment by uvytautas** [comment]
@thijstriemstra `VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported.`

**Comment by thijstriemstra** [comment]
@uvytautas but there must be more console log messages than that. Can you make a screenshot of the full console log and attach it here?

**Comment by thijstriemstra** [comment]
Tested on OSX Opera and didn't get any errors but couldn't playback the video file. Fortunately I could reproduce the issue with https://www.webrtc-experiment.com/RecordRTC/ so it's not a bug in this plugin. I've opened a ticket for RecordRTC: https://github.com/muaz-khan/RecordRTC/issues/347

**Comment by thijstriemstra** [comment]
@muaz-khan provided the solution: https://github.com/muaz-khan/RecordRTC/issues/347#issuecomment-340236258

Can you try this setting @uvytautas:

```javascript
videoMimeType: 'video/webm\;codecs=vp8' // or vp9
```
