### ISSUE TITLE
Stream Upload Videos

### ISSUE THREAD

**Issue by AdamHess** [collab-project/videojs-record#176]
Offer the ability to stream upload to server. 

I imagine this could be triggered on a timer or on a certain file size where the web browser will chop the file into a chunk and then send it up to a server Part of the configuration would indicate what url to hit for a post/upload request. (Unless there is another recommended file upload/stream process that's recommended)

**Comment by thijstriemstra** [comment]
I think what you're describing is already possible but not properly documented yet.

**Comment by thijstriemstra** [comment]
@AdamHess is this basically what you're describing? https://github.com/collab-project/videojs-record/issues/172#issuecomment-338578813

**Comment by AdamHess** [comment]
sounds like it.
