### ISSUE TITLE
Not recording video in Microsoft Edge browser

### ISSUE THREAD

**Issue by bennybee** [collab-project/videojs-record#178]
Having issues with my app not recording in Edge. When looking at the demo page:

https://collab-project.github.io/videojs-record/examples/audio-video.html

In Edge I intialise the camera fine but when I click record nothing happens. There are no console errors. 

Records fine in Chrome on the same device.

#### videojs
videojs version : 6.2.8
videojs-record version : 2.0.0
#### browsers
Edge: 38.14393.1066.0
EdgeHTML: 14.14393
#### OSes
Windows 10

**Comment by thijstriemstra** [comment]
Thanks for the report. Unfortunately I don't have access to windows 10 but I can try it on a windows 7 machine.

**Comment by thijstriemstra** [comment]
@bennybee what happens when you run https://www.webrtc-experiment.com/RecordRTC/ on that browser?

**Comment by bennybee** [comment]
Ah, that only allows me to record audio

**Comment by thijstriemstra** [comment]
See https://github.com/muaz-khan/RecordRTC/issues/353

**Comment by thijstriemstra** [comment]
Same issue, Edge does not support MediaRecorder yet, see https://caniuse.com/#feat=mediarecorder

**Comment by thijstriemstra** [comment]
Also see https://developer.microsoft.com/en-us/microsoft-edge/platform/status/mediarecorder

**Comment by thijstriemstra** [comment]
Check the [Browser support](https://github.com/collab-project/videojs-record/wiki/Browser-support) wiki page to check current browser compatibility with this plugin.

**Comment by thijstriemstra** [comment]
Luckily [Edge will use Chromium](https://www.theverge.com/2018/12/6/18128648/microsoft-edge-chrome-chromium-browser-changes) in the future.

**Comment by sdb1228** [comment]
So looks like edge 44 is out and looks like they have release versions for mac coming out https://www.microsoftedgeinsider.com/en-us/download/

Anyone checked on this recently?

**Comment by thijstriemstra** [comment]
Ah yes, saw the news today. Might give it a try at some point.

**Comment by sdb1228** [comment]
I may have some time tonight as well.  What has been the easiest way to test it out? Do we have a test url or do you just make a toy app and import the package in?

**Comment by thijstriemstra** [comment]
Try any of the examples on https://collab-project.github.io/videojs-record

**Comment by sdb1228** [comment]
Update tried this on the dev and canary release for mac and it crashed the browser...
https://www.dropbox.com/s/0kleatg06h9sbte/Screenshot%202019-05-08%2007.38.19.png?dl=0

**Comment by sdb1228** [comment]
Hey @thijstriemstra do you have a issue to fix the examples page? https://collab-project.github.io/videojs-record/examples/audio-video.html is giving me ```RecordRTC is not defined``` Looks like edge is no longer crashing with the library but non of the browsers I tried is working with the example :(

**Comment by thijstriemstra** [comment]
@sdb1228 thanks for the heads up, it's broken indeed! I will fix the CDN urls, something broke with https://cdn.webrtc-experiment.com/RecordRTC.js

**Comment by thijstriemstra** [comment]
@sdb1228 should be fixed now.

**Comment by sdb1228** [comment]
Awesome and it works in the edge canary release on mac! Thanks for your hard work this is good news 👍

**Comment by thijstriemstra** [comment]
I guess this can be marked as won't fix now that Edge switched to Chromium-based builds. A.k.a they'll never upgrade the original Edge browser for MediaRecorder support?

**Comment by erikkrantzkb** [comment]
It looks like Edge supports MediaRecorder now. I do not have the possibility to test it though.
https://caniuse.com/#feat=mediarecorder

**Comment by thijstriemstra** [comment]
I tested Microsoft Edge in the following browsers with videojs-record 4.2.0 and videojs 7.11.4.

| Platform Version | Edge Version |
| --- | --- |
| Mac OS X 10.15.7 | 88.0.705 |
| Windows 10 | 88.0.705 |

And was able to record audio+video with the default settings, e.g.:

```javascript
let options = {
    // video.js options
    controls: true,
    bigPlayButton: false,
    loop: false,
    fluid: false,
    width: 320,
    height: 240,
    plugins: {
        // videojs-record plugin options
        record: {
            audio: true,
            video: true,
            maxLength: 15,
            displayMilliseconds: true,
            debug: true
        }
    }
};
```

I will update the supported browsers documentation and consider this fixed.
