### ISSUE TITLE
How to execute some events from Javascript.

### ISSUE THREAD

**Issue by jabrena** [collab-project/videojs-record#18]
Testing the example:
https://collab-project.github.io/videojs-record/examples/audio-video.html

It is necessary to interact with the skin to configurate the player to connect with camera and mic.

I would like to execute this methods using a HTML buttons. How to execute the webcam configuration and the event to start recording?

Many thanks in advance

Juan Antonio

**Comment by thijstriemstra** [comment]
See https://github.com/collab-project/videojs-record#methods. Use `getDevice` to start the camera, `stopDevice` to stop it again. `start` and `stop` aren't documented there but use those to start/stop recording.
