### ISSUE TITLE
Can't record video in Safari

### ISSUE THREAD

**Issue by bennybee** [collab-project/videojs-record#181]
Safari 11 added getUserMedia Support in Sept 2017, more details here: https://webkit.org/blog/7763/a-closer-look-into-webrtc/

When looking at the demo page:

https://collab-project.github.io/videojs-record/examples/audio-video.html

I initialise the camera, click record and camera starts recording. I click stop and it stops recording but no playback button appears.

Plays back fine in Chrome on the same device.

Get following console error:
```
GetRecorderType is not a constructor (evaluating 'new Recorder (mediaStream, config) 

from RecordRTC.j:87
```
**versions**

**videojs**

videojs version : 6.2.8
videojs-record version : 2.0.0

**browsers**

Safari v11

**OSes**

Mac OS 10.12.6

**Comment by thijstriemstra** [comment]
Can you reproduce this with a recordrtc.js example? i think the bugs there.

**Comment by thijstriemstra** [comment]
Related issue: https://github.com/muaz-khan/RecordRTC/issues/324

**Comment by thijstriemstra** [comment]
Opened https://github.com/muaz-khan/RecordRTC/issues/351

<img width="774" alt="screen shot 2017-11-08 at 20 30 13" src="https://user-images.githubusercontent.com/305679/32570341-22f5d478-c4c4-11e7-93ca-72b0c62e70e8.png">

**Comment by thijstriemstra** [comment]
@bennybee a new version (5.4.5) of recordrtc was published a few days ago, have you tried that yet?

**Comment by thijstriemstra** [comment]
Getting `TypeError: undefined is not an object (evaluating 'riff.RIFF[0]')` with recordrtc 5.4.6...

**Comment by thijstriemstra** [comment]
Basically Safari does not have MediaRecorder support yet, see https://caniuse.com/#feat=mediarecorder When that becomes available we can look at this again but till then it's [audio-only](https://github.com/muaz-khan/RecordRTC/issues/275#issuecomment-307142681).

**Comment by thijstriemstra** [comment]
Changed the ticket title to reflect that audio-only and image-only recording do work in Safari (tested with 11.0.3), it's video recording that doesn't (using recordrtc).

**Comment by octavn** [comment]
>Basically Safari does not have MediaRecorder support yet

This [bug report](https://bugs.webkit.org/show_bug.cgi?id=85851) on bugs.webkit.org tracks the MediaRecorder implementation in WebKit and thus Safari. 

I encourage everyone to show their interest and [add a comment](https://bugs.webkit.org/show_bug.cgi?id=85851) describing how a MediaRecorder implementation would help their project/development. Creating an account takes a second.

**Comment by dirkk0** [comment]
good idea. done.

**Comment by rbjarnason** [comment]
With ever-growing mobile usage, we're at about 65% for our websites, Safari iOS support is really important for us and we'd be happy to spend some time to help if there could be some sort of a workaround either in videojs-record or RecordRTC.

Plan B is to use WebRTC recording on the server using Kurento but using videojs-record would be easier and wouldn't have to worry about live bandwidth quality issues. Does anybody have any pointers in what direction to look for work-arounds?

I've been testing the audio-video.html example on iPhone 8 and it does not show the live video, if I click on the record button I go into a full screen live preview panel and when I click the X I go back to the browser and now I have a single static camera frame from what I just recorded. So an image has been captured.

I've then ran the same test on BrowserStack on an iPhone 10 with DevTools and captured the errors. They seem all to have to do with "play".

Here is the first one that happens after you have clicked on the camera icon and given system permissions to use the camera and microphone.
![image](https://user-images.githubusercontent.com/43699/44539493-d542f900-a6f3-11e8-843b-b6e510624745.png)

Then I click the record button and get a fullscreen dialog:
![image](https://user-images.githubusercontent.com/43699/44539567-06bbc480-a6f4-11e8-9ee5-a94073bbfa4d.png)

![image](https://user-images.githubusercontent.com/43699/44539641-3a96ea00-a6f4-11e8-90a6-35902295ea90.png)

**Comment by rbjarnason** [comment]
Regarding those play errors, could it be that we're hitting auto-play policy issues? https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/

**Comment by thijstriemstra** [comment]
@rbjarnason I unfortunately do not have access to an iphone to test. If you can send me a fairly recent one I'll surely be able to fix all outstanding iOS bugs.

**Comment by rbjarnason** [comment]
@thijstriemstra I wish we could! :) But we are a small nonprofit working on open source software largely volunteer based. We run citizen crowdsourcing & participatory budgeting platforms and are working on adding audio/video based ideas and debates to the platform.

I will dig around a bit and see if I can work out the iOS auto-play issue and if that is the problem at all. Also, as an open source project, we are sponsored with free testing at BrowserStack and I can add you there to look at this problem, real iOS phones hooked up to the Chrome console, if you want and have the time ;) Actually aside from that you can probably get a BrowserStack open source account for this project.

**Comment by rbjarnason** [comment]
Update: By adding the and muted and playsinline to the <video> element for the demos, videojs-record does not crash. Then after commenting out 3x video.play() in RecorderRTC.js the live preview works and I can see whammy frame being added when I record but I get no playback on iOS and in onRecordComplete() there is nothing coming into this.player.recordedData. I will continue to investigate...

**Comment by rbjarnason** [comment]
Final results on this for now. I managed to record frames using canvas but not assembling them on the client as Safari doesn't support webm, even if that would be possible with webworker then it would be slow on the client at 25 fps. Sending the frames over to the server for assembly is possible but png frames are very large even if you would send them as binaries with web sockets every second or so. I've now researched locally recording a WebRTC stream on Safari quite a bit and there seems not to be any practical solutions yet. Please if anybody has any suggestions please let me know.

In the meantime, I'm working on implementing a recording solution using Kurento where the video is recorded on the server side through a live WebRTC stream. I'm still considering if I should use this solution for all browsers or just for Safari.

**Comment by thijstriemstra** [comment]
> Final results on this for now. I managed to record frames using canvas but not assembling them on the client as Safari doesn't support webm, even if that would be possible with webworker then it would be slow on the client at 25 fps

Thanks for all the valuable feedback. To summarize:

- MediaRecorder does not work natively on Safari yet 
- Whammy does not support Safari (or vice versa)

So Safari can not be supported right now.

**Comment by thijstriemstra** [comment]
Check the [Browser support](https://github.com/collab-project/videojs-record/wiki/Browser-support) wiki page to check current browser compatibility with this plugin.

**Comment by octavn** [comment]
videojs-record relies on RecordRTC which relies mainly on the `MediaRecorder` object from the [MediaStream Recorder API](https://www.w3.org/TR/mediastream-recording/) to record video. 

Safari 11 and 12 do not support the MediaStream Recorder API.

There is a [bug report](https://bugs.webkit.org/show_bug.cgi?id=85851) filled thus if you want native video recording in Safari you can help by commenting on it and explaining your use case.  

Recently the bug's status changed to "under consideration" so there is a slight chance we will see the feature in Safari 13 next year.

**Comment by THEozmic** [comment]
@rbjarnason I'm curious at to what tool you're using to debug on mobile here: 

https://user-images.githubusercontent.com/43699/44539493-d542f900-a6f3-11e8-843b-b6e510624745.png

**Comment by rbjarnason** [comment]
@THEozmic I was using BrowserStack and their tools.

**Comment by thijstriemstra** [comment]
@taiphamhdweb nope, if it ever gets implemented in Safari, this ticket will be updated.

**Comment by taiphamhdweb** [comment]
Thanks you @thijstriemstra

**Comment by voordev** [comment]
Same issue, shame Apple does not give this priority. 
Then we would have an almost cross platform solution. 
Uploading prevents skipped frames and other issues with network connectivity.

**Comment by thijstriemstra** [comment]
Good news! They've started implementing: https://trac.webkit.org/changeset/237106/webkit/

Also mentioned here: https://webkit.org/blog/8475/release-notes-for-safari-technology-preview-68/

**Comment by thijstriemstra** [comment]
Downloaded Safari Preview 73 and there it is:

<img width="661" alt="screenshot 2019-01-10 at 14 46 25" src="https://user-images.githubusercontent.com/305679/50972486-0ecfa180-14e7-11e9-8e64-746a3b466e69.png">

Time to test..

**Comment by voordev** [comment]
That is awesome news !

**Comment by thijstriemstra** [comment]
Safari 12 also doesn't support MediaRecorder unfortunately, we'll have to wait till v12 I guess. See #332

**Comment by fabyeah** [comment]
MediaRecorder hasn't landed in Safari 13 either. Any guesses when this will come? So at least not until Safari 14 in September, in another 9 months? 😢

**Comment by octavn** [comment]
A partial implementation of the MediaStream Recorder API was introduced 1 year ago in Safari Technology Preview 73 but never made it to production Safari.

https://blog.addpipe.com/safari-technology-preview-73-adds-limited-mediastream-recorder-api-support/

**Comment by thijstriemstra** [comment]
Safari team is either understaffed, incompetent or scared of shipping new features, I don't know. I do know it's a shit browser.

**Comment by dankleying** [comment]
> Downloaded Safari Preview 73 and there it is:
> 
> <img alt="screenshot 2019-01-10 at 14 46 25" width="661" src="https://user-images.githubusercontent.com/305679/50972486-0ecfa180-14e7-11e9-8e64-746a3b466e69.png">
> 
> Time to test..

Thanks for the reply. But in production how can we tell the users to allow this? Is there a way to enable MediaRecorder by code? Thank you in advance.

**Comment by thijstriemstra** [comment]
> Is there a way to enable MediaRecorder by code? 

No. If there was I would consider it a security issue in Safari.

**Comment by dankleying** [comment]
> If there was I would consider it a security issue in Safari.

Just a follow-up. Since other browsers(Chrome, Firefox) allow recording, why is it an issue in Safari? Can you share some insights? Thank you.

**Comment by thijstriemstra** [comment]
> No. If there was I would consider it a security issue in Safari.

I meant, enabling a Experimental Feature shouldn't be possible from JS.
