### ISSUE TITLE
Installing without npm or bower

### ISSUE THREAD

**Issue by mooglife** [collab-project/videojs-record#184]
I would like to use your video-recorder but I do not have npm or bower installed. is it possible to install and use our plugin without installing npm/bower. for example, simply including the packages, if yes then could you please guide me a little?

Thank you!

PS: pardon me for the simplicity of the question, I hope it is possible and is not a great effort for you to outline.

**Comment by aveeshkumar** [comment]
download the master branch as a zip. unzip and use

**Comment by thijstriemstra** [comment]
Downloading master branch is not a solution because it doesn't contain compiled dist folder. You should download the .zip from releases which contains the dist folder and use that (and also download the other dependencies mentioned in the readme). Let me know how that works out!

**Comment by mooglife** [comment]
Thanks Aveeshkumar and Thijstriemstra!

My only mistake was not reading "readme" file. Nevertheless, I downloaded the release and dependencies. placed them all in a folder, tweaked the example file to link the the files and it works like a charm. 

Note: do not forget the webrtc-adapter. Thats the final piece of the puzzle ;)

**Comment by thijstriemstra** [comment]
@mooglife good point. Glad you figured it out, cheers.

**Comment by thijstriemstra** [comment]
I will add that webrtc-adapter dependency to the readme.

**Comment by inikonorov** [comment]
@mooglife Can you send me your folder with release and dependencies on mail nikonorov1000@gmail.com, please? Thanks!

**Comment by thijstriemstra** [comment]
@inikonorov have you tried the instructions at https://github.com/collab-project/videojs-record#examples?

**Comment by inikonorov** [comment]
@thijstriemstra yeah, I tried this instructions, but something went wrong

**Comment by inikonorov** [comment]
@thijstriemstra and I don't know how to upload node_modules on hosting, just like other files?

**Comment by thijstriemstra** [comment]
@inikonorov let's continue this conversation in https://github.com/collab-project/videojs-record/issues/186
