### ISSUE TITLE
Problem with font path in dist css files.

### ISSUE THREAD

**Issue by IvanKuzyshyn** [collab-project/videojs-record#185]
## Description
videojs.record.css and videojs.record.min.css contains wrong font path. When i try to import this file, for example, into my style bundle webpack crashes.  

## Steps to reproduce
1 `npm i videojs-record --save`
2 `@import (css) "~videojs-record/dist/css/videojs.record.css";`

### Expected
That it file will be imported and build will be successfull

### Actual
Webpack could not resolve wrong path and crashes.

### Error output
If there are any errors at all, please include them here.

## Additional Information
version is 2.0.1

**Comment by IvanKuzyshyn** [comment]
Looks like we need to change this command like this `"build:fonts": "copy font/*.{eot,svg,ttf,woff} dist/"` and in _icons.scss set up this `$icon-font-path: '../font' !default;`

**Comment by thijstriemstra** [comment]
Thanks for the report. There's definitely something wrong with the copying of the font, I'll take a look.

**Comment by thijstriemstra** [comment]
@IvanKuzyshyn I pushed a fix to master, can you check if this fixes the problem for you? I'll release 2.0.2 asap.

**Comment by IvanKuzyshyn** [comment]
Yes, for now everything works fine!
Thanks a lot!
