### ISSUE TITLE
Failed to build resources on Windows

### ISSUE THREAD

**Issue by inikonorov** [collab-project/videojs-record#186]
During I install dependencies via node.js it shows such errors as: 
1. Failed to load resource: the server responded with a status of 404 (Not videojs.record.css found) or (Not video.js.record.js found)
2. Uncaught Error: plugin "record" does not exist (video.min.js:5)
What should I do?

**Comment by thijstriemstra** [comment]
@inikonorov can you show me some example code, how are you loading this?

**Comment by inikonorov** [comment]
1. Clone git
![image](https://user-images.githubusercontent.com/30556799/33286434-1f7cfc78-d3d7-11e7-89d3-30bc10ddd2a0.png)

2. Install dependencies
![image](https://user-images.githubusercontent.com/30556799/33286540-7adf72f8-d3d7-11e7-943c-27fe1ca45f4d.png)

3. npm start
![image](https://user-images.githubusercontent.com/30556799/33286560-8b4148c4-d3d7-11e7-80ef-3a8421381a9c.png)

4. developer tools 
![image](https://user-images.githubusercontent.com/30556799/33286585-a13f6548-d3d7-11e7-89ed-72bc72ec2ff0.png)

**Comment by thijstriemstra** [comment]
I see, let me take a look.

**Comment by inikonorov** [comment]
look at what?

**Comment by thijstriemstra** [comment]
> look at what?

At what could be wrong on your side (or buggy in this library).

**Comment by inikonorov** [comment]
I just tried to do this instructions
https://github.com/collab-project/videojs-record#examples

Error appears during npm start (look at screen - no such file or directory)
Sorry for my english :)

I don't understand completely what should I show you

**Comment by thijstriemstra** [comment]
@inikonorov hehe don't worry, it wasn't a request for you, I'm going to try to reproduce that error, just sit tight and I'll get back to you ;)

**Comment by inikonorov** [comment]
oh, thank you :)

**Comment by thijstriemstra** [comment]
@inikonorov what operating system are you using? And what version of node and npm? e.g. try running following commands and paste the output (or screenshot):

```
npm --version
```

```
node --version
```

**Comment by inikonorov** [comment]
win 10
npm 5.5.1
node 8.9.1

**Comment by thijstriemstra** [comment]
@inikonorov I've setup a windows build and I can recreate the issue which is good. See log at https://ci.appveyor.com/project/thijstriemstra/videojs-record/build/job/wfd4qlcv7d37n8cg

Now to fix it..

**Comment by thijstriemstra** [comment]
@inikonorov can you do a `git pull` and try again?

**Comment by inikonorov** [comment]
yeah, one second

**Comment by inikonorov** [comment]
hmm, the same error
i tried to clone again and node shows the same error

**Comment by inikonorov** [comment]
![image](https://user-images.githubusercontent.com/30556799/33302154-0a1f96fc-d41c-11e7-8a80-c6fe369ba372.png)

**Comment by inikonorov** [comment]
![image](https://user-images.githubusercontent.com/30556799/33302162-11acfe6e-d41c-11e7-8d96-8887dac557b9.png)

**Comment by thijstriemstra** [comment]
Ok thanks for the feedback I'll take a look at it again.

**Comment by inikonorov** [comment]
thank you very much, you're the best support i've ever seen 🥇

**Comment by inikonorov** [comment]
i can try to do this on Linux, but I have a question - what should i do with node_modules if I want to upload files to hosting? just upload this folder?

**Comment by thijstriemstra** [comment]
> thank you very much, you're the best support i've ever seen :1st_place_medal:

i'm 'always poor, never bored' ;)

**Comment by thijstriemstra** [comment]
i'd like to get it working on windows, i imagine many people tried this on windows and failed, so I'm glad you raised the issue. Never thought about the windows build :-/

**Comment by inikonorov** [comment]
yeah, i think many people tried this on windows too 
if you need anything from me - i'm ready :)

**Comment by thijstriemstra** [comment]
@inikonorov can you upgrade npm/node to version 9 and see if that makes a difference?

**Comment by inikonorov** [comment]
yeah, of course
after university i'll write you

**Comment by inikonorov** [comment]
the same error
![image](https://user-images.githubusercontent.com/30556799/33318848-0d3b3eee-d45e-11e7-8f25-ebc710fbe697.png)

**Comment by inikonorov** [comment]
versions
![image](https://user-images.githubusercontent.com/30556799/33318874-29667a02-d45e-11e7-80ad-6d1671707cb4.png)

**Comment by thijstriemstra** [comment]
@inikonorov can you attach the full log file (as noted at bottom of error), e.g. `2017-11-28T12_03_02_719Z-debug.log?`

**Comment by inikonorov** [comment]
of course
[2017-11-28T12_03_02_719Z-debug.log](https://github.com/collab-project/videojs-record/files/1510826/2017-11-28T12_03_02_719Z-debug.log)

**Comment by thijstriemstra** [comment]
@inikonorov i was able to reproduce your error and improved some things. Can you do:

- a fresh git checkout
- `npm install` (there is a new dependency)
- `npm run build` (so things like the fonts and other assets get build)
- `npm run start` (make sure to use `npm run start`, i think you used `npm start` before)

**Comment by inikonorov** [comment]
woohoooo! everything is work, thank you very much :)

**Comment by inikonorov** [comment]
but i still have a question, help me please, if you know anything about it - what should I do with node/npm, if I want to upload this files on hosting?

**Comment by inikonorov** [comment]
can I just upload node_modules folder?

**Comment by inikonorov** [comment]
and I wanted ask you - can I ask you some questions about videojs? and if i can do this, where does it do better?

**Comment by thijstriemstra** [comment]
@inikonorov you move the javascript, css and html files onto a webserver, not the whole node_modules directory. Use a site like stackoverflow.com for video.js questions or their github page.

**Comment by inikonorov** [comment]
nono, i was wrong, i wanted write "some questions about videojs-record" of course :)

**Comment by thijstriemstra** [comment]
Yea this is the right place.

**Comment by inikonorov** [comment]
okay, thank you very much, i'm very appreciate your support 🥇 
i try to read some information about videojs-record and fine-uploader and make some experiments, if something goes wrong, I'll write you :)

**Comment by thijstriemstra** [comment]
v2.0.3 with the fixes has been released, closing.

**Comment by priyach21** [comment]
Hi I am facing issue with video recording and got the below issue
![issuewithvideorecording](https://user-images.githubusercontent.com/42860064/44897532-a2af8680-ad19-11e8-9def-d5f39db7a9a6.png)
