### ISSUE TITLE
Support for Firefox mobile

### ISSUE THREAD

**Issue by jabrena** [collab-project/videojs-record#19]
Hi, I am testing the solution in a Firefox mobile to upload a .webm file to the server, but current code only upload audio but if I test the same example in a Firefox for Desktop, the code runs nice.

What is the mobile support for videojs-record?

**Comment by thijstriemstra** [comment]
Recording is based on recordrtc (https://github.com/muaz-khan/RecordRTC). There's no specific note about mobile browsers there. It's also something I haven't tested yet. What kind of output do you see in the console from recordrtc? And what does this demo do: https://www.webrtc-experiment.com/RecordRTC/AudioVideo-on-Firefox.html

**Comment by jabrena** [comment]
Hi, this evening I have debugged using the output from upload folder only, and I noticed that I only receive audio, but tomorrow I will try to learn how use the remote debugging with FF Mobile. 
Today, I have tested:

``` 
FF for Android Tablet
FF Beta for Android Tablet
FF with Desktop emulation
```

Tomorrow, I will notify any progress.

Juan Antonio

**Comment by jabrena** [comment]
I tested but for me, I couldn't run that example on FF for OSX:
https://www.webrtc-experiment.com/RecordRTC/AudioVideo-on-Firefox.html

**Comment by mqliutie** [comment]
The same problem. I run [examples/video-only.html](https://graduation.avosapps.com/videojs/examples/video-only.html). It can't run correctly on firefox mobile on Android

**Comment by thijstriemstra** [comment]
Whats exactly the issue @mqliutie?

**Comment by mqliutie** [comment]
@thijstriemstra 
I want to record with browser on mobile . I searched this repository it works well on PC , when I want to test how it show me on mobile, like [it](https://graduation.avosapps.com/videojs/examples/video-only.html). I clicked that icon to record and it no reaction. 

I don't know if you can understand what i said. sorry, my English is not very good

**Comment by thijstriemstra** [comment]
I added some commits that hide the native controls overlaying the interface (also needs a line of css, see one of the examples).

Animated GIF, all the audio examples and the image example worked fine on this Samsung galaxy tab using "Mozilla/5.0 (Android 4.2.2; Tablet; rv:43.0) Gecko/43.0 Firefox/43.0".

But the video-only and audio-video examples failed.

The video-only example threw this error related to MediaRecorder it seems:

```
The UA cannot provide the codec or recording option that has been requested. error
{ target: MediaRecorder, isTrusted: true, name: "GenericError", currentTarget: MediaRecorder, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1453076787372254, originalTarget: MediaRecorder, explicitOriginalTarget: MediaRecorder }
``` 
And the audio-video example produced some webm according to the console log, but neither video or audio was present during playback.

**Comment by thijstriemstra** [comment]
Let's open specific issues for video-only, audio-video example failures, closing this.
