### ISSUE TITLE
How to install the package correctly with Bower?

### ISSUE THREAD

**Issue by priMo-ex3m** [collab-project/videojs-record#191]
I'm new to front-end technologies like` npm or bower`. I spend some hours to read and a little bit understand how it should work.
I'm using Ubuntu 16.04, I installed nodejs, npm, bower globally.
Next, I created a .bowerrc file in kernel directory of my website.
I put in this file:
```
{ 
    "directory": "public/lib" 
}
```
I also have a bower.json file in my kernel directory with following content : 
```
{
  "name": "project",
  "description": "Jobi.md project",
  "main": "",
  "license": "MIT",
  "homepage": "",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "videojs-record": "^2.0.3"
  }
}

```
Then, In kernel directory of the project I wrote - "bower install" and in public/lib appears following folders : 
recordrtc, video.js, videojs-record, videojs-wavesurfer, wavesurfer.js, webrtc-adapter.
They totally have 23.3 MB.
And this folders are not enough for running the project with links to CSS and JS files.

Then, somehow I did some similar stuff out of my project, and obtain folders : dist, dist-test, docs, es5, examples, font, lang, node_modules, scripts, src, test and simple files : appyevor.yml, bower.json, CHANGES.md, LICENSE, package.json, package-lock.json, README.md
They all have 212.9 MB and this structure is enough for running examples and so on.

The question is : How is the correct procedure of installing the package with bower in the project?
If all that files  must really have 212.9 MB, does they need to be in /public directory of the website? This will not slow speed of website?
If it's another way how to structure this folders and files inside a /vendor directory of the project and to reference to it's files by shortcuts when connecting css and javascripts to HTML ?

Please, give a full guide of installation, placing and referencing to required files in <html>. Thanks!

**Comment by thijstriemstra** [comment]
You can follow the instructions here (usng npm): https://github.com/collab-project/videojs-record#examples

**Comment by thijstriemstra** [comment]
No further feedback, closing.
