### ISSUE TITLE
TypeError: player.recorder is undefined

### ISSUE THREAD

**Issue by cloudstudio** [collab-project/videojs-record#193]
## Description
Hello! thanks in advance.

I start working with this library, when i try to use : 

```
player.on('finishRecord', function() {
    player.recorder.saveAs({'video': player.recordedData.name});
    console.log('finished recording: ', player.recordedData);
});
```

I get 

`TypeError: player.recorder is undefined`

I can't find more information about it.

**Comment by thijstriemstra** [comment]
Use `record()` instead:

```javascript
player.on('finishRecord', function() {
    // show save as dialog
    player.record().saveAs({'video': 'my-video-file-name.webm'});
});
```

I see it's a typo in the docs that i'll fix.

**Comment by prathibhatvm** [comment]
player.recordedData.video: undefined
