### ISSUE TITLE
Error with video.js 6.6.0

### ISSUE THREAD

**Issue by IvanKuzyshyn** [collab-project/videojs-record#198]
## Description
I have a factory that get config and create `videojs` instances. When i create image capturing instance with parameters: `image: true, audio: false, video: false,` everything works fine. But when create video recording instance with this config: `image: false, video: true, audio: true,` device an error occurs.

One more thing...
When error occurs property `deviceErrorCode` in my instance has next error message:
`this.engine.on is not a function`.
It looks like it falls on this lines
`
this.engine.on('recordComplete', this.engineStopCallback);
`  
And i found that neither `this.engine` object not it prototype has no `on` method. 

I checked it in Chrome and Firefox browsers.

So i really don't know what exactly had caused this problem but it is really important.

Thanks for your help.

**Comment by thijstriemstra** [comment]
@IvanKuzyshyn always include operating system, browser versions and videojs/videojs-record/recordrtc versions in a bugreport.

**Comment by IvanKuzyshyn** [comment]
@thijstriemstra yes, sure
Version of package: "videojs-record": "^2.0.5"
Chrome version: Version 63.0.3239.132 (Official Build) (64-bit)
Firefox version:  57.0.4 (64-біт)

This problem was tested with:
- Mac OS Hight Siera
- ubuntu/xenial64

Also I could try to reproduce the same problem with any sandbox but if you have any ideas to solve this problem I will appreciate this.
Thank You a lot!

**Comment by thijstriemstra** [comment]
what version of video.js?

**Comment by IvanKuzyshyn** [comment]
@thijstriemstra video.js version is: "6.6.0",
but I haven't video.js package in my dependencies. This package must be a dependency of another package.

**Comment by IvanKuzyshyn** [comment]
@thijstriemstra webrtc-adapter "version": "6.0.4"
recordrtc "version": "5.4.6"

**Comment by thijstriemstra** [comment]
Hehe yeah, its a dependency of this plugin, hence the name ;) can you try 6.4.0?

**Comment by IvanKuzyshyn** [comment]
@thijstriemstra Thanks! Yes, everything works fine with 6.4.0.

**Comment by thijstriemstra** [comment]
Opened #200 that should fix this issue. Would be awesome if you can give that pull request a try with v6.6.0..

**Comment by IvanKuzyshyn** [comment]
Thanks.  I'll try to check it out soon.

**Comment by thijstriemstra** [comment]
Fixed since 2.0.6.
