### ISSUE TITLE
Audio recording quality low?

### ISSUE THREAD

**Issue by natashache** [collab-project/videojs-record#205]
Trying to decide whether to use this module. The audio recording quality in the demo app https://collab-project.github.io/videojs-record/examples/audio-only.html seems rather low-- the recording sounds muffled and echoey even though I used a good microphone. 

Is this something that can be improved by setting a higher bitrate? Want to make sure this module can record quality audios before plunging into it.

**Comment by thijstriemstra** [comment]
@natashache can you attach the recorded audio file here? Setting a higher bitrate should definitely help. If you can find anything else out there that has better sound quality, please let me know and I'll see what can be done to improve it.

**Comment by thijstriemstra** [comment]
@natashache any news?

**Comment by natashache** [comment]
@thijstriemstra Thanks. Have tried it in my own app and the recording quality is good.  A side question though. If I want the recording to be in mp3, I suppose I need to use `lamejs` as the audio encoder in the setting? Then what do I use for `audioMimeType` option?

**Comment by thijstriemstra** [comment]
@natashache you don't need to specify audio mimetype, just follow this example: https://github.com/collab-project/videojs-record/blob/master/examples/plugins/audio-only-mp3.html#L51

**Comment by natashache** [comment]
@thijstriemstra up and running. Thanks a lot!
