### ISSUE TITLE
Missing filename in timestamp blobs

### ISSUE THREAD

**Issue by SergeyKozlov** [collab-project/videojs-record#206]
## Description
Hello.
I noticed a difference between the two browsers.
I have a system Ubuntu 17.10 (64).

## Steps to reproduce
In the browser Chromium, everything works perfectly.
But an error in the Firefox browser when loading chunks

### Expected
Should have loaded 4 pieces of 500 kB each.
![2018-02-17 23-53-31](https://user-images.githubusercontent.com/1781376/36345690-dab256c4-1440-11e8-9663-ec670dd62daf.png)

### Actual
Upload timestamp error:
Only the first 313 bytes of the first piece are loaded.
![2018-02-17 23-55-01](https://user-images.githubusercontent.com/1781376/36345685-c429ed68-1440-11e8-84f7-762c2c24f9d2.png)

### Error output
    [Data] => Array
        (
            [name] => 
            [type] => 
            [tmp_name] => 
            [error] => 4
            [size] => 0
        )

## Additional Information
JS:

    var player = videojs("myVideo", {
        controls: true,
        width: 430,
        height: 240,
        fluid: false,
        plugins: {
            record: {
                audio: true,
                video: true,
                maxLength: 10,
                debug: true,
                // fire the timestamp event every 2 seconds
                timeSlice: 2000
            }
        }
    }, function () {
        // print version information at startup
        videojs.log('Using video.js', videojs.VERSION,
            'with videojs-record', videojs.getPluginVersion('record'),
            'and recordrtc', RecordRTC.version);
    });

    var segmentNumber = 0;

    player.on('timestamp', function() {
        if (player.recordedData && player.recordedData.length > 0) {
            var binaryData = player.recordedData[player.recordedData.length - 1];
            segmentNumber++;
            var formData = new FormData();
            formData.append('SegmentNumber', segmentNumber);
            formData.append('Data', binaryData);
            $.ajax({
                url: 'https://api.vide.me/rec/savem/',
                method: 'POST',
                data: formData,
                cache: false,
                processData: false,
                contentType: false,
                success: function (res) {
                    console.log("segment: " + segmentNumber);
                    $("#result-new-video").append("<p>" + res + "</p>");
                }
            });
        } else {
                console.log("No video: " + player.recordedData);
        }
    });

PHP:

    $fileName = $_POST["SegmentNumber"];
    $uploadDirectory = '/tmp/' . $fileName;
    if (!move_uploaded_file($_FILES["Data"]["tmp_name"], $uploadDirectory)) { // Work!
        echo("tmp_name problem moving uploaded file");
    }

#### videojs
VIDEOJS: Using video.js 6.6.2 with videojs-record 2.1.0 and recordrtc 5.4.7
#### browsers
Firefox 58.0.2 (64)
#### OSes
Ubuntu 17.10 64

**Comment by thijstriemstra** [comment]
@SergeyKozlov check the content of `player.recordedData` in each browser, they probably differ.

**Comment by SergeyKozlov** [comment]
player.recordedData

At Firefox:
![2018-02-18 00-27-34](https://user-images.githubusercontent.com/1781376/36345793-d7d3e42a-1442-11e8-8f12-89cc11ffac56.png)


At Chromium:
![2018-02-18 00-29-22](https://user-images.githubusercontent.com/1781376/36345795-db5ef918-1442-11e8-9963-e6d70de420a0.png)

**Comment by thijstriemstra** [comment]
I'm not sure what to say without Javascript error messages (I'm not familiar with php).

**Comment by SergeyKozlov** [comment]
http://php.net/manual/en/features.file-upload.errors.php

 UPLOAD_ERR_NO_FILE

    Value: 4; No file was uploaded.

**Comment by SergeyKozlov** [comment]
The console of Firefox has no Javascript errors:
![2018-02-18 00-40-49](https://user-images.githubusercontent.com/1781376/36345870-6dd33966-1444-11e8-87a8-78918a6ab6f7.png)

**Comment by SergeyKozlov** [comment]
I discovered a key difference.
The Firefox does not have a field filename = ""
![2018-02-18 01-01-59](https://user-images.githubusercontent.com/1781376/36346065-1d7dc3ba-1448-11e8-87a2-7330eaf81e1a.png)

And the Chromium has a complete description of the field filename = "blob"
![2018-02-18 01-00-45](https://user-images.githubusercontent.com/1781376/36346068-22d1eed6-1448-11e8-88ae-88e593790908.png)

**Comment by SergeyKozlov** [comment]
Yes, if you substitute this field **filename** manually, then everything works as it should.
![2018-02-18 01-10-34](https://user-images.githubusercontent.com/1781376/36346094-be6ed494-1448-11e8-87c9-d2a040bbee0c.png)

**Comment by thijstriemstra** [comment]
@SergeyKozlov thanks for the research. This is the method that inject the file metadata: https://github.com/collab-project/videojs-record/blob/master/src/js/engine/record-engine.js#L54

Can you add some console.log calls there and see if it get's called everytime?

**Comment by thijstriemstra** [comment]
@SergeyKozlov found the bug and will open a pull request.

**Comment by SergeyKozlov** [comment]
I added output to the console in a file **videojs.record.js**:

        key: 'addFileInfo',
        value: function addFileInfo(fileObj) {
            console.log("addFileInfo: " + JSON.stringify(fileObj));
            var now = new Date();
            fileObj.lastModifiedDate = now;

            // guess extension name from mime type, e.g. audio/ogg, but
            // any extension is valid here. Chrome also accepts extended
            // mime types like video/webm;codecs=h264,vp9,opus
            var fileExtension = '.' + fileObj.type.split('/')[1];
            if (fileExtension.indexOf(';') > -1) {
                fileExtension = fileExtension.split(';')[0];
            }

            // use timestamp in filename, e.g. 1451180941326.ogg
            fileObj.name = now.getTime() + fileExtension;
        }

        /**
         * Invoked when recording is stopped and resulting stream is available.
         *
         * @param {blob} data - Reference to the recorded Blob.
         */

But there is only one **addFileInfo** call are empty:
Firefox:
![2018-02-18 10-20-40](https://user-images.githubusercontent.com/1781376/36349425-aa596c22-1497-11e8-920f-884a4b486aab.png)

Chromium:
![2018-02-18 10-27-50](https://user-images.githubusercontent.com/1781376/36349426-af0bc4ea-1497-11e8-9b88-3064724acc65.png)

**Comment by thijstriemstra** [comment]
Can you test pull request #207?
