### ISSUE TITLE
Hiding waveform

### ISSUE THREAD

**Issue by devaptas** [collab-project/videojs-record#209]
Chrome Version 64.0.3282.167, viodejs-record 2.1.1, video.js 6.7.2, videojs-wavesurfer 2.2.0, wavesurfer.js 2.0.4. Follow the config:

My events is config, to show wavesurf only when record is on, like that:
```javascript
player.on('deviceReady', function(){
      player.wavesurfer().pause();
});

player.on('startRecord', function(){
      player.wavesurfer().play();
});
```
but when the startRecord is call, player.wavesurfer().play() call  "VIDEOJS: Pause microphone" on console with debug on.

**Comment by thijstriemstra** [comment]
@devaptas I'm not sure what you're trying to do. Please describe it step by step:

1. ...
2. ...
3. ... etc

**Comment by devaptas** [comment]
I want to show the waves only record is ON, but this wrong call is put mic down

**Comment by thijstriemstra** [comment]
I see. I think manually hiding the element that contains the `wave` element is probably the easiest:

<img width="448" alt="screen shot 2018-02-19 at 22 38 38" src="https://user-images.githubusercontent.com/305679/36398088-afb39182-15c5-11e8-89d0-3325b2640cc8.png">

**Comment by devaptas** [comment]
Ok, this trick solved, I don't knew about this element, tnks again.
