### ISSUE TITLE
Filename field missing in Firefox timestamp blobs

### ISSUE THREAD

**Issue by SergeyKozlov** [collab-project/videojs-record#210]
## Description
Hi

When using the **timestamp** event, the data is sent with empty fields **filename**

## Steps to reproduce
In the Firefox browser, the files are sent without the **filename** field. In the Chrome browser, the entire file chain goes to the fields **filename**.

### Expected
Fields **filename** must be sent with each event **timestamp**

### Actual
Blob File Blob File ...

### Error output
At Firefox:
![2018-02-20 12-33-41](https://user-images.githubusercontent.com/1781376/36418334-9eeeef20-163f-11e8-8d42-4b8c64bdcdaa.png)
![2018-02-20 12-33-03](https://user-images.githubusercontent.com/1781376/36418353-a7c29c5a-163f-11e8-81a4-50e47088631b.png)

At Chrome:
![2018-02-20 12-36-11](https://user-images.githubusercontent.com/1781376/36418361-af505976-163f-11e8-8b0a-47a6cb9c6c77.png)
![2018-02-20 12-39-32](https://user-images.githubusercontent.com/1781376/36418368-b219e9ce-163f-11e8-9098-b97ab22a0c7e.png)

## Additional Information
Code:
```javascript
    var segmentNumber = 0;
    player.on('timestamp', function() {
            console.log('array of blobs: ', player.recordedData);
        if (player.recordedData && player.recordedData.length > 0) {
            var binaryData = player.recordedData[player.recordedData.length - 1];
            segmentNumber++;
            var formData = new FormData();
            formData.append('SegmentNumber', segmentNumber);
            formData.append('Data', binaryData);
            $.ajax({
                url: 'https://ggg.int/rec/savem/',
                method: 'POST',
                data: formData,
                cache: false,
                processData: false,
                contentType: false,
                success: function (res) {
                    console.log("segment: " + segmentNumber);
                    $("#result-new-video").append("<p>" + res + "</p>");
                }
            });
        } else {
                console.log("No video: " + player.recordedData);
        }
    });
```
### versions
released v2.1.1
#### videojs
VIDEOJS: Using video.js 6.6.3 with videojs-record 2.1.1 and recordrtc 5.4.7
#### browsers
Firefox 58.0.2 (64)
#### OSes
Ubuntu 17.10

**Comment by thijstriemstra** [comment]
@SergeyKozlov just to summarize, it's working correctly in Chrome, but sometimes the filename is missing on Firefox?

**Comment by SergeyKozlov** [comment]
Yes @thijstriemstra exactly.
The **filename** only works for odd **timestamp** events at **Firefox**.
Blob, File, Blob, File:
![2018-02-20 12-33-41](https://user-images.githubusercontent.com/1781376/36427592-b4ccdc02-165e-11e8-88d6-ec32987cc505.png)

**Comment by thijstriemstra** [comment]
Very weird it's Blob, File, Blob.. Must be something in the recordrtc library, I'll take a look.

**Comment by thijstriemstra** [comment]
Tested on Firefox 58.0.2 on macOS with following code and `timeSlice` of 2000:

```javascript
var segmentNumber = 0;
player.on('timestamp', function() {
    console.log('array of blobs: ', player.recordedData);
    if (player.recordedData && player.recordedData.length > 0) {
        var binaryData = player.recordedData[player.recordedData.length - 1];
        segmentNumber++;
        console.log('Data', binaryData);
    } else {
        console.log("No video: " + player.recordedData);
    }
});
```

**audio-only**

Results: only blobs.

```
Array [ Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob ]
```

**video-only**

Results: all bobs except the last one.

```
Array [ Blob, Blob, Blob, Blob, File ]
```

**audio-video**

Results: all bobs except the last one.

```
Array [ Blob, Blob, Blob, Blob, File ]
```

So it looks like audio-only is not affected. I'm also only able to produce a `File` object as the last item in the array.

**Comment by thijstriemstra** [comment]
@SergeyKozlov I created pr #216, can you test it?

**Comment by thijstriemstra** [comment]
I guess this PR doesn't solve the issue when the `timeSlice` option isn't enabled; it could still return a `File` object with an empty `name` property..

**Comment by SergeyKozlov** [comment]
Hey.
Sorry, but now I get in the Firefox:
audio-video

Results: all bobs except the last one.

Array [ Blob, Blob, File, File, File, Blob, Blob]

![2018-03-03 20-51-31](https://user-images.githubusercontent.com/1781376/36937495-5bc18b38-1f25-11e8-9fb3-f092c88c8075.png)

**Comment by thijstriemstra** [comment]
I tested on macOS with firefox 58, I'll test again on Ubuntu.

**Comment by SergeyKozlov** [comment]
What is your result on the macOS now?
Array [ Blob, Blob, File, File, Blob, Blob]?

**Comment by thijstriemstra** [comment]
@SergeyKozlov Blobs only.

**Comment by SergeyKozlov** [comment]
@thijstriemstra Tomorrow I will test for Windows.

**Comment by SergeyKozlov** [comment]
Hi @thijstriemstra 
I tested on Win 64 with Firefox 58. And i got a result **blob file file blob file blob blob**:
![web_rec_06032018](https://user-images.githubusercontent.com/1781376/37032780-b7c7e57c-2154-11e8-9fb2-5299038a9e6d.jpg)

**Comment by thijstriemstra** [comment]
@SergeyKozlov can't reproduce it on Ubuntu. Can you try this example and see if it also produces `File` every now and then? https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/ondataavailable.html

**Comment by SergeyKozlov** [comment]
@thijstriemstra Here's what I did:

    document.getElementById('btn-start-recording').onclick = function() {
        this.disabled = true;
        captureCamera(function(camera) {
            setSrcObject(camera, video);
            video.play();

            recorder = RecordRTC(camera, {
                recorderType: MediaStreamRecorder,
                mimeType: 'video/webm',
                timeSlice: 1000, // pass this parameter
                // getNativeBlob: true,
                ondataavailable: function(blob) {
                    blobs.push(blob);
                    console.log('ondataavailable blobs: ', blobs);
                    var size = 0;
                    blobs.forEach(function(b) {
                        size += b.size;
                    });
                    h1.innerHTML = 'Total blobs: ' + blobs.length + ' (Total size: ' + bytesToSize(size) + ')';
                }
            });
            recorder.startRecording();
            // release camera on stopRecording
            recorder.camera = camera;
            document.getElementById('btn-stop-recording').disabled = false;
        });
    };

Here's what I got on Ubuntu 64 FF 58.0.2:
![2018-03-07 07-52-37](https://user-images.githubusercontent.com/1781376/37074192-97e7751e-21dc-11e8-86d2-867c2c503eba.png)
![2018-03-07 07-52-54](https://user-images.githubusercontent.com/1781376/37074193-99d0b994-21dc-11e8-8e3b-8e9654bc07a4.png)

**Comment by thijstriemstra** [comment]
@SergeyKozlov I was thinking about creating a new object that contains the metadata + either blob/file instead of returning the raw blob/file. So something like:

```javascript
var returnedObject = {
    size: 1234,
    type: 'video/webm',
    lastModified: 1520329329728,
    data: Blob{} // or File{} data
};
```

That way you'll always have the correct metadata and blob/file data. Thoughts?

**Comment by SergeyKozlov** [comment]
@thijstriemstra Where should I use it. Instead of the **formData** parameter?:

player.on('timestamp', function() {
    if (player.recordedData && player.recordedData.length > 0) {
        var binaryData = player.recordedData[player.recordedData.length - 1];
        segmentNumber++;
        var formData = new FormData();
        formData.append('SegmentNumber', segmentNumber);
        formData.append('file', fileName);
        formData.append('Data', binaryData);
        $.ajax({
            url: 'https://server.com/save/',
            method: 'POST',
            data: formData,
            cache: false,
            processData: false,
            contentType: false,
            beforeSend: function () {
            },
            success: function (res) {
                console.log("segment: " + segmentNumber);
            },
            error: function (res) {
            }
        });
    } else {
        console.log("No video: " + player.recordedData);
    }
});

**Comment by SergeyKozlov** [comment]
@thijstriemstra this is my code:

```
player.on('timestamp', function() {
    if (player.recordedData && player.recordedData.length > 0) {
        var data = player.recordedData[player.recordedData.length - 1];
        // ------------
        var fileName = data.name;
        var binaryData = data.data; // could be Blob or File
        var size = data.size;
        // --------------
        console.log('data: ', data);
        console.log('fileName: ', fileName);
        console.log('binaryData: ', binaryData);
        console.log('size: ', size);
        // --------------
        segmentNumber++;
        var formData = new FormData();
        formData.append('SegmentNumber', segmentNumber);
        formData.append('file', fileName);
        formData.append('Data', binaryData);
        $.ajax({
            url: 'https://server.com/save/',
            method: 'POST',
            data: formData,
            cache: false,
            processData: false,
            contentType: false,
            beforeSend: function () {

            },
            success: function (res) {
            },
            error: function (res) {
            }
        });
    } else {
        console.log("No video: " + player.recordedData);
    }
});
```

And again I get value of data: **blob file blob file** ...

Is there a reason for the error in this line?:
`        var data = player.recordedData[player.recordedData.length - 1];`
This is error on console:
![2018-04-11 09-17-39](https://user-images.githubusercontent.com/1781376/38599632-f4380420-3d69-11e8-9441-801a13480e52.png)

**Comment by thijstriemstra** [comment]
I was proposing such a fix, not implemented yet

**Comment by SergeyKozlov** [comment]
When install the dependencies using npm i'm got a warning:
![2018-04-11 16-02-06](https://user-images.githubusercontent.com/1781376/38618346-070a10f6-3da2-11e8-92b9-04b34b4d64d1.png)

It is important?

**Comment by thijstriemstra** [comment]
@SergeyKozlov don't think so but can you open a separate ticket for that?

**Comment by SergeyKozlov** [comment]
@thijstriemstra 
I'm adding 
```
                if (fileObj instanceof File) {
                    console.log('addFileInfo: fileObj instanceof File', fileObj);
                    fileObj.name = now.getTime() + fileExtension;
                }
```
to **videjs.record.js**.
Why does not it work like this:

```
...
        key: 'addFileInfo',
        value: function addFileInfo(fileObj) {
            if (fileObj instanceof Blob || fileObj instanceof File) {
                // set modification date
                var now = new Date();
                try {
                    fileObj.lastModified = now.getTime();
                    fileObj.lastModifiedDate = now;
                } catch (e) {
                    if (e instanceof TypeError) {
                        // ignore: setting getter-only property "lastModifiedDate"
                    } else {
                        // re-raise error
                        throw e;
                    }
                }
                // guess extension name from mime type, e.g. audio/ogg, but
                // any extension is valid here. Chrome also accepts extended
                // mime types like video/webm;codecs=h264,vp9,opus
                var fileExtension = '.' + fileObj.type.split('/')[1];
                if (fileExtension.indexOf(';') > -1) {
                    fileExtension = fileExtension.split(';')[0];
                }
                // use timestamp in filename, e.g. 1451180941326.ogg
                try {
                    fileObj.name = now.getTime() + fileExtension;
                } catch (e) {
                    console.log('addFileInfo: catch');
                    if (e instanceof TypeError) {
                        // ignore: setting getter-only property "name"
                    } else {
                        // re-raise error
                        throw e;
                    }
                }
                if (fileObj instanceof File) {
                    console.log('addFileInfo: fileObj instanceof File', fileObj);
                    fileObj.name = now.getTime() + fileExtension;
                }
            }
        }
...
```

I'm got a error:
![2018-04-12 14-12-33](https://user-images.githubusercontent.com/1781376/38674049-cbd98e3e-3e5b-11e8-8699-2049463047e3.png)

**Comment by SergeyKozlov** [comment]
Thanks you @thijstriemstra
