### ISSUE TITLE
Тo information about the video in the file chain

### ISSUE THREAD

**Issue by SergeyKozlov** [collab-project/videojs-record#211]
## Description
There is no information about the video in the file chain of the **timestamp** event

## Steps to reproduce
The video is recorded and sent to the server every time a **timestamp** event occurs.

### Expected
It was expected to see information about the video in each transmitted file.

### Actual
In fact, information about the video is contained only in the first file.

### Error output
![2018-02-20 14-23-54](https://user-images.githubusercontent.com/1781376/36422047-cbc12d54-164b-11e8-90a9-150e35b64453.png)

## Additional Information
released v2.1.1
#### videojs
VIDEOJS: Using video.js 6.6.3 with videojs-record 2.1.1 and recordrtc 5.4.7
#### browsers
Firefox 58.0.2 (64)
#### OSes
Ubuntu 17.10

**Comment by thijstriemstra** [comment]
@SergeyKozlov can you use the `ffprobe` tool (also part of ffmpeg) on these files and paste the output in a gist (https://gist.github.com)?

**Comment by SergeyKozlov** [comment]
![2018-02-21 07-46-02](https://user-images.githubusercontent.com/1781376/36463492-53ff6d0e-16db-11e8-89a7-1ec3d9c040ed.png)

**Comment by thijstriemstra** [comment]
the 2nd command uses `-v quiet` for some reeason. can you just use `ffprobe x.filename` and paste the contents here (dont make a screenshot, just copy/paste text).

**Comment by SergeyKozlov** [comment]
I got output:
```
ubuntu@ip-172-31-92-61:/usr/share/nginx/nadtemp$ ffprobe 2.webm
ffprobe version N-88244-g859144f Copyright (c) 2007-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 20160609
  configuration: 
  libavutil      56.  0.100 / 56.  0.100
  libavcodec     58.  1.100 / 58.  1.100
  libavformat    58.  0.101 / 58.  0.101
  libavdevice    58.  0.100 / 58.  0.100
  libavfilter     7.  0.100 /  7.  0.100
  libswscale      5.  0.100 /  5.  0.100
  libswresample   3.  0.100 /  3.  0.100
2.webm: Invalid data found when processing input
```

**Comment by thijstriemstra** [comment]
Im confused again; what  is 176673385756691122.ts?

**Comment by SergeyKozlov** [comment]
This portion of the stream made a new version videojs.record.js.
Now everything is correct.
