### ISSUE TITLE
save video to specific fixed folder

### ISSUE THREAD

**Issue by sureshPprajapati** [collab-project/videojs-record#219]
Hi, 
I need to store video/audio clip to the specific folder every time, I can easily got form there. is there any way to store directly specified folder no need to ask every time saveAs window. 
is there any way to set up this kind of functionality.

**Comment by thijstriemstra** [comment]
@sureshPprajapati for firefox there is this https://support.mozilla.org/en-US/questions/1192259

**Comment by thijstriemstra** [comment]
No feedback, closing question.
