### ISSUE TITLE
Compatible with videojs-contrib-hls

### ISSUE THREAD

**Issue by crossskyfreely** [collab-project/videojs-record#220]
Hi , I recently test videojs-record function . It seem that videojs-record only record the stream from camera ,right ? Or if we can record stream from HLS what we should do ?  eagerly expect your reply ,Thanks a lots.
Luke

**Comment by thijstriemstra** [comment]
@crossskyfreely it's possible to record from camera/microphone. videojs-contrib-hls does not (or cannot) make the audio data available for recording so it's not possible to record HLS streams (yet). Any research/help is welcome.

**Comment by thijstriemstra** [comment]
also see https://github.com/video-dev/hls.js/issues/410

**Comment by thijstriemstra** [comment]
I don't have time to focus on this, closing ticket. If anyone is interested, open a pull request or let me know here.
