### ISSUE TITLE
Control the display of all buttons

### ISSUE THREAD

**Issue by SergeyKozlov** [collab-project/videojs-record#221]
Hey.
Is there any way to control the display of all buttons?
Do these buttons have methods and events?

![2018-03-16 14-07-54](https://user-images.githubusercontent.com/1781376/37517756-7d794b82-2923-11e8-9f5d-66a6f3914d6a.png)

Thank you.

**Comment by thijstriemstra** [comment]
Yes, they're all located in the `player.controlBar`, e.g. `player.controlBar.volumePanel.hide()`. Check video.js `Player` API documentation and source.
