### ISSUE TITLE
Example for changing video source

### ISSUE THREAD

**Issue by michaelsboost** [collab-project/videojs-record#223]
I'm not seeing anything in the API that shows any option to change the webcam source. (I'm asking cause I may use this library to make a Google Chrome App for Chromebooks. (Testing on Google Chrome)

Demo visible a https://codepen.io/michaelsboost/pen/BrYwjq

**Comment by thijstriemstra** [comment]
@michaelsboost check this example: https://github.com/collab-project/videojs-record/blob/master/examples/change-audio-input.html It's for audio but with some tweaking it should work for video as well.

**Comment by thijstriemstra** [comment]
any feedback @michaelsboost?

**Comment by michaelsboost** [comment]
Nope haven't been able to test it. My only tinkering it just recording the webcam and audio. Just have more important things to deal with in my life besides coding.

This is the pen I originally created to play with VideoJS though: https://codepen.io/michaelsboost/pen/BrYwjq
