### ISSUE TITLE
player.record().start() not work

### ISSUE THREAD

**Issue by nguyenxuanluong-luvina** [collab-project/videojs-record#224]
## Description
I want to call start recording function automatically by calling

```
player.record().start()
```

But I get an error 

```
window.js:14 Uncaught TypeError: Cannot set property 'muted' of undefined
    at Record.startVideoPreview (window.js:14)
    at Record.start (window.js:14)
    at audio-video.html:47
```

## Steps to reproduce
- Download example from repo
- Adding line after init player

```
player.record().start()
```

like this

> var player = videojs("myVideo", {
>     controls: true,
>     width: 320,
>     height: 240,
>     fluid: false,
>     plugins: {
>         record: {
>             audio: true,
>             video: true,
>             maxLength: 10,
>             debug: true
>         }
>     }
> }, function(){
>     // print version information at startup
>     videojs.log('Using video.js', videojs.VERSION,
>         'with videojs-record', videojs.getPluginVersion('record'),
>         'and recordrtc', RecordRTC.version);
> });
> 
> player.record().start() // failed to start
> 
>

**Comment by thijstriemstra** [comment]
@nguyenxuanluong-luvina you cannot call `start` before the user gave access to microphone and/or microphone. You should also wait until player is ready. Try:

```javascript
player.on('ready', function() {
    player.record().getDevice();
});

player.on('deviceReady', function() {
    player.record().start();
});
```

**Comment by nguyenxuanluong-luvina** [comment]
Thank you very much Thijs Triemstra
That's my mistake
