### ISSUE TITLE
Plugin "record" does not exist in Angular 5

### ISSUE THREAD

**Issue by delockdown** [collab-project/videojs-record#230]
## Description
plugin "record" does not exist appears when I try to add video tag with 'record' plugin. This the configurations I added.
`var player = videojs('myVideo', { 
      // video.js options
      controls: true,
      loop: false,
      fluid: true,
      plugins: {
        record: {
          audio: true,
          video: true,
          maxLength: 10,
          debug: true,
        },
      },
    });`
And I used npm to install packages and I import those package via `.angular-cli.json` file with correct paths. 
#### videojs
Using the latest versions 
#### browsers
Chrome 65.0
#### OSes
MacOS High Sierra

**Comment by thijstriemstra** [comment]
@delockdown it's always a good idea to explain why the ticket was closed, maybe others ran into same issue.
