### ISSUE TITLE
Ability to control max file size

### ISSUE THREAD

**Issue by delockdown** [collab-project/videojs-record#234]
Hi, Is there any way to stop record when the video reach to particular value(Ex: 20mb)

**Comment by thijstriemstra** [comment]
@delockdown no I don't think so. You could use the `timeSlice` option though to get the data every x seconds, so you could calculate what recording approximately 20mb would be in seconds and use that value for `timeSlice`.

**Comment by thijstriemstra** [comment]
@delockdown would the [setRecordingDuration](https://github.com/muaz-khan/RecordRTC#setrecordingduration) method work for your use-case?

**Comment by delockdown** [comment]
Hi @thijstriemstra, It is not possible to give duration because based on camera quality video size getting changed. So it is not possible to reply on the duration always.

**Comment by thijstriemstra** [comment]
Maybe there's a way to access the size of the current (local) Blob recording, and stop recording based on that value.

**Comment by thijstriemstra** [comment]
@delockdown, found an example that implements this somewhat.

Source: https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/preview-blob-size-during-recording.html

Demo: https://webrtc-experiment.com/RecordRTC/simple-demos/preview-blob-size-during-recording.html

So I'll add something for this.

**Comment by thijstriemstra** [comment]
@delockdown, added a `maxFileSize` option, e.g.

```javascript
var player = videojs("myVideo", {
    controls: true,
    width: 320,
    height: 240,
    fluid: false,
    controlBar: {
        volumePanel: false
    },
    plugins: {
        record: {
            audio: false,
            video: true,
            maxLength: 100,
            maxFileSize: 1000000 * 3, // limit recording to 3 MB
            debug: true,
            // fire the timestamp event every 200 ms
            timeSlice: 200
        }
    }
}
```

Try it using master branch or wait until 3.0.0 is released.
