### ISSUE TITLE
audio-only with regular videojs player on the same page breaks

### ISSUE THREAD

**Issue by Xteda87** [collab-project/videojs-record#235]
Sorry for my English
## Description
When we have on one page video-record player and videojs player with any video occurs strange behaviour: click on simply player's progress control doesn't have any effect.

## Steps to reproduce
Add to one page video-record object and simply videojs player

#### videojs
6.8
#### browsers
all
#### OSes
win 10

**Comment by thijstriemstra** [comment]
@Xteda87 perhaps it's related to this piece of code: https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L32

Can you rip that out, try again and see if it improves things?

**Comment by Xteda87** [comment]
I found the problem. If I include the file videojs.wavesurfer.js version more than 2.0.3 then click on the progress controls doesn't work.

**Comment by thijstriemstra** [comment]
@Xteda87 can you provide some example code to reproduce this?

**Comment by thijstriemstra** [comment]
I just tried this with the following example:

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Audio-only Example - Record Plugin for Video.js</title>

  <link href="../node_modules/video.js/dist/video-js.min.css" rel="stylesheet">
  <link href="../dist/css/videojs.record.css" rel="stylesheet">

  <script src="../node_modules/video.js/dist/video.min.js"></script>
  <script src="../node_modules/recordrtc/RecordRTC.js"></script>
  <script src="../node_modules/webrtc-adapter/out/adapter.js"></script>
  <script src="../node_modules/wavesurfer.js/dist/wavesurfer.min.js"></script>
  <script src="../node_modules/wavesurfer.js/dist/plugin/wavesurfer.microphone.min.js"></script>
  <script src="../node_modules/videojs-wavesurfer/dist/videojs.wavesurfer.min.js"></script>

  <script src="../dist/videojs.record.js"></script>

  <style>
  /* change player background color */
  #myAudio {
      background-color: #9FD6BA;
  }
  </style>

</head>
<body>

<audio id="myAudio" class="video-js vjs-default-skin"></audio>

<video id="myVideo" class="video-js vjs-default-skin"></video>

<script>
var player = videojs("myAudio", {
    controls: true,
    width: 600,
    height: 300,
    fluid: false,
    plugins: {
        wavesurfer: {
            src: "live",
            waveColor: "#36393b",
            progressColor: "#black",
            debug: true,
            cursorWidth: 1,
            msDisplayMax: 20,
            hideScrollbar: true
        },
        record: {
            audio: true,
            video: false,
            maxLength: 20,
            debug: true
        }
    }
}, function() {
    // print version information at startup
    videojs.log('Using video.js', videojs.VERSION,
        'with videojs-record', videojs.getPluginVersion('record'),
        '+ videojs-wavesurfer', videojs.getPluginVersion('wavesurfer'),
        'and recordrtc', RecordRTC.version);
});

var player2 = videojs("myVideo", {
    controls: true,
    width: 600,
    height: 300
}, function() {
    console.log('second player ready');
});
// load example MP4 at startup
player2.src('big_buck_bunny.mp4');

// user completed recording and stream is available
player.on('finishRecord', function() {
    // the blob object contains the recorded data that
    // can be downloaded by the user, stored on server etc.
    console.log('finished recording: ', player.recordedData);
});
</script>
</body>
</html>
```

And the resulting player looks weird, likely because it picks up the player styles for videojs-record:

![videojs-css-screwed](https://user-images.githubusercontent.com/305679/39971142-b2f0af84-56f6-11e8-9914-cd39d42a3433.png)

> click on the progress controls doesn't work.

I'm not able to reproduce this though..

**Comment by thijstriemstra** [comment]
While working on a fix, I also noticed this weird waveform render issue, bizarre.
![crooked-waveform](https://user-images.githubusercontent.com/305679/39971524-e38853b2-56fc-11e8-8ec3-d6cc111acbf7.png)

**Comment by thijstriemstra** [comment]
There's also an issue in videojs-wavesurfer, opened https://github.com/collab-project/videojs-wavesurfer/issues/60 for that.

**Comment by thijstriemstra** [comment]
@Xteda87 upgrade to videojs-wavesurfer 2.5.0 and videojs-record 2.3.1 (or newer) to fix this.
