### ISSUE TITLE
Error on install using NPM via composer

### ISSUE THREAD

**Issue by devaptas** [collab-project/videojs-record#239]
Error on install using NPM via composer

Composer file:
```
...
"npm-asset/videojs-record": "^2.1.3",
...
```
Error log using `composer update -vv`
> [InvalidArgumentException]                                                                              
>   Unknown downloader type: npm-signature. Available types: git, svn, fossil, hg, perforce, zip, rar, tar  
>   , gzip, xz, phar, file, path.

**Comment by thijstriemstra** [comment]
@devaptas I published version 2.2.0, can you check if it's better now?

**Comment by devaptas** [comment]
Same problem. I tried install the dependencies separated and the problem is on video.js or in any dependence on it

> Package operations: 1 install, 0 updates, 0 removals
> Installs: npm-asset/video.js:6.9.0
> 
>                                                                                                                                        
>   [InvalidArgumentException]                                                                                                           
>   Unknown downloader type: npm-signature. Available types: git, svn, fossil, hg, perforce, zip, rar, tar, gzip, xz, phar, file, path.

**Comment by thijstriemstra** [comment]
@devaptas if it's a video.js problem, can you open a ticket in their repository?

**Comment by thijstriemstra** [comment]
Oh you already opened one: https://github.com/videojs/video.js/issues/5146 (perhaps adding a reference here would've been useful ;)
