### ISSUE TITLE
Add text / image inside video

### ISSUE THREAD

**Issue by bionimic** [collab-project/videojs-record#241]
I want to do something like questionnaire inside the video. User will start record video and read the question and answer during the recording. 

Is it possible? please assist. thanks!

**Comment by thijstriemstra** [comment]
I think you can use webvtt for this but I'm not sure, any suggestions @gkatsev, you know of any plugins that provide this (I can figure out the record-part)?

**Comment by gkatsev** [comment]
Yeah, you could use text tracks. For just text, you could probably mark it as subtitles but for custom styling and images probably use a metadata track with a JSON string inside of it that has various info in it like the image and the text. Here's an example plugin that uses metadata text tracks for displaying thumbnails: https://github.com/dirkjanm/videojs-vtt-thumbnails
