### ISSUE TITLE
Blackscreen video but can record and export to file

### ISSUE THREAD

**Issue by nguyenxuanluong-luvina** [collab-project/videojs-record#242]
Hi there,
I have problem with videjs-record or maybe videojs i'm not sure.
Let me describe my problem:
I using videojs-record and working fine before.
Now my project need to minification code using Uglify
Then after minify, my video screen go to all black,even no control button show out.
I was created  a button for record video (this button call `player.record.start()` action then it still record and export to file normally. video view also good, not a blackscreen video.
Can somebody help me to find out what happend?

**Comment by thijstriemstra** [comment]
@nguyenxuanluong-luvina what browser? what version of video.js/videojs-record? What operating system? Can you share some example code? How do you minify the files?

**Comment by nguyenxuanluong-luvina** [comment]
I using
+ Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)
+ Windows 10 
+ Video.js 6.7.3
+ videojs-record @version 2.1.2

I using ulify-js  2.8.3 to minify source with only one option `mangle: true`

The problem happend only when minify, in full version of source have no problem


Source code using in very simple : 
```
        var player = videojs.getPlayer('proofVideo');
        if(player === null || typeof player === 'undefined') {
            player = videojs('myVideo', {
                // video.js options
                controls: true,
                loop: false,
                fluid: false,
                width: 640,
                height: 480,
                plugins: {
                    // videojs-record plugin options
                    record: {
                        image: false,
                        audio: true,
                        video: true,
                        maxLength: 120,//length in seconds
                        debug: true
                    }
                }
            });
      }
```
Then html is simple too: 
`<video id="proofVideo" class="video-js vjs-default-skin"></video>`

**Comment by thijstriemstra** [comment]
@nguyenxuanluong-luvina please try videojs-record 2.2.0

**Comment by nguyenxuanluong-luvina** [comment]
I just updated with videojs-record 2.2.0 and video.js version 6.9.0 lastest stable but still can not fix
Maybe video.js can not detect `myVideo` :(

**Comment by thijstriemstra** [comment]
@nguyenxuanluong-luvina can you create a simple example, using something like grunt, that reproduces the problem? Otherwise there's not much I can do here..

**Comment by thijstriemstra** [comment]
@nguyenxuanluong-luvina you should use video.js 6.8.0 or older for now, just tested with 6.9.0 and there seems to be an issue (with audio recording).
