### ISSUE TITLE
fluid aspect ratio incorrect on android ( chrome )

### ISSUE THREAD

**Issue by smakinson** [collab-project/videojs-record#247]
# Description
Briefly describe the issue.
The recorder is too tall on android in chrome in **portrait orientation** ( possibly others )

## Steps to reproduce
set fluid: true, load on android in chrome

### Expected
The aspect ratio to match what I see in chrome on the desktop.

### Actual
I see the recorder as much taller in chrome on android.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:

When I dig into the dev tools on android I see:
```
.reportVideo-dimensions.vjs-fluid {
padding-top: 177.77777777777777%
}
```

on the desktop the padding-top is correct at 56.25%.

Here are the settings: 
```javascript
{
              controls: true,
              autoplay: true,
              fluid: true,
              controlBar: {
                volumePanel: false
              },
              plugins: {
                record: {
                  debug: true,
                  audio: true,
                  video: {
                    // video constraints: set resolution of camera
                    mandatory: {
                      minWidth: 1280,
                      minHeight: 720
                    }
                  },
                  maxLength: 120,
                  videoMimeType: 'video/webm;codecs=H264',
                  // dimensions of captured video frames
                  frameWidth: 1280,
                  frameHeight: 720
                }
              }
            }
```
#### videojs
what version of videojs does this occur with?
7.0.0

#### browsers
what browser are affected?
chrome

#### OSes
what platforms (operating systems and devices) are affected?
android

**Comment by thijstriemstra** [comment]
@smakinson thanks for the report. Perhaps you can dig into the fluid styles at https://github.com/collab-project/videojs-record/blob/master/src/css/fluid.scss, I'm not much of help there.

**Comment by thijstriemstra** [comment]
can you also add some screenshots @smakinson ?

**Comment by smakinson** [comment]
Here is what it looks like, its a bit taller than this ( taken from dev tools )
![screen shot 2018-05-15 at 3 14 04 pm](https://user-images.githubusercontent.com/16784/40078486-b378b232-5852-11e8-9747-daadcab2360a.png)

**Comment by smakinson** [comment]
I have the 2.3.0 src downloaded and searching for the reportVideo-dimensions class is returning no results, where might I find that?

**Comment by smakinson** [comment]
I think I found where the padding is set up:
https://github.com/videojs/video.js/blob/master/src/js/player.js#L877

**Comment by smakinson** [comment]
I'll give that aspectRatio property a try, it looks like it does get used for determining the padding-top.

**Comment by thijstriemstra** [comment]
@smakinson you also reported using video.js 7.0.0 (didn't know it was out yet) but I'd stick to 6.9.0 for now, haven't tested with 7 yet.

**Comment by smakinson** [comment]
adding:
`aspectRatio: '16:9'`

 partially fixed it:

![screen shot 2018-05-15 at 3 37 13 pm](https://user-images.githubusercontent.com/16784/40079416-e0a4f93e-5855-11e8-8133-916bcd32dc1c.png)

**Comment by thijstriemstra** [comment]
@smakinson good to see you're making progress. If you have any fixes to contribute, feel free to open a pull request and I'll review it asap.
