### ISSUE TITLE
Saving/Storing on Localhost by default

### ISSUE THREAD

**Issue by megadola** [collab-project/videojs-record#25]
first of all, Thank you for your great tools here, 

What i can do to store the recorded Audio_Video on localhost/Server by default after finishing the recording process?

Wishing for the Code Please :)

Regards,
Mostafa Megahed

**Comment by thijstriemstra** [comment]
@megadola what exactly do you mean with by default?

**Comment by megadola** [comment]
@thijstriemstra thanks for your reply,
by default = stored on server without any action from the user.

so if i'm a user recording a video:
- User clicking on "Start Record"...
- Recording for 15 Seconds ...
- Saving the video on server ...

--

User's only action is: start recording ..

Regards,
Mostafa Megahed

**Comment by thijstriemstra** [comment]
It depends on the serverside scripting you're using. You can simply send the data to the server each time the finishRecord event fires, which is documented in every example.

**Comment by ic-armando-1992** [comment]
Where is the data??? i need the data video and audio

**Comment by thijstriemstra** [comment]
@ic-armando-1992 see https://github.com/collab-project/videojs-record/blob/master/examples/video-only.html#L66

**Comment by thijstriemstra** [comment]
@megadola & @ic-armando-1992 I added a jquery.fileupload example that could help.

**Comment by megadola** [comment]
thanks @thijstriemstra it helps, but actually after several times of trying, it didn't work as well (cause: file of fileupload plugin are missing and i tried to get from source but it didn't work for me), anyway:...
finaly, i can upload the video (ONLY USING FIREFOX):

```javascript
player.on('finishRecord', function()
{
    console.log('finished recording: ', player.recordedData);
	var blob = player.recordedData;
    var reader = new FileReader();
    // this function is triggered once a call to readAsDataURL returns
    reader.onload = function(event){
        var fd = new FormData();
        fd.append('store_video', event.target.result);
        $.ajax({
            type: 'POST',
            url: 'store.php',
            data: fd,
            processData: false,
            contentType: false
        }).done(function(data) {
            // print the output from the store.php script
        });
    };      
    // trigger the read from the reader...
    reader.readAsDataURL(blob);
});
```

```php
$data = substr($_POST['store_video'], strpos($_POST['store_video'], ",") + 1);
// decode it
$decodedData = base64_decode($data);
// print out the raw data, 
//echo ($decodedData);
$filename = "video.mp4";
// write the data out to the file
$fp = fopen($filename, 'wb');
fwrite($fp, $decodedData);
fclose($fp);
exit;
```

and it works fine, BUT:
Audio never match the video (sound is faster than the video) !!
note: saved format is "mp4" and some times i'm saving it with "webm" and both are having the same problem of sound! any idea ?

**Comment by Yamakasi** [comment]
Is it not possible to realtime stream it to the server like with flash ? the issue is when it needs to upload after the recording it might get corrupted because users think, stop is remotely saved which happens with flash realtime.
