### ISSUE TITLE
Video record sample not working in Chrome or Edge on Windows

### ISSUE THREAD

**Issue by leospalteholz** [collab-project/videojs-record#250]
## Description
None of the video record demos are working in Chrome and Edge on Windows.

## Steps to reproduce

1. Visit https://collab-project.github.io/videojs-record/examples/audio-video.html
2. Click the device image to start. 
3.  Authorize webpage to access camera.
4. Press record.

### Expected
Video.

### Actual
Edge: Camera turns on and shows the video feed, but clicking record does nothing (no error in console)
Chrome:  No output, green camera view box.  Clicking record produces error as shown below.

### Error output
```
VIDEOJS: ERROR: TypeError: this.mediaElement.play is not a function
    at t.value (videojs.record.js:1253)
    at t.value (videojs.record.js:588)
    at t.value (record-toggle.js:59)
    at HTMLButtonElement.n (video.min.js:2)
    at HTMLButtonElement.X.n.dispatcher.n.dispatcher (video.min.js:1)
```
## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Using video.js 6.9.0 with videojs-record 2.3.0 and recordrtc 5.4.7
#### browsers
Chrome Version 66.0.3359.181 (Official Build) (32-bit & 64-bit)
and Version 67.0.3396.62 (Official Build) (32-bit & 64-bit)
#### OSes
Windows 8, 10

**Comment by thijstriemstra** [comment]
I see you're using windows 8, other than that not much stands out as problematic. The unit tests are run on windows 8 using appveyor so it is tested there somewhat. I personally don't have access to windows 8 to test.

**Comment by leospalteholz** [comment]
Same results on Windows 10, Chrome 66.   Camera does turn on, but nothing on screen and then the same error

**Comment by leospalteholz** [comment]
I updated the comments above with results from console.

**Comment by leospalteholz** [comment]
On iPhone (Safari, iOS 11.4) it sort of works.  Clicking the device icon asks for permission to use camera and safari indicates the camera is in use, then puts a black square in the green video view (no video output on the page).    Clicking the full screen button makes one frame from the video show up, but it isn't live. 
Clicking record makes live video show up full screen.  Not sure if it is recording, but there seems to be no way to stop it and replay the video.

**Comment by leospalteholz** [comment]
Note that the demo from this article: https://developers.google.com/web/updates/2016/01/mediarecorder  does work fine in Chrome.   https://webrtc.github.io/samples/src/content/getusermedia/record/

**Comment by thijstriemstra** [comment]
> browser-shim.js:19 createObjectURL/srcObject both are not supported.

This looks suspicious.

**Comment by gatesyp** [comment]
Has there been any progress on this? I am receiving the same error with Chrome on Mac. 

MacOS: 10.13.5
Chrome 67

**Comment by thijstriemstra** [comment]
@gatesyp I cannot reproduce this on my Mac 10.11.6 using Chrome and 

```
video.js 7.0.3 with videojs-record 2.3.1 and recordrtc 5.4.7
```

So what to do...

**Comment by gatesyp** [comment]
@thijstriemstra Hmmm, I naturally tried out the demo linked in the OP and had the same exact experience. Green screen, and when pressing record the following error:
```
VIDEOJS: ERROR: TypeError: this.mediaElement.play is not a function
    at t.value (videojs.record.js:1253)
    at t.value (videojs.record.js:588)
    at t.value (record-toggle.js:59)
    at HTMLButtonElement.n (video.min.js:2)
    at HTMLButtonElement.X.n.dispatcher.n.dispatcher (video.min.js:1)
```

When following the steps in the OP, the example works for you?

**Comment by thijstriemstra** [comment]
Tested on Window 7 with Chrome 67.0.3396.99 (Official Build) (64-bit), still cannot reproduce this problem..

**Comment by leospalteholz** [comment]
Odd.   Still same problem here with video.js 7.0.3 and recordrtc 5.4.7.
Doesn't work in Chrome on Windows 8 or Windows 10 on three different machines (Lenovo Thinkpad, Surface Pro 4, Intel Nuc).

**Comment by dirkk0** [comment]
I just tested in on both Win7 and Win10, Chrome 67, and it works perfectly.

Could it be that some chrome extension is interfering?

**Comment by leospalteholz** [comment]
Good idea.  Not sure why I didn't start with extensions.   The primary culprit seems to be an extension called Video Speed Controller:  https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk?hl=en

Just tried on Chrome on Mac, and I got the same problems with it enabled.  After disabling it the sample works.   Will retest on Windows when I have a chance.

**Comment by thijstriemstra** [comment]
> The primary culprit seems to be an extension called Video Speed Controller:

Good to hear.

**Comment by thijstriemstra** [comment]
@leospalteholz any news?

@gatesyp can you check if all extensions are disabled?

**Comment by leospalteholz** [comment]
Sorry for the delay.  Just retested on Chrome on Windows 8 and it works with the Video Speed Controller extension disabled. So it seems that was the culprit.    Bug should be closed as the issue is much less broad than I initially thought.  I believe the remaining issues are:

1. Problems with the sample using Edge
2. Chrome with Video Speed Controller doesn't work.  

Not sure if those bugs are worth reporting, let me know.

**Comment by thijstriemstra** [comment]
Thanks for the feedback.

> Chrome with Video Speed Controller doesn't work 

Is it opensource so I can take a look at that extension?

**Comment by gatesyp** [comment]
Sorry for the delay. 

@leospalteholz good thinking, I've retested on Chrome with MacOS and disabled Video Speed Controller extension. The demo works fine now. 

@thijstriemstra here is the source code for the extension: 

https://github.com/igrigorik/videospeed

**Comment by thijstriemstra** [comment]
> here is the source code for the extension

Couldn't find anything but you can always open a new ticket in that project, maybe they want to figure it out.

**Comment by gauravggg21** [comment]
This happened with me because there was no SSL on my website where I hosted. And if there is no SSL, chrome blocks the video part entierly. Put an SSL on your website and it will be solved.
