### ISSUE TITLE
loadOptions() improvement

### ISSUE THREAD

**Issue by tomasdev** [collab-project/videojs-record#254]
This is a suggestion, after reading #76 

Currently, one needs to do the following for example, to change one of the options (in this case, switching camera facing mode from `environment` to `user`)
```js
var player = videojs('videoTag', {
  plugins: {
    record: {
      video: {
        facingMode: 'environment'
      }
    }
  }
});
// ... then
player.options_.plugins.record.video.facingMode = 'user';
player.record().loadOptions();
```

It would be better to have `loadOptions()` accept an optional parameter being the object to get options merged with:
```js
player.record().loadOptions({
  video: {
    facingMode: 'environment'
  }
});
```

(this would be 2 lines in a PR, I'm willing to do if this idea is accepted)

**Comment by thijstriemstra** [comment]
@tomasdev sounds good, cheers.

**Comment by thijstriemstra** [comment]
@tomasdev any news?

**Comment by naveedabbas2007** [comment]
Both of the above mentioned options are not switching the camera.

**Comment by naveedabbas2007** [comment]
Tried this
player.options_.plugins.record.video.facingMode = 'user';
player.record().loadOptions();
and this on as ell, I want to swith the camera but noting is working in my case
player.record().loadOptions({
  video: {
    facingMode: 'environment'
  }
});

**Comment by thijstriemstra** [comment]
@naveedabbas2007 don't hijack a ticket, please open a new one.
