### ISSUE TITLE
Could not find wavesurfer.js microphone plugin!

### ISSUE THREAD

**Issue by SachinDev108** [collab-project/videojs-record#257]
Hello Guys,

 I get the error when I use the wavesurfer in videojs for only audio 
`VIDEOJS: ERROR: Could not find wavesurfer.js microphone plugin!`

**Comment by thijstriemstra** [comment]
@SachinDev108 can you show the code you're using?

**Comment by SachinDev108** [comment]
```
$("#start-audio-recording").click(function() {
    var player = videojs("myAudio", {
      controls: true,
      width: 600,
      height: 300,
      fluid: false,
      plugins: {
        wavesurfer: {
          src: "live",
          waveColor: "#6fffe9",
          progressColor: "black",
          debug: true,
          cursorWidth: 1,
          msDisplayMax: 20,
          hideScrollbar: true
        },
        record: {
          audio: true,
          video: false,
          maxLength: 20,
          debug: true,
          audioEngine: "recorder.js"
        }
      }
    }, function() {
    // print version information at startup
      var msg = 'Using video.js ' + videojs.VERSION +
        ' with videojs-record ' + videojs.getPluginVersion('record') +
        ' and videojs-wavesurfer ' + videojs.getPluginVersion('wavesurfer');
        videojs.log(msg);
    });
    // error handling
    player.on('deviceError', function() {
        console.log('device error:', player.deviceErrorCode);
    });
    player.on('error', function(error) {
        console.log('error:', error);
    });
    // user clicked the record button and started recording
    player.on('startRecord', function() {
        console.log('started recording!');
    });
    // user completed recording and stream is available
    player.on('finishRecord', function() {
        // the blob object contains the recorded data that
        // can be downloaded by the user, stored on server etc.
        console.log('finished recording: ', player.recordedData);
    });
  });
```

**Comment by thijstriemstra** [comment]
@SachinDev108 are you sure you included all scripts (in this order): https://github.com/collab-project/videojs-record/blob/master/examples/audio-only.html#L10

**Comment by thijstriemstra** [comment]
any news @SachinDev108 ?

**Comment by thijstriemstra** [comment]
No feedback, closing.

**Comment by vatsal2210** [comment]
Any updates? I'm also getting the same error. 

`
import videojs from 'video.js';
import * as adapter from 'webrtc-adapter/out/adapter_no_global.js';
import * as RecordRTC from 'recordrtc';

// register videojs-record plugin with this import
import * as Record from 'videojs-record/dist/videojs.record.js';
import 'webrtc-adapter';

import * as WaveSurfer from 'wavesurfer.js';
import * as MicrophonePlugin from 'wavesurfer.js/dist/plugin/wavesurfer.microphone.js';
import 'videojs-wavesurfer/dist/videojs.wavesurfer.js';
WaveSurfer.microphone = MicrophonePlugin;

const playerOptions = {
	controls: true,
	autoplay: false,
	fluid: true,
	loop: false,
	width: 480,
	height: 360,
	plugins: {
		// configure videojs-wavesurfer plugin
		wavesurfer: {
			src: 'live',
			debug: true,
			cursorWidth: 0,
			// interact: false,
			waveColor: '#e35841',
			progressColor: 'black',
			cursorColor: 'black',
			hideScrollbar: true
		},
		record: {
			audio: true,
			video: false,
			maxLength: 60 * 60 * 2,
			debug: true
		}
	}
};

ngAfterViewInit() {

		// setup the player via the unique element ID
		this.player = videojs('speakAudio', playerOptions, () => {
			// // print version information at startup
			var msg = 'Using video.js ' + videojs.VERSION +
				' with videojs-record ' + videojs.getPluginVersion('record') +
				', videojs-wavesurfer ' + videojs.getPluginVersion('wavesurfer') +
				', wavesurfer.js ' + WaveSurfer.VERSION + ' and recordrtc ' +
				RecordRTC.version;
			videojs.log(msg);
		});

		// device is ready
		this.player.on('deviceReady', () => {
			console.log('device is ready!');
			this.player.wavesurfer().destroy();
		});

		// user clicked the record button and started recording
		this.player.on('startRecord', function () {
			console.log('started recording!');
		});

		// user completed recording and stream is available
		this.player.on('finishRecord', () => {
			// this.player.record().saveAs({ 'video': 'my-video-file-name.webm' });
			console.log('finished recording: ', this.player.recordedData);
		});

		// error handling
		this.player.on('error', (element, error) => {
			console.warn(error);
		});

		this.player.on('deviceError', () => {
			console.error('device error:', this.player.deviceErrorCode);
		});
	}


`

**Comment by thijstriemstra** [comment]
@vatsal2210 what version of videojs-record? what version of videojs-wavesurfer?

**Comment by vatsal2210** [comment]
Hi @thijstriemstra     

`"videojs-record": "^3.8.0"`
`"videojs-wavesurfer": "^2.9.0"`

**Comment by thijstriemstra** [comment]
I improved the [Angular wiki page](https://github.com/collab-project/videojs-record/wiki/Angular) and am also running into this issue now. Reopening ticket.

**Comment by thijstriemstra** [comment]
Also created a Angular wiki page for videojs-wavesurfer and there the exact same microphone plugin import works fine..

https://github.com/collab-project/videojs-wavesurfer/wiki/Angular

**Comment by vatsal2210** [comment]
@thijstriemstra Did you test with `src:'live'`?

I'm still getting error as below on browser:

```
video.es.js:149 VIDEOJS: ERROR: Could not find wavesurfer.js microphone plugin!
```

console.log as below for library versions:
`VIDEOJS: Using video.js 7.5.5 with videojs-record 3.8.0, videojs-wavesurfer 2.9.0, wavesurfer.js 3.0.0 and recordrtc 5.5.8`

**Comment by vatsal2210** [comment]
Hi @thijstriemstra,  any updates for same?

**Comment by thijstriemstra** [comment]
No, not yet. This probably needs a bigger change in videojs-record where the Wavesurfer microphone plugin is passed to videojs-record using parameters/options.

**Comment by wvrzel** [comment]
Is there any information about a the last working version of the dependencies?

**Comment by thijstriemstra** [comment]
With angular? not sure.

**Comment by thijstriemstra** [comment]
See #405 for updates.
