### ISSUE TITLE
getUserMedia() no longer works on insecure origins 

### ISSUE THREAD

**Issue by mqliutie** [collab-project/videojs-record#26]
why?

At first time, I opened the html file it was ok. But when I change html file this problem was coming

getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS

I use gulp browser-sync package load these files

**Comment by mqliutie** [comment]
Also mobile phone is not work in chrome browser.

**Comment by mqliutie** [comment]
graduation.avosapps.com

you can look here use mobile phone

**Comment by thijstriemstra** [comment]
I can't change the fact that HTTPS is now required in Chrome for getUserMedia, what do you suggest?

**Comment by nico0689** [comment]
Hi guys, do you have any solution for this issue? I'm having the same problem. Thanks.

**Comment by thijstriemstra** [comment]
"Starting with Chrome 47, getUserMedia() requests are only allowed from secure origins: HTTPS or localhost." See https://developers.google.com/web/updates/2015/10/chrome-47-webrtc?hl=en
