### ISSUE TITLE
timeSlice acting strange with 100ms

### ISSUE THREAD

**Issue by Ali-Dalal** [collab-project/videojs-record#261]
When I set the timeSlice to  100 ms and video length to 10 seconds

I should get 10000/100 = 100 timeSlices.

but instead, I get only 83 timeSlices

```javascript
var round = 0;
var count = 0
options ={...,timeSlice:100,...}

record.on("timestamp", function (a) {
        round += 100;
        console.log(roundd + '   ' + cnt++);
});
```

when I set the timeSlice to 1000, I get the right result (10 times +1)

could u pleas help?

**Comment by thijstriemstra** [comment]
@Ali-Dalal the timeslice functionality comes from the RecordRTC library, it's likely the bug is there. I'll take a look at some point. First 🌞

**Comment by thijstriemstra** [comment]
@Ali-Dalal how big is one of these 83 slices? Looking at this it seems like it needs to be at least 100 bytes: https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC.js#L2091

And this line suggests the event can not be triggered any faster than 100ms: https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC.js#L2267

**Comment by thijstriemstra** [comment]
No feedback, closing.
