### ISSUE TITLE
stopDevice() and getDevice() not working as expected

### ISSUE THREAD

**Issue by nisalikularatne** [collab-project/videojs-record#262]
## Description
Currently I am trying to switch between cameras. Therefore I stopped the device using stopDevice and want to get it back using getDevice with the new deviceId. However I am getting an error after I stopDevice() and getDevice().

## Steps to reproduce
             videoPlatform.stopDevice()
             videoPlatform.onLoadOptions(deviceId)
             videoPlatform.getDevice()

### Expected
I expected to see the device restarting and allowing the user to record the video

### Actual
The error mentioned below occured and video recording started automatically.

### Error output
VIDEOJS: ERROR: DOMException: Failed to execute 'start' on 'MediaRecorder': The MediaRecorder failed to start because there are no audio or video tracks available.

**Comment by sarathdisha** [comment]
Could You explain how did you find the solution?

**Comment by nisalikularatne** [comment]
It was an error on my side. I had inserted additional lines of code which were redundant and gave errors after videoPlatform.record().getDevice()

**Comment by sarathdisha** [comment]
@nisalikularatne Thanks I fixed my fault in the code.

**Comment by noreen24** [comment]
how
