### ISSUE TITLE
React Wiki - TypeError: EngineClass is not a constructor

### ISSUE THREAD

**Issue by johnblakey** [collab-project/videojs-record#263]
## Description
I am following the React Wiki @ [vidoejs-record/wiki/React](https://github.com/collab-project/videojs-record/wiki/React) and was able to compile and run on `localhost:3000` to test. When clicking on the record button an error is thrown. I tried running with prior versions of videojs-record (2.3.0 and 2.3.1) but the same error was output.

This is related to [Issue 249](https://github.com/collab-project/videojs-record/issues/249).

## Steps to reproduce
Follow all the steps in the React Wiki (link above), execute `npm start`, go to `localhost:3000`, and click on the record button. The only step I modified I modified (per the instructions) the `index.html` file in the 'public' directory. ***NOTE:*** **The Wiki instructions "Edit src/index.html:" should read "Edit public/index.html:".** All other steps were followed exactly.

### Expected
I expect to record video with audio when clicking the record button.

### Actual
In the browser console an error is output.

### Error output
`TypeError: EngineClass is not a constructor at Record.onDeviceReady (videojs.record.js:2214)`
`__stack_frame_overlay_proxy_console__ @ index.js:2178`
`onDeviceReady @ videojs.record.js:2216`
`Promise.then (async)`
`getDevice @ videojs.record.js:2123`
`handleClick @ videojs.record.js:488`
`bound @ video.cjs.js:2070`
`data.dispatcher @ video.cjs.js:1717`

## Additional Information

Excerpt from webpack.config.dev.js file:
```javascript
    // for React Native Web.
    extensions: ['.web.js', '.mjs', '.js', '.json', '.web.jsx', '.jsx'],
    alias: {
      // Per @ https://github.com/collab-project/videojs-record/wiki/React
      videojs: 'video.js',
      WaveSurfer: 'wavesurfer.js',
      // Support React Native Web
      // https://www.smashingmagazine.com/2016/08/a-glimpse-into-the-future-with-react-native-for-web/
      'react-native': 'react-native-web',
    },
```
and from the plugins array at the bottom of the webpack.config.dev.js file:
```javascript
    // Added per @ https://github.com/collab-project/videojs-record/wiki/React
    new webpack.ProvidePlugin({
      videojs: 'video.js/dist/video.cjs.js',
      RecordRTC: 'recordrtc'
    }),
```

From the comment at the bottom of [Issue 249](https://github.com/collab-project/videojs-record/issues/249) I tried changing the webpack.config.dev.js file line `videojs: 'video.js/dist/video.cjs.js'` to `videojs: 'video.js/dist/video.umd.js'`. But when I did the app would not compile and threw this error:
```
Failed to compile.

./node_modules/videojs-record/dist/videojs.record.js
Module not found: Can't resolve 'video.js/dist/video.umd.js' in '/Users/john.blakey/gitref/JB/react-audio-recording/my-app/node_modules/videojs-record/dist'
```

From the package.json file dependencies section:
```javascript
    "videojs-record": "^2.3.2",
```

#### videojs-record
2.3.2
####  video.js
7.1.0
#### recordrtc
5.4.7
#### browsers
Chrome Version 67.0.3396.99
#### OSes
macOS High Sierra Version 10.13.6

**Comment by thijstriemstra** [comment]
@johnblakey what does the video.js config look like?

**Comment by johnblakey** [comment]
@thijstriemstra Thank you for the quick response - are you referring to the videoJsOptions in the index.js file? If so it looks like this:
```javascript
const videoJsOptions = {
    controls: true,
    width: 320,
    height: 240,
    fluid: false,
    plugins: {
        record: {
            audio: true,
            video: true,
            maxLength: 10,
            debug: true
        }
    }
};
```
Or is there a video.js config that is located somewhere else?

**Comment by thijstriemstra** [comment]
> NOTE: The Wiki instructions "Edit src/index.html:" should read "Edit public/index.html:". All other steps were followed exactly.

Updated the path on the wiki page.

**Comment by thijstriemstra** [comment]
Able to reproduce it, will take a look when I have time.

<img width="625" alt="screen shot 2018-07-28 at 01 12 52" src="https://user-images.githubusercontent.com/305679/43349898-7e734864-9203-11e8-8ce1-467956ece3a6.png">

**Comment by thijstriemstra** [comment]
what's weird it references 'video.es.js' and not 'video.js/dist/video.cjs.js' like we specified in the webpack config..

**Comment by thijstriemstra** [comment]
@johnblakey I managed to solve the issue, check #264 and let me know how it goes..

**Comment by johnblakey** [comment]
@thijstriemstra I didn't modify any of the source files related to the Wiki and tried installing the videojs-record npm package from my cloned copy of your vidoejs-record repo by switching to your ```react-import-263``` branch and doing an ```npm install <path to base directory of react-import-263>```. It failed to compile with the following error:

```
Failed to compile.

./src/App.js
Module not found: Can't resolve 'recordrtc' in '/Users/john.blakey/gitref/JB/react-audio-recording/my-app/src'
```

Should I modify the App.js file? Or am I not installing videojs-record from your branch correctly? My Googling leads me to believe I didn't install your experimental npm package correctly. I tried installing directly from the GitHub url but was unsuccessful.

**Comment by johnblakey** [comment]
@thijstriemstra I overwrote the ```node_modules/videojs-record/dist``` directory with the zip above. It compiled but I got the same error as before when trying to record:

```
index.js:2178 TypeError: EngineClass is not a constructor at Record.onDeviceReady (videojs.record.js:2214)
```

**Comment by thijstriemstra** [comment]
thanks for your feedback, I'll release this fix asap.
