### ISSUE TITLE
Documentation: React Wiki and related method

### ISSUE THREAD

**Issue by johnblakey** [collab-project/videojs-record#266]
## Description
I created the React version of from the Wiki https://github.com/collab-project/videojs-record/wiki/React

The ```saveAs``` method https://github.com/collab-project/videojs-record#save-data needs to have ```this.player()``` instead of the original ```player```, full React line:
```javascript
this.player().record().saveAs({'audio': 'my-video-file-name.webm'});
```

Additionally a console.log will return ```undefined``` unless the 'finished recording' log message is changed to:
```javascript
console.log('finished recording: ', this.player().recordedData);
```

It could be helpful pointing this out in a separate section for people like me who are new to React.

**Comment by thijstriemstra** [comment]
@johnblakey I've used arrow functions in #270 so `this.player` can be used everywhere.
