### ISSUE TITLE
Sending realtime audio using websockets

### ISSUE THREAD

**Issue by nkleinert** [collab-project/videojs-record#272]
## Description
Hello, is it possible to send the output from the microphone in real time, for example via socket.io?
I have not found a method in the documentation to get the current buffer from the microphone.

**Comment by thijstriemstra** [comment]
Interesting idea. I'll see if I can come up with an example.

**Comment by nkleinert** [comment]
Thank you so much for taking the time.
I haven't had a chance to test everything today, but I will give you some feedback.

**Comment by thijstriemstra** [comment]
any news @nkleinert?

**Comment by nkleinert** [comment]
It worked fine with socket.io and node-opus.

**Comment by thijstriemstra** [comment]
@nkleinert thanks for the feedback. Let's merge the pull request before closing this ticket ;)

Can you share the code you used?

**Comment by thijstriemstra** [comment]
Ended up adding a `audioBufferUpdate` option. If you enable it, a `audioBufferUpdate` event will be fired.
