### ISSUE TITLE
timeSlice doesn't work with default webpack config

### ISSUE THREAD

**Issue by GDIBass** [collab-project/videojs-record#277]
## Description
Timeslice doesn't work with default webpack config.

## Steps to reproduce
Install default webpack config.  Add timeslice to the config.  Begin recording and watch console log.

### Expected
Expected to see stored blobs when timeslices are hit.

### Actual
No recording is done and there is an error.

### Error output
```javascript
video.es.js:117 VIDEOJS: ERROR: ReferenceError: MediaStreamRecorder is not defined
    at Record.onTimeStamp (videojs.record.js:3202)
    at updateTimeStamp (RecordRTC.js:2216)
    at MediaStreamRecorder.record (RecordRTC.js:2190)
    at initRecorder (RecordRTC.js:94)
    at Object.startRecording (RecordRTC.js:74)
    at MRecordRTC.startRecording (RecordRTC.js:1202)
    at RecordRTCEngine.start (videojs.record.js:1335)
    at Record.startRecording (videojs.record.js:2445)
    at Player.eval (videojs.record.js:2411)
    at HTMLDivElement.bound (video.es.js:2093)
```
## Additional Information
Please include any additional information necessary here. Including the following:
### versions
Latest
#### videojs
Latest
#### browsers
Google Chrome, haven't tested Firefox
#### OSes
Ubuntu 18.04

I have managed to get around the error by adding an additional line to the ProvidePlugin
```
 MediaStreamRecorder: 'msr'
```
However, despite not getting an error I now see nothing in the recordedData blobs when the time slice hits.  Saving at the end of a recording still works fine, but no blobs are created until the recording is finished.

**Comment by thijstriemstra** [comment]
Thanks for the report @GDIBass. Can you still state the versions of video.js, videojs-record, recordrtc and browsers (because 'latest' is already outdated by now).

**Comment by GDIBass** [comment]
Yes of course.  I'll be back in front of my desktop in an hour or two and I'll post the versions then.

**Comment by GDIBass** [comment]
From my yarn.lock file
```
recordrtc@>=5.4.7:
  version "5.4.7"
  resolved "https://registry.yarnpkg.com/recordrtc/-/recordrtc-5.4.7.tgz#812f237fa3f83eb2a9fd5a007421f263b141985f"

...

"video.js@^6.8.0 || ^7.0.0", video.js@>=6.0.0, video.js@>=6.2.7:
  version "7.2.2"
  resolved "https://registry.yarnpkg.com/video.js/-/video.js-7.2.2.tgz#4a1197b2f0c265a1e50d5cd4ff41cd030e22a423"
  dependencies:
    "@videojs/http-streaming" "1.2.4"
    babel-runtime "^6.9.2"
    global "4.3.2"
    safe-json-parse "4.0.0"
    tsml "1.0.1"
    videojs-font "3.0.0"
    videojs-vtt.js "0.14.1"
    xhr "2.4.0"

...

videojs-record:
  version "2.4.1"
  resolved "https://registry.yarnpkg.com/videojs-record/-/videojs-record-2.4.1.tgz#d1e3aa911c1ea9b387460c5e8d1cdac99a21f546"
  dependencies:
    recordrtc ">=5.4.7"
    video.js ">=6.2.7"
    videojs-wavesurfer ">=2.5.0"
    webrtc-adapter ">=6.2.1"
```
My browser is Google Chrome Version 68.0.3440.106 (Official Build) (64-bit) on Ubuntu 18.04 Desktop LTS.

Let me know if you need me to test it in Firefox or another browser, or if you can recreate it with that information. 

The version of MSR I installed is:
```
msr:
  version "1.3.4"
  resolved "https://registry.yarnpkg.com/msr/-/msr-1.3.4.tgz#489458468d5385e6ac1b2e112a8724a844314fa2"
```

**Comment by thijstriemstra** [comment]
The class is available though, I added this to `app.js` and the class is printed properly:

```javascript
const MediaStreamRecorder = RecordRTC.MediaStreamRecorder;
console.log(RecordRTC.MediaStreamRecorder);
console.log(MediaStreamRecorder);
```

Need to figure out how to tell webpack about this..

**Comment by thijstriemstra** [comment]
Figured it out and updated the wiki page. Basically add this `MediaStreamRecorder` reference here:

```javascript
new webpack.ProvidePlugin({
            videojs: 'video.js/dist/video.cjs.js',
            RecordRTC: 'recordrtc',
            MediaStreamRecorder: ['recordrtc', 'MediaStreamRecorder']
        })
```
