### ISSUE TITLE
add vue.js example

### ISSUE THREAD

**Issue by thijstriemstra** [collab-project/videojs-record#283]
A wiki page or example showing how to use vue.js with videojs-record.

see https://cli.vuejs.org/guide/creating-a-project.html#vue-create

**Comment by thijstriemstra** [comment]
See https://github.com/collab-project/videojs-record/wiki/Vue.js

**Comment by 4unkur** [comment]
Example here is not playing the recorded video...  
https://github.com/collab-project/videojs-record/wiki/Vue.js  

When I hit on play button after recording is finished it doesn't do anything

**Comment by hyvyys** [comment]
Add a link to this example to README?

**Comment by thijstriemstra** [comment]
sounds good. Feel free to make the change and open a pull request @hyvyys

**Comment by talalz94** [comment]
@thijstriemstra  Hi buddy. Do you have any idea how can I get the live image frames from the web-cam stream from the front end. So I want to send the web-stream to a backend server but I want to do it frame by frame, regardless of the FPS of the web-cam. I was thinking if I could put a canvas over the video-class and just fetch that in a loop while the camera is on. Could you comment on that? Thanks :)

**Comment by thijstriemstra** [comment]
@talalz94 please open a new ticket for questions, don't hijack an existing ticket.
