### ISSUE TITLE
Upload files to Server

### ISSUE THREAD

**Issue by zang** [collab-project/videojs-record#29]
I am trying to use the following popular file upload lib (https://github.com/blueimp/jQuery-File-Upload) to get the recorded blob data to php server, but couldn't figure out how to call the upload function. 

Could anybody point me to the right direction?

thanks in advance,
Lucy

**Comment by thijstriemstra** [comment]
That's a nice plugin. I can add an example but it'll take a day or two since it's christmas ;)

**Comment by zang** [comment]
Thanks a lot. :)

Yep, one of the reason I am choosing that lib is the chunked upload feature to improve the memory performance etc. I tried with their example but not able to figure out how to pass the generated blob data. It will be great if you can create an example, much appreciated.

Thanks again,
Lucy

**Comment by pmccarren** [comment]
Hi!

This is an outstanding plugin! I have one quick question that is an extension of the one above. After I get the recordedData uploaded and stored offsite, how can I feed the data back into the player on a subsequent page load? Eg. User A records + uploads a video, and User B wants to watch it.

Any help you can provide would be much appreciated!

Thanks!
Patrick

**Comment by zang** [comment]
@pmccarren , did you try videojs to play the recorded video? e.g. http://videojs.com/
BTW, did you use blueimp to get the recordedData to server? If so, do you mind to share your code with us? :)

thanks,
Lucy

**Comment by pmccarren** [comment]
Hi @zang! I utilized the logic found here: http://bit.ly/1TmDg7k to do an Amazon S3 upload. I've been looking at videojs but am not sure how to load both the audio + video tracks in the chrome browser. (video is a webm blob and the audio is a wav blob). Obviously in the videojs-record demo (https://collab-project.github.io/videojs-record/examples/audio-video.html) you can record a video with audio and play it back. Know how to take the recorded data and load it at a later date? What if someone records with Firefox and someone else wants to play with Chrome? Chrome doesn't support the single track webm+audio format.

Thanks a bunch!!
Patrick

**Comment by thijstriemstra** [comment]
@zang I uploaded an jquery fileupload example just now, could you give it a try and let me know how it works out?

**Comment by thijstriemstra** [comment]
@pmccarren you could use http://ffmpeg.org on the server-side to generate the files for different browsers (mp3, mp4, ogg etc).

**Comment by zang** [comment]
You are a star!! The file uploading works perfectly. However, I got a separate issue when I try to trans-code the video with ffmpeg. It throws an error saying 'invalid duration'. I then run ffprobe and got the following results. Any idea on how to set the duration and bitrate? :)

Input #0, matroska,webm, from '1451315141116.webm':
  Metadata:
    encoder         : QTmuxingAppLibWebM-0.0.1
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp8, yuv420p, 640x480, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: vorbis, 44100 Hz, mono, fltp (default)

--- A separate question ---
Btw, is there a way to increase resolution from 640*480 to 720p?


thanks again,
Lucy

**Comment by zang** [comment]
Hi Patrick, I am planning to use ffmpeg to merge the audio and video for chrome recording. :)

**Comment by thijstriemstra** [comment]
@zang what browser version and platform? Sounds like an issue with the way RecordRTC records these mixed media files.

**Comment by thijstriemstra** [comment]
@zang try setting width and height, it defaults to 640*480 I think.

**Comment by zang** [comment]
@thijstriemstra I am on Macintosh Firefox 43.0. and my initialize script is : 
	var player = videojs("record", { controls: true, loop: false, width: 1280, height: 720, plugins: { record: { audio: true, video: true, maxLength: 60 } } });

The recorded video is still in 640*480. 

thanks,
Lucy

**Comment by thijstriemstra** [comment]
That sounds like a separate issue, can you create a new ticket for that?

**Comment by alsar** [comment]
@zang @thijstriemstra 
I implemented setting video constraints in #30

**Comment by zang** [comment]
Excellent! :) 

@thijstriemstra , I've created a separate issue for the 'invalid duration' via https://github.com/collab-project/videojs-record/issues/31

thanks @thijstriemstra @alsar

**Comment by thijstriemstra** [comment]
I've also added an example for the Fine Uploader library. Considering this ticket fixed and closing.

**Comment by zang** [comment]
Thank you so much for your help! 

P.S. As requested, I created a separate ticket for the invalid duration issue. thanks again. :)

**Comment by zang** [comment]
Updated to latest script, got a few errors when I setup the recorder with the following script:
var player = videojs("record", { controls: true, loop: false, plugins: { record: { audio: true, video: { width: 1280, height: 720 }, maxLength: 60 } } });

1) On Chrome Version 47.0.2526.106 (64-bit), I got the following error
Uncaught TypeError: Failed to execute 'webkitGetUserMedia' on 'Navigator': Malformed constraints object.

2) On Firefox, I got the following error when playback the recorded video (I don't get this error for 640*480 solution):
The media playback was aborted due to a corruption problem or because the media used features your browser did not support.

3) On Chrome, I also got the following error when recording both video and audio 
Uncaught TypeError: Cannot read property 'split' of undefined

**Comment by alsar** [comment]
Chrome doesn't support the latest specification for constraints.
You still have to use the "old" syntax for Chrome:
```js
video: {
    mandatory: {
        minWidth: 1280,
        minHeight: 720,
    },
},
```

@thijstriemstra What about using this shim https://github.com/webrtc/adapter to abstract the differences with constraints between browsers?

**Comment by thijstriemstra** [comment]
@alsar I'd prefer to not to add another dependency but after looking at the code I guess it makes sense not to add all of that compat code to this plugin.

**Comment by thijstriemstra** [comment]
Thanks for testing @zang. I've fixed point 3 and 1 should be fixed once the webrtc adapter is used. Still need to test point 2.

**Comment by thijstriemstra** [comment]
Let's use separate tickets to discuss any other issues, this ticket is about uploading files to the server.

**Comment by minhnguyenwp** [comment]
Pls help me. How to upload a video file.  step by step. 

plugins:
                    record:
                        audio: true,
                        video: true,

**Comment by thijstriemstra** [comment]
@minhnguyenwp there are obvious examples here: https://github.com/collab-project/videojs-record/tree/master/examples/upload If you can't figure it out, contact me and send me a bitcoin and I'll help you out ;)

**Comment by minhnguyenwp** [comment]
Thk master. i did exactly like that. but i need upload a video file and i dont know how to add header options with 'blueimp-file-upload', and a simple php get that data file. would u pls help me.!

**Comment by thijstriemstra** [comment]
@minhnguyenwp this sounds like a blueimp-file-upload issue, and you should ask them or place your question on stackoverflow.

**Comment by imrizwan89** [comment]
@thijstriemstra can you share upload example for the same for php server
