### ISSUE TITLE
Unable to hide time controls

### ISSUE THREAD

**Issue by josefpohl** [collab-project/videojs-record#293]
This is basically a question.  Is there a way to set the maxLength (on audio only in this case) to undefined or to set the control to not show the maxLength ( 0:00.000 instead of for instance 0:00.000 / 0:10.000 when maxLength is set to the default).  
Thanks!

video.js 7.2.3 
video.js-record 2.4.1

**Comment by thijstriemstra** [comment]
@josefpohl, you can hide the duration component like this:

```javascript
var player = videojs("myVideo", {
    controls: true,
    width: 320,
    height: 240,
    fluid: false,
    controlBar: {
        durationDisplay: false
    },
```

**Comment by josefpohl** [comment]
Thanks @thijstriemstra , 
With the wavesurfer component this does throw an error on the                                                                                                        setDuration method.

```

index.js:2178 VIDEOJS: ERROR: TypeError: Cannot read property 'contentEl' of undefined
    at Wavesurfer.setDuration (videojs.wavesurfer.js:956)
    at Record.setDuration (videojs.record.js:2785)
    at Record.onDeviceReady (videojs.record.js:2166)
    at wavesurfer.min.js:6
    at Array.forEach (<anonymous>)
    at MicrophonePlugin.value [as fireEvent] (wavesurfer.min.js:6)
    at MicrophonePlugin.gotStream (wavesurfer.microphone.js:442)
    at wavesurfer.microphone.js:274

```

Thanks for the quick response though.
I appreciate the project.

**Comment by thijstriemstra** [comment]
@josefpohl you're right, I'll take a look and consider this a bug.

**Comment by thijstriemstra** [comment]
Also see https://github.com/collab-project/videojs-wavesurfer/issues/73

**Comment by thijstriemstra** [comment]
@josefpohl can you try with videojs-wavesurfer 2.6.1 or newer?

**Comment by thijstriemstra** [comment]
Updated to videojs-wavesurfer 2.6.1 in https://github.com/collab-project/videojs-record/commit/42f6da0107250b7f2aa40ed64149b233d06b0dbf.

**Comment by josefpohl** [comment]
This worked.  Thank you so very much for your diligence!
Once again, I truly appreciate your efforts here.
Joe
