### ISSUE TITLE
Safari Audio Only Recording Fails

### ISSUE THREAD

**Issue by EZWrighter** [collab-project/videojs-record#295]
The audio only demo here: https://collab-project.github.io/videojs-record/examples/audio-only.html

Fails to record On Safari 11 & 12.

In the Console - TypeError: GetRecorderType is not a constructor (evaluating 'new Recorder(mediaStream, config)')

However, RecordRTC audio only example here works fine:  https://webrtc-experiment.com/RecordRTC/simple-demos/audio-recording.html

They seem to do some trickery with the record button in safari.

**Comment by thijstriemstra** [comment]
Source of that demo can be found here: https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/audio-recording.html

@EZWrighter can you try the following, I don't have a safari browser available at the moment:

```javascript
var player = videojs("myAudio", {
    controls: true,
    width: 600,
    height: 300,
    plugins: {
        wavesurfer: {
            src: "live",
            waveColor: "#36393b",
            progressColor: "black",
            debug: true,
            cursorWidth: 1,
            msDisplayMax: 20,
            hideScrollbar: true
        },
        record: {
            audio: true,
            video: false,
            audioRecorderType: StereoAudioRecorder,
            audioSampleRate: 44100,
            audioBufferSize: 4096,
            audioChannels: 2,
            maxLength: 20,
            debug: true
        }
    }
}
```

**Comment by EZWrighter** [comment]
That worked, Thanks!  I previously tried with the StereoAudioRecorder set, but not the Rate,Size or channels.  Would probably be nice if the library defaulted to these settings if required.   Closing as my issue is not resolved.

**Comment by EZWrighter** [comment]
Can we not detect when only certain recording abilities are available?  Like recordertype, channels, rate and size?  Then default to what makes sense for the environment.  I agree browser detection and hacks suck and should not be in the library.  If we cannot detect the features/settings needed, then an example would be the best alternate.

**Comment by thijstriemstra** [comment]
> Can we not detect when only certain recording abilities are available?

if you have any suggestions, fine, but Safari is crippled already, I doubt we can detect that.. I'm going with examples for now.

**Comment by thijstriemstra** [comment]
ps. it seems this workaround should also be applied in MS Edge browser..

**Comment by thijstriemstra** [comment]
@EZWrighter I tested with safari 12.0 and was able to record but did not see the mic audio preview during recording, did you?

**Comment by EZWrighter** [comment]
No, I don't see the preview and if you try to record multiple times, the audio goes to garbage after the first recording.  I ended up just telling safari users to use chrome or firefox for live recording until safari gets better or something gets figured out here.

**Comment by thijstriemstra** [comment]
> No, I don't see the preview 

I made some updates to the example and it now also shows a preview in safari: https://collab-project.github.io/videojs-record/examples/audio-only.html

**Comment by thijstriemstra** [comment]
Note that Safari Technology Preview 73 (presumably the future Safari 13) supports MediaRecorder and this removes the need for the `audioRecorderType: StereoAudioRecorder` workaround.
