### ISSUE TITLE
Get blobs after specific time-intervals

### ISSUE THREAD

**Issue by thijstriemstra** [collab-project/videojs-record#3]
This could be useful in scenarios where you're recording long clip and planning to submit/upload recorded blobs to a server that stiches it together (or maybe even do it clientside).

**Comment by v3ss0n** [comment]
yeah that will be very useful for our realtime chat too.

**Comment by erikdonohoo** [comment]
Is this something that still needs to be done?  We would also like to have this functionality and I'm happy to do the work if someone can help point me in the right direction

**Comment by thijstriemstra** [comment]
PRs are welcome!

**Comment by faraz-purelogics** [comment]
Hi @thijstriemstra ,

Very nice library worked very well.
I will be very thank full to anyone who let me know how to achieve functionality of getting blob after some time intervals.

Thanks,
Faraz

**Comment by thijstriemstra** [comment]
It looks like the latest recordrtc improves support for this. I added a PR (https://github.com/muaz-khan/RecordRTC/pull/283) and will implement a `timeSlice` option in this plugin.

**Comment by thijstriemstra** [comment]
@faraz-purelogics and @erikdonohoo it's now implemented in master, see https://github.com/collab-project/videojs-record#timestamps. Can you give that a try?

**Comment by code-wizard** [comment]
Hey Am having issues with the timestamp event. I am trying to upload a "slice"  of the recorded video. Below is what I noticed.

1. The first slice of the `player.recordedData `contains a blob of  size 1

2. The subsequent slices contain blob array of size + 1
 
I only want to send a particular slice at a time and not the total recorded file. How do I achieve this?

**Comment by code-wizard** [comment]
I just saw this block of code under the timestamp event section of your documentation
// monitor stream data during recording
player.on('timestamp', function() {
    // timestamps
    console.log('current timestamp: ', player.currentTimestamp);
    console.log('all timestamps: ', player.allTimestamps);

    // stream data
    console.log('array of blobs: ', player.recordedData);
    // or construct a single blob:
    // var blob = new Blob(blobs, {
    //     type: 'video/webm'
    // });
});

 How do I construct a single blob?

**Comment by thijstriemstra** [comment]
> How do I construct a single blob?

it says it right there

```javascript
var blob = new Blob(blobs, {
     type: 'video/webm'
 });
```

**Comment by code-wizard** [comment]
How about the timeslice issue I raised? 
 I did the following
`        var binaryData = player.recordedData[player.recordedData.length - 1];
`
The first blob is playable but the subsequent blobs are not playable. How do I resolve this?

**Comment by thijstriemstra** [comment]
> How about the timeslice issue I raised?

you should open a new ticket and not use an existing ticket, thanks.
