### ISSUE TITLE
Need to be able to uninitialize a video recorder once recording done.

### ISSUE THREAD

**Issue by stingrayzboy** [collab-project/videojs-record#304]
I work on a project wherein the UI is completely Ajax based hence once the DOM is loaded there is no way other than to reload the page to refresh the recorder.
I have been working on an ability t record and upload a video in case you dont have a video file ready for upload.
I am able to get the recorder being rendered once through AJAX calls to the media form.
also I was successful in recording the video and populating it in the upload form.

1. But when I close and re open the form the recorder doesnt show.
The console show error of already initialized the video element with ID:

2. Also,since the page is not being refreshed the recording icon that began in the beginning of the recording continues to show even after the form is closed.

I  was able to solve the problem 1 with a bad fix by appending a random number to the recorder ID everything a form is opened.

but if we get a methof that essentially destroys the recorder object. we can call it on finishedRecording callback and get both the issues solved in one go.

**Comment by thijstriemstra** [comment]
@stingrayzboy can you create a simple standalone example that demonstrates the issue? or would `player.record().destroy()` fix your issue? That way you can instantiate a new videojs-record (programatically) every time the form opens (and destroy when it's closed).

**Comment by stingrayzboy** [comment]
Hi, 
Sure I will take a look into both Approaches and let you know.
First will try to delete the player.record().destroy()
