### ISSUE TITLE
Unable to proceed with the recorded data.

### ISSUE THREAD

**Issue by stingrayzboy** [collab-project/videojs-record#305]
I have integrated the VideoJS library in web page .
The Audio only recorder seems to work fine and achieves the required results.
However the video recorder fails to do so.

On investigating I get the following errors in the console:
![image](https://user-images.githubusercontent.com/15889661/48837857-849f7280-edac-11e8-8b9c-129910138d7e.png)
![image](https://user-images.githubusercontent.com/15889661/48837874-8e28da80-edac-11e8-9da0-08afa63a9e86.png)
![image](https://user-images.githubusercontent.com/15889661/48837883-9719ac00-edac-11e8-90ec-7184caab0279.png)

**Comment by thijstriemstra** [comment]
@stingrayzboy I don't see any references to errors in videojs-record library in that stacktrace. Can you create a simple example that re-creates the issue?

You also did not list the video.js, videojs-record versions, browser, operating system etc. Why not?

**Comment by stingrayzboy** [comment]
Hi,
It appears that the issue was a confilcting JS. I was able to resolve it.
