### ISSUE TITLE
Video Preview not working

### ISSUE THREAD

**Issue by bobyper** [collab-project/videojs-record#309]
Video preview not working in demo too
https://collab-project.github.io/videojs-record/examples/audio-video.html

Just record a video and try to preview

**Comment by bobyper** [comment]
Lol, the problem is in 
https://webrtc.github.io/adapter/adapter-latest.js

the file not working.

**Comment by thijstriemstra** [comment]
lol? I'm also seeing the warning below, I'll take a look.

![screenshot from 2018-12-03 18-55-14](https://user-images.githubusercontent.com/305679/49391857-186a2a80-f72d-11e8-97fe-e14967088b8d.png)

**Comment by bobyper** [comment]
i downloaded this version for adapter.js and now working  fine 
https://codeload.github.com/webrtc/adapter/zip/master

**Comment by thijstriemstra** [comment]
@bobyper can you try with `https://unpkg.com/webrtc-adapter/out/adapter.js`?

**Comment by bobyper** [comment]
working fine with https://unpkg.com/webrtc-adapter/out/adapter.js

**Comment by thijstriemstra** [comment]
Cool, updated the examples with that URL.
