### ISSUE TITLE
'Invalid Duration' - Recorded video on Firefox

### ISSUE THREAD

**Issue by zang** [collab-project/videojs-record#31]
- Device - 
Macintosh Firefox 43.0

- Recorder setup script -
var player = videojs("record", { controls: true, loop: false, width: 1280, height: 720, plugins: { record: { audio: true, video: true, maxLength: 60 } } });

- Video info from ffprobe -
Input #0, matroska,webm, from '1451315141116.webm':
Metadata:
encoder : QTmuxingAppLibWebM-0.0.1
Duration: N/A, start: 0.000000, bitrate: N/A
Stream #0:0(eng): Video: vp8, yuv420p, 640x480, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
Stream #0:1(eng): Audio: vorbis, 44100 Hz, mono, fltp (default)

- Error -
Got 'Invalid duration' when I try to use ffmpeg to take thumbnails or seeking in player etc

**Comment by thijstriemstra** [comment]
Looks like a firefox issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1068001

**Comment by zang** [comment]
Thanks @thijstriemstra 
Is there a way to set duration and bitrate manually? :)

**Comment by thijstriemstra** [comment]
@zang does the same happen with this RecordRTC demo? https://www.webrtc-experiment.com/RecordRTC/AudioVideo-on-Firefox.html
If so you probably have to file a ticket for either RecordRTC, whammy (the webm lib that recordrtc uses) or look into Firefox, there's probably not much I can do.

**Comment by thijstriemstra** [comment]
I'm getting the same on Firefox with the demo from the previous comment.

```
ffprobe ~/Downloads/RecordRTC.webm 
ffprobe version N-74720-g21bfeec Copyright (c) 2007-2015 the FFmpeg developers
  built with Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
  configuration: --prefix=/usr/local --enable-gpl --enable-nonfree --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --disable-doc
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 59.100 / 56. 59.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.100 /  5. 40.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, matroska,webm, from '/Users/thijstriemstra/Downloads/RecordRTC.webm':
  Metadata:
    encoder         : QTmuxingAppLibWebM-0.0.1
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp8, yuv420p, 640x480, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: vorbis, 44100 Hz, mono, fltp (default)
```

**Comment by thijstriemstra** [comment]
But opening the webm file in firefox (so without video.js) seems to playback fine...

**Comment by thijstriemstra** [comment]
Clips recorded using [this demo](https://html5-demos.appspot.com/static/getusermedia/record-user-webm.html) look better in ffmpeg:

```
ffprobe ~/Downloads/capture.webm 
ffprobe version N-74720-g21bfeec Copyright (c) 2007-2015 the FFmpeg developers
  built with Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
  configuration: --prefix=/usr/local --enable-gpl --enable-nonfree --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --disable-doc
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 59.100 / 56. 59.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.100 /  5. 40.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, matroska,webm, from '/Users/thijstriemstra/Downloads/capture.webm':
  Metadata:
    encoder         : whammy
  Duration: 00:00:20.34, start: 0.000000, bitrate: 3093 kb/s
    Stream #0:0: Video: vp8, yuv420p, 320x240, SAR 1:1 DAR 4:3, 16.67 fps, 16.67 tbr, 1k tbn, 1k tbc (default)
```

**Comment by thijstriemstra** [comment]
Also looks like such high resolutions as 1280 x 720 are very slow with whammy (2-3 fps) according to [the comments in this issue](https://github.com/muaz-khan/RecordRTC/issues/69).

**Comment by thijstriemstra** [comment]
Looks like recording on Chrome (and Edge) also needs the `video` and `canvas` settings to correctly set the width and height of the recorded video. I suspect these are used by Whammy and Firefox MediaRecorder simply uses the getUserMedia constraints.

```diff
diff --git a/src/js/videojs.record.js b/src/js/videojs.record.js
index 4b6ac3d..6b1a383 100644
--- a/src/js/videojs.record.js
+++ b/src/js/videojs.record.js
@@ -94,6 +94,16 @@
             this.engine.bufferSize = this.bufferSize;
             this.engine.sampleRate = this.sampleRate;
 
+            // XXX: video/canvas settings
+            this.engine.video = {
+                width: 1280,
+                height: 720
+            }
+            this.engine.canvas = {
+                width: 1280,
+                height: 720
+            }
+
             // animated gif settings
             this.engine.quality = this.quality;
             this.engine.frameRate = this.frameRate;
```

Very annoying but I suppose we either find a way to parse the video constraints or we need to add an explicit (video) `width` and `height` option.

**Comment by thijstriemstra** [comment]
So MediaRecorder in Firefox is definitely broken and I added more information to the related ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1068001

Last thing we can try is forcing the Whammy recorder in Firefox which seems to properly write the duration and bitrate.

**Comment by thijstriemstra** [comment]
In Chrome 47 it's using whammy which seems to work fine (as expected):

```
ffprobe version N-74720-g21bfeec Copyright (c) 2007-2015 the FFmpeg developers
  built with Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
  configuration: --prefix=/usr/local --enable-gpl --enable-nonfree --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --disable-doc
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 59.100 / 56. 59.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.100 /  5. 40.100
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Input #0, matroska,webm, from '/Users/thijstriemstra/Sites/jQuery-File-Upload/server/php/files/1451783610600.webm':
  Metadata:
    encoder         : whammy
  Duration: 00:00:03.52, start: 0.000000, bitrate: 3644 kb/s
    Stream #0:0: Video: vp8, yuv420p, 1280x720, SAR 1:1 DAR 16:9, 6.75 tbr, 1k tbn, 1k tbc (default)
```

**Comment by thijstriemstra** [comment]
Looks like you can fix the duration using a couple of ffmpeg command as mentioned here: http://superuser.com/questions/1012170/fix-mediarecorder-videos-with-ffmpeg Could you give that a try @zang?

**Comment by zang** [comment]
thanks a lot @thijstriemstra , I will try the ffmpeg commands and let you know the outcome.

**Comment by zang** [comment]
Tested the commands and duration being added. I also tried a simple command with 'ffmpeg -i old.webm new.mp4' and duration being added to the new.mp4 as well. 

So, I will upload the recorded video to server and run ffmpeg to convert the videos to mp4, problem should be solved. :)

**Comment by thijstriemstra** [comment]
This might be related as well: https://www.fxsitecompat.com/en-CA/docs/2015/x-content-duration-header-for-ogg-media-is-no-longer-supported/

**Comment by thijstriemstra** [comment]
It's now possible to use the ts-ebml plugin to add metadata in Firefox, see https://github.com/collab-project/videojs-record/wiki/Plugins#ts-ebml
