### ISSUE TITLE
video.min.js:12 VIDEOJS: ERROR: TypeError: Cannot read property 'one' of null

### ISSUE THREAD

**Issue by myphproad** [collab-project/videojs-record#310]
## Description
my env is vue2,when i shut down device...                
player.record().destroy();
then the error happened

**Comment by myphproad** [comment]
player.on('finishRecord', function () {
                console.log('finished recording: ', player.recordedData);
                const formData = new FormData();
                formData.append("video_icon", player.recordedData);
                util.uploadFile(formData, that.uploadSuccess);
                player.record().destroy();
            });

**Comment by thijstriemstra** [comment]
@myphproad I need the complete error message, this is not enough info to tell if it's a videojs-record issue or not.

**Comment by thijstriemstra** [comment]
I was able to produce a different error with following code:

```javascript
// user completed recording and stream is available
player.on('finishRecord', function() {
    // the blob object contains the recorded data that
    // can be downloaded by the user, stored on server etc.
    console.log('finished recording: ', player.recordedData);

    player.record().destroy();
});
```

<img width="829" alt="screenshot 2018-12-08 at 14 34 38" src="https://user-images.githubusercontent.com/305679/49686551-75cbf600-faf6-11e8-90bc-8414d07a583d.png">

I'll take a look at it.

**Comment by thijstriemstra** [comment]
@myphproad I pushed a fix to the master branch. Please try that PR (#311) or wait till the next release.
