### ISSUE TITLE
play button is not working for  audio/video demo

### ISSUE THREAD

**Issue by Sathishchary** [collab-project/videojs-record#312]
## Description
I have checked the latest videojs record demo, i am able to record video and audio but when i try to play the video,its not playing and camera is coming.

## Steps to reproduce
https://collab-project.github.io/videojs-record/examples/audio-video.html
just open the demo and click audio/video demo and click capture button and after 10 sec just play the video

### Expected
it should play the video 

### Actual
its not playing and directly changing the time to end .

what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
#### chrome
what platforms (operating systems and devices) are affected?
windows 10

**Comment by thijstriemstra** [comment]
i also noticed this and have not found a fix yet. @Sathishchary what browser version(s) are you using exactly? also include the video.js and videojs-record versioh nrs.

**Comment by awanishraj** [comment]
I am facing the same issue. @thijstriemstra Could you point to an earlier release where this was functional?

**Comment by thijstriemstra** [comment]
Turns out it was an issue in recordrtc and a new version was released.

@Sathishchary and @awanishraj can you try again with recordrtc 5.5.0 and the videojs-record master branch? #315 should've fixed it.

If it works I'll release it as videojs-record 3.2.0.

**Comment by Sathishchary** [comment]
@thijstriemstra , Thanks !. Tested the master code in my local system. It's working. but opera browser has some issue when i play the video,its not showing the video, remaining all browsers i don't see any issue.

**Comment by nicopapy** [comment]
Still the same problem for me : 
Browser: Mozilla Firefox, Version 64.0 (64-bit)
Videojs: 7.4.1
videojs-record js : version 3.2.0
RecordRTC js :5.5.0

**Comment by Sathishchary** [comment]
@nicopapy  di you pull the code  (videojs-record master branch) and test with RecordRTC 5.5.0 ?

**Comment by thijstriemstra** [comment]
@nicopapy what operating system?

**Comment by thijstriemstra** [comment]
@nicopapy turns out there's something happening with webrtc-adapter and after some testing it looks like this was introduced somewhere after v6.3.0 (that works) because 7.1.1 does not work.

So a workaround for now is to pin webrtc-adapter to 6.3.0:
```
npm install webrtc-adapter@6.3.0
```

I'll take a look at what changed..

**Comment by thijstriemstra** [comment]
Should be fixed in v3.2.1.

**Comment by nicopapy** [comment]
yes, fixed in v3.2.1, thanks
