### ISSUE TITLE
Upload isn't Working

### ISSUE THREAD

**Issue by conan1987** [collab-project/videojs-record#314]
Hi
I tried to upload using the explaination and simple file example everything works fine in console but i can't find the uploaded file 
Here is my script :

```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Audio/Video Example - Record Plugin for Video.js</title>

  <link href="../node_modules/video.js/dist/video-js.min.css" rel="stylesheet">
  <link href="../dist/css/videojs.record.css" rel="stylesheet">

  <script src="../node_modules/video.js/dist/video.min.js"></script>
  <script src="../node_modules/recordrtc/RecordRTC.js"></script>
  <script src="../node_modules/webrtc-adapter/out/adapter.js"></script>

  <script src="../dist/videojs.record.js"></script>

  <style>
  /* change player background color */
  #myVideo {
      background-color: #9ab87a;
  }
  </style>
</head>
<body>

<video id="myVideo" class="video-js vjs-default-skin"></video>

<script>
var options = {
    controls: true,
    width: 640,
    height: 480,
    fluid: false,
    plugins: {
        record: {
            audio: true,
            video: true,
            maxLength: 1800,
            debug: true
        }
    }
};

var player = videojs('myVideo', options, function() {
    // print version information at startup
    var msg = 'Using video.js ' + videojs.VERSION +
        ' with videojs-record ' + videojs.getPluginVersion('record') +
        ' and recordrtc ' + RecordRTC.version;
    videojs.log(msg);
});

// error handling
player.on('deviceError', function() {
    console.log('device error:', player.deviceErrorCode);
});

player.on('error', function(error) {
    console.log('error:', error);
});

// user clicked the record button and started recording
player.on('startRecord', function() {
    console.log('started recording!');
});

// user completed recording and stream is available
player.on('finishRecord', function() {
    // the blob object contains the recorded data that
    // can be downloaded by the user, stored on server etc.
    console.log('finished recording: ', player.recordedData);
	    //player.record().saveAs({'video': 'my-video-file-name.webm'});
player.record().stopDevice();
    upload(player.recordedData);

});
function upload(blob) {

    var serverUrl = '/upload';
    var formData = new FormData();
    formData.append('file', blob, blob.name);
    console.log('upload recording ' + blob.name + ' to ' + serverUrl);
    // start upload
    fetch(serverUrl, {
        method: 'POST',
        body: formData
    }).then(
        success => console.log('upload recording complete.')
    ).catch(
        error => console.error('an upload error occurred!')
    );
}
</script>

</body>
</html>
```

**Comment by thijstriemstra** [comment]
> but i can't find the uploaded file

Can you be more specific @conan1987? any errors or log messages?

**Comment by conan1987** [comment]
There is no error messages , just can't find the file in any folder
Here is the console log
`VIDEOJS: Using video.js 7.2.2 with videojs-record 3.1.0 and recordrtc 5.4.9
RecordRTC.js:59 started recording video stream.
RecordRTC.js:1039 Using recorderType: MediaStreamRecorder
RecordRTC.js:2044 Passing following config over MediaRecorder API. Object
RecordRTC.js:699 Recorder state changed: recording
RecordRTC.js:99 Initialized recorderType: MediaStreamRecorder for output-type: video
audio-video.html:62 started recording!
RecordRTC.js:125 Stopped recording video stream.
RecordRTC.js:699 Recorder state changed: stopped
RecordRTC.js:166 video/webm -> 25.0 KB
audio-video.html:69 finished recording:  Blob(25030)lastModified: 1546710314650lastModifiedDate: Sat Jan 05 2019 19:45:14 GMT+0200 (Eastern European Standard Time) {}name: "1546710314650.webm"size: 25030type: "video/webm"__proto__: Blob
audio-video.html:80 upload recording 1546710314650.webm to /upload
audio-video.html:86 upload recording complete.`

**Comment by thijstriemstra** [comment]
@conan1987 I guess you're using the simple upload example using `npm run start`. The file will be placed in a new folder called `uploads`.

**Comment by conan1987** [comment]
yes that is what i am using but i can't find any files

**Comment by thijstriemstra** [comment]
@conan1987 can you copy/paste the last 30 lines of the `npm run start` process? Everytime you upload a file it should print a line in the terminal.

**Comment by conan1987** [comment]
I ma new to node JS
But here is the lines
`Version: webpack 4.27.1
Time: 2419ms
Built at: 2019-01-05 20:00:48
                     Asset      Size          Chunks                    Chunk Names
    css/videojs.record.css  8.37 KiB  videojs.record  [emitted]         videojs.record
css/videojs.record.css.map  10.1 KiB  videojs.record  [emitted]         videojs.record
  fonts/videojs-record.svg  2.42 KiB                  [emitted]
  fonts/videojs-record.ttf  2.25 KiB                  [emitted]
 fonts/videojs-record.woff  1.33 KiB                  [emitted]
         videojs.record.js   441 KiB  videojs.record  [emitted]  [big]  videojs.record
     videojs.record.js.map   512 KiB  videojs.record  [emitted]         videojs.record
Entrypoint videojs.record [big] = css/videojs.record.css videojs.record.js css/videojs.record.css.map videojs.record.js.map
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./src/js/videojs.record.js ./src/css/videojs.record.scss 52 bytes {videojs.record} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {videojs.record} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {videojs.record} [built]
[./node_modules/url/url.js] 22.8 KiB {videojs.record} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 7.78 KiB {videojs.record} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {videojs.record} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {videojs.record} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {videojs.record} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {videojs.record} [built]
[./src/css/videojs.record.scss] 39 bytes {videojs.record} [built]
[./src/js/controls/animation-display.js] 3.92 KiB {videojs.record} [built]
[./src/js/controls/camera-button.js] 6.32 KiB {videojs.record} [built]
[./src/js/controls/device-button.js] 3.65 KiB {videojs.record} [built]
[./src/js/controls/record-canvas.js] 3.87 KiB {videojs.record} [built]
[./src/js/videojs.record.js] 50 KiB {videojs.record} [built]
    + 28 hidden modules
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/sass-loader/lib/loader.js!src/css/videojs.record.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/lib/loader.js!./src/css/videojs.record.scss] 8.69 KiB {mini-css-extract-plugin} [built]
    [./node_modules/css-loader/dist/runtime/api.js] 2.35 KiB {mini-css-extract-plugin} [built]
i ｢wdm｣: Compiled successfully.`

**Comment by thijstriemstra** [comment]
@conan1987 when you upload a file, a new line should appear below this one:

```
i ｢wdm｣: Compiled successfully.
```

**Comment by conan1987** [comment]
then what might be the problem ? is it related to the local host ?

**Comment by thijstriemstra** [comment]
@conan1987 you should also see these lines when you scroll up:

```
 [examples] wasm mime-type handler ready


 [examples] /upload handler ready

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /foo/projects/videojs-record
ℹ ｢wdm｣: Hash: c16853d00321b6cb013a
Version: webpack 4.27.1
Time: 2764ms
Built at: 2019-01-05 19:05:30
```

**Comment by thijstriemstra** [comment]
In the browser I see:

```
 upload recording 1546711643550.webm to /upload simple.html:80:5
upload recording complete. simple.html:87:20 
```

In the console I see:

```
saving uploaded file...
filename: 1546711643550.webm
saved file.
```

**Comment by conan1987** [comment]
i saw the upload handler ready lines

**Comment by conan1987** [comment]
and i searched the files all over the computer but i can't find it anywhere

**Comment by thijstriemstra** [comment]
@conan1987 can you create the `uploads` folder yourself, perhaps it's a permission issue? You also didn't state what operating system version etc you're using.

**Comment by conan1987** [comment]
I created 2 upload folder , i am  using windows 10

**Comment by thijstriemstra** [comment]
@conan1987 can you create a screenshot of your videojs-record directory?

**Comment by conan1987** [comment]
![n1](https://user-images.githubusercontent.com/46288686/50727686-1b3ead80-1127-11e9-98e0-07799d08ce81.png)
![n2](https://user-images.githubusercontent.com/46288686/50727687-1b3ead80-1127-11e9-960f-93fa0aaed574.png)
![n3](https://user-images.githubusercontent.com/46288686/50727688-1b3ead80-1127-11e9-8790-fecc29748fc5.png)

**Comment by thijstriemstra** [comment]
@conan1987 create a folder called `uploads` in `videojs-record-master` and try again..

**Comment by thijstriemstra** [comment]
no it shouldn't be `upload`, here's the code for the node.js part: https://github.com/collab-project/videojs-record/blob/master/build-config/fragments/dev.js#L56

**Comment by conan1987** [comment]
Here is the console results if i changed upload to uploads
finished recording:  Blob(155172) {lastModified: 1546713288537, lastModifiedDate: Sat Jan 05 2019 20:34:48 GMT+0200 (Eastern European Standard Time), name: "1546713288537.webm", size: 155172, type: "video/webm"}
audio-video.html:80 upload recording 1546713288537.webm to /upload
audio-video.html:82 POST http://localhost/upload 404 (Not Found)
upload @ audio-video.html:82
(anonymous) @ audio-video.html:72
n @ video.min.js:12
o.dispatcher.o.dispatcher @ video.min.js:12
bt @ video.min.js:12
trigger @ video.min.js:12
onRecordComplete @ videojs.record.js:840
n @ video.min.js:12
o.dispatcher.o.dispatcher @ video.min.js:12
bt @ video.min.js:12
trigger @ video.min.js:12
(anonymous) @ record-rtc.js:165
MRecordRTC.getBlob @ RecordRTC.js:1348
onStopRecording @ record-rtc.js:137
(anonymous) @ RecordRTC.js:1264
_callback @ RecordRTC.js:173
mediaRecorder.ondataavailable @ RecordRTC.js:2124
audio-video.html:86 upload recording complete.

**Comment by thijstriemstra** [comment]
@conan1987 you should use http://localhost:8080 in the browser, the dev server doesn't run on localhost:80

**Comment by conan1987** [comment]
it worked , thanks

**Comment by thijstriemstra** [comment]
I will adjust the node script so it creates the directory automatically, otherwise you'll see an error like this:

```
saving uploaded file...
filename: 1546713324709.webm
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'uploads/1546713324709.webm'
```

@conan1987 good to hear it worked!

**Comment by conan1987** [comment]
ok that will be better , thanks
