### ISSUE TITLE
Audio codec/mime

### ISSUE THREAD

**Issue by jacobzlogar** [collab-project/videojs-record#324]
## Description

- I have my mimes set to: 
```
                audioMimeType: 'audio/wav',
                videoMimeType: 'video/webm;codes=H264',
```
however when i `ffprobe` the downloaded file i still see 
<img width="1280" alt="screen shot 2019-01-19 at 3 48 55 pm" src="https://user-images.githubusercontent.com/10762368/51432201-be9cc180-1c01-11e9-9d12-86b43e8c6311.png">
`.opus` audio, do i need wavesurfer in order to change the audio codec?

**Comment by thijstriemstra** [comment]
@jacobzlogar can you paste the output of the console as well? Important to check the recordrtc config and figure out what params it used.

**Comment by jacobzlogar** [comment]
The `record` plugin options: 
<img width="523" alt="screen shot 2019-01-19 at 3 54 15 pm" src="https://user-images.githubusercontent.com/10762368/51432263-7e8a0e80-1c02-11e9-91df-807e0c270708.png">

**Comment by thijstriemstra** [comment]
you need to make sure the `debug` option is set to true and paste the console output, e.g. 

<img width="440" alt="screenshot 2019-01-19 at 22 04 09" src="https://user-images.githubusercontent.com/305679/51432350-3f75b080-1c36-11e9-99db-abb91369a696.png">

**Comment by jacobzlogar** [comment]
Okay, heres my console output:
<img width="570" alt="screen shot 2019-01-19 at 4 07 07 pm" src="https://user-images.githubusercontent.com/10762368/51432362-4a175200-1c04-11e9-88c6-ddb179d4f0be.png">

**Comment by thijstriemstra** [comment]
Here are the supported recordrtc modes:

```javascript
    // video/webm;codecs=vp9
    // video/webm;codecs=vp8
    // video/webm;codecs=h264
    // video/x-matroska;codecs=avc1
    // video/mpeg -- NOT supported by any browser, yet
    // audio/wav
    // audio/webm
    // audio/ogg
    mimeType: 'video/webm'

    // MediaStreamRecorder, StereoAudioRecorder, WebAssemblyRecorder
    // CanvasRecorder, GifRecorder, WhammyRecorder
    recorderType: MediaStreamRecorder,
```

can you try the StereoAudioRecorder with the MediaStreamRecorder, or WebAssemblyRecorder, or any other combination. I've never tried to use specific audio codec when recording audio+video (which I assume you are). Also you have not specified what operating system, browser etc etc

**Comment by jacobzlogar** [comment]
MacOS 10.14.02
Chrome Version 71.0.3578.98
so try `recorderType: 'StereoAudioRecorder/WebAssemblyRecorder`? I'm confused as to what you mean by ` try the StereoAudioRecorder with the MediaStreamRecorder, or WebAssemblyRecorder, ` how do i use them in combination?

**Comment by jacobzlogar** [comment]
nvm i see, will give that a shot now

**Comment by thijstriemstra** [comment]
I think this is the issue: https://github.com/muaz-khan/RecordRTC/blob/master/dev/MRecordRTC.js#L166

Prevents this from working:

```javascript
var options = {
    controls: true,
    width: 320,
    height: 240,
    fluid: false,
    plugins: {
        record: {
            audio: true,
            video: true,
            audioMimeType: 'audio/wav',
            audioRecorderType: StereoAudioRecorder,
            videoMimeType: 'video/webm;codes=H264',
            maxLength: 10,
            debug: true
        }
    }
};
```

Same with Mrecordrtc standalone:

```javascript
        var mRecordRTC = new MRecordRTC();
        mRecordRTC.mediaType = {
            audio: StereoAudioRecorder, // or StereoAudioRecorder or MediaStreamRecorder
            video: MediaStreamRecorder  // or WhammyRecorder      or MediaStreamRecorder
        };
        mRecordRTC.mimeType = {
            audio: 'audio/wav',
            video: 'video/webm',
            gif:   'image/gif'
        };
```

Should a new recordrtc.js ticket be opened @muaz-khan ?

**Comment by thijstriemstra** [comment]
MP4 only supports AAC or MP3: https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#MP4_H.264_(AAC_or_MP3) So no wav there.

And https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#WebM

"The WebM format is based on a restricted version of the Matroska container format. It **always uses** the VP8 or VP9 video codec and the **Vorbis or Opus audio codec**."

So no wav there either.

Afraid it's likely not possible at the moment and a browser issue.

**Comment by jacobzlogar** [comment]
No problem, thanks for the info @thijstriemsta
