### ISSUE TITLE
Creating build for Videojs-recorder in reactjs

### ISSUE THREAD

**Issue by manishatiwari1696** [collab-project/videojs-record#326]
## Description
Im using videojs-recorder for recording video in our project with reactjs(version: "^16.5.2"). Its working fine as i run this project but its giving an error while creating the build. 

## Steps to reproduce
"https://github.com/collab-project/videojs-record/wiki/React" I used these steps to create my project.

## Results
Module not found: Error: Can't resolve 'WaveSurfer' in '/home/manishtiwari/provider-desktop-app/node_modules/videojs-wavesurfer/dist'

### Expected
i am expecting my build should create successfully .
### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
#### OSes
what platforms (operating systems and devices) are affected?

**Comment by thijstriemstra** [comment]
> Module not found: Error: Can't resolve 'WaveSurfer' in '/home/manishtiwari/provider-desktop-app/node_modules/videojs-wavesurfer/dist'

You need to include the `WaveSurfer` alias in your webpack config @manishatiwari1696. See the [webpack configuration](https://github.com/collab-project/videojs-record/wiki/React#webpack-configuration) section of the wiki page.

**Comment by manishatiwari1696** [comment]
I've already done this, as per the guidelines. It's running fine but error is showing when I'm trying to create a build.

**Comment by manishatiwari1696** [comment]
I've already done this, as per the guidelines. It's running fine but error is showing when I'm trying to create a build.



> > Module not found: Error: Can't resolve 'WaveSurfer' in '/home/manishtiwari/provider-desktop-app/node_modules/videojs-wavesurfer/dist'
> 
> You need to include the `WaveSurfer` alias in your webpack config @manishatiwari1696. See the [webpack configuration](https://github.com/collab-project/videojs-record/wiki/React#webpack-configuration) section of the wiki page.

I've already done this, as per the guidelines. It's running fine but error is showing when I'm trying to create a build.

**Comment by thijstriemstra** [comment]
can you paste the config here?

**Comment by manishatiwari1696** [comment]
> can you paste the config here?


resolve: {   
    modules: ["node_modules", paths.appNodeModules].concat(
      // It is guaranteed to exist because we tweak it in `env.js`
      process.env.NODE_PATH.split(path.delimiter).filter(Boolean)
    ),
    extensions: [".web.js", ".mjs", ".js", ".json", ".web.jsx", ".jsx"],
    alias: {
      videojs: "video.js",
      WaveSurfer: "wavesurfer.js",
      "react-native": "react-native-web"
    },
    plugins: [
      new ModuleScopePlugin(paths.appSrc, [paths.appPackageJson]),
     
    ]
  },


  plugins: [
    new InterpolateHtmlPlugin(env.raw),
    // Generates an `index.html` file with the <script> injected.
    new HtmlWebpackPlugin({
      inject: true,
      template: paths.appHtml
    }),
    new webpack.NamedModulesPlugin(),
    new webpack.DefinePlugin(env.stringified),
    // This is necessary to emit hot updates (currently CSS only):
    new webpack.HotModuleReplacementPlugin(),
    new CaseSensitivePathsPlugin(),
    new WatchMissingNodeModulesPlugin(paths.appNodeModules),
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
    new webpack.ProvidePlugin({
      videojs: "video.js/dist/video.cjs.js",
      RecordRTC: "recordrtc",
      MediaStreamRecorder: ["recordrtc", "MediaStreamRecorder"]
    })
  ],

**Comment by manishatiwari1696** [comment]
> can you paste the config here?
 plugins: [
  
    new InterpolateHtmlPlugin(env.raw),
    // Generates an `index.html` file with the <script> injected.
    new HtmlWebpackPlugin({
      inject: true,
      template: paths.appHtml
    }),
    new webpack.NamedModulesPlugin(),
    new webpack.DefinePlugin(env.stringified),
    // This is necessary to emit hot updates (currently CSS only):
    new webpack.HotModuleReplacementPlugin(),
    new CaseSensitivePathsPlugin(),
    new WatchMissingNodeModulesPlugin(paths.appNodeModules),
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
    new webpack.ProvidePlugin({
      videojs: "video.js/dist/video.cjs.js",
      RecordRTC: "recordrtc",
      MediaStreamRecorder: ["recordrtc", "MediaStreamRecorder"]
    })
  ],

  resolve: {
    
    modules: ["node_modules", paths.appNodeModules].concat(
      // It is guaranteed to exist because we tweak it in `env.js`
      process.env.NODE_PATH.split(path.delimiter).filter(Boolean)
    ),
   
    extensions: [".web.js", ".mjs", ".js", ".json", ".web.jsx", ".jsx"],
    alias: {
      videojs: "video.js",
      WaveSurfer: "wavesurfer.js",

     
      "react-native": "react-native-web"
    },
    plugins: [
      new ModuleScopePlugin(paths.appSrc, [paths.appPackageJson]),
     
    ]
  },

**Comment by manishatiwari1696** [comment]
yes, I've install the wavesurfer.js, that's why its running fine. I request you to please run "npm run build" command once at your end and let me know whether this command is running for your project or not.

**Comment by AbhishekTaparia** [comment]
config/webpack.config.dev.js   can't find this file

**Comment by AbhishekTaparia** [comment]
./node_modules/videojs-record/dist/videojs.record.js
Module not found: Can't resolve 'videojs' in 'C:\.......................\videojs-record-master\workvideo\node_modules\videojs-record\dist'


also this

**Comment by AbhishekTaparia** [comment]
also i have serviceregister and not registerServiceWorker

**Comment by thijstriemstra** [comment]
@AbhishekTaparia see #333
