### ISSUE TITLE
ERROR Error: plugin "record" does not exist

### ISSUE THREAD

**Issue by phanikumarballa** [collab-project/videojs-record#328]
Getting error as in below for video.js

```
HomeComponent_Host.ngfactory.js? [sm]:1 ERROR Error: plugin "record" does not exist
    at Player.<anonymous> (video.js:21579)
    at Array.forEach (<anonymous>)
    at new Player (video.js:21575)
    at videojs$1 (video.js:25846)
    at HomeComponent.push../src/app/components/home/home.component.ts.HomeComponent.ngAfterViewInit (home.component.ts:83)
    at callProviderLifecycles (core.js:10414)
    at callElementProvidersLifecycles (core.js:10388)
    at callLifecycleHooksChildrenFirst (core.js:10378)
    at checkAndUpdateView (core.js:11316)
    at callViewAction (core.js:11548)
```

**Comment by thijstriemstra** [comment]
hey @phanikumarballa, can you explain to me how I would be able to help you with this, if you do not include ANY additional information whatsoever? I am not a psychic.

**Comment by phanikumarballa** [comment]
Sorry @thijstriemstra , below are the details. Am doing a project in Angular 6.0.7 have a requirement of capturing the video and send it to backend rest service. For this am using below versions:     "video.js": "^7.4.1",
    "videojs-record": "^3.3.0",
    "webrtc-adapter": "^7.2.0",

Am am getting error as record doen not exist, so for this I have commented record in the plugin of video-record configuration as in below:

constructor(elementRef: ElementRef) {
    this.player = false;

    // save reference to plugin (so it initializes)
    this.plugin = Record;

    // video.js configuration
    this.config = {
      controls: true,
      autoplay: false,
      fluid: false,
      loop: false,
      width: 320,
      height: 240,
      controlBar: {
        volumePanel: false
      },
    plugins: {
       // record: {
       //     audio: true,
        //    video: true,
        //    maxLength: 10,
       //     debug: true
      //  }
    }
    };
  }

with this screen is loaded but video is not coming, as in below screenshot:

![image](https://user-images.githubusercontent.com/43027693/52171873-6a114e80-278a-11e9-9eab-f25b6dec5129.png)

I have followed the same steps as mentioned in https://github.com/collab-project/videojs-record/wiki/Angular. Except am using Angular 5. Please help

**Comment by thijstriemstra** [comment]
can you also paste the includes?

**Comment by phanikumarballa** [comment]
import {Component, OnInit, AfterViewInit, OnDestroy,ElementRef,Input} from '@angular/core';
import * as adapter from 'webrtc-adapter/out/adapter_no_global.js';
import * as RecordRTC from 'recordrtc';
// register videojs-record plugin with this import
import videojs from 'video.js';
import Record from 'videojs-record/dist/videojs.record.js';
import 'webrtc-adapter';

declare var videojs: any;

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit, AfterViewInit, OnDestroy {
  private videoJSplayer: any;
private _elementRef: ElementRef

// index to create unique ID for component
@Input() idx: string;

private config: any;
private player: any;
private plugin: any;


constructor(elementRef: ElementRef) {
    this.player = false;

    // save reference to plugin (so it initializes)
    this.plugin = Record;

    // video.js configuration
    this.config = {
      controls: true,
      autoplay: false,
      fluid: false,
      loop: false,
      width: 320,
      height: 240,
      controlBar: {
        volumePanel: false
      },
    plugins: {
       // record: {
       //     audio: true,
        //    video: true,
        //    maxLength: 10,
       //     debug: true
      //  }
    }
    };
  }

//  ngOnInit() {
  //}

 // ngAfterViewInit(): void {
 //   this.initVideoJs();
 // }

 // initVideoJs() {
 //   this.videoJSplayer = videojs('video_player');
    // const transcript = this.videoJSplayer.transcript();
    // const transcriptCon = document.querySelector('#transcriptContainer');
    // transcriptCon.appendChild(transcript.el());
 // }

 // ngOnDestroy() {
  //  this.videoJSplayer.dispose();
 // }

  ngOnInit() {}

  // use ngAfterViewInit to make sure we initialize the videojs element
  // after the component template itself has been rendered
  ngAfterViewInit() {
    // ID with which to access the template's video element
    let el = 'video_1';// + this.idx;

    // setup the player via the unique element ID
    this.player = videojs(document.getElementById(el), this.config, () => {
      console.log('player ready! id:', el);

      // print version information at startup
      var msg = 'Using video.js ' + videojs.VERSION +
       // ' with videojs-record ' + videojs.getPluginVersion('record') +
        ' and recordrtc ' + RecordRTC.version;
      videojs.log(msg);
    });

    // device is ready
    this.player.on('deviceReady', () => {
      console.log('device is ready!');
    });

    // user clicked the record button and started recording
    this.player.on('startRecord', () => {
      console.log('started recording!');
    });

    // user completed recording and stream is available
    this.player.on('finishRecord', () => {
      // recordedData is a blob object containing the recorded data that
      // can be downloaded by the user, stored on server etc.
      console.log('finished recording: ', this.player.recordedData);
    });

    // error handling
    this.player.on('error', (error) => {
      console.warn(error);
    });
  }

  // use ngOnDestroy to detach event handlers and remove the player
  ngOnDestroy() {
    if (this.player) {
      this.player.dispose();
      this.player = false;
    }
  }
}





Above is my complete .ts file

**Comment by phanikumarballa** [comment]
And in .html as in below:
<video id="video_1" class="video-js vjs-default-skin"></video>

Otherthan these I dont have any other code

**Comment by thijstriemstra** [comment]
> I have followed the same steps as mentioned in https://github.com/collab-project/videojs-record/wiki/Angular. Except am using Angular 6. Please help

I am not an Angular expert and cannot help you with this issue, please ask on stackoverflow or something. I would compare the difference between the Angular wiki page and your Angular 6 project. Looks like you need some webpack fixes (??)

**Comment by kay28** [comment]
I have the same issue while using in react. Any updates?

**Comment by medonajohn** [comment]
ERROR in ./node_modules/videojs-record/dist/videojs.record.js
Module not found: Error: Can't resolve 'videojs' in 'F:\lms\angular\baashaa-lms\node_modules\videojs-record\dist'

**Comment by medonajohn** [comment]
I got this error while using video js ...plugin is not getting .please help me

**Comment by George191** [comment]
did you fix it?   I get this problem in Vue

**Comment by thijstriemstra** [comment]
What version of videojs-record? Should work with latest.

**Comment by George191** [comment]
VIDEOJS: Using video.js 7.8.4 with videojs-record  and recordrtc 5.6.1
It should be a conflict with other extensions, but I have no idea
New projects are fine

**Comment by George191** [comment]
"dependencies": {
    "@chenfengyuan/vue-countdown": "^1.1.2",
    "aes-decrypter": "^3.0.0",
    "ag-grid-community": "^21.0.1",
    "ag-grid-vue": "^21.0.1",
    "algoliasearch": "^3.33.0",
    "apexcharts": "^3.6.12",
    "auth0-js": "^9.10.4",
    "axios": "^0.19.0",
    "chart.js": "^2.8.0",
    "core-js": "2.6.5",
    "echarts": "^4.2.1",
    "file-saver": "2.0.1",
    "firebase": "^7.13.2",
    "instantsearch.css": "^7.3.1",
    "jsonwebtoken": "^8.5.1",
    "m3u8-parser": "^4.4.3",
    "material-icons": "^0.3.1",
    "msr": "^1.3.4",
    "mux.js": "^5.6.4",
    "perfect-scrollbar": "^1.4.0",
    "postcss-rtl": "1.5.0",
    "prismjs": "^1.16.0",
    "vee-validate": "^2.2.8",
    "video.js": "^7.8.4",
    "videojs-record": "^4.1.0",
    "vue": "^2.6.10",
    "vue-acl": "4.0.7",
    "vue-apexcharts": "^1.3.5",
    "vue-awesome-swiper": "^3.1.3",
    "vue-backtotop": "^1.6.1",
    "vue-chartjs": "^3.4.2",
    "vue-clipboard2": "^0.3.0",
    "vue-context": "4.0.0",
    "vue-echarts": "^4.0.3",
    "vue-feather-icons": "^5.0.0",
    "vue-flatpickr-component": "^8.1.2",
    "vue-form-wizard": "^0.8.4",
    "vue-fullcalendar": "^1.0.9",
    "vue-i18n": "^8.11.2",
    "vue-instantsearch": "^2.2.1",
    "vue-perfect-scrollbar": "^0.1.0",
    "vue-prism-component": "^1.1.1",
    "vue-property-decorator": "^8.1.1",
    "vue-quill-editor": "^3.0.6",
    "vue-router": "^3.0.6",
    "vue-select": "^3.1.0",
    "vue-simple-calendar": "^4.2.2",
    "vue-simple-suggest": "^1.9.5",
    "vue-star-rating": "^1.6.1",
    "vue-tour": "^1.1.0",
    "vue-tree-halower": "^1.8.0",
    "vue2-google-maps": "^0.10.6",
    "vue2-hammer": "^2.1.2",
    "vuecode.js": "0.0.27",
    "vuedraggable": "^2.21.0",
    "vuejs-datepicker": "^1.5.4",
    "vuesax": "3.11.13",
    "vuex": "^3.1.1",
    "xlsx": "^0.15.0"
  },
  "devDependencies": {
    "@fullhuman/postcss-purgecss": "^1.2.0",
    "@vue/cli-plugin-babel": "^3.7.0",
    "@vue/cli-plugin-eslint": "^3.7.0",
    "@vue/cli-service": "^3.7.0",
    "axios-mock-adapter": "^1.17.0",
    "node-sass": "^4.12.0",
    "purgecss": "^1.3.0",
    "sass-loader": "^7.1.0",
    "script-loader": "0.7.2",
    "tailwindcss": "^1.0.1",
    "vue-template-compiler": "^2.6.10"

**Comment by thijstriemstra** [comment]
> New projects are fine

Please open a new ticket that reproduces the problem **exactly**. Keep in mind this is **not** a library focused on a specific framework like vue so most of the time it's not an issue in videojs-record but in specific framework you use.
