### ISSUE TITLE
Upgrading to version 3.4.2 resulted in react build using webpack to throw `videojs is not defined`

### ISSUE THREAD

**Issue by pwob** [collab-project/videojs-record#333]
## Description
Upgrading to version 3.4.2 resulted in react build using webpack to throw `videojs is not defined`

## Steps to reproduce
Use version 3.4.2 in react app then build just like in the documentation (https://github.com/collab-project/videojs-record/wiki/Webpack#webpack-config)

### Expected
Succesfully build

### Actual
Throws an error when using react app

### Error output
`animation-display.js:34 Uncaught (in promise) ReferenceError: videojs is not defined
    at eval (animation-display.js:34)
    at Object../src/js/controls/animation-display.js (videojs.record.js?3966:147)
    at __webpack_require__ (videojs.record.js?3966:37)
    at eval (videojs.record.js:8)
    at Object../src/js/videojs.record.js (videojs.record.js?3966:339)
    at __webpack_require__ (videojs.record.js?3966:37)
    at eval (videojs.record.scss:1)
    at Object.0 (videojs.record.js?3966:350)
    at __webpack_require__ (videojs.record.js?3966:37)
    at eval (videojs.record.js?3966:101)
    at eval (videojs.record.js?3966:104)
    at webpackUniversalModuleDefinition (videojs.record.js?3966:10)
    at eval (videojs.record.js?3966:17)....`

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
videojs-record version: 3.4.2 video.js version: 7.4.1
#### browsers
Chrome and Firefox tested
#### OSes
OSX

**Comment by thijstriemstra** [comment]
This is probably related to #330. ping @extronics

**Comment by pwob** [comment]
Also tried 3.4.0, with sam result.

**Comment by thijstriemstra** [comment]
that's good to hear (I guess). Try the https://github.com/collab-project/videojs-record/wiki/React wiki instead.

**Comment by extronics** [comment]
I was bundling videojs-record with rollup but saw the same error there. It means that your [webpack|rollup] configuration somehow isn't providing videojs as a global variable. So to debug this, you can always verify whether your bundle defines that variable.

I also used webpack with videojs-record, but with different configuration:

```
resolve: {
    alias: {
      videojs: 'video.js',
    },
    mainFields: ['module', 'main'],
  },
  externals: {
    'video.js': {
      commonjs: 'video.js',
      commonjs2: 'video.js',
      root: 'videojs',
    },
    videojs: {
      commonjs: 'video.js',
      commonjs2: 'video.js',
      root: 'videojs',
    },
  },
```

This fixed problems with videojs-record requiring "videojs" instead of "video.js" as well as the missing global variable. Hope that helps.

**Comment by thijstriemstra** [comment]
> This fixed problems with videojs-record requiring "videojs" instead of "video.js"

this global/amd/common thing in Javascript is so annoying and this project has always been struggling with it. Should it be video.js then?

**Comment by extronics** [comment]
In general, yes. I spent quite some time in my project with build-related struggles. Not only with video.js and videojs-record but also in my own code. All related to the question of "how do i properly bundle a library project without ending in the umd/amd/commonjs bundle nightware".

I took some notes there and can take some time during the next days to sum them up and create a PR with some proposed changes.

**Comment by thijstriemstra** [comment]
sounds good!

**Comment by pwob** [comment]
Thanks for the suggestion but no luck in my set up. Still returns that error, for now Im not gonna upgrade. Also i cannot set `videoRecorderType` to WhammyRecorder in 2.4.1 :(

**Comment by thijstriemstra** [comment]
>Also i cannot set `videoRecorderType` to WhammyRecorder in 2.4.1 :(

weird. can you try with recordrtc 5.5.0 or 5.5.1?

**Comment by swatijadhav** [comment]
I am also facing same issue while setting up video-js record (version 3.4.2) with **webpack**. Following steps given in wiki https://github.com/collab-project/videojs-record/wiki/Webpack

Is anyone working on this? and PR for this fix is expecting? 
cc: @extronics

**Comment by thijstriemstra** [comment]
@swatijadhav and @snelanga I was seeing the same error. Looking at that error message:

```
animation-display.js:34 Uncaught (in promise) ReferenceError: videojs is not defined at eval (animation-display.js:34) at Object../src/js/controls/animation-display.js
```

it appears videojs cannot be found in `src/js/controls/animation-display.js`. The top of that file looks like this:

```javascript
/**
 * @file animation-display.js
 * @since 2.0.0
 */

const Component = videojs.getComponent('Component');
```

so it's trying to access videojs but I noticed it's not imported at all, so maybe that's it? After I added the following line:

```javascript
import videojs from 'video.js';
```

at the top of the following files:

```
	modified:   src/js/controls/animation-display.js
	modified:   src/js/controls/camera-button.js
	modified:   src/js/controls/device-button.js
	modified:   src/js/controls/record-canvas.js
	modified:   src/js/controls/record-indicator.js
	modified:   src/js/controls/record-toggle.js
	modified:   src/js/engine/convert-engine.js
	modified:   src/js/engine/record-engine.js
	modified:   src/js/engine/record-rtc.js
```

everything works as expected. So I'll make that change as release a new version asap.

**Comment by thijstriemstra** [comment]
@swatijadhav @snelanga @pwob did v3.4.3 fix this for you?

**Comment by pwob** [comment]
Yes thanks so much and for this great module! Will read codes so I can help sometime.

**Comment by snelanga** [comment]
@thijstriemstra Yes, it did fix the issue. Thank you very much for that.
But I'm not getting the video preview with the controllers even though the camera is turned on. This was reported in the issue #256 by @birgittab. 

There you mentioned about not adding the **'videojs.record.css'**. But I've even added that as follows,
- index.html (public) -> link href="../node_modules/videojs-record/dist/css/videojs.record.css" rel="stylesheet"
- App.js -> import 'videojs-record/dist/css/videojs.record.css'

But I'm still getting only this.
![screen shot 2019-03-04 at 4 07 43 pm](https://user-images.githubusercontent.com/11583488/53728429-c73b1580-3e98-11e9-8cef-4adf30616ce2.png)
![screen shot 2019-03-04 at 4 04 53 pm](https://user-images.githubusercontent.com/11583488/53728454-d15d1400-3e98-11e9-90b7-14270a2f7c46.png)

**Comment by thijstriemstra** [comment]
@snelanga **any errors in the console? what browser/operating system? what is your video.js config?**

**Comment by birgittab** [comment]
> @snelanga **any errors in the console? what browser/operating system? what is your video.js config?**

I am using google chrome on windows 10.
I have no errors in the console but it seems like the "device is ready" function is never reached.

![image](https://user-images.githubusercontent.com/31894516/53742757-4af10400-3e91-11e9-81ba-0c372d7b8329.png)

**Comment by thijstriemstra** [comment]
Sigh.. ** what is your video.js config?**
