### ISSUE TITLE
v3.4.3 does not include new changes

### ISSUE THREAD

**Issue by pwob** [collab-project/videojs-record#334]
## Description
Updating to v3.4.3 break video recording, looking at code it does not include the changes specified in the PR

## Steps to reproduce
Update to 3.4.3, look into the code and search for `videoEngine`

### Expected
Setting `webm-wasm` as the videoEngine uses the new web-wasm plugin.

### Actual
Can't switch to `webm-wasm` engine

### Error output
No error, accepting video and mic permission throws `deviceError`

## Additional Information
Please include any additional information necessary here. Including the following:
### versions
videojs-record 3.4.3
#### videojs
7.4.1
#### browsers
Firefox latest, Chrome latest
#### OSes
Mac OSX

**Comment by thijstriemstra** [comment]
New changes? What are you talking about? The webm-wasm plugin? Because that is part of a new upcoming v3.5.0, not 3.4.3. You're confused.
