### ISSUE TITLE
Waveform is ready but doesn't appear in player

### ISSUE THREAD

**Issue by Chivavik** [collab-project/videojs-record#335]
Hi! I'm using videojs-record for audio only. Recording and playing recorded file works fine. But waveform doesn't work in real-time while recording and doesn't appear after recording ends. After switching on and off full-screen mode waveform works fine. There are no errors in the console. Could you, please, help me to make waveform works without switching to full-screen mode? 
![versions](https://user-images.githubusercontent.com/19816683/53076760-8985d680-3501-11e9-9d4a-fa39841593fd.PNG)
![logs](https://user-images.githubusercontent.com/19816683/53076784-94406b80-3501-11e9-9a06-9004fe2f3e40.PNG)
![before fullscreen](https://user-images.githubusercontent.com/19816683/53076791-99051f80-3501-11e9-9872-4470d9f0556f.PNG)
![after fullscreen](https://user-images.githubusercontent.com/19816683/53076798-9d313d00-3501-11e9-91e0-c42248866e58.PNG)
![code](https://user-images.githubusercontent.com/19816683/53076804-a1f5f100-3501-11e9-8efe-67e46ee8623a.PNG)

**Comment by thijstriemstra** [comment]
what browser? what operating system? Can you change the player background color and wavecolor, i think it's there but colors make it impossible to see.

**Comment by Chivavik** [comment]
Chrome 73. Windows 7. Tried to change color but the problem is still here.
Before fullscreen:
![before](https://user-images.githubusercontent.com/19816683/53104596-b0173200-3540-11e9-95a2-036c99652895.PNG)
After fullscreen:
![after](https://user-images.githubusercontent.com/19816683/53104650-d2a94b00-3540-11e9-9f35-5430d1b9dd4a.PNG)

**Comment by thijstriemstra** [comment]
i see you specified 'responsive: false', can you try without that?

**Comment by Chivavik** [comment]
Sure. 
That didn't solve the problem. 
![312](https://user-images.githubusercontent.com/19816683/53106866-fa021700-3544-11e9-9a25-7f35eb42bd04.PNG)

**Comment by thijstriemstra** [comment]
arer you able to reproduce it with this? https://collab-project.github.io/videojs-record/examples/audio-only.html

**Comment by Chivavik** [comment]
I've actually copied the source code from this example and placed scripts in the same order. The only difference is that I'm not using workarounds. The example works perfectly fine for me.

**Comment by thijstriemstra** [comment]
if the example works for you, you'll have to narrow it down to the differences between both.

**Comment by Chivavik** [comment]
Could you please tell me where I can find this script "browser-workarounds.js"?

**Comment by thijstriemstra** [comment]
all is located in https://github.com/collab-project/videojs-record/tree/master/examples

**Comment by thijstriemstra** [comment]
@Chivavik this is not a problem in Firefox right, only Chrome? If you change the line to `var safari = true;` in `browser-workarounds.js`, does it work then?

**Comment by Chivavik** [comment]
@thijstriemstra I have the same problem in Firefox too. And I'm also receiving this warning message in Chrome. Does it mean that I need to reproduce a user gesture before recording to fix this problem?

**Comment by thijstriemstra** [comment]
@Chivavik try calling this from a button or type it in console and the visualization will appear:

```
player.record().surfer.backend.ac.resume()
```

I don't see this issue in Firefox though..

**Comment by thijstriemstra** [comment]
@Chivavik give PR #344 a try.
