### ISSUE TITLE
RecordRTC is not defined at RecordRTCEngine.setup

### ISSUE THREAD

**Issue by ajthegamedev** [collab-project/videojs-record#345]
## Description
RecordRTC is undefined during videojs setup when following the Webpack tutorial.

## Steps to reproduce
Follow the tutorial here:
https://github.com/collab-project/videojs-record/wiki/Webpack

### Expected
Recording initializes and begins preview after pressing through the permissions button.

### Actual
Permissions button disappears, and recording light in tab turns on. However there is no preview and the engine does not appear to be running.

### Error output
```
ReferenceError: RecordRTC is not defined at RecordRTCEngine.setup (webpack://VideojsRecord/./src/js/engine/record-rtc.js?:57:25) at Record.onD

videojs.record.js line 455: this.engine.setup(this.stream, this.mediaType, this.debug);
record-rtc.js line 57:          this.engine = new RecordRTC.MRecordRTC();
videojs.record.js line 513: key: "onDeviceError",
```

#### videojs-record
3.5.0
#### videojs
7.4.1
#### browsers
Chrome
Firefox
Safari
#### OSes
Tested on a macbook pro

**Comment by thijstriemstra** [comment]
I can reproduce this after adding a `deviceError` handler, looking into it.

**Comment by thijstriemstra** [comment]
@ajthegamedev I updated the webpack wiki page (with other css-related improvements) and I'll release v3.5.1 with the fix. If you want to try it out, test pull request #346

**Comment by ajthegamedev** [comment]
Thanks @thijstriemstra

**Comment by ajthegamedev** [comment]
Hey @thijstriemstra sorry to pop back in bu #346 :

import videojs from 'video.js';

import RecordRTC from 'recordrtc';

import Event from '../event';

Doesn't seem to change the issue for me. I just followed the updated wiki again from scratch and I am seeing the same error.

**Comment by thijstriemstra** [comment]
@ajthegamedev there's also a change in the webpack alias section.
