### ISSUE TITLE
iPhone XR bugs

### ISSUE THREAD

**Issue by Chivavik** [collab-project/videojs-record#347]
Hi! For some reasons, the plugin works strangely on "audio only example" page on iPhone XR(Ios 12.1.4) in both Chrome and Safari.
Safari:
When clicked on the Device button, the prompt asking for microphone access appears. When clicked Allow, and the Round icon to record is pressed, the icon changes to Square (Stop), live stream of soundwave appears, everything is working. When Square is pressed to stop recording, icon changes to Round and the soundwave is not appearing (instead flat line appears)
![photo_2019-03-06_18-32-43](https://user-images.githubusercontent.com/19816683/53892930-43bb2900-403e-11e9-9f19-16a87bad27d9.jpg)

Chrome 
When the Device button is clicked, the prompt to allow recording does not appear, the screen goes like this:
![photo_2019-03-06_18-35-15](https://user-images.githubusercontent.com/19816683/53893116-9a286780-403e-11e9-9fc5-2a2a3d4cabe9.jpg)

**Comment by thijstriemstra** [comment]
thanks for the report. It would be really useful to see the browser console messages. Can you follow these instructions and paste the results here? https://www.lifewire.com/activate-the-debug-console-in-safari-445798

**Comment by Chivavik** [comment]
![photo_2019-03-06_19-09-38](https://user-images.githubusercontent.com/19816683/53895620-803d5380-4043-11e9-8c65-4e425aef27a6.jpg)

**Comment by thijstriemstra** [comment]
@Chivavik make sure to use videojs-record v3.5.1. Strange there's not a single error message (so far).

**Comment by Chivavik** [comment]
Hi, @thijstriemstra! I have a question about videojs-record plugin but it does not relate to this issue. Can I ask you here?

**Comment by thijstriemstra** [comment]
you can open a separate issue/question for that.

**Comment by thijstriemstra** [comment]
>  make sure to use videojs-record v3.5.1. Strange there's not a single error message (so far). Looking at the second image in your ticket, the UI changed in a way that usually indicates an error. Are you sure you can playback .wav files in that browser using a regular <audio> element?

any feedback @Chivavik?

**Comment by thijstriemstra** [comment]
Also give https://blog.chromium.org/2019/03/debugging-websites-in-chrome-for-ios.html a try.

**Comment by thijstriemstra** [comment]
No feedback. Closing in favor of #353
