### ISSUE TITLE
delay before recording

### ISSUE THREAD

**Issue by ehartz01** [collab-project/videojs-record#348]
Hi, I'm trying to have a short delay before recording begins after the user presses the record button.
I want to do something like 
```javascript
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
await sleep(5000);
```
before the recording is called -- but I can't find a good place to drop this snippet.  Any advice?

**Comment by thijstriemstra** [comment]
I tried a couple of things but couldn't override it with a hack, e.g.

```javascript
player.deviceButton.el().onclick = function(e) {
        e.preventDefault();
        console.log('yo', e);
    };

player.deviceButton.on('click', function(e) {
        e.preventDefault();
        console.log('yo', e);
    });
```

now what would be a sensible approach to this, without having to add a dedicated timeout setting etc..

**Comment by ehartz01** [comment]
I figured it out. I dropped a little code in the the record toggle class

async handleClick(event) {
        console.log("clicked record toggle");
        let recorder = this.player_.record();
        if (!recorder.isRecording()) {
            await sleep(5000);
            console.log("woke up")
            recorder.start();
        } else {
            recorder.stop();
        }
    }

The problem was I had forgotten to npm run build again after editing the file lol
This works well enough for my use case. I hope this helps someone else with the same issue. I feel this was a somewhat naive question but I'm new to JS -- a lot of the asynchronous stuff is foreign to me.
