### ISSUE TITLE
Blob into input[type="file"]

### ISSUE THREAD

**Issue by Chivavik** [collab-project/videojs-record#349]
Hi! I'm looking for a way to upload blob with input[type="file"]. So you can download it on your device. Also, you can create an XMLHttpRequest to upload without input[type="file"], but I can't do that for certain reasons. How can I upload a blob using input[type="file"] without downloading it?

**Comment by thijstriemstra** [comment]
@Chivavik can you show some example or pseudo-code? `player.record().saveAs()` does not work for you?

**Comment by Chivavik** [comment]
player.record().saveAs() works fine. But I don't need a recorded file on my PC, I need to upload it to the server using input[type="file"].

**Comment by thijstriemstra** [comment]
I see, that is not a videojs-record specific question, it's a general question about Blobs. Please use stackoverflow or some other forum for this.
