### ISSUE TITLE
How does this differ from VideoJS?

### ISSUE THREAD

**Issue by sferoze** [collab-project/videojs-record#350]
Can someone briefly explain why would I use this, how does it differ from VideoJS? I thought VideoJS was a html5 player? Does this package just add more options or skins or something? It is very confusing navigating the javascript libraries for recordrtc and video recording

**Comment by thijstriemstra** [comment]
it's a plugin for video.js. video.js provides a skinnable player and component structure, and videojs-record extends this with cross-browser/platform recording for audio, video and image files.
