### ISSUE TITLE
'RecordRTC' camelcase problem on webpack build

### ISSUE THREAD

**Issue by alienpavlov** [collab-project/videojs-record#357]
## Description
I'm getting an error about RecordRTC dependency on case-sensitive system like Linux

## Steps to reproduce
Run a simple configured webpack

### Expected
Webpack should make a build
### Actual
Error "Can't resolve 'RecordRTC'" received

### Error output
> ERROR in ./node_modules/videojs-record/dist/videojs.record.js
Module not found: Error: Can't resolve 'RecordRTC' in '/var/www/html/project_name/node_modules/videojs-record/dist'
 @ ./node_modules/videojs-record/dist/videojs.record.js 10:47-67
 @ ./path/to/my/code/file.js

## Additional Information
I tried to rename 'RecordRTC' to 'recordrtc' (all lowercase) in ./node_modules/videojs-record/dist/videojs.record.js in all 4 entries and it works perfect. Then I've added alias `RecordRTC: 'recordrtc'` to my webpack config and it does a job. But it seems everywhere all npm modules are lowercased so this alias is some kind of a workaround here
#### videojs
3.5.1
#### OSes
Ubuntu

**Comment by thijstriemstra** [comment]
Did you see https://github.com/collab-project/videojs-record/wiki/Webpack? If you are able to config a videojs-record app without any plugins/alias/resolve config, I'd be all ears.

**Comment by retrocausal** [comment]
Apologies, wanted to comment here, but commented on a different ticket. And I can not unereference it for some reason


As a follow up on the above comment (https://github.com/collab-project/videojs-record/issues/357#issuecomment-478720503), I just have a question: 

Is there a downside to not externalising libraries in `build-config/fragments/common.js` ? 

```
// specify dependencies for the library that are not resolved by webpack,
    // but become dependencies of the output: they are imported from the
    // environment during runtime.
    externals: [
        // mandatory
        {'video.js': 'videojs'},
        // optional
        {'wavesurfer.js': 'WaveSurfer'},
        {'recordrtc': 'RecordRTC'}
    ]
```

**Comment by thijstriemstra** [comment]
> Is there a downside to not externalising libraries

ehm, I don't think so, can you elaborate?

**Comment by retrocausal** [comment]
> > Is there a downside to not externalising libraries
> 
> ehm, I don't think so, can you elaborate?

So, I forked out the repo, and removed the externals section in the build config, and I did not have to add aliases in my webpack for the build to go through. (Unfortunately, our org has a policy of not allowing aliases in webpack configs) 

Still, have not ascertained if that is all I need to do,  will have a clearer picture later. 

So, I just wanted to know, If removing such externals would have any negative impact on the videojs-record library and its functioning at all .

**Comment by thijstriemstra** [comment]
> So, I just wanted to know, If removing such externals would have any negative impact on the videojs-record library and its functioning at all .

No, I don't think it will. It's just there so webpack does not include these libraries in the videojs-record library itself.
