### ISSUE TITLE
Improvement? using react-app-rewired to avoid Eject in demo 

### ISSUE THREAD

**Issue by rluiten** [collab-project/videojs-record#358]
## Description
To avoid ejecting create react app use rect-app-rewired.

## Steps to reproduce
I created a simple config-overrides.js file for react-app-rewire to be able to run the 
https://github.com/collab-project/videojs-record/wiki/React and get the changes required
into the wepback config without ejecting.

You will need to do the installs steps of https://github.com/timarney/react-app-rewired as well.

I attach my config-overrides.js used by react-app-rewired to avoid ejecting create react app.
It was created with 
* "videojs-record": "^3.5.1"
* "react-scripts": "2.1.8"
* "react-app-rewired": "^2.1.1"

Inline copy of config-overrides.s
```js
const webpack = require("webpack");

module.exports = function override(config, env) {
  // Extend the config to work with the videojs-record project without ejecting create react app.
  // Reference: https://github.com/collab-project/videojs-record/wiki/React
  // Instead of ejecting apply webpack config changes here.
  const videojsPlugin = new webpack.ProvidePlugin({
    videojs: "video.js/dist/video.cjs.js",
    RecordRTC: "recordrtc",
    MediaStreamRecorder: ["recordrtc", "MediaStreamRecorder"]
  });
  const videojsAlias = {
    videojs: "video.js",
    WaveSurfer: "wavesurfer.js",
    RecordRTC: "recordrtc"
  };
  config.resolve.alias = { ...config.resolve.alias, ...videojsAlias };
  config.plugins.push(videojsPlugin);
  return config;
};

```

[config-overrides.txt](https://github.com/collab-project/videojs-record/files/3036814/config-overrides.txt)

**Comment by thijstriemstra** [comment]
sounds good, I'll take a look at some point.

**Comment by thijstriemstra** [comment]
Updated the wiki, thanks for the suggestion.
