### ISSUE TITLE
wav options audioSampleRate 22050 not ok?

### ISSUE THREAD

**Issue by thinktothings** [collab-project/videojs-record#359]
## Description
https://github.com/collab-project/videojs-record/examples/plugins/audio-only-recorderjs.html

i use example wav setting  options plugins record audioSampleRate:22050, but the result file is 44100, who can help to me ?

```javascript
var options = {
    controls: true,
    width: 600,
    height: 300,
    fluid: false,
    plugins: {
        wavesurfer: {
            src: 'live',
            waveColor: '#6fffe9',
            progressColor: 'black',
            debug: true,
            cursorWidth: 1,
            msDisplayMax: 5,
            hideScrollbar: true
        },
        record: {
            audio: true,
            video: false,
            maxLength: 5,
            debug: true,
            audioSampleRate: 22050,
            audioEngine: 'recorder.js'
        }
    }
};
```

**Comment by thijstriemstra** [comment]
@thinktothings the `audioSampleRate` option is not supported in the recorderjs plugin. Also note that the recorderjs library is not maintained anymore so I would suggest to use the default recordrtc instead and specify a `audio/wav` mimetype.
