### ISSUE TITLE
While using in angular 6 getting this error that videojs and RecordRTC not found.

### ISSUE THREAD

**Issue by imranbash** [collab-project/videojs-record#361]
## Description
In angular 6,
ERROR in ./node_modules/videojs-record/dist/videojs.record.js
Module not found: Error: Can't resolve 'RecordRTC' in '/home/napc0472/Desktop/Prj Test/video-emr/node_modules/videojs-record/dist'
ERROR in ./node_modules/videojs-record/dist/videojs.record.js
Module not found: Error: Can't resolve 'videojs' in '/home/napc0472/Desktop/Prj Test/video-emr/node_modules/videojs-record/dist'

## Steps to reproduce
![image](https://user-images.githubusercontent.com/49266874/55535939-27aab600-56d6-11e9-82db-9129d0decd05.png)

include all dependency in package.json as per given example and import as given syntax but when i'm alias object Record then i'm getting this error.

### Error output
If there are any errors at all, please include them here.
![image](https://user-images.githubusercontent.com/49266874/55535857-f7fbae00-56d5-11e9-9409-88e967d432e8.png)

**Comment by thijstriemstra** [comment]
@imranbash you're missing the webpack config, see https://github.com/collab-project/videojs-record/wiki/Angular#webpack-config
