### ISSUE TITLE
audio-only.html  setting timestamp ,file recorded first can be played,the other can not play normally

### ISSUE THREAD

**Issue by thinktothings** [collab-project/videojs-record#362]
## Description
).audio-only.html  setting timestamp  ,use webm format
).Except for the first time interval file recorded can be played, the other can not play normally, is it because there is less Head?

### Expected
The expected result is that each time interval contains the complete file format and can be played normally.

### Actual
In fact, only files recorded at the first interval can be played.

**Comment by thijstriemstra** [comment]
what operating system? what version of video.js and videojs-record? what wavesurfer.js version? you did not read the ticket instructions.

**Comment by thijstriemstra** [comment]
I cannot reproduce this, please provide an example that reproduces this.
