### ISSUE TITLE
[Question] Is it possible to use fluid width for image capture?

### ISSUE THREAD

**Issue by kylemadkins** [collab-project/videojs-record#363]
There's a (good) chance that this is a dumb question, and I just don't know how this works. Any information that would help me understand why this works the way it does would be helpful

## Description
I'm using videojs-record to capture an image from a webcam to use as a thumbnail in an email. When I try to set `fluid: true` and take the photo, I just get a black screen and the `player.recordedData` is blank (It logs `data:,`)

## Steps to reproduce
1. Set up videojs-record with these options:
```
playerOptions: {
  controls: true,
  fluid: true,
  controlBar: {
    volumePanel: false,
    fullscreenToggle: false,
  },
  plugins: {
    record: {
      image: true,
      debug: true,
    },
  },
}
```
2. Start recording and then click the button to take a photo
3. Notice the screen is black

### Expected
I wanted to be able to record a video at a certain resolution with a fluid width and then capture a still of that video

### Actual
When I tried to take a photo, the screen just went black and the `recordedData` was empty

### Error output
No errors

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
7.4.1
#### browsers
I tested with Chrome and Firefox. Disabled all of my Chrome extensions too
#### OSes
I'm on macOS High Sierra 10.13.3

**Comment by thijstriemstra** [comment]
@kylemadkins why did you close this? what fixed it?

**Comment by kylemadkins** [comment]
I figured out a solution. I used this config:
```
{
  controls: true,
  width: 1280,
  height: 720,
  fluid: true,
  controlBar: {
    volumePanel: false,
    fullscreenToggle: false,
  },
  plugins: {
    record: {
      image: {
        width: { min: 640, ideal: 1280, max: 1920 },
        height: { min: 480, ideal: 720, max: 1080 },
      },
    debug: true,
  },
}
```

**Comment by thijstriemstra** [comment]
Cool. If you think the default settings for the image capture example could benefit from these settings, please open a PR.
