### ISSUE TITLE
Can I pause the audio while in recording and then resume on user request (Need help)

### ISSUE THREAD

**Issue by abhrodipgit** [collab-project/videojs-record#364]
## Description
I want to pause the recording audio only not the video and resume on user request

**Comment by abhrodipgit** [comment]
I want to pause the recording audio only not the video and resume on user request. Is there any way I can achieve this ?

**Comment by thijstriemstra** [comment]
No this is not possible. You could create 2 separate players, one of for recording video and one for recording audio and use `pause`/`resume` on the audio player.
