### ISSUE TITLE
RecordedData in to Wavesurfer.js

### ISSUE THREAD

**Issue by Ziggy2001** [collab-project/videojs-record#365]
I'm having trouble understanding how I can get the recordedData from videojs-record into Wavesurfer-js

I'm storing the recordedData blob in IndexedDB and that's all fine, but when I retreive it and try to load it into Wavesurfer-js using loadBlob I just get an error in the console:

```
TypeError: t is undefined[Learn More] wavesurfer.min.js:6:47681
HTTP load failed with status 404. Load of media resource https://rss-developer:444/[object%20AudioBuffer] failed.
```

Of course at this point it doesn't load anything and this is with the latest videojs-record and wavesurfer-js. I'm using Firefox but it does the same in Chrome as well. I haven't tried any other browsers as I'm sure it's not a browser related issue.

Is it possible to move the recordedData immediately to an instance of Wavesurfer-js, and if so, how is it done?

**Comment by thijstriemstra** [comment]
> but when I retreive it and try to load it into Wavesurfer-js using loadBlob 

@Ziggy2001 can you show the code you're using to achieve this? also use the non-minified version of wavesurfer.js so we get a better error message.

**Comment by Ziggy2001** [comment]
Sure this is the code I use to retreive the data from the IndexedDB:


```
//Get the blob data
var tx = db.transaction('audio', 'readonly');
var audio = tx.objectStore('audio');
var request = audio.get( uid );

request.onsuccess = function(e) {
   wave.loadBlob( request.result['data'] );
};	
```


This is the code I use to save it in the IndexedDB:

```
  var transaction = db.transaction(['audio'], 'readwrite');
  var audio = transaction.objectStore('audio');
  var item = {
    uid: uid,
    data: vtplayer.recordedData,
    created: new Date().getTime()
  };

 var request = audio.put(item);
```


Hope that's of some use. I'll try using the non-minified version as well to see if I get a clearer message.

**Comment by thijstriemstra** [comment]
have you tried without indexeddb?

**Comment by Ziggy2001** [comment]
I did try loading the recordedData directly in using loadBlob but that didn't seem to want to work either. It gave the same TypeError: t is undefined error.

I've just tried using the non-minified version but oddly it's giving me two new errors:

```
SyntaxError: import declarations may only appear at top level of a module wavesurfer.js:1
TypeError: WaveSurfer.create is not a function
```

**Comment by Ziggy2001** [comment]
Okay I've managed to figure out a way around this issue by simply creating a createObjectURL blob from the stored data in the IndexedDB which is brilliant. However, the reason I'm trying to do all this is because in Chrome dataURLs have seek problems when you try to set the seek. For example you will try to seek to the middle of the file and it'll go to just before the end. I think it's to do with the server not providing the Accept-Ranges: bytes header on blob urls. If anyone has any ideas on how to resolve this then please let me know.

**Comment by thijstriemstra** [comment]
good to hear. You should use the ts-ebml plugin to inject metadata and make the file seekable.

**Comment by Ziggy2001** [comment]
Thanks for this. I have tried it but the further issue I have is I need the audio to be wav, not webm.
