### ISSUE TITLE
Record as WAV and convert to WEBM

### ISSUE THREAD

**Issue by Ziggy2001** [collab-project/videojs-record#366]
I was wondering if it's possible to record as WAV and have the WAV blob available in recordedData, whilst as the same time having access to the audio as WEBM in the convertedData?

The reasons for this are because I need WAV which I upload to a server via a worker, but I also need WEBM so I can immediately play the audio in Wavesurfer-js.

WAV isn't seekable in Chrome so the user can't jump around the file properly, WEBM does allow this but I can't upload a WEBM file because the application receiving the file doesn't recognise WEBM.

**Comment by thijstriemstra** [comment]
> I was wondering if it's possible to record as WAV and have the WAV blob available in recordedData, whilst as the same time having access to the audio as WEBM in the convertedData?

You could record as wav, and use the ffmpeg.js plugin to convert to webm, all on the clientside. Take a look at pull request (it's a work in progress but should work, just needs some cleanup and remove some hardcoded values): #201

**Comment by Ziggy2001** [comment]
I'll take a look. I struggle to understand where all the js files are that are needed. I've found the ffmpegjs-plugin.js but there appears to be other required files that I just cannot find.

**Comment by thijstriemstra** [comment]
@Ziggy2001 start with checking out the repository, then folllow this: https://github.com/collab-project/videojs-record#development

**Comment by Ziggy2001** [comment]
Ah I'm not installing the files that way. I'm probably doing it a very unorthodox way in that I've downloaded the zip and deployed the files where they need to be within the site.

**Comment by thijstriemstra** [comment]
If you want to test the pull request, I would recommand checking it out using git etc.
