### ISSUE TITLE
Ask for permission every time in Safari for iOS

### ISSUE THREAD

**Issue by chrisbenseler** [collab-project/videojs-record#368]
In Safari 12 for iOS (with experimental api allowed), every time a webpage in a certain domain tries to access the camera, the browser asks the user to allow access.
Is it possible to keep the user's preference set?

**Comment by thijstriemstra** [comment]
Looks like it's not possible (yet): https://stackoverflow.com/questions/48847388/how-to-permanently-allow-usage-of-camera-on-trusted-websites-with-ios-safari/49942017#49942017
