### ISSUE TITLE
When selecting another input device, nothing happens.

### ISSUE THREAD

**Issue by anselmoma9** [collab-project/videojs-record#369]
## Description
change-video-input does not work.

## Steps to reproduce
Access the demo: https://collab-project.github.io/videojs-record/examples/change-video-input.html
Enable the camera;
Select another device;
The action appears in the log, but nothing happens.

### Expected
Change the displayed device when you select.

### Actual
It does not change the device, even by selecting another device.

### Error output
No error ...

### versions
video.js 7.4.1 with videojs-record 3.6.0 and recordrtc 5.5.3

#### browsers
Google Chrome V 74.0.3729.131 64 bits

#### OSes
Windows 10 Professional

**Comment by thijstriemstra** [comment]
@anselmoma9 do you have multiple video devices connected? can you make a screenshot?

**Comment by anselmoma9** [comment]
> @anselmoma9 do you have multiple video devices connected? can you make a screenshot?

Yes, I have 3 devices connected, at the moment I can not take a screenshot because I'm not at work.

All three are listed, the device ID appears in the browser console, but it does not switch from image, always stays on the same device.

**Comment by anselmoma9** [comment]
@thijstriemstra 

Hello, I took a screenshot of the screen.

http://oi65.tinypic.com/2exly75.jpg

Note that selecting the other webcams appears in the chrome log, but the image does not change.

I also tested on Opera and Firefox, without success.

Thank you.

**Comment by anselmoma9** [comment]
Good Morning.

Any updates?

@thijstriemstra 

Thank you.

**Comment by thijstriemstra** [comment]
I haven't had time to look at it, but it's probably an issue with the example, not this plugin.

**Comment by anselmoma9** [comment]
@thijstriemstra 

I implemented the plugin in my project and presented the same behavior.

**Comment by thijstriemstra** [comment]
I don't have a 2nd webcam to test with atm. Donating one is always welcome ;)

**Comment by thijstriemstra** [comment]
Turns out nothing was implemented for changing video input, working on that now (it basically needs to call `getDevice` again with the correct deviceId constraints).

```javascript
video: {
    optional: [{sourceId: deviceId}]
}
```

**Comment by thijstriemstra** [comment]
@anselmoma9 can you give pr #374 a try?
