### ISSUE TITLE
iOS Safari video orientation

### ISSUE THREAD

**Issue by wayne530** [collab-project/videojs-record#370]
## Description
This issue seems to only affect iOS devices when recording in Safari. The issue is that when the orientation is 0 (portrait mode), the recorded video frames are rotated 90 degrees and stretched to fit the 9:16 orientation. If you rotate the device 90 degrees to the left and record in landscape mode, the video frames are recorded upside down but maintain the correct aspect ratio. If you rotate 90 degrees to the right and record in landscape, the video frames are recorded right side up with the correct aspect ratio. Given that Media Recorder and RTC are experimental features in iOS Safari, I'm not sure if these issues are an artifact of the data coming from the browser, or if there's an underlying issue with videojs-record in handling these orientations.

## Steps to reproduce
In iOS Safari, record a video in portrait mode and download the resultant webm. Play back the video and notice the rotation of the frame and distortion of the aspect ratio. Rotate 90 degrees left (and right) and record landscape orientation. Download the resultant webms and play back. Only the one rotated 90 degrees to the right plays back correctly.

### Expected
Portrait mode should produce a video in portrait orientation with the indicated aspect ratio (in my case, 9:16).
Landscape mode, regardless of specific orientation, should produce a video in the indicated aspect ratio (16:9), right side up.

### Actual
Portrait mode recorded frames are rotated 90 degrees and stretched to the portrait mode aspect ratio.
Landscape mode, when rotated to the left, plays back upside down.

### Error output
No errors.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
VIDEOJS: Using video.js 7.5.4 with videojs-record 3.6.0 and recordrtc 5.5.4
#### browsers
Safari
Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.16 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1

#### OSes
iOS 12.2

**Comment by wayne530** [comment]
Also of note, there is really substantial flickering of the control bar, such that it appears I may only be getting a few frames/sec refresh. This also happens on the audio/video demo from your README. Playback of the recorded video also fails - it appears to show only what's live in the camera's view at the moment but won't play back any recorded material. I wonder if this is the case because the recorded material is in webm, but iOS Safari can't play back webm?

**Comment by thijstriemstra** [comment]
> Portrait mode should produce a video in portrait orientation with the indicated aspect ratio (in my case, 9:16).
Landscape mode, regardless of specific orientation, should produce a video in the indicated aspect ratio (16:9), right side up.

this sounds like something specific to mobile devices. Is there a way to detect the orientation?

> This also happens on the audio/video demo from your README

this does not work, a known issue: #332

**Comment by wayne530** [comment]
@thijstriemstra Actually, #332 is for Safari on desktop. Safari on iOS does have this capability (see the screenshot below), and recording seems to work, but playback does not. I can detect the viewport orientation but then it requires post-processing to rotate and correct the aspect ratio. It seems you may not have access to an iOS device so I am happy to do any additional debugging/testing that might help to isolate the issue. Please let me know.

![IMG_5197](https://user-images.githubusercontent.com/313354/57707102-e0d8a600-761b-11e9-913e-8c659370a2bb.PNG)

**Comment by thijstriemstra** [comment]
> recording seems to work, but playback does not.

why do you think recording works? did you download/playback the recording elsewhere?

> I can detect the viewport orientation

How?

**Comment by wayne530** [comment]
It works because I (and others) can successfully record video on iPhone/iPod/iPad devices (assuming iOS 12) and this video can then be played back. The viewport orientation can be detected using the `window.orientation` property, though it's only defined on mobile devices. 0 is generally portrait, 90 is landscape rotated counter clockwise, and -90 is landscape rotated clockwise.

**Comment by thijstriemstra** [comment]
sounds like the width/height constraints need to be determined based on orientation. you said it only applies to ios (so I am assuming not android) so should this be part of the examples or should it be part of videojs-record?

**Comment by namnode** [comment]
I met same problem. Do not have any way to fix that at the moment ?

**Comment by wayne530** [comment]
@namnode @thijstriemstra Unfortunately, no combination of settings corrected the issue for me and the issue still persists. I had to correct it server-side by storing the user agent string (in a poor attempt to detect if it's iOS) as well as the viewport orientation, and then adding parameters to `ffmpeg` to correct the video's aspect ratio/orientation:

```python
        # run ffmpeg
        additional_options = ''
        if media.user_agent_is_ios():
            if media.viewport_orientation == 0:
                additional_options = '-vf "scale=960:720,transpose=1" '
            elif media.viewport_orientation == 90:
                additional_options = '-vf vflip '

        command = settings.FFMPEG_BINARY + ' -i ' + input_file.name + \
            ' -movflags faststart -profile:v high -level 4.2 -b:v 2500k -b:a 128k -vsync 0 ' + \
            additional_options + output_file.name
```

**Comment by namnode** [comment]
@wayne530 Thank you so much ! But use ffmpeg require much time ! 
Not have other way, Ⅰ used css for fix that if detect is recorded in iOS
`video {
    transform: rotate(90deg) scaleX(1);
    object-fit: fill;
}`

**Comment by thijstriemstra** [comment]
> there is really substantial flickering of the control bar, such that it appears I may only be getting a few frames/sec refresh.

See #413 for this.

**Comment by thijstriemstra** [comment]
> Ⅰ used css for provisional fix that if detect is recorded in iOS

@namnode can you show with some sample code how that works?

**Comment by FrostyJet** [comment]
So I didn't find any combination of options to make this work on fronted.
I solved the problem on server side, sending also the device OS, and rotating the video for IOS devices using ffmpeg.

ffmpeg -i myVideo.mp4 -vf "scale=960:720,transpose=1" myVideoRotated.mp4

"transpose=1" means it will rotate 90 deg (one time) clockwise.

**Comment by miguel258** [comment]
I have the same problem, but i dont use video-js iam using MediaRecord API, obviously enabling MediaRecord on my iPhone, im recording video in portrait mode but when display in video tag show me as landscape video....

**Comment by andriworld** [comment]
Webkit bug report, for reference: https://bugs.webkit.org/show_bug.cgi?id=198912

**Comment by duhar** [comment]
![image](https://user-images.githubusercontent.com/17267400/105572655-809d7f80-5d7e-11eb-87ba-c3181d9eaafb.png)
I am facing rotation issue

**Comment by thijstriemstra** [comment]
> Webkit bug report, for reference: https://bugs.webkit.org/show_bug.cgi?id=198912

that ticket was fixed and merged on 2020-10-01. So it should be fixed in latest Safari?

**Comment by thijstriemstra** [comment]
> that ticket was fixed and merged on 2020-10-01. So it should be fixed in latest Safari?

I tested with videojs-record 4.2.0/video.js 7.11.4 on Mobile Safari iOS 14.4 using an iPhone and the rotation issue was fixed, portrait and landscape recordings worked as expected.

Closing.
