### ISSUE TITLE
iOS 12 Safari recording indicates type video/webm, but is in fact mp4[h.264/aac]

### ISSUE THREAD

**Issue by wayne530** [collab-project/videojs-record#371]
## Description
Not sure if this is a videojs-record issue or a RecordRTC issue, but the metadata associated with the recorded video assigns the filename a .webm extension and indicates a type of video/webm, but according to ffprobe:

<img width="997" alt="Web_Inspector_—_Wayne’s_iPhone_—_Safari_—_heroapp-staging_herokuapp_com_—_attach_media_and_New_Issue_·_collab-project_videojs-record" src="https://user-images.githubusercontent.com/313354/57559544-315bb500-7337-11e9-9976-0b110e6da704.png">

```
ffprobe version 4.1.3 Copyright (c) 2007-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.3_1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'orientation_0.webm':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.20.100
  Duration: 00:00:04.18, start: 0.000000, bitrate: 862 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc), 480x640, 790 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Metadata:
      handler_name    : Core Media Video
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 22050 Hz, mono, fltp, 76 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
```

## Steps to reproduce
Using an iOS device running 12.2, record a video and on finishRecord, console.log the recordedData associated with the videojs player. Download the recorded file and use ffprobe to see its metadata.

### Expected
Since iOS is recording in mp4[h.264 + aac], the video should have an extension of .mp4 and should have a type of video/mp4.

### Actual
Independent of the actual encoding, the video is given a .webm extension and a type of video/webm.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
[Log] VIDEOJS: – "Using video.js 7.5.4 with videojs-record 3.6.0 and recordrtc 5.5.4" (video.min.js, line 12)
#### browsers
Safari on iOS 12.2
#### OSes
iOS 12.2

**Comment by thijstriemstra** [comment]
@wayne530 you didn't include the videojs config. **why not**?

**Comment by wayne530** [comment]
@thijstriemstra here it is:
```
    var options = {
        controls: true,
        fluid: true,
        plugins: {
            record: {
                audio: true,
                video: {
                    mandatory: {
                        minWidth: 1280,
                        minHeight: 720
                    }
                },
                maxLength: 600,
                frameWidth: 1280,
                frameHeight: 720,
                debug: true
            }
        }
    };
```

**Comment by thijstriemstra** [comment]
try using a `videoMimeType` of `video/mp4` to force the extension..

**Comment by wayne530** [comment]
We want to support recording on multiple devices/browsers and some (it appears) cannot record using mp4 containers. Can't we determine the container and audio/video encoding by examining the first several bytes of the recorded binary data and/or get this information back from the browser API that is responsible for recording?

**Comment by thijstriemstra** [comment]
> get this information back from the browser API that is responsible for recording?

yes, see https://www.webrtc-experiment.com/RecordRTC/simple-demos/isTypeSupported.html ([source](https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/isTypeSupported.html))

It uses `MediaRecorder.isTypeSupported()`. I could expose this method in videojs-record, e.g. `player.record().isTypeSupported()`.

**Comment by ignl** [comment]
Chrome also puts h264 to matroska container and there is an issue where Firefox cannot play it: https://bugzilla.mozilla.org/show_bug.cgi?id=1422891
I guess same thing here.

**Comment by thijstriemstra** [comment]
The mime-type detection in v4.0.0 has improved and if it's matroska, it will not use the `.webm` extension anymore (but `.mkv`). This should clear up the confusion, closing this ticket.
