### ISSUE TITLE
Cross browser issue

### ISSUE THREAD

**Issue by karan-chauhan** [collab-project/videojs-record#372]
## Description
Giving cross browser issue.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

### Expected
If its work on localhost on Chrome then it should work on same browser for online server too.

### Actual
I create a demo on my local environment and everything is working fine on Chrome but demo is giving error on Firefox. And error is "Failed to allocate videosource".
After then i upload the same demo on my online server then it start works on Firefox but not worked on Chrome. And error in chrome is "This browser does not support navigator.mediaDevices.getUserMedia".

### Error output
Firefox Error on local environment : "Failed to allocate videosource"
Chrome error on online server : "This browser does not support navigator.mediaDevices.getUserMedia"

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
what version of videojs does this occur with?
Video.js 7.5.4
videojs-record 3.6.0
RecordRTC v5.5.4

#### browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
Chrome Version : 74.0
Firefox Quantum Version : 66.0.5 

#### OSes
what platforms (operating systems and devices) are affected?
Windows 10 Home (64-bit)

**Comment by thijstriemstra** [comment]
> Chrome error on online server : "This browser does not support navigator.mediaDevices.getUserMedia"

are you sure this is happening in a desktop browser and not the chrome ios browser? are you using https everywhere?

**Comment by karan-chauhan** [comment]
Hello @thijstriemstra,
Thanks for your quick reply. My issue is solved. Actually i was not using https server. But when i convert it to https then it works fine on both firefox and chrome.
