### ISSUE TITLE
Support for audio pitch shifting

### ISSUE THREAD

**Issue by mcvladthegoat** [collab-project/videojs-record#373]
I'm not sure this feature is useful. The "pitch shifting" could be made as standalone plugin (maybe WebAssembly)

**Comment by thijstriemstra** [comment]
@mcvladthegoat pull requests are welcome!

**Comment by mcvladthegoat** [comment]
Awesome! I'll do it asap

**Comment by thijstriemstra** [comment]
Sounds good! You might want to create a separate project for the webassembly/js code so it can be used as an npm dependency. And then add a plugin for this library to videojs-record.

**Comment by thijstriemstra** [comment]
any news @mcvladthegoat?

**Comment by mcvladthegoat** [comment]
Still working on it. There is some problems with pitching stereo files. I'll finish soon :)

**Comment by thijstriemstra** [comment]
ping @mcvladthegoat

**Comment by mcvladthegoat** [comment]
@thijstriemstra i apologize for the very long work on a feature, try to return to the development in a few days

**Comment by thijstriemstra** [comment]
Closing this ticket for now. Please re-open, or open a pull request, if there is more news.
