### ISSUE TITLE
Cant correct save video in Nodejs server

### ISSUE THREAD

**Issue by iokononyuk** [collab-project/videojs-record#375]
## Description
I need record video from webcam and save file on NodeJs server. But I have a problem.
I can save *.webm file, but when I open file I see only audio and backscreen.

## Frontend
```javascript
        player.on('finishRecord', function () {  
                upload(player.recordedData);
        });
```
## Backend:
 ```javascript
app.post('/upload', function (req, res) {

    let file = req.files.file;
    file.mv("video.webm", function (err) {
        if (err)
            return res.status(500).send(err);
        res.send('File uploaded!');
    });
    res.send('ok')
})`

**Comment by thijstriemstra** [comment]
@iokononyuk what videojs-record config are you using? what browser and operating system? when you view it in the browser it's ok?

**Comment by iokononyuk** [comment]
> @iokononyuk what videojs-record config are you using? what browser and operating system? when you view it in the browser it's ok?

Yes, in browser all correct, thank you)

One more question: 

How brosers support this plugin?

**Comment by thijstriemstra** [comment]
@iokononyuk you ignored most of my questions, why?

**Comment by iokononyuk** [comment]
@thijstriemstra Thanks, now video save correct)
But problem with cross-platforms(

**Comment by thijstriemstra** [comment]
> Thanks, now video save correct)

No problem, but what changed, are you using master branch?

> But problem with cross-platforms(

what platforms? make sure to use https everywhere.

**Comment by iokononyuk** [comment]
@thijstriemstra In window player dont plays videos, but in browser <video> plays good. Its solve my problem.

Safari, Opera, FF - last 2 versions and mobile Chrome, Safari, dont record.
Localhost

**Comment by thijstriemstra** [comment]
you can play them with VLC.
