### ISSUE TITLE
Not able to view 'Camera View', a black box appears at top left side

### ISSUE THREAD

**Issue by ehsanali1992** [collab-project/videojs-record#377]
## Description
I am a newbie to this one. When I run the project I am not able to see camera view in web, a black rectangle box appears at top left side 
![image](https://user-images.githubusercontent.com/45037292/58410168-0c7f7580-808b-11e9-8f5b-36aff4b716b1.png)

No error message gets displayed on console as well.
![image](https://user-images.githubusercontent.com/45037292/58410237-3042bb80-808b-11e9-86a4-c2de568656b5.png)

## Steps to reproduce
Followed all the steps written here at 
https://github.com/collab-project/videojs-record/wiki/React
When I run **npm start** command, no camera view appears. Checked it on Chrome and Edge

### Expected
Camera view should be visible in that block box or wherever in the web.

### Actual
No camera view appears

### Error output
No error output.

## Additional Information
VIDEOJS: Using video.js 7.5.4 with videojs-record 3.6.0 and recordrtc 5.5.4

what version of videojs does this occur with?
VIDEOJS: Using video.js 7.5.4 with videojs-record 3.6.0 and recordrtc 5.5.4
Chrome version :Version 74.0.3729.169 (Official Build) (64-bit

**Comment by thijstriemstra** [comment]
@ehsanali1992 that screenshot shows references to 'logo' but there is not logo in this wiki example. Just went through the wiki page, especially for you, and it works just fine here.

**Comment by ehsanali1992** [comment]
@thijstriemstra Thanks for your quick response, but the issue is not with the warnings, I just created a new app using create-react-app, in that project, logo was declared but never used so those were the warnings. 
![image](https://user-images.githubusercontent.com/45037292/58418461-40fe2c00-80a1-11e9-9648-fa92c01b4d84.png)

The point I want to raise is why I am not being able to view camera in that black little box?

**Comment by ehsanali1992** [comment]
@thijstriemstra I am sharing code with you, please have a look at code so you may understand what I am doing wrong. I am also using another library on which camera view is visible. 
`import React, { Component } from "react";
import "./App.css";
import "video.js/dist/video-js.css";
import videojs from "video.js";

import "webrtc-adapter";
import RecordRTC from "recordrtc";
import "videojs-record/dist/css/videojs.record.css";
class App extends Component {
  componentDidMount() {
    console.log("hello");
    // instantiate Video.js
    this.player = videojs(this.videoNode, this.props, () => {
      // print version information at startup
      var version_info =
        "Using video.js " +
        videojs.VERSION +
        " with videojs-record " +
        videojs.getPluginVersion("record") +
        " and recordrtc " +
        RecordRTC.version;
      videojs.log(version_info);
    });

    // device is ready
    this.player.on("deviceReady", () => {
      console.log("device is ready!");
    });

    // user clicked the record button and started recording
    this.player.on("startRecord", () => {
      console.log("started recording!");
    });

    // user completed recording and stream is available
    this.player.on("finishRecord", () => {
      // recordedData is a blob object containing the recorded data that
      // can be downloaded by the user, stored on server etc.
      console.log("finished recording: ", this.player.recordedData);
    });

    // error handling
    this.player.on("error", (element, error) => {
      console.warn(error);
    });

    this.player.on("deviceError", () => {
      console.error("device error:", this.player.deviceErrorCode);
    });
  }

  // destroy player on unmount
  componentWillUnmount() {
    if (this.player) {
      this.player.dispose();
    }
  }
  render() {
    return (
      <div data-vjs-player>
        <video
          id="myVideo"
          ref={node => (this.videoNode = node)}
          className="video-js vjs-default-skin"
          playsInline
        />
      </div>
    );
  }
}

export default App;
`

**Comment by thijstriemstra** [comment]
@ehsanali1992 please compare that App.js with the App.js in the wiki. There are differences (like `Record` import missing) that explain why you're having issues.

**Comment by ehsanali1992** [comment]
@thijstriemstra  I removed it by purpose, just to remove warnings. It is not working with it as well.

**Comment by thijstriemstra** [comment]
@ehsanali1992 what does the network tab show? can you make a screenshot? any 404 errors?

**Comment by ehsanali1992** [comment]
@thijstriemstra Have a look at the network tab. No 404 error.
![image](https://user-images.githubusercontent.com/45037292/58453416-76a02500-8134-11e9-929b-0c79ec39e9df.png)

**Comment by thijstriemstra** [comment]
@ehsanali1992 in your screenshot there is 'videojs-record ' (notice the missing version number) so it's definitely something with videojs-record. What that is, I don't know. What operating system are you testing this on?

![image](https://user-images.githubusercontent.com/45037292/58418461-40fe2c00-80a1-11e9-9648-fa92c01b4d84.png)

**Comment by ehsanali1992** [comment]
@thijstriemstra videojs-record version was missing because I removed **Record** import to avoid 'never used warning' in console. I am working on Windows 10 and testing it on Chrome version :Version 74.0.3729.169 (Official Build) (64-bit). I have also tried it on Edge and Mozilla.

![image](https://user-images.githubusercontent.com/45037292/58531732-cc400480-81fc-11e9-8950-c4e703001bff.png)

**Comment by thijstriemstra** [comment]
I'm working on a fix for #378 that might fix this issue as well, stay tuned.

**Comment by ehsanali1992** [comment]
Ok @thijstriemstra . Will wait for it. Thanks for your time.

**Comment by thijstriemstra** [comment]
@ehsanali1992  can you try with the master branch? run `npm run build` for videojs-record and overwrite the `dist` directory in your react project's `node_modules/videojs-record/` to test it.

**Comment by ehsanali1992** [comment]
@thijstriemstra okay let me try this
