### ISSUE TITLE
Can't use ts-ebml plugin in React app

### ISSUE THREAD

**Issue by jelenamilanovic** [collab-project/videojs-record#378]
## Description
Hi,

We have a problem with ts-ebml converter library in the React project. For some reason, imported ts-ebml plugin cannot access videojs instance. 

We have installed and imported all necessary dependencies into the component, instantiated videojs and everything worked fine until we've imported ts-ebml plugin and set convertEngine property to 'ts-ebml'. The whole app crashed logging : "Uncaught ReferenceError: videojs is not defined" into the console. When it's set to empty string or omitted, it works as it should.

Any kind of help would be appreciated.  

## Steps to reproduce
1. Install video.js, videojs-record, recordrtc, webrtc-adapter;
2. Follow [these instructions](https://github.com/collab-project/videojs-record/wiki/React) to run everything using create-react-app;
3. Import dependencies in the component where video.js is going to be instantiated;
4. Set the property plugins.record.convertEngine of the options object to 'ts-ebml' and pass it as a parameter when the video.js constructor function is called.

### Error output
>ReferenceError: videojs is not defined
eval
.VideojsRecord.%5Bname%5D/./src/js/plugins/ts-ebml-plugin.js?:22:21
./src/js/plugins/ts-ebml-plugin.js
C:/Users/pc11/Documents/Projects/eyesee-platform/node_modules/videojs-record/dist/plugins/videojs.record.ts-ebml.js:672
  669 | function (module, exports, __webpack_require__) {
  670 |   "use strict";
  671 | 
> 672 |   eval("\n\nvar _interopRequireDefault = __webpack_require__(/*! @babel/runtime/helpers/interopRequireDefault */ \"./node_modules/@babel/runtime/helpers/interopRequireDefault.js\");\n\nObject.defineProperty(exports, \"__esModule\", {\n  value: true\n});\nexports.default = void 0;\n\nvar _classCallCheck2 = _interopRequireDefault(__webpack_require__(/*! @babel/runtime/helpers/classCallCheck */ \"./node_modules/@babel/runtime/helpers/classCallCheck.js\"));\n\nvar _createClass2 = _interopRequireDefault(__webpack_require__(/*! @babel/runtime/helpers/createClass */ \"./node_modules/@babel/runtime/helpers/createClass.js\"));\n\nvar _possibleConstructorReturn2 = _interopRequireDefault(__webpack_require__(/*! @babel/runtime/helpers/possibleConstructorReturn */ \"./node_modules/@babel/runtime/helpers/possibleConstructorReturn.js\"));\n\nvar _getPrototypeOf2 = _interopRequireDefault(__webpack_require__(/*! @babel/runtime/helpers/getPrototypeOf */ \"./node_modules/@babel/runtime/helpers/getPrototypeOf.js\"));\n\nvar _inherits2 = _interopRequireDefault(__webpack_require__(/*! @babel/runtime/helpers/inherits */ \"./node_modules/@babel/runtime/helpers/inherits.js\"));\n\nvar _tsEbml = __webpack_require__(/*! ts-ebml */ \"./node_modules/ts-ebml/lib/index.js\");\n\nvar ConvertEngine = videojs.getComponent('ConvertEngine');\n\nvar TsEBMLEngine = function (_ConvertEngine) {\n  (0, _inherits2.default)(TsEBMLEngine, _ConvertEngine);\n\n  function TsEBMLEngine() {\n    (0, _classCallCheck2.default)(this, TsEBMLEngine);\n    return (0, _possibleConstructorReturn2.default)(this, (0, _getPrototypeOf2.default)(TsEBMLEngine).apply(this, arguments));\n  }\n\n  (0, _createClass2.default)(TsEBMLEngine, [{\n    key: \"convert\",\n    value: function convert(data) {\n      var _this = this;\n\n      var decoder = new _tsEbml.Decoder();\n      var reader = new _tsEbml.Reader();\n      reader.logging = false;\n      reader.drop_default_duration = false;\n      var timestamp = new Date();\n      timestamp.setTime(data.lastModified);\n      this.loadBlob(data).then(function (buffer) {\n        var elms = decoder.decode(buffer);\n        elms.forEach(function (elm) {\n          reader.read(elm);\n        });\n        reader.stop();\n\n        var refinedMetadataBuf = _tsEbml.tools.makeMetadataSeekable(reader.metadatas, reader.duration, reader.cues);\n\n        var body = buffer.slice(reader.metadataSize);\n        var result = new Blob([refinedMetadataBuf, body], {\n          type: data.type\n        });\n\n        _this.addFileInfo(result, timestamp);\n\n        _this.player().convertedData = result;\n\n        _this.player().trigger('finishConvert');\n      });\n    }\n  }]);\n  return TsEBMLEngine;\n}(ConvertEngine);\n\nvideojs.TsEBMLEngine = TsEBMLEngine;\nvar _default = TsEBMLEngine;\nexports.default = _default;\nmodule.exports = exports.default;\n\n//# sourceURL=webpack://VideojsRecord.%5Bname%5D/./src/js/plugins/ts-ebml-plugin.js?");
      | ^  673 |   /***/
  674 | }

### versions
video.js: ^7.5.4,
recordrtc: ^5.5.4, 
videojs-record: ^3.6.0,
webrtc-adapter: ^7.2.3,

react: ^16.8.6,
react-app-rewired: ^2.1.3

#### browsers
Chrome
#### OSes
Windows 10

**Comment by thijstriemstra** [comment]
> Import dependencies in the component where video.js is going to be instantiated;

can you show these imports?

> Set the property plugins.record.convertEngine of the options object to 'ts-ebml' and pass it as a parameter when the video.js constructor function is called.

can you show the videojs-record config?

**Comment by jelenamilanovic** [comment]
Sure. 

Imports:

```
import 'video.js/dist/video-js.css';
import videojs from 'video.js';
import 'webrtc-adapter';
import RecordRTC from 'recordrtc';
import Record from 'videojs-record/dist/videojs.record.js'; 
import 'videojs-record/dist/plugins/videojs.record.ts-ebml.js';
```

Options:
```
const videoJsOptions = {
    controls: false,
    width: 640,
    height: 480,
    fluid: false,
    plugins: {
        record: {
          audio: false,
          video: {frameRate: { ideal: 30, max: 30 }, width: 640, height: 480},
          maxLength: 9999,
          debug: true,
          frameWidth:640,
          frameHeight:480,
          videoMimeType: "video/webm;codecs=H264",
          convertEngine: 'ts-ebml'
        }
    }
}
```

**Comment by thijstriemstra** [comment]
@jelenamilanovic I was able to reproduce this issue and working on a fix in #379.

**Comment by thijstriemstra** [comment]
@jelenamilanovic can you try with the master branch? should be fixed now. `npm run build` videojs-record and overwrite the `dist` directory in your react project's `node_modules/videojs-record/` to test it.

**Comment by jelenamilanovic** [comment]
@thijstriemstra, everything works perfectly. 

HUGE THANKS! You were really efficient on this one. 🥇

**Comment by thijstriemstra** [comment]
my pleasure, thanks for the report!
