### ISSUE TITLE
convertedData is undefined after finishConvert

### ISSUE THREAD

**Issue by soulpaul** [collab-project/videojs-record#380]
## Description
Hi!
Using ts-embl plugin I get `convertedData `object as undefined when `finishConvert` is triggered. 

## Steps to reproduce

In a React component:
- import videojs, videojs-record and ts-enml as follows
```javascript
let videojs

if (!process.env.TESTING) {
  import('video.js')
    .then((mod) => {
      videojs = mod.default
    })
    .catch((error) => {
      throw new Error(`Dynamic page loading failed: ${error}`)
    })
  import('videojs-record/dist/videojs.record.js').catch((error) => {
    throw new Error(`Dynamic page loading failed: ${error}`)
  })
  import('videojs-record/dist/plugins/videojs.record.ts-ebml.js').catch((error) => {
    throw new Error(`Dynamic page loading failed: ${error}`)
  })
}
```
- set options as
```javascript
this.playerOptions = {
  controls: true,
  fluid: false,
  plugins: {
    record: {
      audio: true,
      video: {
        // video constraints: set resolution of camera
        mandatory: {
          minWidth: 1280,
          minHeight: 720
        }
      },
      videoMimeType: "video/webm;codecs=h264",
      maxLength: this.props.maxLength,
      convertEngine: "ts-ebml",
      debug: true
    }
  },
  controlBar: {
    fullscreenToggle: false
  }
}
```
- Load the player
```javascript
this.player = videojs(this.videoNode, this.playerOptions, () => {
  // print version information at startup
  var msg =
    "Using video.js " +
    videojs.VERSION +
    " with videojs-record " +
    videojs.getPluginVersion("record") +
    " and recordrtc " +
    RecordRTC.version;
  videojs.log("log", msg);
})
```
- Record a video
- Listen to `finishConvert` action
```javascript
this.player.on('finishConvert', function() {
 console.log('finished converting: ', this.player.convertedData)
})
```
## Results
`this.player.convertedData` is returned `undefined`

### Expected
`this.player.convertedData` should return a blob containing the converted video with metadata included

### Error output
No error output

### versions
video.js 7.5.5 with videojs-record 3.7.1 and recordrtc 5.5.4 on Google Chrome 75.0.3770.100

**Comment by thijstriemstra** [comment]
@soulpaul does the online example work for you? https://collab-project.github.io/videojs-record/examples/video-only-ebml.html

**Comment by soulpaul** [comment]
@thijstriemstra the online example works for me. 
I tried to record video-only in my implementation but it does not work as well. Any idea on what I could be doing wrong?

**Comment by thijstriemstra** [comment]
The `videoMimeType` you specify cannot be used, see https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/isTypeSupported#Example

On Firefox 67:

```
Is video/webm supported? Maybe! 
Is audio/webm supported? Maybe! 
Is video/webm;codecs=vp8 supported? Maybe! 
Is video/webm;codecs=daala supported? Nope :( 
Is video/webm;codecs=h264 supported? Nope :(
Is audio/webm;codecs=opus supported? Maybe!
Is video/mpeg supported? Nope :(
```

But more importantly, your `finishConvert` method uses the wrong scope. Use arrow function instead, otherwise reference to `this.player` can't be made.

```javascript
this.player.on('finishConvert', () => {
 console.log('finished converting: ', this.player.convertedData)
})
```
