### ISSUE TITLE
How to configure webpack with umijs instead of create react app?

### ISSUE THREAD

**Issue by RusseII** [collab-project/videojs-record#382]
## Description
Can't get videojs-record react starter project running https://github.com/collab-project/videojs-record/wiki/React

## Steps to reproduce
https://codesandbox.io/s/configure-webpack-plugins-y0shn - the webpack config I tried is in umirc.ts

Here is how I have the config setup
```
  chainWebpack(config, { webpack }) {
    const videojsPlugin = new webpack.ProvidePlugin({
      videojs: 'video.js/dist/video.cjs.js',
      RecordRTC: 'recordrtc',
      MediaStreamRecorder: ['recordrtc', 'MediaStreamRecorder'],
    });

    config.plugin('record').use(videojsPlugin);
    config.resolve.alias
      .set('videojs', 'video.js')
      .set('WaveSurfer', 'wavesurfer.js')
      .set('RecordRTC', 'recordrtc');
  },
```

### Expected
The starter project without errors

### Actual
Error: plugin "record" does not exist

### Error output
Error: plugin "record" does not exist

**Comment by thijstriemstra** [comment]
You are missing a videojs-record import. Actually, where are you importing the classes?

**Comment by RusseII** [comment]
https://github.com/collab-project/videojs-record/wiki/React - I followed this tutorial - they don't seem to be importing videojs-record anywhere either

All of the imports and logic is in src/pages/index.tsx
https://codesandbox.io/s/configure-webpack-plugins-y0shn

**Comment by thijstriemstra** [comment]
> they don't seem to be importing videojs-record anywhere either

Not true, take a look at `src/App.js`

**Comment by RusseII** [comment]
Where? They just have 

```
// register videojs-record plugin with this import
import 'videojs-record/dist/css/videojs.record.css';
import Record from 'videojs-record/dist/videojs.record.js';
```

And the code sandbox src/pages/index.tsx is a complete copy of src/App.js
https://codesandbox.io/s/configure-webpack-plugins-y0shn

**Comment by thijstriemstra** [comment]
> Where? They just have

that's an import of videojs-record right? so your statement about no imports isn't true. I am not familiar with umijs. You are able to run the react wiki example without umijs right?

**Comment by thijstriemstra** [comment]
@RusseII what version of videojs-record are you using? at least v3.7.1?

**Comment by thijstriemstra** [comment]
@RusseII was able to get this working, see https://github.com/collab-project/videojs-record/wiki/UmiJS
