### ISSUE TITLE
Firefox 68 breaks functionality

### ISSUE THREAD

**Issue by jarkt** [collab-project/videojs-record#387]
## Description
Firefox 68 seems to affect recording functionality in some situations.
While it works in production environment, it's no longer possible to capture a video in development environment.
The only relevant difference is that the development system does not use https.
There are no error messages in the JavaScript console, there is only no reaction when I want to start recording.
When you downgrade to Firefox 67 everything works fine.

Can someone confirm the issue?

## Steps to reproduce
Try to record a video on a http page.

### Expected
Browser asks for camera access.

### Actual
No reaction.

### Error output
No error output.

#### videojs
7.5.4

#### browsers
Firefox 68 with disabled Plugins.

#### OSes
Win 10

**Comment by thijstriemstra** [comment]
It's fine on Ubuntu 18.04 so likely something else @jarkt (haven't tested on win10 though).

**Comment by thijstriemstra** [comment]
>  The only relevant difference is that the development system does not use https.

it should be either https or localhost though.

**Comment by jarkt** [comment]
Chrome has the same behaviour, but there is an option to trust a defined host with `--unsafely-treat-insecure-origin-as-secure="http://docker.local"`.

But ok, not a topic for here, thank you @thijstriemstra
