### ISSUE TITLE
Recorded video is not stable

### ISSUE THREAD

**Issue by megadola** [collab-project/videojs-record#39]
thanks @thijstriemstra it helps, but actually after several times of trying, it didn't work as well (cause: file of fileupload plugin are missing and i tried to get it from the source on github but it didn't work for me), anyway:...
finaly, i can upload the video (ONLY with FIREFOX):

JS
```javascript
player.on('finishRecord', function()
{
    console.log('finished recording: ', player.recordedData);
	var blob = player.recordedData;
    var reader = new FileReader();
    // this function is triggered once a call to readAsDataURL returns
    reader.onload = function(event){
        var fd = new FormData();
        fd.append('store_video', event.target.result);
        $.ajax({
            type: 'POST',
            url: 'store.php',
            data: fd,
            processData: false,
            contentType: false
        }).done(function(data) {
            // print the output from the store.php script
        });
    };      
    // trigger the read from the reader...
    reader.readAsDataURL(blob);
});
```

PHP
```php
$data = substr($_POST['store_video'], strpos($_POST['store_video'], ",") + 1);
// decode it
$decodedData = base64_decode($data);
// print out the raw data, 
//echo ($decodedData);
$filename = "video.mp4";
// write the data out to the file
$fp = fopen($filename, 'wb');
fwrite($fp, $decodedData);
fclose($fp);
exit;
```

and it works fine, BUT:
Audio never match the video (sound is faster than the picture - AUDIO_VIDEO) !!
notes:
- saved format was "mp4" and sometimes it was "webm" and both are having the same problem of sound!
- also video is not stable, there is flashing with black screen every 2-4 seconds: using (VLC Player) MP4 Format.

any idea ?

Thank You

**Comment by thijstriemstra** [comment]
What versions of video.js, recordrtc, videojs-record, browser, operating system etc are you using?

**Comment by megadola** [comment]
RecordRTC: January 8th, 2016
video.js: 5.2.1
jQuery: 2.1.4
Windows: 10, DELL latitude E5540 i5, 8G RAM

[jsfiles.zip](https://github.com/collab-project/videojs-record/files/93287/jsfiles.zip)

**Comment by thijstriemstra** [comment]
what version of firefox?

**Comment by thijstriemstra** [comment]
I think the audio/video timing issue can be fixed with https://github.com/muaz-khan/RecordRTC#initrecorder, it does mention these issues.

**Comment by thijstriemstra** [comment]
The PR was merged. @megadola can you grab the latest videojs-record and RecordRTC.js from their repository and try again?

**Comment by thijstriemstra** [comment]
Closing this for now, please reopen if issue still exists.
