### ISSUE TITLE
Question: Can a record and a replay be triggered programatically?

### ISSUE THREAD

**Issue by retrocausal** [collab-project/videojs-record#391]
## Description
I am looking for ways to trigger a record as soon as the camera turns on, or via an external click

## Steps to reproduce
1. remove the controls by input `controls: false` in the configuration
2. click on a button outside of the video player
3. on click of the button, call `player.getDevice()` to turn on the camera
### Expected
1. the recording should begin as soon as the camera turns on
2. based on the `maxLength`, the recording stops
3. replay is triggered as soon as the recording stops
### Actual
nil

### Error output
none

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
3.8.0
#### browsers
chrome v 75.x 
#### OSes
macOS mojave

**Comment by retrocausal** [comment]
I tried using `player.recordToggle.trigger('click')`. However, I get an error 
<img width="541" alt="Screenshot 2019-07-22 at 15 33 17" src="https://user-images.githubusercontent.com/15086525/61624424-2e196980-ac96-11e9-8c96-8636e52cc1a5.png">

**Comment by thijstriemstra** [comment]
if the recording needs to start as soon as the device is enabled:

```javascript
player.on('deviceReady', function() {
    player.record().start();
});
