### ISSUE TITLE
Uncaught Error: plugin "record" does not exist

### ISSUE THREAD

**Issue by inyourcorner** [collab-project/videojs-record#398]
## Description
I'm running into an issue that others have run into:
`Uncaught Error: plugin "record" does not exist`

I read through other issues and tried updating the `video.js` links to use `7.2.2` (something suggested in a different issue), but that doesn't seem to resolve it.  I tried digging into the source generated, but because it's minified I couldn't get much from it.  The good news is i'm not running react, angular, or any other framework 🙃 ... and it's a one-pager example.

Page/Code:
`video-snap.html`

```javascript
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Video-only Example - Record Plugin for Video.js</title>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.2.2/video.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/6.1.1/adapter.min.js"></script>
    <script src="https://cdn.WebRTC-Experiment.com/RecordRTC.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/2.0.6/videojs.record.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.2.2/video.min.js"></script>
    

    <link href="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.2.2/video-js.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/2.0.6/css/videojs.record.min.css" rel="stylesheet">

</head>
<body>

    <video id="myImage" playsinline class="video-js vjs-default-skin"></video>

    <script>
    /* eslint-disable */
    var options = {
        controls: true,
        width: 320,
        height: 240,
        fluid: false,
        controlBar: {
            volumePanel: false,
            fullscreenToggle: false
        },
        plugins: {
            record: {
                image: true,
                debug: true
            }
        }
    };
    var player = videojs('myImage', options, function() {
        // print version information at startup
        var msg = 'Using video.js ' + videojs.VERSION +
            ' with videojs-record ' + videojs.getPluginVersion('record');
        videojs.log(msg);
    });
    // error handling
    player.on('deviceError', function() {
        console.warn('device error:', player.deviceErrorCode);
    });
    player.on('error', function(element, error) {
        console.error(error);
    });
    // snapshot is available
    player.on('finishRecord', function() {
        // the blob object contains the image data that
        // can be downloaded by the user, stored on server etc.
        console.log('snapshot ready: ', player.recordedData);
    });
    </script>


</body>
</html>
```

Sorry you've had to troubleshoot this issue so many times... asking here was the last thing I could think of before posting to SO. 

FWIW I couldn't get the "video-only" example to work, either (same error). 

## Steps to reproduce
Open the page above in chrome (`Version 76.0.3809.132 (Official Build) (64-bit)`) on Windows 10 (`Pro, Version 1903`) and look at the dev-console.

### Expected

Working version similar to those [here](https://github.com/collab-project/videojs-record#examples)

### Actual
Black image box

### Error output
If there are any errors at all, please include them here.
`Uncaught Error: plugin "record" does not exist`

## Additional Information
Please include any additional information necessary here. Including the following:

### versions
* Windows 10 Pro Version 1903
* Chrome Version 76.0.3809.132 (Official Build) (64-bit)

#### videojs
what version of videojs does this occur with?
`6.7.1`, `7.2.2`

#### browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
* Chrome Version 76.0.3809.132 (Official Build) (64-bit)

#### OSes
* Windows 10 Pro Version 1903

**Comment by thijstriemstra** [comment]
you are using a really old version of video.js and videojs-record. Please try the latest versions @inyourcorner

**Comment by inyourcorner** [comment]
Sure! I want to make sure I have the latest versions: 
* I looked and the latest version of videojs-record I could find was 3.8.0: https://github.com/collab-project/videojs-record/releases
* The latest non-pre release of video.js that I saw was 7.5.5: https://github.com/videojs/Video.js/releases

I updated the links to:

```
    <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.5.5/video.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/3.8.0/videojs.record.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/6.1.1/adapter.min.js"></script>
    <script src="https://cdn.WebRTC-Experiment.com/RecordRTC.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.5.5/video.min.js"></script>
    

    <link href="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.5.5/video-js.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/3.8.0/css/videojs.record.min.css" rel="stylesheet">
```

and ran it again, but I get the same plugin error.  Are there other versions of libraries I should also update?  Thanks for the help!

**Comment by thijstriemstra** [comment]
you're including video.js twice, I think that's causing this issue. Simply copy one of the examples from this repository and then replace the local `node_modules` links with cdnjs references.

**Comment by inyourcorner** [comment]
OK - they're a little difficult for me to parse and understand which swaps with which:
I swapped: 
```
   <link href="../node_modules/video.js/dist/video-js.min.css" rel="stylesheet">
    <link href="../dist/css/videojs.record.css" rel="stylesheet">
    <link href="assets/css/examples.css" rel="stylesheet">
  
    <script src="../node_modules/video.js/dist/video.min.js"></script>
    <script src="../node_modules/webrtc-adapter/out/adapter.js"></script>
  
    <script src="../dist/videojs.record.js"></script>
```
with:
```
    <link href="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.5.5/video-js.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/3.8.0/css/videojs.record.min.css" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.5.5/video.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/6.1.1/adapter.min.js"></script>
```
and got the same error.  Do these look like correct replacements?

**Comment by inyourcorner** [comment]
A little progress: I added:
```
    <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/3.8.0/videojs.record.js"></script>
```
Which looks better, but gives a slightly different web-rtc error.  So it looks like I'm still missing an import.  I'll dig into it more tonight but I think you're right about the imports.  Thanks for your help that's enough to help me for now!

**Comment by inyourcorner** [comment]
In case it's useful to anyone else later, this was the properly ordered (and non-duped 😉) import list:

```
    <link href="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.5.5/video-js.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/3.8.0/css/videojs.record.min.css" rel="stylesheet">

    <script src="https://cdn.WebRTC-Experiment.com/RecordRTC.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.5.5/video.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/6.1.1/adapter.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/3.8.0/videojs.record.js"></script>
```

**Comment by inyourcorner** [comment]
Thanks for everything, @thijstriemstra - keep up all your good work!

**Comment by jaydeep-vala** [comment]
** Error: plugin "eventTracking" does not exist **







 autoplay: true,
                controls: true,
                responsive: true,
                html5: {
                  hls: {
                    // withCredentials: true,
                  },
                  nativeTextTracks: false,
                },
              
                plugins: {
                    eventTracking: true
                  
                },
                userActions: {
                  hotkeys: (event: any) => {
                    if (event.which === 32) {
                      if (this.player.paused()) {
                        this.player.play();
                      } else {
                        this.player.pause();
                      }
                    }
                    if (event.which === 37) {
                      const backward = this.player.currentTime() - 10;
                      this.player.currentTime(backward);
                    }
                    if (event.which === 39) {
                      const forward = this.player.currentTime() + 10;
                      this.player.currentTime(forward);
                    }
                    if (event.which === 38) {
                      this.player.volume(this.player.volume() + 0.1);
                    }
                    if (event.which === 40) {
                      this.player.volume(this.player.volume() - 0.1);
                    }
                  },

**Comment by jaydeep-vala** [comment]
I tried the various solutions but still, it gives an error like  **Logging service: 
Message: plugin "eventTracking" does not exist 
Stack: Error: plugin "eventTracking" does not exist**

**Comment by thijstriemstra** [comment]
no idea what that plugin is you're talking about. Stop hijacking tickets!!
