### ISSUE TITLE
improve videojs-wavesurfer microphone plugin imports

### ISSUE THREAD

**Issue by thijstriemstra** [collab-project/videojs-record#405]
This requires videojs-wavesurfer v3.0 or newer.

So videojs-record 4.0 would stop using the `src: 'live'` option and use a config like this instead (note the `WaveSurfer.microphone.create` call):

```javascript
let player = videojs('myAudio', {
    controls: true,
    width: 600,
    height: 300,
    plugins: {
        wavesurfer: {
            debug: true,
            backend: 'WebAudio',
            waveColor: 'black',
            cursorWidth: 0,
            interact: false,
            hideScrollbar: true,
            plugins: [
                // enable microphone plugin
                WaveSurfer.microphone.create({
                    bufferSize: 4096,
                    numberOfInputChannels: 1,
                    numberOfOutputChannels: 1
                })
            ]
        },
        record: {
            audio: true,
            video: false,
            maxLength: 20,
            debug: true
        }
    }
});
```

This should move the import of the wavesurfer.js microphone plugin out of the videojs-record plugin and make it easier for the user to debug/fix that import in their own code.

**Comment by StevenPMX** [comment]
I need to mention that for Vue it needs a few changes. First, you need to import the Microphone plugin: 
`import Microphone from 'wavesurfer.js/dist/plugin/wavesurfer.microphone.min.js'`

Then instead of WaveSurfer.microphone.create it must be
`Microphone.create`

I don't know why this is not in the documentation, without this it does not work on Vue.

**Comment by thijstriemstra** [comment]
> I don't know why this is not in the documentation, without this it does not work on Vue.

It's because the documentation uses a video-only example with vue.js.

But I added them (commented out) to the guide in https://github.com/collab-project/videojs-record/commit/fa3f8d42b049d85d1aba7ebabfbcf4726db44ccb, see https://collab-project.github.io/videojs-record/#/frameworks/vue?id=application for update.
