### ISSUE TITLE
videojs-record allows to capture empty photo

### ISSUE THREAD

**Issue by GordonDrop** [collab-project/videojs-record#406]
## Description
Videojs-record allows to capture empty photo just after **start record** button was clicked.

## Steps to reproduce
1. Open https://collab-project.github.io/videojs-record/examples/image-only.html
2. click **start record** button
3. there will be short amount of time before viewport shows image from camera(viewport shows purple background). That's when **CameraButton** should be clicked

### Actual
Image that contains only empty pixels is captured.

### Expected
Capture empty image shouldn't be allowed. Possible solution is disable button until camera is ready.

### Error output
No errors.

### versions
v3.8.0

#### videojs
v7.6.5

#### browsers
Version 77.0.3865.90 (Official Build) (64-bit)

#### OSes
MacOS

Please let me know if any additional info is required.

**Comment by thijstriemstra** [comment]
not sure if this browser thing is something that can be worked around, but I'll check it out at some point.

**Comment by thijstriemstra** [comment]
Looks like waiting for the `onplaying` event should fix it (https://stackoverflow.com/questions/36091400/is-it-possible-to-detect-when-the-camera-is-on-ready-with-getusermedia). Will test later.

**Comment by thijstriemstra** [comment]
can you test #427 @GordonDrop, seems to work ok now.

**Comment by GordonDrop** [comment]
@thijstriemstra It works, can't reproduce. Thanks 😊
