### ISSUE TITLE
Stop go to selected browser tab

### ISSUE THREAD

**Issue by onyxnl** [collab-project/videojs-record#410]
Hi,

I want screen share by using browser tab. My problem is I dont want to go selected tab and remain. How can I do that?

I am using on php,jquery,iframe and html

**Comment by thijstriemstra** [comment]
I'm not sure if this is possible. You also don't specify what browser, please ask on stackoverflow or a forum dedicated to the browser you're using.

**Comment by onyxnl** [comment]
I am using chrome browser.
VIDEOJS: Using video.js 7.6.5 with videojs-record 3.8.0 and recordrtc [5.5.9]
