### ISSUE TITLE
TypeError: "component is undefined"

### ISSUE THREAD

**Issue by jarkt** [collab-project/videojs-record#411]
Since the update from 3.7.1 to 3.8.0 I get the following error in firefox on page load.
But it seems all to work fine...

```
VIDEOJS: ERROR: TypeError: "component is undefined"
    addChild video.js:3539
    setupUI videojs.record.js:218
    func video.js:1997
    dispatcher video.js:1811
    trigger video.js:1947
    trigger$1 video.js:2832
    triggerReady video.js:3784
    timeoutId video.js:4438
video.js:80
    LogByTypeFactory video.js:80
    error video.js:268
    dispatcher video.js:1813
    trigger video.js:1947
    trigger$1 video.js:2832
    triggerReady video.js:3784
    timeoutId video.js:4438
```

**Comment by Ravelin** [comment]
I am also getting this issue but only on firefox.  It is also auto starting the recording process on firefox only.

VIDEOJS: ERROR: TypeError: "component is undefined"
    addChild video.es.js:3546
    setupUI videojs.record.js:218
    func video.es.js:2004
    dispatcher video.es.js:1818
    trigger video.es.js:1954
    trigger$1 video.es.js:2839
    triggerReady video.es.js:3791
    timeoutId video.es.js:4445
video.es.js:87:47
    LogByTypeFactory video.es.js:87
    error video.es.js:275
    dispatcher video.es.js:1820
    trigger video.es.js:1954
    trigger$1 video.es.js:2839
    triggerReady video.es.js:3791
    timeoutId video.es.js:4445

Any solutions? we can't be the only two getting his problem

**Comment by thijstriemstra** [comment]
@Ravelin @jarkt what videojs-record config, what browser/os?

**Comment by Ravelin** [comment]
Firefox Developer Edition
MacOS/Windows

      options: {
        controls: true,
        controlBar: {
          fullscreenToggle: false,
          volumePanel: false,
          cameraButton: false,
          recordToggle: false,
          playToggle: true
        },
        width: 780,
        height: 600,
        plugins: {
          record: {
            audio: true,
            fluid: true,
            maxLength: 180,
            video: {
              framerate: {
                ideal: 30,
                max: 60
              },
              width: 780,
              height: 600
            },
            hotKeys: true,
            frameWidth: 780,
            frameHeight: 600,
            videoMimeType: "video/mp4"
          }
        }
      }

**Comment by jarkt** [comment]
```
{
  "controls": true,
  "fluid": false,
  "width": 640,
  "height": 480,
  "plugins": {
    "record": {
      "maxLength": 15,
      "audio": true,
      "debug": true,
      "video": true,
      "videoMimeType": "video/webm;codecs=vp8"
    }
  }
}
```

**Comment by thijstriemstra** [comment]
what version of video.js?

**Comment by jarkt** [comment]
> what version of video.js?

```
├─ recordrtc@5.5.8
├─ video.js@7.6.5
│  ├─ @babel/runtime@^7.4.5
│  ├─ @videojs/http-streaming@1.10.6
│  ├─ global@4.3.2
│  ├─ global@4.3.2
│  │  ├─ min-document@^2.19.0
│  │  └─ process@~0.5.1
│  ├─ keycode@^2.2.0
│  ├─ process@0.5.2
│  ├─ safe-json-parse@4.0.0
│  ├─ videojs-font@3.2.0
│  ├─ videojs-vtt.js@^0.14.1
│  └─ xhr@2.4.0
├─ videojs-font@3.2.0
├─ videojs-record@3.8.0
│  ├─ recordrtc@>=5.5.8
│  ├─ video.js@>=6.2.7
│  ├─ videojs-wavesurfer@>=2.9.0
│  └─ webrtc-adapter@>=7.2.8
├─ videojs-vtt.js@0.14.1
│  └─ global@^4.3.1
├─ videojs-wavesurfer@2.11.0
│  ├─ video.js@>=6.0.0
│  └─ wavesurfer.js@>=3.1.0
```

> can you reproduce it with https://collab-project.github.io/videojs-record/examples/audio-video.html?

No, the linked page works fine.

**Comment by thijstriemstra** [comment]
> No, the linked page works fine.

can you recreate it with a simple webpack build (see wiki)?

**Comment by Ravelin** [comment]
Still getting this issue, the linked page works fine. The error only occurs on Firefox, chrome doesn't seem to be affected.  I've tried delaying videojs until the page has fully loaded then rendering the recorder and the problem still persists.

**Comment by thijstriemstra** [comment]
@Ravelin can you recreate it with a simple webpack build (see wiki)?

**Comment by Ravelin** [comment]
@thijstriemstra Sorry for the delay been on other projects will attempt this this afternoon and get back to you with my results

**Comment by jarkt** [comment]
For me the problem concerns only a project in development. Other than before I will use it with Vue.js and so I will import it in another way. So the issue is (currently) done for me, because the example page is working fine. Thx.

**Comment by hangloos** [comment]
I came across this error as well. I was able to fix it by adding pictureInPictureToggle: true in the controlBar options. Here are my defaultOptions

`const defaultVideoJsOptions = {
  controls: true,
  controlBar: {
    fullscreenToggle: false,
    deviceButton: false,
    volumePanel: false,
    recordToggle: false,
    cameraButton: false,
    pictureInPictureToggle: true,
  },
  fluid: false,
  autoMuteDevice: true,
  height: 90,
  width: CONTENT_WIDTH,
  plugins: {
    wavesurfer: {
      src: 'live',
      waveColor: '#424242',
      progressColor: '#424242',
      cursorColor: '#424242',
      barWidth: 1,
      barGap: 2,
      height: 60,
      debug: true,
      cursorWidth: 0,
      msDisplayMax: 1,
      hideScrollbar: true,
    },
    record: {
      video: false,
      audio: true,
      audioMimeType: 'audio/webm',
      audioRecorderType: RecordRTC.StereoAudioRecorder,
      audioChannels: 1,
      convertEngine: '',
      maxLength: 1800, // max 30 minutes
      timeSlice: 2000,// 60000, // timestamp trigger every minute
      msDisplayMax: 1,
      height: 60,
      debug: true
    }
  }
};`

**Comment by Ravelin** [comment]
Adding pictureInPictureToggle: true solved my issue too

**Comment by thijstriemstra** [comment]
thanks for the feedback @hangloos, I'll take a look.

**Comment by alienpavlov** [comment]
I've faced the same issue and @hangloos' advice `pictureInPictureToggle: true` does work for me, but I don't really need PIP button..

here is the exact error:
![image](https://user-images.githubusercontent.com/2844990/69436153-e3961f80-0d51-11ea-98fd-822d0aab3315.png)

and here is the place where `this.player.pipToggle` is **undefined**
![image](https://user-images.githubusercontent.com/2844990/69435988-9619b280-0d51-11ea-85ed-22a02edbac4f.png)

my options:
`{
  controls: true,
  width: 320,
  height: 240,
  fluid: false,
  plugins: {
    record: {
      audio: true,
      video: true,
      maxLength: 300,
      debug: true
    }
  },
  controlBar: {
    fullscreenToggle: false,
    volumePanel: false,
    pipToggle: false,
    deviceButton: false,
    pictureInPictureToggle: false
  }
}`

I hope it helps
