### ISSUE TITLE
the browser does not support navigator.mediaDevices.getDisplayMedia

### ISSUE THREAD

**Issue by onyxnl** [collab-project/videojs-record#412]
## Description
I encounter this issue.

### Error output
the browser does not support navigator.mediaDevices.getDisplayMedia

#### videojs
VIDEOJS: Using video.js 7.6.5 with videojs-record 3.8.0 and recordrtc 5.5.9

#### browsers
Chrome (Version 77.0.3865.120)
#### OSes
Window 64bit

**Comment by thijstriemstra** [comment]
that would be a pretty extreme bug; I will take a look.

**Comment by thijstriemstra** [comment]
I cannot reproduce this, closing.
