### ISSUE TITLE
Control bar flickering in Safari mobile

### ISSUE THREAD

**Issue by Gha4** [collab-project/videojs-record#413]
## Description
There is constant flickering/flashing at the control bar before record button is pressed. It disappear when record button is pressed.

Another user make mention of it here: https://github.com/collab-project/videojs-record/issues/370

> Also of note, there is really substantial flickering of the control bar, such that it appears I may only be getting a few frames/sec refresh. 

## Steps to reproduce
I use: https://collab-project.github.io/videojs-record/examples/audio-video.html
I only added saving recorded video to a folder using jquery

## Additional Information

This configuration does not work properly with Safari: https://github.com/collab-project/videojs-record/issues/407 . It shows a still/not moving image image while recording but can playback a video shifted 90 degrees left.

This configuration which i use now record successfully but has no playback, has flickering at control bar and video is rotated 90 degrees left. https://collab-project.github.io/videojs-record/examples/audio-video.html

**Comment by thijstriemstra** [comment]
I am not sure where the flickering comes from but I'll take a look at it for videojs-record 4.0.

**Comment by pwob** [comment]
Meanwhile you can add a transform style `<div data-vjs-player style={{ WebkitTransform: 'translate3d(0, 0, 0)' }}>` for temporary fix.

**Comment by thijstriemstra** [comment]
I came across this in [release notes for Safari Tech Preview 97](https://webkit.org/blog/9672/release-notes-for-safari-technology-preview-97/):

- Fixed image flashing with `transform: rotate` animation ([r252486](https://trac.webkit.org/changeset/252486/webkit/))

Not sure if it's related to this specific issue but indicates to me they have more issues with 'flickering' in WebKit.

Thanks for the workaround @pwob, I think I'll add it to the videojs-record css.

**Comment by thijstriemstra** [comment]
I marked this is a bug but it's actually a browser issue. If someone has a good workaround for this, please let me know. I tried a few things but couldn't make the flickering go away.

**Comment by FrostyJet** [comment]
For someone still struggling with this issue.
This chunk of code saved my life. This applies to the video itself.

.video-js .vjs-tech {
    -webkit-perspective: 1000;
}

**Comment by M-Annis** [comment]
using this example: https://collab-project.github.io/videojs-record/demo/audio-video.html

control bar is still flickering on iPhone safari, any update?

Thanks in advance

**Comment by thijstriemstra** [comment]
@M-Annis try adding this:

```css
.video-js .vjs-tech {
-webkit-perspective: 1000;
}
```

does it fix the flickering?

**Comment by thijstriemstra** [comment]
> does it fix the flickering?

The suggested fix in the previous comment fixed the flickering but it pushed the video to foreground, overlapping the control bar.

**Comment by LarryBarker** [comment]
I'm also experiencing a number of issues on mobile. The flickering still exists, and playback doesn't seem to be working. After I stop recording, and attempt to play the video, it's actually just showing the camera stream again and not playing back anything.

**Comment by thijstriemstra** [comment]
Related webkit ticket: https://bugs.webkit.org/show_bug.cgi?id=184025

**Comment by LarryBarker** [comment]
Thanks for that @thijstriemstra. I know you've put a lot of time into this project so thank you for making it available.

Just curious if you have issues with playback on iOS Chrome and Safari?

I seem to be able to record but playback just streams the device again, and the audio does some weird echoing thing.

**Comment by thijstriemstra** [comment]
> Just curious if you have issues with playback on iOS Chrome and Safari?

Oh yes, for years ;)

I am working on ios/safari testing today. Will be testing with ios 14.4 (anyone know what safari version that runs?) and macOS safari 14.0.2 and Safari Technology Preview 119 (Safari 14.1, WebKit 15611.1.10.1).

**Comment by LarryBarker** [comment]
I’m not the greatest JS dev but what I can do to help?

**Comment by thijstriemstra** [comment]
> I’m not the greatest JS dev but what I can do to help?

Test upcoming release, 4.2.0.

**Comment by thijstriemstra** [comment]
> I seem to be able to record but playback just streams the device again, and the audio does some weird echoing thing.

I opened #552 for that.

**Comment by thijstriemstra** [comment]
I tested audio+video with Mobile Safari on iOS 14.4 and @FrostyJet's workaround fixed it here:

```html
<video id="recorder" style="-webkit-perspective: 1000;"/>
```

No more control bar flickering!
