### ISSUE TITLE
Every blob file except the first blob file generated at "timestamp" doesn't work

### ISSUE THREAD

**Issue by grigull** [collab-project/videojs-record#415]
## Description
When trying to stream the blob files generated using the "timestamp" function all the blobs are not working except for the first blob generated. The files are definitely slightly different from the first blob generated, as my OS can't detect any information about the file other than it being a webm file. Things/theories i have checked and tested.

1. It has nothing to do with the the first blob, but rather the first blob that is attempted to be saved. Unsuccessful - Still appears that after skipping a save of the first blob and saving the second blob, the second blob is still broken. 

2. Various timestamps - Timestamp length appears to be unrelated, have tried 2-5-20 seconds and all of them have the same issue. 

3. I tried both locally saving files as well as streaming the blob files to a server. In both cases, every other blob than the first appears too broken.

4. Saving the first blob even after the second-third blob has been created. The first blob still works perfectly. 

## Steps to reproduce
Follow the standard instructions to setup in react https://github.com/collab-project/videojs-record/wiki/React, use the FileSaver package to save the blobs locally and add the following code to the App.js file. 

```
    this.player.on("timestamp", () => {
      console.log("current timestamp: ", this.player.currentTimestamp);
      console.log(
        this.player.allTimestamps
      );
      const blobLength = this.player.recordedData.length - 1;
      const blob = this.player.recordedData[blobLength];
      FileSaver.saveAs(blob, `blobs/test${blobLength}.webm`);

      console.log("array of blobs: ", this.player.recordedData);
      console.log("---------------------------------------");
    });
```

### Error output
No detected errors when videojs is running.
Video player error: No Valid Frames decoded before end of stream.

#### videojs
6.10.0
#### browsers
Tested with extensions disabled on Chrome: 77.0.3865.90
Tested with Brave browser: Chromium: 77.0.3865.90

**Comment by thijstriemstra** [comment]
Looks like a duplicate of #376

**Comment by grigull** [comment]
I concur this is a duplicate.
