### ISSUE TITLE
Stuck in login password when tryed to run as instructed.

### ISSUE THREAD

**Issue by duodecimo** [collab-project/videojs-record#416]
I did (ubuntu 18.04 lts):
git clone https://github.com/collab-project/videojs-record.git
cd videojs-record/
npm install
npm run build
npm run start
when I point my browser (chrome, newest) to:
http://localhost:8080/examples/audio-video.html
It asks for login and password, neither of them known to me.
I'm not sure if it is an npm issue or videosj.
Any help would be appretiated.

**Comment by thijstriemstra** [comment]
that's odd, you probably already have something else running on port 8080. webpack-dev-server automatically increases the port number when 8080 is in use, so try http://localhost:8081 instead.

**Comment by duodecimo** [comment]
Perfect, this is exactly what was happening.
Thank you for your help, I was already able to test recording a video with soud.
