### ISSUE TITLE
Iframe in mobile issue

### ISSUE THREAD

**Issue by amy111patel** [collab-project/videojs-record#418]
Hello Team.

I have implemented one  functionality which is working fine on each of the browser available on any operating system on desktop pc.
But when I test It on google chrome ( version 78.0.39+) android mobile  browser it doesn't.

We have setup the recordjs module on one domain and accessing it on another domain inside an iframe. On all the desktop browsers it is working fine but in google chrome mobile it isn't  popup to give device camera permission.

In the center of recordjs video section, when we click it pops up for camera device permission, but in mobile not. The google chrome i am using is latest version, Please check.

Thanks

**Comment by thijstriemstra** [comment]
@amy111patel are you using https? can you reproduce it with any of the online examples?

**Comment by amy111patel** [comment]
Hello @thijstriemstra 

Yes I am using HTTPS, 

Steps to reproduce :
1. Setup 2 domain
2. Create an HTML I-frame element 
3. Setup videojs on one domain and call it through iframe on the another domain.

video js will work on all the browser and pop's up to allow camera device, but in android google chrome it doesn't work in iframe just the green background window display, But when i open the domain where i setup the videojs separately it will work on all the browser mobile+desktop.

Please check

**Comment by amy111patel** [comment]
Hello @thijstriemstra 

Any update please.

Thanks

**Comment by thijstriemstra** [comment]
can you not do that? if there's an update you'll see an update.

**Comment by thijstriemstra** [comment]
there's a statement about iframe/getUserMedia here: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Privacy_and_security

```
Only a window's top-level document context for a valid origin can even request permission to use 
getUserMedia(), unless the top-level context expressly grants permission for a given <iframe> to do so
 using Feature Policy. Otherwise, the user will never even be asked for permission to use the input 
devices.
```

You should check the `Feature Policy security management feature of HTTP` as mentioned on above link and try setting the `allow` attribute of the iframe. I've never encountered this and curious if it works @amy111patel 

```html
<iframe src="https://mycode.example.net/etc" allow="camera;microphone">
</iframe>
```

**Comment by thijstriemstra** [comment]
No feedback, closing.
