### ISSUE TITLE
how can i share my screen to other pc/handphone device?

### ISSUE THREAD

**Issue by haohuancheng** [collab-project/videojs-record#420]
## Description
I want to brow my live screen on another pc device, how to do? The demo on this site is only share the screen in local device.

### Expected
if my pc is 192.168.1.101,  the other pc is 192.168.1.102, can i see my 101 pc screen in 102 browser?

**Comment by thijstriemstra** [comment]
I've never tried webrtc, will take a look at some point.

**Comment by danyalUb** [comment]
Hi @thijstriemstra. Did you find some time to look into this? 

P.S: I know its not easy to maintain open source projects and cater all new requests. Please let me know if I can be of any help. Also if you can guide me in the right direction so I can try to do it myself. Thanks :)

**Comment by thijstriemstra** [comment]
@danyalUb can you find a simple webrtc server, preferrably node.js based, that shows how to stream one video stream to another machine?

**Comment by danyalUb** [comment]
Sure thing. I'll look into it. Thanks

**Comment by danyalUb** [comment]
[https://github.com/priologic/easyrtc](this one) looks interesting. I'm sorry if this is not what we are looking for.

**Comment by thijstriemstra** [comment]
if you can show an example that connects to a video stream, please share here.

**Comment by danyalUb** [comment]
Alright. I am looking into this now. I'll share as soon as I find something.

**Comment by Viruss98** [comment]
you can get the MediaStream while recording and send it into a peer with ice and signaling server (using webrtc) :D But it can be delay for 1- 3 seconds depend on your server.
