### ISSUE TITLE
I want to flip the camera on a button click and re-record the video

### ISSUE THREAD

**Issue by naveedabbas** [collab-project/videojs-record#421]
## Description
I am using this pluign to record live videos on my website, it is working fine with the front cam on both desktop and mobile devices. and if I use the "facingMode: ("environment")" it open the rar camera on mobile devices just fine.
What I want to achieve is to add a new button and on button click, I want to flip the camera from front to rear and vise versa.

## Steps to reproduce
Started a new video record with facingMode : user
on a button click I used the below code
---------------------------------
player.options_.plugins.record.video.facingMode = 'environment';
player.record().loadOptions();
and
player.record().loadOptions({
video: {
facingMode: 'environment'
}
});

### Expected
Expected result was to switch the camera on mobile devices from front to rear and vise versa

### Actual
Nothing happened, this only shows the front camera and not switching to the rear camera on mobile devices

### Error output
No errors

## Additional Information
I tried this by destroying the player and reinitializing it with updated options, still it is working only with the facingMode that is setup for the first time, means in that case it is destroying and switching facingMode but that don't work.
#### videojs
Latest version
#### browsers
Chrome on android
#### OSes
Android

**Comment by vendramini** [comment]
I'm facing the same problem here: https://github.com/collab-project/videojs-record/issues/394
Could you close your issue and continue on mine? So we can solve the problem together.

**Comment by naveedabbas** [comment]
The same issue is in discussion here https://github.com/collab-project/videojs-record/issues/394 I am going to clost this one.
