### ISSUE TITLE
Opus Codec not supported by AWS Transcoder! 

### ISSUE THREAD

**Issue by nzee** [collab-project/videojs-record#423]
## Description
Recorded Video's audio codec is always Opus and the same codec is not supported by the transcoding API I am using currently. Wondering if this library supports any other audio codec, apart from Opus.

## Steps to reproduce
I am using Videojs-record with following record options
`
plugins: {                        
  record: {
                            audio: true,                                      
                            video: true,
                            debug: true,
                            fluid: true,
                            maxLength: 60                    
                        }
                  }
`

### Expected
Its working as expected but I want to force audio alone to be encoded with a different codec so that I can transcode the videos via AWS MediaConvert which is currently not supporting Opus Audio Codec.

Here are all the supported AWS Input Audio codecs
https://docs.aws.amazon.com/mediaconvert/latest/ug/reference-codecs-containers-input.html

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Videojs : 7.6.6 | Videojs-Record : 3.8.0 | RecordRTC : 5.5.8
#### browsers
I am testing on Chrome 
disabled**.
#### OSes
Android and Linux/Ubuntu

**Comment by thijstriemstra** [comment]
sure, try wav or mp3. See audio plugins: https://github.com/collab-project/videojs-record/wiki/Plugins#audio

**Comment by nzee** [comment]
@thijstriemstra most if these Audio plugins are supported for Audio only recordings. I am looking for Video & Audio solution. 

If it's possible to capture audio and video separately via this library?

**Comment by thijstriemstra** [comment]
No (not yet). Why not use `ffmpeg` on AWS, or use the `ffmpeg` converter plugin for videojs-record on the clientside to convert it into any type you want?
