### ISSUE TITLE
How to do add my logo image when record video via my webcam

### ISSUE THREAD

**Issue by AngelosR** [collab-project/videojs-record#424]
Hi How are you. I am AngelosR.
Thanks for you videojs plugin.
I want to add my logo image when record video via my webcam using videojs-record.
I want to record video together my logo image.
If possible, please explain how to implement it in Vue.js. 
But, The implementation in vanilla js is fine too.
I am waiting your solution.
Thanks and Regard.

**Comment by thijstriemstra** [comment]
Duplicate of #288
