### ISSUE TITLE
Can i use image + audio + video options? 

### ISSUE THREAD

**Issue by ahmer110** [collab-project/videojs-record#431]
## Description
I want the player with image and record button. So it's up to the user either take the snapshot or record the video. it's possible or not?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
#### OSes
what platforms (operating systems and devices) are affected?

**Comment by thijstriemstra** [comment]
why did you close the ticket? maybe that info can help others..
