### ISSUE TITLE
this.mediaElement.src is undefined

### ISSUE THREAD

**Issue by tacman** [collab-project/videojs-record#435]
## Description
Example programs using the camera fail in Firefox.

## Steps to reproduce
clone the example repo, install (npm install), build (npm run build)  then start the npm server (npm run start), as described in the the instructions at https://github.com/collab-project/videojs-record#examples

Then go to https://127.0.0.1:8003/examples/audio-only.html 

The page loads, but when you attempt to start the microphone or camera (it happens on other pages, too), you get (in the js console)

```
VIDEOJS: ERROR: TypeError: "this.mediaElement.src is undefined"
    removeRecording webpack://VideojsRecord/./src/js/videojs.record.js?:1031
    startVideoPreview webpack://VideojsRecord/./src/js/videojs.record.js?:1127
    start webpack://VideojsRecord/./src/js/videojs.record.js?:632
    handleClick webpack://VideojsRecord/./src/js/controls/record-toggle.js?:72
    dispatcher http://localhost:8080/node_modules/video.js/dist/video.min.js:12
video.min.js:12:695
```

Latest version of this library (clone master on Jan 22, 2020).

![image](https://user-images.githubusercontent.com/619585/72920036-7fbeb180-3d16-11ea-8629-df87a220f3f7.png)

**Comment by thijstriemstra** [comment]
@tacman you are visiting https://127.0.0.1:8003/examples/audio-only.html but the exmaple server runs on http://localhost:8080/ If you followed the instructions you should be testing with http://localhost:8080/

**Comment by thijstriemstra** [comment]
No feedback, closing.
