### ISSUE TITLE
frameWidth & frameHeight not reflecting

### ISSUE THREAD

**Issue by nzee** [collab-project/videojs-record#436]
## Description
I have set frameWidth and frameHeight to 360x480 yet the recording area is not reflecting the set values. Instead I get a black bar on top and the bottom of the video. 

## Steps to reproduce
Here are the options that I have

```
           options: {
                    controls: true,
                    autoplay: false,
                    fluid: false,
                    loop: false,
                    width: 360,
                    height: 480,
                    controlBar: {
                        // hide fullscreen and volume controls
                        fullscreenToggle: false,
                        volumePanel: false,
                    },
                    plugins: {
                        // configure videojs-record plugin
                        record: {
                            audio: true,
                            video: true,
                            debug: true,
                            fluid: true,
                            maxLength: 60,
                            frameWidth: 360,
                            frameHeight: 480                            
                        }
                    }
            }
```

### Expected
Was expecting the entire width and heigh specified on frameWidth & frameHeight to reflect as recording dimensions.

### Actual
Attaching image here
[https://i.imgur.com/DH4uMQ1.jpg](https://i.imgur.com/DH4uMQ1.jpg)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Using video.js 7.6.6 with videojs-record 3.8.0 and recordrtc 5.5.8
#### browsers
Latest Chrome
#### OSes
Ubuntu 18.04

**Comment by nzee** [comment]
@thijstriemstra gentle reminder. :)

**Comment by thijstriemstra** [comment]
see #408

**Comment by thijstriemstra** [comment]
@nzee make sure your camera supports the resolution you're asking for. I tested the config below with a camera that supports 640x480:

```javascript
var options = {
    controls: true,
    width: 640,
    height: 480,
    fluid: false,
    controlBar: {
        fullscreenToggle: false,
        volumePanel: false
    },
    plugins: {
        record: {
            audio: true,
            video: {
                // video constraints: set resolution of camera
                minWidth: 640,
                minHeight: 480
            },
            // dimensions of captured video frames
            frameWidth: 640,
            frameHeight: 480,
            maxLength: 10,
            debug: true
        }
    }
};
```

And result has no bars:

![Screenshot from 2020-02-02 21-55-40](https://user-images.githubusercontent.com/305679/73615285-cf4e8880-4606-11ea-8b49-ccf0b5bf9d7b.png)
