### ISSUE TITLE
normal player with empty src still shows loading spinner when clicked play button

### ISSUE THREAD

**Issue by Monkey-D-Pixel** [collab-project/videojs-record#437]
## Description
As stated in title.

## Steps to reproduce
0. include both video.js and this plugin, all latest
1. create a normal player instance, with no src
2. click play button

codepen available [here](https://codepen.io/monkey-d-pixel/pen/ExazBRN?editors=1010)

### Expected
the player should not show a loading spinner, as it does when this plugin is not included.

### Actual
the player shows a loading spinner

#### videojs
7.7.4
#### browsers
chrome 79
firefox 72
#### OSes
Manjaro Linux 18

**Comment by thijstriemstra** [comment]
you don't actually use the plugin in your example, you're only including it:

```javascript
var player = videojs('my_video');
```

That's fine though, but you are adding the 'big play button' which this plugin doesn't use:

```
// customize controls
this.player.bigPlayButton.hide();
```

And that button triggers an early `play` call on the player: https://github.com/videojs/video.js/blob/master/src/js/big-play-button.js#L46

you expected:

> the player should not show a loading spinner, as it does when this plugin is not included.

And looks like the import/definition of:

```javascript
// monkey-patch play (#152)
Player.prototype.play = function play() {
    let retval = this.techGet_('play');
    // silence errors (unhandled promise from play)
    if (retval !== undefined && typeof retval.then === 'function') {
        retval.then(null, (e) => {});
    }
    return retval;
};
```

in https://github.com/collab-project/videojs-record/blob/3.9.0/src/js/videojs.record.js#L35 screws things up.

I'll take a look.

**Comment by thijstriemstra** [comment]
@Monkey-D-Pixel can you give PR #442 a try?

**Comment by Monkey-D-Pixel** [comment]
> @Monkey-D-Pixel can you give PR #442 a try?

Yes, seems all good. Thanks!
