### ISSUE TITLE
Iphone audio only not recording version 12.4.3 (Model Iphone 6)

### ISSUE THREAD

**Issue by subbulakshmi-techy** [collab-project/videojs-record#438]
## Description
Audio Only not working  using any of the library files mentioned i have tried all these

https://collab-project.github.io/videojs-record/examples/audio-only-lamejs.html
https://collab-project.github.io/videojs-record/examples/audio-only-mp3.html
https://collab-project.github.io/videojs-record/examples/audio-only-ogg.html
https://collab-project.github.io/videojs-record/examples/audio-only-opus.html
https://collab-project.github.io/videojs-record/examples/audio-only-recorderjs.html
https://collab-project.github.io/videojs-record/examples/audio-only.html

I tried with recordrtc directly it works fine

https://www.webrtc-experiment.com/RecordRTC/simple-demos/audio-recording.html

## Steps to reproduce

Open safari in  Iphone 6 start recording 

https://collab-project.github.io/videojs-record/examples/audio-only.html

### Expected
Audio to be recorded with waves and return recorded audio blob. 

### Actual
No voice has been recorded, It is neither  recording nor waves are generated 

### Error output
No error no audio

## Additional Information

**Without Enabling Media recorder in safari settings this has to be recorded.**, which is possible through record rtc whic is internally used in our project.

### versions
I checked in 
Iphone model - 6 && 6s
IOS version - 12.4.3, 12.4

Safari version - 12.1

#### videojs
what version of videojs does this occur with?

v 3.9.0

Changed recordrtc version to 5.5.9 also.

#### browsers

Safari 
Safari version - 12.1
All extensions are disabled.

#### OSes

IOS-> Iphone

**Comment by thijstriemstra** [comment]
Tested it with the same configuration and device and for some reason passing an `audioRecorderType` of `StereoAudioRecorder` isn't working, e.g.

```javascript
options.plugins.record.audioRecorderType = StereoAudioRecorder;
options.plugins.record.audioSampleRate = 44100;
options.plugins.record.audioBufferSize = 4096;
options.plugins.record.audioChannels = 2;
```

Will look into it.

**Comment by rdurish** [comment]
@thijstriemstra any updates on this, I'm running into this issue as well.

**Comment by thijstriemstra** [comment]
no not yet, will try to look at it on the weekend.

**Comment by rdurish** [comment]
@thijstriemstra anything I can do to help?  Is there some settings I can set in my project that will make this work?

**Comment by thijstriemstra** [comment]
try to figure out what the difference is between our implementation and https://www.webrtc-experiment.com/RecordRTC/simple-demos/audio-recording.html

**Comment by numerized** [comment]
Hello here, I was having issue when I access the stream to display a waveform too on other libs.
I would love to have waveform audio displayed on IOS too, any news guys ?

**Comment by thijstriemstra** [comment]
> I tried with recordrtc directly it works fine
> https://www.webrtc-experiment.com/RecordRTC/simple-demos/audio-recording.html

It depends on what you call fine. That demo shows a horrible UI with an even worse user experience. These workarounds are needed for Safari but are simply too hacky and not viable to implement in videojs-record. 

Safari, how did you ever become so sh*tty..

**Comment by thijstriemstra** [comment]
I am not going to support Safari < 14 anymore, but will test this on Mobile Safari on iOS 14.4.
