### ISSUE TITLE
Successive Image captures on Safari IOS results in same image after first few are taken.

### ISSUE THREAD

**Issue by rdurish** [collab-project/videojs-record#439]
## Description
Successive Image captures on Safari IOS results in same image after first few are taken.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

```javascript
var optionsImage = {
            controls: true,
            width: 640,
            height: 480,
            controlBar: {
                volumePanel: false,
                fullscreenToggle: false
            },
            plugins: {
                record: {
                    image: true,
                    audio: false,
                    debug: true,
                    imageOutputType: 'dataURL',
                    imageOutputFormat: 'image/png',
                    imageOutputQuality: 0.70
                }
            }
        };

var playerImage = videojs('myVideo', optionsImage, function () {
            // print version information at startup
            var msg = 'Using video.js ' + videojs.VERSION +
                ' with videojs-record ' + videojs.getPluginVersion('record') +
                ' and recordrtc ' + RecordRTC.version;
            videojs.log(msg);
            $('#buttonGroup2').hide();
            //playerImage.record().getDevice();
            playerImage.record().enumerateDevices();
        });

        var playerVideo = videojs('myVideoFinal', optionsVideo);


        $('#myAudio').hide();
        $('#myVideoFinal').hide();
            $('#unrappWrap').hide();


        playerImage.on('deviceError', function () {
            console.log('device Image error:', player.deviceErrorCode);
            alert('device Image error:' + error);
        });

        playerImage.on('error', function (element, error) {
            console.error(error);
            alert(error);
        });
        playerImage.on('enumerateReady', function () {
            console.log('Enumerate Ready (IMAGE)...');
            playerImage.record().getDevice();
            if (record) {
                playerImage.record().start();
            }
        });
        playerImage.on('startRecord', function () {
            console.log('started Image recording!');
        });
        playerImage.on('finishRecord', function () {
            // the blob object contains the recorded data that
            // can be downloaded by the user, stored on server etc.
            console.log('finished image: ', playerImage.recordedData);
            // Let handler know we are done...
            var formData = new FormData();
            formData.append('file', dataURLToBlob(playerImage.recordedData));
            formData.append('id', id);  //Replace with real ID later...
            formData.append('last', '0');
            formData.append('type', 'R');
            y++;
            formData.append('count', y);

            $.ajax({
                url: "/admin/ws/WebApp2019.ashx",
                type: "POST",
                data: formData,
                processData: false,
                contentType: false,
                success: function (result) {
                    console.log('posted: ', y);
                    console.log('result reaction image: ', result);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    console.log(xhr.status, ': ', thrownError);
                    console.log(xhr.responseText);
                }
            });

            setTimeout(shouldRecord, 10);
            

        });

        function shouldRecord() {
            if (record) {
                // Make another image snap...
                playerImage.record().retrySnapshot();
                //playerImage.record().enumerateDevices();
                playerImage.record().start();
            }
        }
```

## Results
After first 5-6 images it starts to be the same screen shot over and over...same code works fine when on in safari ios.
### Expected
To be a new screenshot everytime it is executred.

### Actual
After first 5-6 images it starts to be the same screen shot over and over...same code works fine when on in safari ios.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
Using video.js 7.6.6 with videojs-record 3.9.0 and recordrtc 5.5.8
#### browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
IOS - Safari
#### OSes
what platforms (operating systems and devices) are affected?
IOS - Safari

**Comment by thijstriemstra** [comment]
> After first 5-6 images it starts to be the same screen shot over and over...same code works fine when on in safari ios.

It works fine in iOS? I thought that was the OS with problems according to this ticket?

This example uses a lot of different api's, like `enumerateDevices`, which makes it hard to track down the bug. Can you make a minimal example that reproduces it @rdurish?

**Comment by rdurish** [comment]
Sorry that should say NON-IOS devices.  I'm having trouble editing.  I will put together an example here shortly.

**Comment by rdurish** [comment]
Simple example.  Confirmed working on PC not on phone (Safari).
https://1drv.ms/u/s!AtiXKZF_BIouhtouz8UA4pVK2RcrvA?e=T8jTWv

**Comment by rdurish** [comment]
@thijstriemstra anything else I can do to help?

**Comment by thijstriemstra** [comment]
Not sure. I will try reproducing this on the weekend and look into a fix.

**Comment by rdurish** [comment]
Any updates? Trying to do this to be able to do video recording on iOS by taking multiple screenshots.

**Comment by thijstriemstra** [comment]
@rdurish i tested on an iPhone 6 with the simplest example: https://collab-project.github.io/videojs-record/examples/image-only.html

And could not reproduce it.. can you, with that example?

**Comment by rdurish** [comment]
I will try it out....did you try my example I made for you?  Do you want me to host it for you so it is easier to try?

**Comment by thijstriemstra** [comment]
> Do you want me to host it for you so it is easier to try?

shouldn't be necessary if you can reproduce it with that example..

**Comment by rdurish** [comment]
> @rdurish i tested on an iPhone 6 with the simplest example: https://collab-project.github.io/videojs-record/examples/image-only.html
> 
> And could not reproduce it.. can you, with that example?

@thijstriemstra 
I wasn’t able to reproduce with that link. My guess based on that is it is a timing issue? I call resetSnap then start back to back...maybe I need a slight delay? Your thoughts?

**Comment by thijstriemstra** [comment]
your code contains:

```javascript
// Delay to take next snapshot...
setTimeout(shouldRecord, 10);
```

which, apparently, is way too short. Since you're using jQuery, maybe try the [imagesloaded](https://github.com/desandro/imagesloaded) jquery plugin and only record again as soon as the image is ready.


```javascript
$('#output1 img').imagesLoaded( function() {
  // image has loaded, now record again...
});
```

I also noticed you call both retry and start, e.g.

```javascript
// Make another image snap...
playerImage.record().retrySnapshot();
playerImage.record().start();
```

but only one of them should be neccessary.

**Comment by rdurish** [comment]
@thijstriemstra just FYI your proposed solutions didn't work for me.  I needed to have retry snapshop and start in order for a picture to be taken (any device for my example of auto taking pictures).  For this to work on the iphone I had to not HIDE the image grabber but move it off screen.  Once I did that everything worked.  I updated my example on dropbox if you care to see.  Thanks for your help!
