### ISSUE TITLE
Can not preview video when record screen with chrome tab

### ISSUE THREAD

**Issue by nthieu21075** [collab-project/videojs-record#444]
I am using latest chrome version and cannot play video after recording screen with chrome tab. @

**Comment by nthieu21075** [comment]
@thijstriemstra Pls help me check this issue

**Comment by thijstriemstra** [comment]
can you make a screenshot and/or video to demonstrate the problem? you also didn't include the videojs-record config, so it's hard to help without so little info.

**Comment by nthieu21075** [comment]
https://drive.google.com/file/d/1Kulu1kCYJMqYBuLD0f-wsAYn00QZqGDU/view

@thijstriemstra this is video i recorded with your example. But it only occured on MAC OS with lastest chrome version

**Comment by thijstriemstra** [comment]
> But it only occured on MAC OS with lastest chrome version

so it doesn't happen on other browsers on macOS?

**Comment by thijstriemstra** [comment]
I just tested on macOS 10.15.1 with Chrome 80 and everything worked fine here, I did the same steps like you showed in the youtube clip. I did get a popup for Security, make sure you give Chrome sufficient permissions to record the screen.

<img width="515" alt="Screenshot 2020-02-07 at 19 57 02" src="https://user-images.githubusercontent.com/305679/74057521-67bc8280-49e4-11ea-9fa6-39751335669d.png">

**Comment by nthieu21075** [comment]
It still happening. You can see video in this link. I turned console log and you can see more information and this is my chrome version. Thanks
![image](https://user-images.githubusercontent.com/55969808/74216671-b5343a80-4cd7-11ea-9f9f-5c6eab14e093.png)

https://drive.google.com/file/d/1pkGwX3tQNSyirvspOCZgs-l_vZhRUsjF/view
