### ISSUE TITLE
Select screen capture source programmatically

### ISSUE THREAD

**Issue by hyvyys** [collab-project/videojs-record#450]
Is it possible to limit the choice of screen capture sources, for instance to the current browser window? And then pre-select / auto-select it for the user to just accept it without needing to choose a window.

**Comment by thijstriemstra** [comment]
I'm not sure if there's any browser with an API yet. Maybe ask on stackoverflow (it's more a `getDisplayMedia` question).. If you have more info, please share it here.

**Comment by tomhatzer** [comment]
`displaySurface` would be the option that let's you define the available sources.

Though it's pretty much useless as it doesn't limit the resources the user can select: https://stackoverflow.com/questions/56891971/displaysurface-constraint-not-restricting-user-share-screen-selection-options

Demo:
https://www.webrtc-experiment.com/getDisplayMedia/
