### ISSUE TITLE
Play button don't work for video.js videos when record plugin is not used

### ISSUE THREAD

**Issue by ignl** [collab-project/videojs-record#452]
## Steps to reproduce
Import video.js and videojs-record like this:
```
    <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.7.5/video.min.js"></script>
    <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/RecordRTC/5.5.9/RecordRTC.min.js"></script>
    <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/7.3.0/adapter.min.js"></script>
    <script type='text/javascript' src="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/3.11.0/videojs.record.min.js"></script>
```
Run video.js without record plugin on some video.
Play button doesn't work for that video.

If video.js record plugin is used somewhere in the code - video.js play button works normally.
This is most likely related to this PR: https://github.com/collab-project/videojs-record/pull/442
3.9.0 version doesn't have this issue.

### Error output
No error output

**Comment by thijstriemstra** [comment]
Sorry for late reply. And that sucks to hear.

**Comment by thijstriemstra** [comment]
@ignl can you revert these specific changes in latest master and test if that solves it? I guess it'll break #437 again but we'll have to find a different workaround for that.

**Comment by ignl** [comment]
I am using 3.9.0 version for now. I can try next week hopefully.

**Comment by thijstriemstra** [comment]
@ignl can you give #474 a try, I added a `examples/multi.html` example and I can't reproduce this issue anymore.

**Comment by ignl** [comment]
@thijstriemstra Hi, I tried and unfortunately version 4.0 still have the same problem. Only 3.9.0 is the one working for me in this scenario.

**Comment by thijstriemstra** [comment]
@ignl I made https://collab-project.github.io/videojs-record/demo/multi.html for this. It's not working for you? Or is there a different issue?

**Comment by ignl** [comment]
My scenario would be applying simple videojs on 'myPlayer' and removing/not applying videojs with record plugin on 'myRecorder'. I will try to modify your example to try to reproduce.
