### ISSUE TITLE
Webm plugin not working in combination with vue / webpack

### ISSUE THREAD

**Issue by HenSei** [collab-project/videojs-record#453]
Hey, 

first of all thank you very much for providing such an easy recorder for video-js player.
I'm using it and it works great! Since I also want to use recording functionality in the browser of mobile devices I wanted to use the webm-wasm plugin. 

I'm using it in a vue project with webpack. I have implemented like described in the example but somehow it is not working for me I always get the following error:

![image](https://user-images.githubusercontent.com/8431183/77850779-fa9fbf00-71d4-11ea-824d-27b5f91824a7.png)

I think it is because there also has to be a change in webpack which I currently use like this:
![image](https://user-images.githubusercontent.com/8431183/77850803-2ae75d80-71d5-11ea-9d66-2ba8b3a656c8.png)

Do you have an example what I have to change that it is also working with webpack or what could cause this error?

Thank you very much for your support in advance!

**Comment by thijstriemstra** [comment]
>  I have implemented like described in the example 

can you show the video.js config and plugin imports?

**Comment by HenSei** [comment]
Hey @thijstriemstra!
Thank you for your fast response.
Actually I tried both ways, web-worker.js & webm-wasm.wasm available in node_modules and in project's public folder but both versions are not working.

My video.js config looks like this:

<img width="724" alt="image" src="https://user-images.githubusercontent.com/8431183/77897210-a8fd4000-7279-11ea-96c6-1b661c0b458b.png">

The files are available in the public folder and can be accessed successfully:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/8431183/77897338-d3e79400-7279-11ea-93fe-5cbebc0c43d7.png">

I also tried with the with full path and just with the file name for videoWebAssemblyURL.

When I console.log the RecordRTCEngine and WebmWasmEngine var in videojs.record.webm-wasm.js both are undefined which probably causing the "Super expression must either be null or a function"-error. Thats why I thought there also has to be a change in webpack.config.

Would be great if you have any other ideas to get that working.
Thank you very much for your help!

**Comment by HenSei** [comment]
I just could fix the problem. It was the wrong import order when I put videojs RecordRTC and Record to the first place it is working ;-)

Is there also the possibility to combine webm recording with audio?

**Comment by thijstriemstra** [comment]
>  Is there also the possibility to combine webm recording with audio? 

Recording audio+video will record into webm format in most browsers.

**Comment by thijstriemstra** [comment]
> I just could fix the problem. It was the wrong import order when I put videojs RecordRTC and Record to the first place it is working ;-)

Could you attach a screenshot or code sample to show what fixed it so it could possibly help others?

**Comment by HenSei** [comment]
> Could you attach a screenshot or code sample to show what fixed it so it could possibly help others?

Sure, I just changed the order of the imports to the following:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/8431183/77903454-2da08c00-7283-11ea-902c-c89a5e3b3906.png">

So first import videojs, RecordRTC and Record and then do the other imports.

Maybe one last question at the end what experience do you have with recording on mobile devices what would you suggest is working best?
