### ISSUE TITLE
yet another Uncaught Error: plugin "record" does not exist

### ISSUE THREAD

**Issue by 7Ds7** [collab-project/videojs-record#454]
## Description
I have been trying to setup videojs-record on a rails setup with rails webpacker and always run into the error ```Uncaught Error: plugin "record" does not exist```
I went trough the related closed issues and that did not solved the problem, hence i am here requesting some input on how to solve it

## Steps to reproduce
So without being very familiar with codesandbox i managed to setup one with the bare minimum as per the videojs webpack wiki entry https://github.com/collab-project/videojs-record/wiki/Webpack

The sandbox can be found here https://codesandbox.io/s/unruffled-dream-lkcvp

### Expected
Should create one instance of videojs with the videojs-record plugin

### Actual
Always bump into the error ```Uncaught Error: plugin "record" does not exist```
Please open the browser console to see the error

### Error output
```Uncaught Error: plugin "record" does not exist```

## Additional Information
The versions of the plugins can be found on the codesandbox link

**Comment by 7Ds7** [comment]
After some attempts i think the problem might be the latest version of videojs [v7.7.6](https://github.com/videojs/video.js/releases/tag/v7.7.6) because it does seem to work with [v.7.7.5](https://github.com/videojs/video.js/releases/tag/v7.7.5)

**Comment by thijstriemstra** [comment]
Interesting. I'll give it a try.

**Comment by thijstriemstra** [comment]
`npm install videojs-record` installs video.js 7.7.5 so this is basically working. If it breaks with 7.7.6 (pre-release for now) and that is actually released, I'll reopen this.

**Comment by Kulgar** [comment]
Hello, 

I'm commenting this issue because I got the exact same error but with video.js v7.9.2.

I had to downgrade to 7.8.4 to make it work again. I didn't test 7.9.0 nor 7.9.1, so I don't know if the error comes with these 2 versions too. 

I'll gladly help investigating the issue if needed cc @thijstriemstra :-)

**Comment by thijstriemstra** [comment]
> I'm not sure if I should open a new issue though

@Kulgar please do.
