### ISSUE TITLE
[question] How to change icon in button?

### ISSUE THREAD

**Issue by lossen** [collab-project/videojs-record#455]
## Description
I want to change the icons on the button on my own icons. 
How can I do it? Have you any option to do that? Or I need to do it via CSS?
I am using videojs-record with React.js.

![Screenshot 2020-04-05 at 21 09 26](https://user-images.githubusercontent.com/14949813/78502223-cd798080-7781-11ea-8c15-56cd1161774f.png)

"react": "^16.8.6",
"videojs-record": "^3.11.0"

Any help will be appreciated. 
Thanks in advance.

**Comment by thijstriemstra** [comment]
@lossen take a look at instructions on https://github.com/collab-project/videojs-record/tree/master/src/fonts

**Comment by lossen** [comment]
@thijstriemstra thanks for the quick answer. In the instructions using grunt, how can I use it with without grunt in React? 
If I understood correctly for using custom icons I need to fork videojs-record, make changes and use this. Did I get it right?

**Comment by thijstriemstra** [comment]
No you simply update the custom videojs-record fonts by checking out the videojs/font repository and adjusting the json file so it can uses your custom icons. Simply follow the instructions and it should be clear: https://github.com/collab-project/videojs-record/tree/master/src/fonts#setup

**Comment by lossen** [comment]
Ok, I understood. But if reinstall project, all node modules including videojs-record will install again. And videojs-record will not have my changes in icons, right?

**Comment by thijstriemstra** [comment]
True. You need to store these new fonts in some static directory, and treat them like fonts that do not get generated/compiled when you run npm install in your project.

**Comment by lossen** [comment]
Ok. Thanks for the explanations. But this way not comfortable for me. I will do it via CSS.
Anyways, thanks so much for your time and help!

**Comment by thijstriemstra** [comment]
Sounds good. Please share the solution you end up with here so others can possibly use it as well.

**Comment by lossen** [comment]
Sure. 

![Screenshot 2020-04-07 at 15 41 09](https://user-images.githubusercontent.com/14949813/78654407-4691e880-78e6-11ea-986a-f9c94501bed8.png)


```javascript
.video-js.video-js-custom{
  .vjs-icon-av-perm,.vjs-icon-audio-perm,.vjs-icon-video-perm{
    &:before{
      content: '';
      background-size: 28px 28px;
      height: 28px;
      width: 28px;
      position: absolute;
      transform: translate(-50%, -50%);
      left: 50%;
      right: 50%;
    }
  }
  .vjs-icon-audio-perm:before{
    background-image: url('../images/asset-icon-tabs/record-audio-icon.svg');
  }
  .vjs-icon-av-perm:before{
    background-image: url('../images/asset-icon-tabs/take-video-icon.svg');
  }
  .vjs-icon-video-perm:before{
    background-image: url('../images/asset-icon-tabs/take-photo-icon.svg');
  }
}

**Comment by thijstriemstra** [comment]
thanks!
