### ISSUE TITLE
Downloaded in mp4 not in webm

### ISSUE THREAD

**Issue by Franchescote** [collab-project/videojs-record#456]
Hi, I need you to please help me with a topic.
I need the recorded video to be downloaded in mp4 not in webm, we try to follow the steps https://github.com/collab-project/videojs-record/wiki/Plugins#ffmpegjs but when you want to install the packages it gives me this error and not I know how to fix it.

![temp](https://user-images.githubusercontent.com/305679/79147168-d098f000-7dc3-11ea-8314-4a1c5c996433.JPG)

Regards, Franco.

**Comment by thijstriemstra** [comment]
I would first setup the ffmpeg.js example on your server: https://github.com/collab-project/videojs-record/blob/master/examples/plugins/audio-only-ffmpegjs.html

Once you have that working, let me know if you still see these errors.

**Comment by thijstriemstra** [comment]
no feedback, closing.
