### ISSUE TITLE
Change Filename Issue

### ISSUE THREAD

**Issue by lwaterslisa** [collab-project/videojs-record#458]
## Description
I am trying to name the filename of the uploaded video to the server the date_requestorFname_requestorLname. The requestor_fname and requestor_lname are url parameters. I have to launch this by Monday and I can't find the answer anywhere. :(

### Actual
With my current code, I can get it to name the filename with the date but, it doesn't include my dynamic url parameters.

Here is the video recorder page:
`<script>
var player = videojs("myVideo", {
    controls: true,
    width: 320,
    height: 240,
    fluid: true,
    plugins: {
        record: {
            audio: true,
            video: true,
            maxLength: 180,
            debug: true
        }
    }
}, function(){
    // print version information at startup
    var msg = 'Using video.js ' + videojs.VERSION +
        ' with videojs-record ' + videojs.getPluginVersion('record') +
        ' and recordrtc ' + RecordRTC.version;
    videojs.log(msg);
});
// error handling
player.on('deviceError', function() {
    console.log('device error:', player.deviceErrorCode);
});
player.on('error', function(error) {
    console.log('error:', error);
});
// user clicked the record button and started recording
player.on('startRecord', function() {
    console.log('started recording!');
});
// user completed recording and stream is available
player.on('finishRecord', function() {
    // the blob object contains the recorded data that
    // can be downloaded by the user, stored on server etc.
    console.log('finished recording: ', player.recordedData);

    var formData = new FormData();
    formData.append('audiovideo', player.recordedData.video);
    // file name
formData.append('media-filename', player.recordedData.video.name);

// mime-type
formData.append('media-type', player.recordedData.video.type);
    
    // Execute the ajax request, in this case we have a very simple PHP script
    // that accepts and save the uploaded "video" file
    xhr('upload-video.php', formData, function (fName) {
        console.log("Video succesfully uploaded !");
    });

    // Helper function to send 
    function xhr(url, data, callback) {
        var request = new XMLHttpRequest();
        request.onreadystatechange = function () {
            if (request.readyState == 4 && request.status == 200) {
                callback(location.href + request.responseText);
            }
        };
        request.open('POST', url);
        request.send(data);
    }
});
</script>`

Here is the upload-video.php file
`<?php
 
if(isset($_FILES["audiovideo"])){ // save audio and video
     $fileName = $thename;
   $uploadDirectory = 'upload_files/'. $fileName;
    if (!move_uploaded_file($_FILES["audiovideo"]["tmp_name"], $uploadDirectory)) {
        echo("Couldn't upload video !");
    }
    else{
     echo("File Moved");
    }
}elseif(isset($_FILES["audio"])){ // save audio only
    $fileName = $thename;
    $uploadDirectory = 'upload_files/'. $fileName;
    if (!move_uploaded_file($_FILES["audio"]["tmp_name"], $uploadDirectory)) {
        echo("Couldn't upload video !");
    }
    else{
     echo("File Moved");
    }
}
elseif(isset($_FILES["video"])){ // save video only
    $fileName = $thename;
    $uploadDirectory = 'upload_files/'. $fileName;
    if (!move_uploaded_file($_FILES["video"]["tmp_name"], $uploadDirectory)) {
        echo("Couldn't upload video !");
    }
    else{
     echo("File Moved");
    }
}
elseif(isset($_FILES["stream"])){ // save streamming
    $fileName = $thename;
   $uploadDirectory = 'upload_files/'. $fileName;
    if (!move_uploaded_file($_FILES["stream"]["tmp_name"], $uploadDirectory)) {
        echo("Couldn't upload video !");
    }
    else{
     echo("Success");
    }
}
else{
    echo "No file uploaded";
}
header("Location: confirm.php");
?>`

**Comment by thijstriemstra** [comment]
> I have to launch this by Monday and I can't find the answer anywhere. :(

try stackoverflow, this is not a php support forum.
