### ISSUE TITLE
Nuxt.js plugin "record" does not exist

### ISSUE THREAD

**Issue by Alakar-Nallavan** [collab-project/videojs-record#460]
## Description
Briefly describe the issue.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

### Expected
I trying to add just video rendering in my web cam through Nuxt.js 

### Actual
There is some difficulties on importing your Project. 

I follow some steps in vue.js wiki
i try to change the thing is
in nuxt.config.js file
```javascript
import webpack from 'webpack'
export default {
  mode: 'universal',
  /*
  ** Build configuration
  */
  build: {
    plugins: [
      new webpack.ProvidePlugin({
        videojs: 'video.js/dist/video.cjs.js',
        RecordRTC: 'recordrtc'
      })
    ],
    postcss: {
      preset: {
        features: {
          customProperties: false
        }
      }
    },
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
      config.resolve.alias['videojs'] = 'video.js'
      config.resolve.alias['WaveSurfer'] = 'wavesurfer.js'
      config.resolve.alias['RecordRTC'] = 'recordrtc'
    }
  }
}
```

### Error output
If there are any errors at all, please include them here.
![image](https://user-images.githubusercontent.com/30324835/79940397-34d04980-847f-11ea-87bf-db375cbc389a.png)

## Additional Information
if i modified la option plugin
from
```      options: {
        controls: true,
        autoplay: true,
        fluid: false,
        loop: false,
        width: 320,
        height: 240,
        controlBar: {
          volumePanel: false
        },
        plugins: {
          // configure videojs-record plugin
          record: {
            audio: false,
            video: true,
            debug: false
          }
        }
      }
```
to
```
      options: {
        controls: true,
        autoplay: true,
        fluid: false,
        loop: false,
        width: 320,
        height: 240,
        controlBar: {
          volumePanel: false
        }
      }
```
note: my side there is some problem in Plugins
#### videojs
VIDEOJS: Using video.js 7.7.5 with videojs-record  and recordrtc 5.5.9
#### browsers
platforms (Windows 10,node v10.16.0) are affected.

**Comment by thijstriemstra** [comment]
Where do you import videojs-record? Take a look at https://github.com/collab-project/videojs-record/wiki/Webpack for import examples.

**Comment by thijstriemstra** [comment]
no feedback, closing.
