### ISSUE TITLE
saving and playing the fetched file from s3

### ISSUE THREAD

**Issue by frontr-uk** [collab-project/videojs-record#461]
I am saving the file directly in s3, than fetching I get 

------WebKitFormBoundaryeCQv7fgn8RKZbRu5
Content-Disposition: form-data; name="file"; filename="1587655663144.x-matroska"
Content-Type: video/x-matroska;codecs=avc1,opus

What is a blob as I understand, How do I render the video - play it for the user?

**Comment by thijstriemstra** [comment]
You can playback the clip in a separate video.js player and load the blob there.
