### ISSUE TITLE
Audio+screen: incomplete permissions do not fire error 

### ISSUE THREAD

**Issue by jbarmanet** [collab-project/videojs-record#463]
When we use the plugin to record Screen+Audio, the user is asked to give permission to share his screen, then a second permission to share his microphone. 

If you accept the first permission, but you deny the second microphone permission (lets say you missed the button), we end up into the blue because nothing happens: no error nor deviceReady… it looks like it's just waiting… for nothing. 

It happens at least on Mac OS X Chrome 81, Firefox 75, and Safari 13.1

**Is there any way to test somehow the microphone authorization state?**

**Comment by thijstriemstra** [comment]
I'm not sure. I doubt it though.

**Comment by thijstriemstra** [comment]
Also see #468 that might over a solution here.

**Comment by thijstriemstra** [comment]
In Firefox 76, when I:

- give screen permissions
- deny microphone permissions

it throws this cryptic error:

```
uncaught exception: Object
```

![Screenshot from 2020-05-19 21-53-42](https://user-images.githubusercontent.com/305679/82371903-43c50000-9a1b-11ea-8279-84cc58c15ee5.png)

**Comment by thijstriemstra** [comment]
I added the missing error handler for the microphone in pull request #474, please give it a try or wait until v4.0.0 is released.

> we end up into the blue because nothing happens: no error nor deviceReady… it looks like it's just waiting… for nothing.

It should now give you a proper error. Fortunately in both Firefox and Chrome it's not even possible to make this window go away without clicking deny or accept:

![Screenshot from 2020-05-19 22-32-15](https://user-images.githubusercontent.com/305679/82375450-e59b1b80-9a20-11ea-9fa7-77a95a5e62cd.png)

and in Chrome:

![Screenshot from 2020-05-19 22-35-35](https://user-images.githubusercontent.com/305679/82375608-21ce7c00-9a21-11ea-9aec-94e930a98305.png)

haven't tried safari though.
