### ISSUE TITLE
Videojs Record not accessing camera/microphone or Share Screen if website running on AWS EC2 & Azure VM

### ISSUE THREAD

**Issue by engr-zeeshan** [collab-project/videojs-record#466]
## Description
The web page has the capability of using videojs record for screen recording and webcam video recording. It is working fine on localhost and on shared hosting. But I have deployed website on AWS EC2 and Azure VM for testing and videojs record is not working there. As per my understanding it is all javascript and should be working on browsers where ever the site is hosted.

Any clue?

### code on both pages is same.
https://clearn.codeschunks.com/test/recordvideo (working)
http://ec2-54-185-50-254.us-west-2.compute.amazonaws.com/index.php/test/recordvideo (not working)

### screenshot-1
When user clicks on a button within square box, a window should appear for confirmation (shown in screenshot-2)
![ss1](https://user-images.githubusercontent.com/6541601/81286285-394d5280-907a-11ea-94d5-4cab433986c0.jpg)

### screenshot-2
![ss2](https://user-images.githubusercontent.com/6541601/81286295-3eaa9d00-907a-11ea-99f9-8d56c8c7350f.jpg)

This window appears if site is running on localhost or shared hosting service, but not if site is running on Azure VM or AWS EC2.

### Error output
cannot see any error on console

## Stackover question link
https://stackoverflow.com/questions/61647890/videojs-record-not-accessing-camera-microphone-or-share-screen-if-website-runnin

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Video.js 7.8.0
#### browsers
All browsers

**Comment by thijstriemstra** [comment]
You need to serve application with https.
