### ISSUE TITLE
Videojs-record in Angular 6 without Webpack

### ISSUE THREAD

**Issue by poojas17** [collab-project/videojs-record#467]
I'm trying to integrate videojs-record in Angular 6 (without webpack). Older version of videojs-record is intentionally used because it doesn't have webpack. Please suggest if latest version can be used without webpack config or if there's any documentation to add videojs-record without webpack.

Command to build the app: ng build
Command to start the app: ng serve

Please find the versions of the dependencies below:
"@types/video.js": "^7.3.7"
"video.js": "^6.1.0"
"videojs-record": "^1.5.2"
"@angular/cdk": "^6.4.7"
"@angular/core": "^6.1.0"
"@angular-devkit/build-angular": "~0.7.0"
"@angular/cli": "~6.1.1"
"@angular/compiler-cli": "^6.1.0"

Please find the errors below:
ERROR in ./node_modules/videojs-record/dist/videojs.record.js Module not found: Error: Can't resolve 'RecordRTC' in '/path/to/project/root/node_modules/videojs-record/dist'

ERROR in ./node_modules/videojs-record/dist/videojs.record.js Module not found: Error: Can't resolve 'videojs' in '/path/to/project/root/node_modules/videojs-record/dist'

Browser: Google Chrome (latest version)

**Comment by thijstriemstra** [comment]
That version is so old, it's not supported anymore. I can't help with Angular issues, only reference I have for you is: https://github.com/collab-project/videojs-record/wiki/Angular

**Comment by poojas17** [comment]
The latest version used in the documentation doesn't work with Angular 6

**Comment by thijstriemstra** [comment]
Fixed in v4.1.0.
