### ISSUE TITLE
Distorted video/audio

### ISSUE THREAD

**Issue by alsar** [collab-project/videojs-record#47]
Sometimes it happens that the audio and video is recorded like this: https://www.youtube.com/watch?v=iI1yHDF2DYA

This happens in Firefox, but I don't know in which circumstances. It seems that this happens randomly.

**Comment by thijstriemstra** [comment]
@alsar is this something you noticed since v1.1.0 released this week or was it already present.

**Comment by alsar** [comment]
@thijstriemstra this happened also in 1.0.3
I didn't have the chance to check it in Chrome, if there is the same problem.

**Comment by thijstriemstra** [comment]
@alsar the youtube link you're referring to is gone it seems ("This video has been removed by the user.")

What version of Firefox is this? Are you using the latest recordrtc version?

**Comment by alsar** [comment]
@thijstriemstra I deleted it by mistake as I removed some testing videos. 
I've found another one: https://www.youtube.com/watch?v=mwvvR1Dh3Wg

It's the latest version of RecordRTC, but it also happened with previous versions of RecordRTC and videojs-record. I'm using Firefox 43 on Linux.

I couldn't reproduce it on Chrome (Chromium) as this happens rarely.

**Comment by muaz-khan** [comment]
This issue seems happening only on Windows. 

Firefox 44.0 on Mac seems working fine (tested in MacOSX 10.10.5)

**Comment by thijstriemstra** [comment]
Thanks for your feedback @muaz-khan. @alsar mentions he's using Linux Firefox 43, seems it's not a Windows only problem..

**Comment by vojka** [comment]
I also encountered this problem a few times.
@thijstriemstra @muaz-khan Is this a problem with RecordRTC or videojs-record?

**Comment by muaz-khan** [comment]
Seems issue in Firefox. If you record merely video-tracks then it works in all platforms.

Maybe we need to pass `video/webm; codecs=vp8` or vp9/etc. parameters instead of simply passing `video/webm`.

PS. There seems something wrong in Firefox implementation. Maybe need to track bugzilla.

**Comment by thijstriemstra** [comment]
Is https://bugzilla.mozilla.org/show_bug.cgi?id=1234230 related?

**Comment by alsar** [comment]
It seems that it is the same issue. According to the bug report it should be fixed in Firefox 47. 
I'll close the issue for now.

**Comment by thijstriemstra** [comment]
thanks @alsar, if you can confirm at some point that this is fixed, please let us know.
