### ISSUE TITLE
[README.md] videoMimeType's description URL is broken

### ISSUE THREAD

**Issue by vitor251093** [collab-project/videojs-record#470]
## Description
The URL in videoMimeType's description is the one below:
https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/mediarecorder/MediaRecorder-isTypeSupported.html

But it's broken. It should be, instead:
https://cs.chromium.org/chromium/src/third_party/blink/web_tests/fast/mediarecorder/MediaRecorder-isTypeSupported.html

**Comment by thijstriemstra** [comment]
thanks for letting me know @vitor251093, I'll get it fixed.
