### ISSUE TITLE
Audio only implementation have stopped working

### ISSUE THREAD

**Issue by vora1993** [collab-project/videojs-record#471]
## Description
Audio only implementation is not working anymore

## Steps to reproduce
Go to the following link and try to record audio:
https://collab-project.github.io/videojs-record/examples/audio-only.html

### Expected
Recorder should have recorded audio

### Actual
Recorder is not recording audio and there is some error in console

### Error output
![image](https://user-images.githubusercontent.com/42148414/81939004-61f1c100-9613-11ea-8bcd-6c0102c68bb5.png)

**Comment by thijstriemstra** [comment]
Ah yea, it's using videojs-wavesurfer 3.0.3 and that is not supported by videojs-record yet. I will pin videojs-wavesurfer to 2.11.0 on the website until then.

Thanks for the report.

**Comment by vora1993** [comment]
So it has stopped working for me locally too...What exact change should I do to make it work again?

**Comment by thijstriemstra** [comment]
`npm install --save videojs-wavesurfer@2.11.0`

**Comment by thijstriemstra** [comment]
Installing videojs-record should not install v3.0.3 of videojs-wavesurfer, not sure how you ended up with a local videojs-wavesurfer v3.0.3.

**Comment by thijstriemstra** [comment]
If you clear browser cache and reload https://collab-project.github.io/videojs-record/examples/audio-only.html it should work again. Will now update the other audio-related examples.

**Comment by vora1993** [comment]
@thijstriemstra thanks for all your help...Actually I was using CDN.
I have also now pinned it to 2.11.0 which solved my issue

**Comment by thijstriemstra** [comment]
I will add a note to the readme as well.
