### ISSUE TITLE
Chrome MediaRecorder 

### ISSUE THREAD

**Issue by zang** [collab-project/videojs-record#48]
MediaRecorder API seems to be available in both Canary and stable, behind a flag (chrome://flags/#enable-experimental-web-platform-features). Does it mean that video+audio can be recorded as a single webm (similar to Firefox) in the future? :)

Is there any change I need to do with this lib to force Chrome MediaRecorder or it automatically detect MediaRecorder?

Thanks

**Comment by thijstriemstra** [comment]
Yes, support for MediaRecorder in Chrome was added to RecordRTC: https://github.com/muaz-khan/RecordRTC/commit/565347c8b1fbcce3cb1118746b373de781cb9673 but there's this comment:

```
enable below block when MediaRecorder in Chrome gets out of flags; and it also supports audio recording.
```
So audio isn't supported yet, Chrome supports only video recording at the moment.

@zang, does the browser console log show that RecordRTC is using MediaRecorder in Chrome stable or beta?

**Comment by zang** [comment]
I enabled the flags on Chrome stable and I got the following from console log:

started recording audio stream.
initializing audio stream recorder.
StereoAudioRecorder is set to record number of channels:  2
sample-rate 44100
buffer-size 4096
started recording video stream.
initializing video stream recorder.
Using frames-interval: 10
canvas resolutions 320 * 240
video width/height 320 * 240

**Comment by thijstriemstra** [comment]
Try Chrome Beta as well @zang

**Comment by zang** [comment]
Version 50.0.2631.0 canary (64-bit)

started recording audio stream.
initializing audio stream recorder.
StereoAudioRecorder is set to record number of channels:  2
sample-rate 44100
buffer-size 4096
started recording video stream.
initializing video stream recorder.
Using frames-interval: 10
canvas resolutions 320 * 240
video width/height 320 * 240

**Comment by thijstriemstra** [comment]
And what if you disable the flag. Also see https://github.com/muaz-khan/RecordRTC/issues/78

**Comment by zang** [comment]
Disabled the flags on stable, and got same console log.

**Comment by thijstriemstra** [comment]
@zang and what if you remove the `!isChrome` here: https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC.js#L790 (try with both beta/stable and flags on/off)?

**Comment by thijstriemstra** [comment]
@zang well that will probably not make much difference, but try commenting out the various checks and force it to use MediaRecorder on Chrome that way.

**Comment by thijstriemstra** [comment]
If that doesn't work than it's simply too early to rely on it in Chrome I think.

**Comment by zang** [comment]
Will try and keep you posted. thanks :)

**Comment by muaz-khan** [comment]
### Chrome stable

1. Supports video-only recording
2. Not following spec i.e. 2nd argument of MediaRecorder API is expected to be a string (`video/vp8`) rather than an object `{mimeType:"video/webm"}`
3. RecordRTC is forcefully skipping stable versions i.e. using WhammyRecorder/StereoAudioRecorder instead.

You can force `recorderType` but you've to manually modify MediaStreamRecorder.js to pass `video/vp8` as second argument over MediaRecorder constructor.

### Canary

1. Following the spec code style
2. Supporting both audio+video recording
3. RecordRTC is (auto) using MediaRecorder API for audio+video, audio-only, and video-only (until, if end user is NOT forcing `recorderType`)

Canary seems supporting captureStream API as well; which is not functional yet. It will allow us record canvas2d animations as well as any of the `<video>` element.

**Comment by zang** [comment]
Removed !isChrome and the console log is different as below:

started recording audio stream.
initializing audio stream recorder.
Passing following config over MediaRecorder API. video/vp8
started recording video stream.
initializing video stream recorder.
Using frames-interval: 10
canvas resolutions 320 * 240
video width/height 320 * 240

**Comment by thijstriemstra** [comment]
Thanks for the details @muaz-khan! You mention it's possible to force the `recorderType` but this project uses MRecordRTC and I don't see a way to specify this. Would you accept a pull request for this?

**Comment by thijstriemstra** [comment]
@zang, that looks better, how's the quality of the resulting audio or video file?

**Comment by zang** [comment]
@thijstriemstra quality looks similar. I will change resolutions and intervals to see if them make difference. :)

**Comment by zang** [comment]
With MediaRecorder enabled, the recorded video doesn't seem to have sound. It works without though.

**Comment by zang** [comment]
Related to https://github.com/collab-project/videojs-record/issues/54 and https://github.com/collab-project/videojs-record/pull/55
