### ISSUE TITLE
ffmpeg.js plugin: record video+audio fails

### ISSUE THREAD

**Issue by freedytag** [collab-project/videojs-record#481]
## Description
So far If I want record video+audio, it seem need use the RecordRTC?
If use other plugin such as "webm-wasm" it seem will only record video without sound.
So I want to try use some converter, such as ffmpeg.js with RecordRTC?
But seem not luck with many config I try.
Do you mind provide a example for convert to mp4 (Video+Audio) with common codec such as h264?

## Steps to reproduce
Some config I test
```javascript
			convertOptions: ['-f', 'mp4', '-codec:a', 'aac', '-codec:v', 'libx264'],
			pluginLibraryOptions: {
				outputType: 'video/mpeg'
			},
```
### Expected
Convert success

### Actual
Throw exception

### Error output
uncaught exception: [object Object] 
ffmpeg-worker-mp4.js:17:59

## Additional Information
It may be not a bug, may need a tips for demo how to use ffmpeg with videojs record with Video+Audio?

#### videojs
4.0.0

#### browsers
Firefox 76.0.1

#### OSes
MacOS

**Comment by thijstriemstra** [comment]
can you make a screenshot of the error in the console? the error is not very descriptive as is.

**Comment by freedytag** [comment]
<img width="474" alt="Screenshot 2020-05-25 at 7 33 05 PM" src="https://user-images.githubusercontent.com/65017590/82809448-b2dca180-9ebe-11ea-8eb2-c8e177748870.png">

I think you can use 
https://collab-project.github.io/videojs-record/demo/audio-only-ffmpegjs.html
and change the plugin option to

	plugins: {
		record: {
			audio: true,
			video: true,
			maxLength: 30,
			debug: true,
			displayMilliseconds: true,
			convertEngine: 'ffmpeg.js',
			convertOptions: ['-f', 'mp4', '-codec:a', 'aac', '-codec:v', 'libx264'],
			pluginLibraryOptions: {
				outputType: 'video/mpeg'
			},
			convertWorkerURL: 'lib/ffmpeg.js/ffmpeg-worker-mp4.js'
		}
	}

And can repeat my case.

**Comment by thijstriemstra** [comment]
Tested recording audio + video with these ffmpeg settings:

```javascript
// convert recorded data to MP3
convertOptions: ['-f', 'mp3', '-codec:a', 'libmp3lame', '-qscale:a', '2'],
// specify MP3 output mime-type
pluginLibraryOptions: {
    outputType: 'audio/mpeg'
},
```

And it produced and MP3:


```javascript
Blob { lastModified: 1590407529576, lastModifiedDate: Date Mon May 25 2020 13:52:09 GMT+0200 (Midden-Europese zomertijd), name: "1590407529576.mp3", size: 150627, type: "audio/mpeg" }
```

Using your settings:

```javascript
    convertEngine: 'ffmpeg.js',
    // convert recorded data
    convertOptions: ['-f', 'mp4', '-codec:a', 'aac', '-codec:v', 'libx264'],
    // specify output mime-type
    pluginLibraryOptions: {
        outputType: 'video/mpeg'
    },
```

produces an unhandled exception:

<img width="525" alt="Screenshot 2020-05-25 at 13 59 37" src="https://user-images.githubusercontent.com/305679/82810976-02f03f80-9e90-11ea-89f5-f2079158f5f5.png">

That ffmpeg.js error, whatever it is, should be handled properly so marking this a bug. Not sure why the conversion failed, will look into it.

**Comment by thijstriemstra** [comment]
I opened https://github.com/Kagami/ffmpeg.js/issues/111 for that unhandled error.

**Comment by thijstriemstra** [comment]
see pull request #481 that improves error handling, revealing another ffmpeg.js error (something with `OOM`).

**Comment by freedytag** [comment]
I was using unpkg.com, so that may need next pkg version?
//unpkg.com/videojs-record/dist/plugins/videojs.record.ffmpegjs.min.js

**Comment by thijstriemstra** [comment]
build from source using these instructions: https://collab-project.github.io/videojs-record/#/development

**Comment by freedytag** [comment]
ok. thanks your fast response, will chcek it tmr. I will need work off soon XD

**Comment by thijstriemstra** [comment]
And: https://github.com/Kagami/ffmpeg.js/issues/111#issuecomment-633624593

**Comment by freedytag** [comment]
I can rebuilt ffmpeg.js worker from their source.
But when I try to build videojs-record, it was throw error when npm install in the folder.

<img width="1013" alt="Screenshot 2020-05-26 at 4 22 47 PM" src="https://user-images.githubusercontent.com/65017590/82877728-250bbf80-9f6d-11ea-9759-0f17a72fb0fd.png">

[npm-debug.log](https://github.com/collab-project/videojs-record/files/4680829/npm-debug.log)

**Comment by thijstriemstra** [comment]
you can also try installing an older version of ffmpeg.js from npm so you don't have to build it, maybe that'll work: https://www.npmjs.com/package/ffmpeg.js?activeTab=versions

**Comment by freedytag** [comment]
For ffmpeg.js i am fine to build it. and able to get the final ffmpeg-worker-mp4.js

The above error was when I using the **npm intall** in the **video.js-record** folder.
Which follow from
https://collab-project.github.io/videojs-record/#/development

**Comment by aphavichitr** [comment]
@freedytag were you able to get this to work? What are the convertOptions and the pluginLibraryOptions supposed to be if I'm trying to convert the default webm video to mp4?

**Comment by thijstriemstra** [comment]
I tested with:

```
"ffmpeg.js": "^4.2.9003",
```

and audio + video just now using this config:

```javascript
var options = {
    controls: true,
    bigPlayButton: false,
    width: 600,
    height: 300,
    fluid: false,
    plugins: {
        record: {
            audio: true,
            video: true,
            maxLength: 20,
            debug: true,
            displayMilliseconds: true,
            convertEngine: 'ffmpeg.js',
            // convert recorded data to MP4
            convertOptions: ['-c:v', 'libx264', '-preset', 'slow', '-crf', '22', '-c:a', 'copy', '-f', 'mp4'],
            // specify MP4 output mime-type
            pluginLibraryOptions: {
                outputType: 'video/mp4'
            },
            // use MP4 encoding worker (H.264 & AAC & MP3 encoders)
            convertWorkerURL: '../../node_modules/ffmpeg.js/ffmpeg-worker-mp4.js'
            // or use WebM encoding worker (VP8 & Opus encoders)
            // convertWorkerURL: '../../node_modules/ffmpeg.js/ffmpeg-worker-webm.js'
        }
    }
};
```

which did not throw any errors but produced a 0 bytes blob.

I tested with the new ffmpeg.wasm plugin in videojs-record 4.2.0 and this worked fine.

I'm marking the ffmpeg.js plugin as deprecated, since it looks unmaintained and doesn't work properly. Use the ffmpeg.wasm plugin instead if you want video + audio.

Closing this ticket, if anyone finds a fix, please leave a comment.

**Comment by aphavichitr** [comment]
> Use the ffmpeg.wasm plugin instead if you want video + audio.

I tried to use the ffmpeg.wasm plugin, but in the docs it tells me to import this line:
import FFmpegWasmEngine from 'videojs-record/dist/plugins/videojs.record.ffmpeg-wasm.js';

However, the videojs.record.ffmpeg-wasm.js doesn't exist in the directory. I have videojs-record 4.1.1, which is the latest.

**Comment by aphavichitr** [comment]
> I have videojs-record 4.1.1, which is the latest.

Nevermind, i updated to 4.2.0. Github through me off because it says that the latest is 4.1.1. Maybe the main page needs to be updated?

**Comment by thijstriemstra** [comment]
It's not released yet (at time of this writing) but you can install master branch using: `npm install https://github.com/collab-project/videojs-record.git`

**Comment by aphavichitr** [comment]
@thijstriemstra i just tried installing, but it's missing the dist directory probably because it's in the gitginore. Is there a way I can build this inside node_modules?

**Comment by thijstriemstra** [comment]
yes follow the documentation, see development section.
