### ISSUE TITLE
Support for setFormatTime

### ISSUE THREAD

**Issue by grigull** [collab-project/videojs-record#483]
After upgrading 3.10.0 to 4.0.0 I noticed that the default time stamps when recording are now formatted to 05:00 as apposed to 5:00. Is there any way to be able to customize the format similar to how videojs does so with the setFormatTime function.

**Comment by thijstriemstra** [comment]
> Is there any way to be able to customize the format

Not yet. Pull requests welcome.

**Comment by thijstriemstra** [comment]
Unfortunately such a custom format will apply to all video.js players on the page, until https://github.com/videojs/video.js/issues/6660 is resolved.

**Comment by thijstriemstra** [comment]
@grigull this is working in videojs-record 4.2.0. See https://collab-project.github.io/videojs-record/#/controls?id=time-format for details.
