### ISSUE TITLE
How To Use Source, Compiled Instantly?

### ISSUE THREAD

**Issue by GuyMight44** [collab-project/videojs-record#484]
Hi, so I am not sure if it is just me but I feel like the documentation. Or really just the 'Install' guide is very vague.

I am trying to download a copy for myself to use offline but I feel like I get the source precompiled. Looking at the examples in the folder, they all fetch from a CDN instead of an offline source which hurts understanding how this works.

When I am downloading a source and copying to my Apache server (for example), do I need to compile anything beforehand or is the compiled files in the 'src' folder?

What is the best way to set up this package to just include onto my HTML page?

**Comment by thijstriemstra** [comment]
> I am trying to download a copy for myself to use offline but I feel like I get the source precompiled. 

The source is only pre-compiled when you download videojs-record using NPM, e.g. `npm install videojs-record`. It'll download the compiled files in place them in `node_modules/videojs-record/dist/`.

When you download the source zip file (or checkout using git) the source is not compiled and you have to do this yourself, see instructions at https://collab-project.github.io/videojs-record/#/development

I agree that the installation document should mention how to compile it yourself, or at least link to https://collab-project.github.io/videojs-record/#/development

> Looking at the examples in the folder, they all fetch from a CDN instead of an offline source which hurts understanding how this works.

The examples on the website use a CDN. The examples in the `examples` directory don't use a CDN, they use scripts downloaded using npm.

I will update the documentation with this info.
