### ISSUE TITLE
Timeslices in Safari 13

### ISSUE THREAD

**Issue by taylerz** [collab-project/videojs-record#485]
## Description
Briefly describe the issue.

On Mac OS X, Chrome, Edge, and Firefox works with Timeslices. Safari, instead of timeslices, uploads one whole clip.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

Record video with timeslice in player configuration.

     record: {
            maxLength: 900,
            debug: false,
            audio: false,
            timeSlice: 2000,
            videoMimeType: "video/mp4;codecs=H264",

### Expected
Please describe what you expected to see.

Video Timeslices 

### Actual
Please describe what actually happened.

on finishRecord, player.on('timestamp', function() uploads a single video clip.

### Error output
If there are any errors at all, please include them here.

No errors in console

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?

videojs 7.6

#### browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.

Safari 13.1

#### OSes
what platforms (operating systems and devices) are affected?

Mac OS X 10.15.5

**Comment by thijstriemstra** [comment]
@taylerz can you try this RecordRTC demo in Safari and check if it works. If not, can you check the console and paste the output (or screenshot) here?

https://www.webrtc-experiment.com/RecordRTC/simple-demos/ondataavailable.html

**Comment by taylerz** [comment]
@thijstriemstra The page does not work for Safari. 

A single blob is recorded, similarly to my videojs recorder code. Moreover, the header title just above the recorder does not update automatically like it does for Chrome. The header title, which reads at initialization: "ondataavailable | get Intervals based blobs using RecordRTC" remains the same throughout the recording. At end of recording, Safari displays the title "Total blobs: 1 (Total size: 4.97 MB)"

On the other hand, in Chrome, the header title automatically updates for each blob. The title at the end of a test recording read: "Total blobs: 6 (Total size: 1.30 MB)"

Console output appears to be identical for both Safari and Chrome. I believe insufficient data is output to console showing the timesliced blobs.

It would appear the issue is with RecordRTC, not Videojs recorder. Thanks!

**Comment by thijstriemstra** [comment]
> It would appear the issue is with RecordRTC, not Videojs recorder. Thanks!

Can you open a ticket there and link it here?

**Comment by taylerz** [comment]
@thijstriemstra This issue is fixed in Safari Technology Preview 111, and presumably in Safari 14 when it's released this fall with Mac OS Big Sur.

**Comment by thijstriemstra** [comment]
thanks for the feedback @taylerz!
