### ISSUE TITLE
Cannot disable PIP button

### ISSUE THREAD

**Issue by Cicno** [collab-project/videojs-record#486]
Hi, I'm trying to set some options and it's not working. I've tried many things, but the options doesn't work, here is my code:

```javascript
var options = {
    controls: true,
    bigPlayButton: false,
    loop: false,
    width: 320,
    height: 240,
    fluid: true,
    frameWidth: 320,
    frameHeight: 240,
    plugins: {
        record: {
            muted: false,
            audio: true,
            video: true,
            maxLength: 10,
            debug: true,
            videoMimeType: 	'video/webm;codecs=vp9',
            videoRecorderType: 'auto',
            videoFrameRate: 20,
            displayMilliseconds: false,
            pip: false
        },
    },
    controlBar: {
        // hide fullscreen and volume controls
        volumePanel: false,
        recordToggle: false,
        deviceButton: false,
        cameraButton: false,
        fullscreenToggle: false
    },
    video: {
        // video media constraints: set resolution of camera
        width: 320,
        height: 240
    }
};
```

1- The video options to change set resolution of camera, is not changing anything
2- The pip true or false doesn't hide the button
3- The frame rate doesn't change if I put 1 or 200

I don't see any error at JavaScript, but the options are not working, these options are not working or I'm doing something wrong?

**Comment by thijstriemstra** [comment]
> The video options to change set resolution of camera, is not changing anything

Use constraints, see https://collab-project.github.io/videojs-record/#/media-constraints

> 2- The pip true or false doesn't hide the button

You didn't include information about operating system, video.js version, browser version etc. Why not?

> The frame rate doesn't change if I put 1 or 200

`videoFrameRate` option is only available when using the webm-wasm plugin.

**Comment by Cicno** [comment]
> > The video options to change set resolution of camera, is not changing anything
> 
> Use constraints, see https://collab-project.github.io/videojs-record/#/media-constraints

It worked! Thank you!!!

> > 2- The pip true or false doesn't hide the button
> 
> You didn't include information about operating system, video.js version, browser version etc. Why not?
ops, sorry. I'm using windows, the browser is chrome and opera. For firefox it's working

![image](https://user-images.githubusercontent.com/3309507/84617308-e0f14800-aea4-11ea-9956-b1165eb93ec7.png) - Opera

![image](https://user-images.githubusercontent.com/3309507/84617329-f49cae80-aea4-11ea-961c-ea1374487561.png) Chrome

![image](https://user-images.githubusercontent.com/3309507/84617130-6cb6a480-aea4-11ea-9e32-0bf97077b1c8.png) -Firefox

> > The frame rate doesn't change if I put 1 or 200
> 
> `videoFrameRate` option is only available when using the webm-wasm plugin.

It worked too :)

**Comment by thijstriemstra** [comment]
Not being able to disable pip is a bug, will look into it.

**Comment by thijstriemstra** [comment]
> ops, sorry. I'm using windows, the browser is chrome and opera. For firefox it's working

I tested this on browsers below using videojs-record 4.2.0:

| Platform | Browser | Has bug |
| --- | --- | --- |
| MacOS 11.2.2 | Firefox 86 | No (no pip support) |
| MacOS 11.2.2 | Chrome 89.0.4389.72 | Yes |
| MacOS 11.2.2 | Safari 89.0.4389.72 | Yes |
