### ISSUE TITLE
Cannot compile in ReactJs

### ISSUE THREAD

**Issue by VapiSoft** [collab-project/videojs-record#487]
After Install I get an error
Error: Can't resolve 'videojs' in 'C:\wamp64\www\mesibaba\node_modules\videojs-record\dist'
My code import lines are:
`import 'video.js/dist/video-js.min.css';
import videojs from 'video.js';
import 'videojs-record/dist/css/videojs.record.css';
import Record from 'videojs-record/dist/videojs.record.js';
`

**Comment by thijstriemstra** [comment]
Please make sure webpack is configured properly. Follow this guide: https://collab-project.github.io/videojs-record/#/frameworks/react

**Comment by VapiSoft** [comment]
It is vary strange to change the "scripts" section that worked up till now (and I am afraid that it will cause other changes).
But I tried it?
And I get the following error:
Error: Cannot find module 'C:\wamp64\www\mesibaba/config-overrides'

**Comment by thijstriemstra** [comment]
@VapiSoft did you follow the guide and install react-app-rewired?

```
npm install react-app-rewired --save-dev
```

**Comment by VapiSoft** [comment]
I did every thing, then it told me upgrade to wepack-server 8, and then it didn't want to compile because something was wron with the 'presets', and I couldn't solve it.
Isn't there a simple solution to make it find the videojs ?
When I change the packge.json so many things break!!!
I aleady spent too many hours trying to fix it.
So now I am trying to use "react-video-recorder".
It works, but but its UI is bad.

**Comment by thijstriemstra** [comment]
I am sorry to hear that. React is just not easy to customize, I hate that framework so can't help you. I know the guide shows how to create a working React application so either use that or find a different way to include video.js (and it's plugins).

**Comment by VapiSoft** [comment]
You are very right, but it is still easier than trying to solve the
unresolve vidojs problem.
But thank you very much for you trying to help me.

Shlomo Aran
054-7399-340

**Comment by thijstriemstra** [comment]
@VapiSoft I found the issue and a solution, stay tuned.

**Comment by thijstriemstra** [comment]
Fixed in v4.1.0.
