### ISSUE TITLE
Wave Surfer4.0 breaks audio recording

### ISSUE THREAD

**Issue by rdurish** [collab-project/videojs-record#488]
## Description
Wave Surfer 4.0 breaks audio recording

## Steps to reproduce
Run Current Example, it no longer works.

### Expected
The example should work.

### Actual
Audio is visually shown but can not record.

### Error output
TypeError: this._disabledEventEmissions is undefinedobserver.js:125:30

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
Latest Version
#### browsers
All Browsers
#### OSes
All OS.

**Reverting to using 3.3.3 everything works as expected, which is what I did for my app.**

**Comment by thijstriemstra** [comment]
See https://github.com/katspaugh/wavesurfer.js/issues/1975 for related issue.

**Comment by thijstriemstra** [comment]
Use wavesurfer.js v4.0.1 or newer instead.
