### ISSUE TITLE
Trigger vjs-device-button

### ISSUE THREAD

**Issue by zang** [collab-project/videojs-record#49]
Is there a way to trigger the vjs-device-button button programmatically? 

Use case:
1) click a link outside the player to trigger the camera
2) automatically trigger the camera to skip clicking of the button

thanks

**Comment by thijstriemstra** [comment]
Yes, use `getDevice` (and `stopDevice`). See https://github.com/collab-project/videojs-record/issues/12.

**Comment by zang** [comment]
thanks

**Comment by oobie11** [comment]
getDevice doesn't seem to work if doing audio only. It seems this is because of it automatically using wavesurfer? How would I trigger the button programmatically with an audio only set up?
