### ISSUE TITLE
Maximum browser compatability settings

### ISSUE THREAD

**Issue by Toktik** [collab-project/videojs-record#494]
I currently have those settings, which I think are totally wrong.
```
audioMimeType: 'audio/webm',
videoMimeType: 'video/mpeg;codecs=h264'
```

I have an button which changes the mode, so some users can record audio only. This works in most devices and browsers, except
- OSX with Chrome: Audio only recordings do produce a corrupted file
- Android occasionally producing corrupted videos

What is the best configuration for maximum browser compatibility? Which mimeTypes? Any other properties? Should I just hardcode opus and use https://github.com/kbumsik/opus-media-recorder as a polyfill?

**Comment by thijstriemstra** [comment]
> Should I just hardcode opus and use https://github.com/kbumsik/opus-media-recorder as a polyfill?

videojs-record 4.2.0 includes a new opus-media-recorder plugin that should work on all platforms. vmsg is another option. Give it a try and let us know how it goes.

**Comment by Toktik** [comment]
Thanks @thijstriemstra . Do you know approximately when you will release 4.2.0?

**Comment by thijstriemstra** [comment]
This week @Toktik
