### ISSUE TITLE
using with vue-web-cam

### ISSUE THREAD

**Issue by mobh13** [collab-project/videojs-record#495]
## Description
Briefly describe the issue.
I would like to record a twilio video call on the client side, I'm using vue-web-cam for the cam, can I use this to record the video session ?

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
#### OSes
what platforms (operating systems and devices) are affected?

**Comment by thijstriemstra** [comment]
> I'm using vue-web-cam for the cam, can I use this to record the video session ?

No, not that I know of.
