### ISSUE TITLE
Issue with  `WaveSurfer.microphone` in version 4.0.0

### ISSUE THREAD

**Issue by lnalbandyan** [collab-project/videojs-record#496]
## Description
 WaveSurfer.microphone is undefined, and there is no way to record audio only. Also there is no way to change audio input device.

## Steps to reproduce
You can just go to example page of audio only: https://collab-project.github.io/videojs-record/demo/audio-only.html

## Version
4.0.0

**Comment by thijstriemstra** [comment]
Just recorded a 5 sec clip on that example page using firefox on ubuntu 20. You don't mention what operating system or browser you're using.
