### ISSUE TITLE
Start a recording once a browser tab has been selected.

### ISSUE THREAD

**Issue by mattdorst** [collab-project/videojs-record#499]
## Description
I would like to automatically start the video recording when the user selects to share a tab for a screen recording.

## Steps to reproduce
Screen Recording > Select Tab > Share

### Expected
I would like to automatically start the video recording when the user selects to share a tab.

### Actual
When recording a screen and choosing to record a browser tab the browser automatically switches to the selected tab once clicking "Share".  What this means is that the user has to navigate back to the tab where the videojs player is and initiate the recording, then switch back to the tab being recorded.  This causes confusion with the user as they don't know they have to click record after sharing the tab.  The browser implies it's recording the selected tab since it show's a rec recording indicator on the browser tab that was selected yet it's not recording.

**Comment by thijstriemstra** [comment]
What browser @mattdorst? Since this is browser-specific behavior it would be good to search the browser's bugs and find a ticket and/or open a new ticket if it's not there yet. And add the links to this ticket.

**Comment by thijstriemstra** [comment]
Closing because there's no feedback and it's a browser limitation videojs-record can't fix.
