### ISSUE TITLE
No examples of videojs-record methods

### ISSUE THREAD

**Issue by pbojinov** [collab-project/videojs-record#5]
For those who are not very familiar with `videojs`, it is not obvious, at first, that you can access the methods through the `recorder` object on a video instance. @thijstriemstra would you accept a PR with an example HTML file documenting how to use them?

``` javascript
// create video
var player = videojs('myAudio', {
    controls: true,
    width: 600,
    height: 300,
    plugins: {
        record: {
            audio: true,
            video: false,
            maxLength: 20
        }
    }
});

// recorder methods available through `recorder` object
player.recorder.isRecording()
player.recorder.getRecordType()
player.recorder.destroy()
```

**Comment by thijstriemstra** [comment]
hi @pbojinov, thanks for your feedback. If you could add these instructions to the README as well as the existing index.html, I will accept your PR, I would like to prevent adding more HTML example files.

**Comment by thijstriemstra** [comment]
Closing, no feedback, feel free to open a PR.
