### ISSUE TITLE
IE record for video+audio

### ISSUE THREAD

**Issue by zang** [collab-project/videojs-record#50]
I tried to record video+audio on IE and it seems only recorded audio as wav and no video. Is that the limitation with RecordRTC?

**Comment by thijstriemstra** [comment]
@zang what version of Internet Explorer? What version of Windows?

**Comment by zang** [comment]
@thijstriemstra 
IE Edge 25.105686.0.0
Window 10 Home

**Comment by thijstriemstra** [comment]
I've signed up for https://dev.windows.com/en-us/microsoft-edge/tools/remote/ and I'll take a look, haven't tested with IE at all.

**Comment by thijstriemstra** [comment]
Well, that sucked, there's no webcam/mic support for that remote desktop tool.

**Comment by thijstriemstra** [comment]
The RecordRTC [changelog](https://github.com/muaz-khan/RecordRTC/blob/master/RecordRTC.js#L27) mentions there's audio-only support for now in Edge.

**Comment by zang** [comment]
Thanks, and I will ask users to use Chrome on Windows.
