### ISSUE TITLE
Audio laggs on standard mobile browsers when recording audio+video

### ISSUE THREAD

**Issue by anantaramdas** [collab-project/videojs-record#502]
I have issues with implementing videojs-record in my project. it works absolutely as expected in Desktop browser however on both mobiles (Android and iPhone) it does not work - sound is slower than it should be and there is extra distortion.
On Android I tested both Edge (45.*) and Chrome (84.*) - behavior is the same.

I'm using:
"videojs-record": "^4.1.0"

I have found old ticker related to this https://github.com/collab-project/videojs-record/issues/71 which was ended by @thijstriemstra however I do not see that issue was resolved from my end.

Code is simple as this:
````
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

const videoJsOptions = {
    controls: true,
    bigPlayButton: false,
    width: 320,
    height: 240,
    fluid: false,
    plugins: {
        record: {
            audio: true,
            video: true,
            maxLength: 10,
            debug: true
        }
    }
};

ReactDOM.render(
    <React.StrictMode>
        <App { ...videoJsOptions }/>
    </React.StrictMode>,
    document.getElementById('root')
);

serviceWorker.unregister();
````

Please help what I'm doing wrong?

**Comment by thijstriemstra** [comment]
> sour is slower than it should be and there is extra.

extra..?

**Comment by anantaramdas** [comment]
sorry extra distortion during play. On desktop it is all ok.

**Comment by anantaramdas** [comment]
@thijstriemstra same is happening if I use https://collab-project.github.io/videojs-record

**Comment by thijstriemstra** [comment]
@anantaramdas can you try some of the recordrtc demos related to audio and see if it's the same problem there?

https://www.webrtc-experiment.com/RecordRTC/simple-demos/

**Comment by thijstriemstra** [comment]
ping @anantaramdas see prev comment

**Comment by anantaramdas** [comment]
Sorry yes Same issue

**Comment by thijstriemstra** [comment]
@anantaramdas 

> it works absolutely as expected in Desktop browser however on both mobiles (Android and iPhone) i

have you tested with latest iOS 14.4?

> On Android I tested both Edge (45.) and Chrome (84.) - behavior is the same.

Still happening with latest edge and chrome on android?

**Comment by thijstriemstra** [comment]
any feedback on previous comment @anantaramdas?

**Comment by thijstriemstra** [comment]
no feedback, closing.
