### ISSUE TITLE
ffmpeg.js plugin: converted result problem

### ISSUE THREAD

**Issue by wahono77** [collab-project/videojs-record#505]
## Description
I try https://github.com/collab-project/videojs-record/blob/master/examples/plugins/audio-only-ffmpegjs.html
I add this on top 

```html
<audio id="player" controls type="audio/mp3" src="" autoplay></audio>
```
and

```javascript
// converter completed and stream is available
player.on('finishConvert', function() {
    // the convertedData object contains the recorded data that
    // can be downloaded by the user, stored on server etc.
    var mp3result = URL.createObjectURL(player.convertedData);
    var htmlplayer = document.getElementById('player');
    htmlplayer.src = mp3result;
    htmlplayer.load();
    console.log('finished converting: ', player.convertedData);
});
```
But audio player from converteddata not loaded.
Any wrong step in my code?

Thanks in advance

**Comment by thijstriemstra** [comment]
related to #503 maybe?

**Comment by thijstriemstra** [comment]
I tested with the new ffmpeg.wasm plugin in videojs-record 4.2.0 and this worked fine.

I'm marking the ffmpeg.js plugin as deprecated, since it looks unmaintained and doesn't work properly. Use the ffmpeg.wasm plugin instead if you want a better working ffmpeg converter.

Closing this ticket.
