### ISSUE TITLE
How to save (download to the computer) converted video by ffmpeg?

### ISSUE THREAD

**Issue by aleksey-lav** [collab-project/videojs-record#506]
## Description
Hello! After recorded the video and converted it using plugin ffmpeg need to download it? How to do it? AFAIK I can't use method `saveAs 
`
## Steps to reproduce
this is my options for record 
```
record: {
    audio: useAudio,
    [type]: true,
    maxLength: 5 * 60,
    convertEngine: 'ffmpeg.js',
    convertOptions: ['-f', 'mp3', '-codec:a', 'libmp3lame', '-qscale:a', '2'],
    pluginLibraryOptions: {
      outputType: 'audio/mpeg',
    },
    convertWorkerURL: '/static/js/ffmpeg/ffmpeg.js/ffmpeg-mp4.js',
  },
```
and after converted I am getting the object in player.convertedData but if I want to save using `saveAs` from `npm` my video doesn't work since mp4 and each of devices (mobile also) can't open this video. What method I should use to download recorded video correctly in mp4 format? Thanks

### Expected
Need to download recorded video in format mp4!

### Actual
my video is saved in the format webm

**Comment by igasparetto** [comment]
This would be great!

**Comment by thijstriemstra** [comment]
I was able to save the .ogg file from the `audio-only-ffmpegjs.html` sample in Firefox/Ubuntu using ` player.record().saveAs({'audio': 'foo'});`

This isn't working for video? E.g. ` player.record().saveAs({'video': 'foo'});`?

**Comment by thijstriemstra** [comment]
> I was able to save the .ogg file from the audio-only-ffmpegjs.html sample in Firefox/Ubuntu using player.record().saveAs({'audio': 'foo'});

Hmm, not sure about this comment, because I'm also unable to download the file.

**Comment by thijstriemstra** [comment]
This will be supported in videojs-record 4.2.0 or newer with:

```javascript
player.record().saveAs({'video': 'foo'}, 'convert');
```
