### ISSUE TITLE
Could not load vmsg plugin (and other plugins as well)

### ISSUE THREAD

**Issue by fosteman** [collab-project/videojs-record#507]
## Description
Following instructions, when I am either adding vmsg engine or ts-ebml, or ffmpeg converter - plugins could not be loaded

## Steps to reproduce
https://collab-project.github.io/videojs-record/#/plugins/ffmpeg.js
https://collab-project.github.io/videojs-record/#/plugins/ts-ebml
https://collab-project.github.io/videojs-record/#/plugins/vmsg

### Error output
<img width="559" alt="Screen Shot 2020-09-11 at 10 44 50 AM" src="https://user-images.githubusercontent.com/32850517/92939451-d4d14400-f41b-11ea-8dfd-e84b6cc98b04.png">

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
```
"video.js": "^7.6.6",
"videojs-record": "4.1.0",
vmsg": "^0.3.6",
"ffmpeg.js": "^4.2.9003",
```

what version of videojs does this occur with?
Chrome latest
#### OSes
MacOS

**Comment by thijstriemstra** [comment]
I cannot reproduce this.
