### ISSUE TITLE
Firefox video quality

### ISSUE THREAD

**Issue by zang** [collab-project/videojs-record#51]
Using the default 640*480 setting on Firefox, and the recorded video seems in much lower quality compared with Chrome recorded video with 640*480 setting. I also tested on the recordrtc example page, and the Firefox video quality seems fine and match the chrome quality.  Is there any setting I can change to improve the Firefox video quality? 

All the tests performed on latest iMac with latest browsers.

Thanks in advance.

**Comment by thijstriemstra** [comment]
@zang can you compare the output of the recordrtc console log?

**Comment by zang** [comment]
**Example console from https://www.webrtc-experiment.com/RecordRTC/**

started recording video stream.
RecordRTC.js (line 105)
initializing video stream recorder.
RecordRTC.js (line 129)
Passing following config over MediaRecorder API. Object { type="video",  mimeType="video/webm",  disableLogs=false,  more...}
RecordRTC.js (line 1477)
Stopped recording video stream.
RecordRTC.js (line 154)
video/webm -> 2.20 MB
RecordRTC.js (line 182)
MediaStream.stop() is deprecated and will soon be removed. Use MediaStreamTrack.stop() instead.
button.stream.stop();

Object content:
disableLogs false
initCallback null
mimeType "video/webm"
type "video"

**Example console from videojs-record**

> var player = videojs(players[i], { controls: true, loop: false, plugins: { record: { audio: true, video: { mandatory: { minWidth: 640, minHeight: 480 } }, frameWidth: 640, frameHeight: 480, maxLength: 60 } } });

started recording video stream.
initializing video stream recorder.
Passing following config over MediaRecorder API. Object { type="video",  video={...},  canvas={...},  more...}
Stopped recording video stream.

Object content:
bitsPerSecond 128000
canvas Object { width=640,  height=480}
initCallback null
mimeType "video/webm"
type"video" video Object { width=640,  height=48

**Comment by thijstriemstra** [comment]
@zang I meant the videojs-record console output for Chrome versus Firefox, there must be something to see in the log that explains the quality difference.

**Comment by zang** [comment]
@thijstriemstra Chrome console log below:

started recording audio stream.
RecordRTC.10297.js:129 initializing audio stream recorder.
RecordRTC.10297.js:1704 StereoAudioRecorder is set to record number of channels:  2
RecordRTC.10297.js:2065 sample-rate 44100
RecordRTC.10297.js:2066 buffer-size 4096
RecordRTC.10297.js:105 started recording video stream.
RecordRTC.10297.js:129 initializing video stream recorder.
RecordRTC.10297.js:2438 Using frames-interval: 10
RecordRTC.10297.js:2509 canvas resolutions 640 * 480
RecordRTC.10297.js:2510 video width/height 640 * 480
RecordRTC.10297.js:154 Stopped recording audio stream.
RecordRTC.10297.js:154 Stopped recording video stream.
RecordRTC.10297.js:182 audio/wav -> 819 KB
RecordRTC.10297.js:182 video/webm -> 1.29 MB

I posted my recorder init script in the previous post. Is there anything I can set to bring Firefox same quality or have I missed something? :)

Thanks in advance.

**Comment by zang** [comment]
Would it be the 'bitsPerSecond 128000' affecting the quality? If so, is there a way not to pass it to media stream API? :)

**Comment by thijstriemstra** [comment]
@zang does [this RecordRTC](https://github.com/muaz-khan/RecordRTC/commit/6c3d5bd59e9017c6374432499cd021aad0d884c5) commit (log) help?

**Comment by thijstriemstra** [comment]
I suppose being able to set this value from videojs-record would be necessary, but confirming this fixes the issue would be nice first.

**Comment by zang** [comment]
fixed by upgrade recordrtc to latest commit. thanks.

**Comment by thijstriemstra** [comment]
Thanks for the update. Could you open a recordtrtc ticket and ask him to release a new version?
