### ISSUE TITLE
TypeError: Cannot read property 'deviceError' of undefined

### ISSUE THREAD

**Issue by dns-gh** [collab-project/videojs-record#510]
## Description
(let me know if this is a double of another issue, took a quick look and did not see it, thx !)
(maybe it's related to wavesurfer only...)
![videojs_error](https://user-images.githubusercontent.com/10922555/94115222-b4f14580-fe49-11ea-94ee-e78c8119d7c7.PNG)

Errors when loading the videojs + wavesurfer
- Cannot read property 'deviceError' of undefined
- Cannot read property 'deviceReady' of undefined

## Steps to reproduce
1. Go to https://collab-project.github.io/videojs-record/demo/audio-only.html
2. Open inspector

### Expected
No errors and ability to record audio

### Actual
When loading the test page (I have the same error on my web app), the error is displayed in the console

### Error output
VIDEOJS: Using video.js 7.8.4 with videojs-record 4.1.0, videojs-wavesurfer 3.3.0, wavesurfer.js 4.1.0 and recordrtc 5.6.1
video.min.js:12 VIDEOJS: Using wavesurfer.js WebAudio backend.
video.min.js:12 VIDEOJS: wavesurfer.js microphone plugin enabled.
video.min.js:12 VIDEOJS: ERROR: TypeError: Cannot read property 'deviceError' of undefined
    at e.value [as on] (observer.js:36)
    at h.value (videojs.wavesurfer.min.js:8)
    at HTMLDivElement.n (video.min.js:12)
    at HTMLDivElement.o.dispatcher.o.dispatcher (video.min.js:12)
    at pe (video.min.js:12)
    at l.trigger (video.min.js:12)
    at l.<anonymous> (video.min.js:12)
    at video.min.js:12
(anonymous) @ video.min.js:12
video.min.js:12 VIDEOJS: ERROR: TypeError: Cannot read property 'deviceReady' of undefined
    at e.value [as un] (observer.js:58)
    at i.value (videojs.record.min.js:8)
    at i.value (videojs.record.min.js:8)
    at HTMLButtonElement.o.dispatcher.o.dispatcher (video.min.js:12)

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
VIDEOJS: Using video.js 7.8.4 with videojs-record 4.1.0, videojs-wavesurfer 3.3.0, wavesurfer.js 4.1.0 and recordrtc 5.6.1
video.min.js:12 VIDEOJS: Using wavesurfer.js WebAudio backend.
video.min.js:12 VIDEOJS: wavesurfer.js microphone plugin enabled.
#### browsers
On chrome in private mode
#### OSes
Seen on windows

Thanks !

**Comment by thijstriemstra** [comment]
This is an issue with wavesurfer.js 4.1.0 (see https://github.com/katspaugh/wavesurfer.js/issues/2067). Please downgrade to wavesurfer.js 4.0.1 for now.

**Comment by dns-gh** [comment]
Thanks will try this !

**Comment by thijstriemstra** [comment]
wavesurfer.js 4.1.1 was released and fixed the issue.
