### ISSUE TITLE
Way to record system output audio?

### ISSUE THREAD

**Issue by Kkkassini** [collab-project/videojs-record#512]
## Description
Hello, is there a way to record system output audio instead of using the microphone to record exterior audio?

**Comment by thijstriemstra** [comment]
Yes, pick your audio device from the list, e.g. this is one my machine with 3 audio devices:

![audio-select](https://user-images.githubusercontent.com/305679/94488481-f8013f00-01e2-11eb-9516-ec7fd9b34c4e.png)

When I pick the one at the bottom, it'll record my VLC music playback.
