### ISSUE TITLE
Lower Pitch Audio (Garbled in Safari)

### ISSUE THREAD

**Issue by cogdog** [collab-project/videojs-record#520]
## Description
I've implemented audio only recording into a custom WordPress theme. My code uses the same settings and structure as the audio only demo combined with the lamejs plugin for saving as mp3.

A few people are reporting that their recordings come out with a lower pitch (on Firefox/Windows and another on Safari/OSX) I cannot reproduce on Firefox/Chrome. One sample

https://lab.cogdogblog.com/splotbox/2020/01/27/clints-groovy-test/

My tests on Safari/OSX actually end up garbled
https://splot.ca/box/2020/254/

## Steps to reproduce
Go to   https://splot.ca/box/share/ (use 3rd option under sharing). Record audio, select for saving, enter additional form field elements 

### Expected
A decent audio recording

### Actual
Some report lower pitches, I found garbled sound on Safari/OSX

## Additional Information

Safari Version 14.0 (14610.1.28.1.9) on OSX 10.14.6

#### videojs

```
VIDEOJS: Using video.js 7.6.6 with videojs-record 3.9.0, videojs-wavesurfer 2.11.0 and wavesurfer.js 3.3.0
video.min.js?ver=5.5.3:12 VIDEOJS: wavesurfer.js microphone plugin enabled.
video.min.js?ver=5.5.3:12 VIDEOJS: Pause microphone
video.min.js?ver=5.5.3:12 VIDEOJS: Loading object: {"lastModified":1604541587330,"lastModifiedDate":"2020-11-05T01:59:47.330Z","name":"1604541587330.mp3"}

started recording!
splotbox-recorder.js?ver=5.5.3:77 finished recording:  BloblastModified: 1604541587330lastModifiedDate: Wed Nov 04 2020 19:59:47 GMT-0600 (Central Standard Time) {}name: "1604541587330.mp3"size: 42631type: "audio/mp3"__proto__: Blob
splotbox-recorder.js?ver=5.5.3:148 

```

**Comment by thijstriemstra** [comment]
> My tests on Safari/OSX actually end up garbled

What versions of Safari? OSX? You haven't included any browser version. You're also using old versions of videojs-record, videojs-wavesurfer and video.js.

**Comment by cogdog** [comment]
Of course, I forgot I was using local versions of libraries. I had a problem with linking to hosted versions. Will retry and update. This was Safari Version 14.0 (14610.1.28.1.9) on OSX 10.14.6

**Comment by ignl** [comment]
There were some issues with safari 14 and MediaRecorder api. You can track results here: https://bugs.webkit.org/show_bug.cgi?id=85851
From that bug ticket it seems that everything should work and MediaRecorder should be enabled by default on Safari 14.1, so you can try to check beta version of newest safari to see if it works.

**Comment by thijstriemstra** [comment]
> From that bug ticket it seems that everything should work and MediaRecorder should be enabled by default on Safari 14.1

That would be great.

**Comment by thijstriemstra** [comment]
I tested with Safari Technology Preview 119 (Safari 14.1, WebKit 15611.1.10.1) just now and a forced `audioMimeType` of `audio/mp4` and there was no low pitched audio noticable. No other videojs-record options were changed.

Running `ffprobe` on the downloaded file shows:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/foo/Downloads/safari-8.mp4':
  Metadata:
    major_brand     : iso5
    minor_version   : 1
    compatible_brands: isomiso5hlsf
    creation_time   : 2021-01-31T22:56:41.000000Z
  Duration: 00:00:01.00, start: 0.000000, bitrate: 651 kb/s
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 639 kb/s (default)
    Metadata:
      creation_time   : 2021-01-31T22:56:41.000000Z
      handler_name    : Core Media Audio
```

Safari 14.0.2 showed some weird errors though, but once Safari 14.1 is released (and this is tested on iOS) I consider this fixed.

**Comment by thijstriemstra** [comment]
> forced audioMimeType of audio/mp4 

I added this change for safari to the examples here: https://github.com/collab-project/videojs-record/commit/24db0b37c328cf0eeef9ca032ed86b68b72aa6d0
