### ISSUE TITLE
Audio only displayMilliseconds false is not working

### ISSUE THREAD

**Issue by ignl** [collab-project/videojs-record#521]
## Description
Milliseconds are not removed in audio-only even if displayMilliseconds property is set to false.

## Steps to reproduce
Change to displayMilliseconds: false in https://collab-project.github.io/videojs-record/demo/audio-only.html

It seems to change only starting timestamp, but end and during recording it still shows milliseconds.

**Comment by thijstriemstra** [comment]
@ignl thanks for the report. What about other modes (video-only, audio+video etc), does it work ok there?

**Comment by ignl** [comment]
@thijstriemstra yes, it seems to be working correctly. In demo I don't see milliseconds.

**Comment by thijstriemstra** [comment]
Also disabling the option for the videojs-wavesurfer plugin fixes the issue:

```javascript
var options = {
    controls: true,
    bigPlayButton: false,
    width: 600,
    height: 300,
    fluid: false,
    plugins: {
        wavesurfer: {
            backend: 'WebAudio',
            waveColor: '#36393b',
            progressColor: 'black',
            displayMilliseconds: false, // <====
            debug: true,
            cursorWidth: 1,
            hideScrollbar: true,
            plugins: [
                // enable microphone plugin
                WaveSurfer.microphone.create({
                    bufferSize: 4096,
                    numberOfInputChannels: 1,
                    numberOfOutputChannels: 1,
                    constraints: {
                        video: false,
                        audio: true
                    }
                })
            ]
        },
        record: {
            audio: true,
            video: false,
            maxLength: 20,
            displayMilliseconds: false,
            debug: true
        }
    }
};
```

But I'll fix it so wavesurfer's `displayMilliseconds` will always match the `displayMilliseconds` of videojs-record, so you don't have to specify it twice.

**Comment by thijstriemstra** [comment]
> But I'll fix it so wavesurfer's displayMilliseconds will always match the displayMilliseconds of videojs-record, so you don't have to specify it twice.

Actually, it's less work to just update the examples and make sure the property is visible/enabled for every videojs-wavesurfer config (#542).
