### ISSUE TITLE
Safari macOS - play recorded video

### ISSUE THREAD

**Issue by bobyper** [collab-project/videojs-record#525]
## Description
Safari browser on MacOS cannot play recorded video
## Steps to reproduce
Just test demo example
https://collab-project.github.io/videojs-record/demo/audio-video.html

## Results
After recording and click on play, browser showing camera preview instead recorded video.
Tested on"High Sierra" and "Big Sur"

**Comment by pmaganti** [comment]
Safari is currently not supporting the Media Recorder. 
```
VIDEOJS: – "ERROR:" – "Your browser does not support the Media Recorder API. Please try other modules e.g. WhammyRecorder or StereoAudioRecorder."
(anonymous function) — video.min.js:12:796
(anonymous function) — video.min.js:12:10970
fe — video.min.js:12:11735
(anonymous function)
bound
(anonymous function) — video.min.js:12:10946
warningLog — RecordRTC.js:344
```

**Comment by bobyper** [comment]
No, this is not a problem. You must enable Media Recorder from Safari Delevop menu. 
Develop -> Experimental Features -> MediaRecorder.
In this case, Safari recorded a video in mp4 format. I can upload video from Safari to server or save local but cannot preview what is recorded.

**Comment by pmaganti** [comment]
@bobyper I totally understand that this can get it to work by enabling **Experimental Features** but to me, that is only a developer workaround. 

Correct me if I am wrong but suggesting to enable an Experimental Feature is not a solution that is acceptable since you or I or anybody else who is developing a real product will never ask End users to enable them to use it.

**Comment by ignl** [comment]
Since IOS 14.3 MediaRecorder should be enabled by default. I can also confirm the same bug.

**Comment by thijstriemstra** [comment]
I tested this on macOS Safari Tech Preview 119 (Safari 14.1, WebKit 15611.1.10.1) and the recorded video can be played there correctly.

If it also works on iOS 14.4 (I'll test later) I will consider this ticket fixed, because eventually a Safari desktop release will include the fix.
