### ISSUE TITLE
Not able to record video

### ISSUE THREAD

**Issue by sourabh-prologic** [collab-project/videojs-record#526]
I am unable to record video using an OBS (Green Screen) camera. The recording process is working fine with other cameras and also my OBS camera is working fine with TokBox Live Video Calling functionality.

Can you help me out in this? I am not getting any error either. It shows like it is recording the video but the blob data is empty when stop recording

**Comment by thijstriemstra** [comment]
>  The recording process is working fine with other cameras and also my OBS camera is working fine with TokBox Live Video Calling functionality.

@sourabh-prologic can you show a screenshot of the camera/mic dialog of browser it's working in?

But more importantly, what browser/operating system versions are you using?

**Comment by thijstriemstra** [comment]
No feedback, closing.
