### ISSUE TITLE
Force Firefox to record video/audio separately 

### ISSUE THREAD

**Issue by zang** [collab-project/videojs-record#53]
Is there a way to force Firefox to record video and audio separately (similar to Chrome)? The reason is that the default recorded webm got audio issues when uploaded to YouTube, Vimeo or transcode with ffmpeg. I saw other people have the same issue and reported on https://www.webrtc-experiment.com/RecordRTC/AudioVideo-on-Firefox.html

[To reproduce the issue]
1) Record video+audio as single webm
2) Either upload it to youtube OR encode the video to mp4 using ffmpeg OR play the video on VLC
3) Audio breaks

I also tried to extract both video and audio steams from recorded webm, and then merge them to a new webm. but, that didn't work either. (I am using latest version of videojs-record, recordrtc, firefox and ffmpeg)

**Comment by zang** [comment]
@thijstriemstra , is there a way to force firefox to record video/audio seperately? e.g. set isChrome is true or something like that. I don't particularly like this approach, but there seems no other way to fix the firefox encoder issue. I really want to support Firefox, any advice would be appreciated. :)

**Comment by thijstriemstra** [comment]
@zang videojs-record uses recordrtc for recording by default and i would ask thebquestion in that project and open ticket there.

**Comment by zang** [comment]
@thijstriemstra thanks a lot, much appreciated :)

**Comment by zang** [comment]
@thijstriemstra I've found the following code example from Muaz Khan's response, and wondering if that would help to build the logic into videojs-record? Sorry that I am able to tell based on my limited javascript knowledge. :(

`
var audioStream = new MediaStream();
var videoStream = new MediaStream();

audioStream.addTrack(originalStream.getAudioTracks()[0]);
videoStream.addTrack(originalStream.getVideoTracks()[0]);

var audioRecorder = RecordRTC(audioStream, {
    type: 'audio'
});

var videoRecorder = RecordRTC(videoStream, {
      type: 'video'
});
`

**Comment by thijstriemstra** [comment]
@zang looks like recordrtc 5.2.9 added ability to select specific audio/video recorder type but no way to record streams seperately yet.

**Comment by zang** [comment]
thanks @thijstriemstra , do you think that could solve the firefox audio encoder issue?  I can give it a try, it will be great if you can let me know how to set the recorder type within videojs-record :)

**Comment by thijstriemstra** [comment]
Recordrtc doesn't allow you to separate the audio/video yet so I don't think your issue is solved yet. But specifying the `audioRecorderType` and `videoRecorderType` can be done like:

```javascript
var player = videojs("myVideo",
{
    // video.js options
    controls: true,
    loop: false,
    width: 320,
    height: 240,
    plugins: {
        // videojs-record plugin options
        record: {
            audio: true,
            video: true,
            maxLength: 5,
            debug: true,
            audioRecorderType: StereoAudioRecorder,
            videoRecorderType: WhammyRecorder
        }
    }
});
```

**Comment by zang** [comment]
thanks @thijstriemstra . :) I will give it a try later on and post the results here.

**Comment by zang** [comment]
Upgraded videojs.record to latest and upgraded recordrtc to 5.2.9
Using the following code to setup the recorder:

{ record: { audio: true, video: { mandatory: { minWidth: 640, minHeight: 480 } }, frameWidth: 640, frameHeight: 480, audioRecorderType: "StereoAudioRecorder", videoRecorderType: "WhammyRecorder", maxLength: 60 }

Recorded the video on firefox and ffprobe info below: 
Input #0, matroska,webm, from 'firefox.webm':
  Metadata:
    encoder         : QTmuxingAppLibWebM-0.0.1
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp8, yuv420p, 640x480, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: vorbis, 44100 Hz, mono, fltp (default)


@thijstriemstra , It seems using the default firefox audio and video encoder rather than the specified ones. Have I missed anything? :)

**Comment by thijstriemstra** [comment]
You should use the javascript class name not a string value, e.g. WhammyRecorder without quotes.

**Comment by zang** [comment]
@thijstriemstra , I tried that as well, and I got the following error on firefox:

TypeError: riff.RIFF is undefined

I think it might be caused by lack of WebP support on Firefox.

**Comment by thijstriemstra** [comment]
@zang something I'd ask @muaz-khan

**Comment by thijstriemstra** [comment]
Looks like 5.3.0 works around that error on firefox.

**Comment by zang** [comment]
@thijstriemstra , I've tried with the following on Firefox (5.3.0):
audio: StereoAudioRecorder,  video: MediaStreamRecorder   

And the recorded file got no audio stream, ffprobe info below:

Metadata:
    encoder         : QTmuxingAppLibWebM-0.0.1
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp8, yuv420p, 640x480, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)

**Comment by zang** [comment]
I can manage to get around now. closing this ticket.
