### ISSUE TITLE
device error: DOMException: Could not start video source

### ISSUE THREAD

**Issue by ishwarid** [collab-project/videojs-record#533]
## Description
Complete error output 
device error: DOMException: Could not start video source
(anonymous) @ applicationVideo.js:376
i.dispatcher.i.dispatcher @ video.es.js:1935
en @ video.es.js:2073
trigger @ video.es.js:2965
onDeviceError @ videojs.record.js:638
Promise.catch (async)
getDevice @ videojs.record.js:460
l @ applicationVideo.js:425
dispatch @ jquery.js:4670
v.handle @ jquery.js:4490

## Steps to reproduce
Not able to record  video in windows 10 chrome browser getting above error when started recording 

### Expected
Same code working on Mac chrome browser

version:
"videojs-record": "^4.0.0"

**Comment by thijstriemstra** [comment]
@ishwarid this usually means the webcam/video device is not connected or being used by a different application or webpage. Can you doublecheck this?

**Comment by thijstriemstra** [comment]
no feedback, closing.
