### ISSUE TITLE
video recording is missing metadata information.

### ISSUE THREAD

**Issue by Alferdize** [collab-project/videojs-record#535]
## Description
I implement Record Video from videojs-record (Using with Angular). But when Record Video success, I save the video to my computer. This video is missing information: Time Length, Frame Width, Frame height
Can you help me add this information for video after record?

## Configuration Options
```
    this.config = {
      preload: 'metadata',
      controls: true,
      width: 320,
      height: 240,
      fluid: false,
      bigPlayButton: false,
      controlBar: {
        volumePanel: false
      },
      plugins: {
        record: {
          audio: false,
          video: true,
          maxLength: 20,
          debug: true,
          displayMilliseconds: false,
          convertEngine: 'ts-ebml'
        }
      }
    };
```

```
ngAfterViewInit() {
    // ID with which to access the template's video element
    let el = 'video_' + this.idx;

    // setup the player via the unique element ID
    this.player = videojs(document.getElementById(el), this.config, () => {
      console.log('player ready! id:', el);

      // print version information at startup
      var msg = 'Using video.js ' + videojs.VERSION +
        ' with videojs-record ' + videojs.getPluginVersion('record') +
        ' and recordrtc ' + RecordRTC.version;
      videojs.log(msg);
    });

    // device is ready
    this.player.on('deviceReady', () => {
      console.log('device is ready!');
    });



    // user clicked the record button and started recording
    this.player.on('startRecord', () => {
      console.log('started recording!');
    });

    this.player.on('startConvert', () => {
      console.log('started converting!');
    });

    // user completed recording and stream is available
    this.player.on('finishRecord', () => {
      // recordedData is a blob object containing the recorded data that
      // can be downloaded by the user, stored on server etc.
      var result = this.injectMetadata(this.player.recordedData);
      this.player.record().saveAs({ 'video': 'my-video-file-name.webm' });
      console.log(result)
      console.log('finished recording: ', this.player.recordedData);

    });

    this.player.on('finishConvert', () => {

      console.log('finished converting: ', this.player.convertedData)
    })

    // error handling
    this.player.on('error', (element, error) => {
      console.warn(error);
    });

    this.player.on('deviceError', () => {
      console.error('device error:', this.player.deviceErrorCode);
    });
  }

```

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

## Results
finished converting:  
Blob {lastModified: 1611129573902, lastModifiedDate: Wed Jan 20 2021 13:29:33 GMT+0530 (India Standard Time), name: "1611129573902.mkv", size: 109964, type: "video/x-matroska;codecs=avc1"}
lastModified: 1611129573902
lastModifiedDate: Wed Jan 20 2021 13:29:33 GMT+0530 (India Standard Time) {}
name: "1611129573902.mkv"
size: 109964
type: "video/x-matroska;codecs=avc1"
### Expected
MetaData Contains Time Length, Frame Width, Frame height
### Actual
Conversion Is not working.

## Additional Information
VIDEOJS: Using video.js 7.10.2 with videojs-record 4.1.1 and recordrtc 5.6.1
#### videojs 7.10.2
what version of videojs does this occur with?
#### browsers
Chorme, Firefox with the latest version.
#### OSes
Windows 10.

**Comment by thijstriemstra** [comment]
This is a known browser issue. You can use the ts-ebml plugin to create seekable files: https://collab-project.github.io/videojs-record/#/plugins/ts-ebml Or use ffmpeg on the client (https://collab-project.github.io/videojs-record/#/plugins/ffmpeg.wasm) or server to convert the files and add metadata.

**Comment by Alferdize** [comment]
>  (https://collab-project.github.io/videojs-record/#/plugins/ffmpeg.wasm) 
This plugin is missing in the plugin folder
`Module not found: Error: Can't resolve 'videojs-record/dist/plugins/videojs.record.ffmpeg-wasm.js' in 'E:\NO_NAME\Angular\photo-id-verification\src\app\views\dashboard'`

**Comment by thijstriemstra** [comment]
yea 4.2.0 is not released yet.

**Comment by Alferdize** [comment]
When it is going to release Since ts-ebml is not adding metadata in video.
![Screenshot (106)](https://user-images.githubusercontent.com/33134277/107033894-f290b280-67db-11eb-93b8-bb766a39d26c.png)
is not adding the metadata like frame rate duration

**Comment by thijstriemstra** [comment]
how did you download that file @Alferdize?

**Comment by Alferdize** [comment]
```
this.player.on('finishConvert', () => {
          // show save as dialog
          this.player.record().saveAs({'video': 'my-video-file-name.mp4'}, 'convert');
      });
```

**Comment by thijstriemstra** [comment]
@Alferdize so you build videojs-record from source? what version are you using?

**Comment by Alferdize** [comment]
VIDEOJS: Using video.js 7.10.2 with videojs-record 4.1.1 and recordrtc 5.6.1

**Comment by thijstriemstra** [comment]
Right. Wait for videojs-record 4.2.0 or build it from source.
