### ISSUE TITLE
ffmpeg.js plugin: cannot import convertWorkerURL

### ISSUE THREAD

**Issue by aphavichitr** [collab-project/videojs-record#536]
## Description
I'm trying to add ffmpeg.js in my Vue.js + Nuxt.js project. I've imported the convertWorkerURL as shown in the example on https://collab-project.github.io/videojs-record/#/plugins/ffmpeg.js, however when after I record i'm getting undefined for the this.player.convertedData object. My guess is either I'm importing it wrong or there's some issue with the library's options for this plugin.

## Steps to reproduce
Using the following options:

```javascript
convertEngine: 'ffmpeg.js',
    // convert recorded data to MP3
    convertOptions: ['-f', 'mp3', '-codec:a', 'libmp3lame', '-qscale:a', '2'],
    // specify output mime-type
    pluginLibraryOptions: {
        outputType: 'audio/mpeg'
    },
    // use MP4 encoding worker (H.264 & AAC & MP3 encoders)
    convertWorkerURL: '../../node_modules/ffmpeg.js/ffmpeg-worker-mp4.js'
```

After recording, this.player.convertedData is undefined

### Expected
Should be able to see the convertedData

### Actual
Seeing undefined value

### Error output
N/A

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
4,.1.1
#### browsers
Chrome
#### OSes
Mac

**Comment by thijstriemstra** [comment]
> I'm trying to add ffmpeg.js in my Vue.js + Nuxt.js project. 

Not sure, I can't help debugging projects with external frameworks and no error messages.

I'm marking the ffmpeg.js plugin as deprecated, since the library looks unmaintained and doesn't work properly. Use the ffmpeg.wasm plugin instead.

Closing this ticket.
