### ISSUE TITLE
How do you set different videoMimeTypes for different browsers

### ISSUE THREAD

**Issue by aphavichitr** [collab-project/videojs-record#538]
## Description
I'm trying to record all videos in mp4 format to support all browsers, since I can't get ffmpeg to work for converting .webm to .mp4 format. In the docs it says "Use video/mp4 (Firefox) or video/webm;codecs=H264 (Chrome 52 and newer) for MP4". How does this library determine when a user is recording from a specific browser eg. firefox or chrome or ie, and is able to change the videoMimeType in the options? I didn't see this in the documentation. 

Also I found another issue about recording in mp4 format by using the videoMimeType: video/webm;codecs=H264, and just by changing the file extenstion from to webm to mp4 it will automatically convert or be in that video format?

## Steps to reproduce
Only able to enter one videoMimeType in the options, not sure how to change it for each browser.

### Expected
Videos should be recorded in mp4 format for each browser.

### Actual
Can only record in .webm in chrome at the moment, haven't been able to record in mp4 yet.

### Error output
N/A

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
4.1.1
#### browsers
Chrome/Firefox/Safari/IE
#### OSes
Mac

**Comment by aphavichitr** [comment]
@thijstriemstra do you have an example of how to set the options for the type of browser someone is using when recording? How do you set mp4 for firefox and webm for chrome? Also how do you do this while also converting the video to the other format with ffmpeg?

**Comment by thijstriemstra** [comment]
> How does this library determine when a user is recording from a specific browser eg. firefox or chrome or ie, and is able to change the videoMimeType in the options? I didn't see this in the documentation.

The default `videoMimeType` is listed in the docs ('Default' column): https://collab-project.github.io/videojs-record/#/options

> Also I found another issue about recording in mp4 format by using the videoMimeType: video/webm;codecs=H264, and just by changing the file extenstion from to webm to mp4 it will automatically convert or be in that video format?

What issue? The filename and extension is just a wrapper, you can rename it to whatever you want, but the content inside won't change when you rename it.

> do you have an example of how to set the options for the type of browser someone is using when recording? How do you set mp4 for firefox and webm for chrome? Also how do you do this while also converting the video to the other format with ffmpeg?

Check for the browser, Safari for example:

```javascript
var isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
```

And set options based on that:

```javascript
let options = {
    controls: true,
    bigPlayButton: false,
    controlBar: {
        // hide fullscreen and volume controls
        fullscreenToggle: false,
        volumePanel: false
    },
    width: 320,
    height: 240,
    plugins: {
        // videojs-record plugin options
        record: {
            audio: false,
            video: true,
            maxLength: 5,
            debug: true,
            videoMimeType: 'video/webm',
            displayMilliseconds: true
        }
    }
};

if (isSafari) {
    options.plugins.record.videoMimeType = 'video/mp4';
}

// now create the player etc
```

**Comment by aphavichitr** [comment]
@thijstriemstra just want to confirm by setting the videoMineType to 'video/webm;codecs=H264' for Chrome as stated in the docs and by saving it in .mp4 format it doesn't work (can't playback), if i change it to .mkv it works. Also in the debug console it outputs as type: "video/x-matroska;codecs=avc1,opus". I just wanted to confirm if this is broken and that the only way to record in Chrome is to use ffmpeg? I've already tried everything and have exhausted all options.

Would you be willing to help me take a look at my codebase and check my configuration? I would really appreciate your expertise in this area since video recording is very new to me and of course would pay for your time. We have launched this feature in production for about almost 3 weeks now, and users are only able to record in .webm format on Chrome, however I have to manually convert each video to .mp4 with the ffmpeg script "ffmpeg -i video.webm video.mp4" so that it can be played back in each browser. Obviously this is not scalable as we're getting more and more video recordings each day. Thanks in advance!

**Comment by thijstriemstra** [comment]
> Would you be willing to help me take a look at my codebase and check my configuration?  I would really appreciate your expertise in this area since video recording is very new to me and of course would pay for your time. 

Sure, I'll send you an email and we can go from there. Whats your email address?

**Comment by aphavichitr** [comment]
> > Would you be willing to help me take a look at my codebase and check my configuration?  I would really appreciate your expertise in this area since video recording is very new to me and of course would pay for your time.
> 
> Sure, I'll send you an email and we can go from there. Whats your email address?

andrew@riveterworks.com

thanks!

**Comment by heeropunjabi** [comment]
@thijstriemstra @aphavichitr any output on the conversation. please share it will be helpful :)
