### ISSUE TITLE
Recorder freezes on Chrome 49 beta

### ISSUE THREAD

**Issue by alsar** [collab-project/videojs-record#54]
When i hit the record button it doesn't start to record, but it just freezes after a few seconds.
The console output shows that the recorder tries to initialize the MediaRecorder API over and over again until it crashes the browser.

![selection_009](https://cloud.githubusercontent.com/assets/1380676/13195996/12f929c6-d7c2-11e5-9766-a3ab23786396.png)

On Chrome 48 it works without a problem.

On the WebRTC example it works without a problem on Chrome 49 beta: https://webrtc.github.io/samples/src/content/getusermedia/record/

**Comment by zang** [comment]
I can reproduce this issue on MRecordRTC demo page as well with Chrome 49. I think there might be conflicts between MRecordRTC() and RecordRTC() on handling audio stream. @thijstriemstra , what do you think?

**Comment by thijstriemstra** [comment]
@zang if you can reproduce it with the mrecordrtc demo, please file a ticket in recordrtc (as well).

**Comment by zang** [comment]
Created the ticket at https://github.com/muaz-khan/RecordRTC/issues/92

@thijstriemstra , @alsar , does Chrome 49 generate video/audio in single webm? If so, any impact to videojs-record?

**Comment by alsar** [comment]
@zang Chrome 49 finally implements the MediaRecorder API and generates a single file.

**Comment by zang** [comment]
RecordRTC.js line 892: 
I replaced isChrome with isMediaRecorderCompatible() and it seems to work now. Unsure of other conditions in that line though.

**Comment by zang** [comment]
p.s. Chrome 49+ supports 720p well.

**Comment by thijstriemstra** [comment]
Can you link the recordrtc PR here @zang?

**Comment by zang** [comment]
https://github.com/muaz-khan/RecordRTC/pull/94

**Comment by thijstriemstra** [comment]
@zang so this is fixed with the latest recordrtc?

**Comment by alsar** [comment]
Yes it is. I tested it and it works.
