### ISSUE TITLE
This browser does not support navigator.mediaDevices.getUserMedia (when connecting externally, localhost connections work)

### ISSUE THREAD

**Issue by bmsan** [collab-project/videojs-record#548]
## Description
Using an nginx as an webserver to serve a static page containing videojs-record.
When connecting through localhost everything works ok. (I can access the webcam & record)

When connecting externally to the same server I get the following error:

```
This browser does not support navigator.mediaDevices.getUserMedia
(anonymous) @ (index):223
o.dispatcher.o.dispatcher @ video.min.js:12
ve @ video.min.js:12
trigger @ video.min.js:12
getDevice @ videojs.record.js:2576
handleClick @ videojs.record.js:590
o.dispatcher.o.dispatcher @ video.min.js:12
```

I am using:
VIDEOJS: Using video.js 7.11.4 with videojs-record 4.2.0 and recordrtc 5.6.1

This happens with both chrome & firefox (working locally, not working externally)
Chrome version: Version 88.0.4324.150 (Official Build) (64-bit)
Firefox version: 85.0.2 (64-bit)
OS: Windows 10

I am not sure what the difference could be going from localhost to an external server that could cause this issue.
I'm sure this is something I might be to blame, since the videojs-record online examples work remote but I am not sure how to digg into this problem.

Any advice is welcomed.

**Comment by thijstriemstra** [comment]
getUserMedia requires https.

**Comment by bmsan** [comment]
@thijstriemstra thank you!
