### ISSUE TITLE
How to retrigger "deviceReady" after stopping&re-starting device 

### ISSUE THREAD

**Issue by bmsan** [collab-project/videojs-record#549]
## Description
When calling player.record().getDevice() for the first time, I will see 'deviceReady' being triggered by the player.
If I stop the video & then recall getDevice() the browser will request video/audio permissions again, the video will start but  'deviceReady' won't get triggered again.

## Steps to reproduce
```
1.player.record().getDevice()
2. wait for deviceReady
3. player.record().enumerateDevices();
4. Wait for enumerateReady & select one of the video input devices
5. Try to stop the webcam and bring everything to the "initial state" such that I can rely on deviceReady(or something similar) when accessing getDevice again.
6. player.record().getDevice() <-- at this point I am not sure how detect when the webcam is turned on the second time(deviceReady doesn't seem to trigger the second time).
```
## Player Options
```
var options = {
    controls: true,
    bigPlayButton: false,
    width: 384,
    height: 216,
    fluid: false,
    controlBar: {
        fullscreenToggle: false,
        pipToggle: false,
        liveDisplay: true,
        pictureInPictureToggle: false,
        volumePanel: false,
        cameraButton: false,
        recordToggle: false
    },
    plugins: {
        record: {
            audio: true,
            video: {
                width: { min: 1280, ideal: 1280, max: 1280 },
                height: { min: 720, ideal: 720, max: 920 }
            },
            // dimensions of captured video frames
            frameWidth: 1280,
            frameHeight: 720,
            maxLength: 60,
            displayMilliseconds: false,
            debug: true
        },
        
    }
};

```

## Expected behavior
A way to find out when the device starts operating the second time (either by retriggering 'deviceReady' or some other callback mechanism).

To stop the video I have tried the following
```
opt1: 
       player.record().stopDevice();
opt2:
    player.record().stopDevice();
    player.record().reset();
opt3:
    player.record().stopDevice();
    player.record().reset();
    player.reset();

```

## Versions used
VIDEOJS: Using video.js 7.11.4 with videojs-record 4.2.0 and recordrtc 5.6.1

## Browser
Version 88.0.4324.182 (Official Build) (64-bit)

## OS 
Windows

**Comment by thijstriemstra** [comment]
> If I stop the video 

Stop what exactly? Please be as specific as possible.

**Comment by bmsan** [comment]
@thijstriemstra  Thanks for the lightning fast response & sorry for not being very clear !
 
I encountered this in "live preview mode"(seeing the live webcam contents) before actually pressing the "record" button. 

The steps made were
```
1.player.record().getDevices()
2. wait for deviceReady
3. player.record().enumerateDevices();
4. Wait for enumerateReady & select one of the video input devices
5. Try to stop the webcam and bring everything to the "initial state" such that I can rely on deviceReady(or something similar) when accessing getDevice again.
```  
 Basically I want to implement a start/stop Webcam toggle button and I was trying to get a consistent event for  its "on state"(deviceReady seemed like a good idea initally).

**Comment by bmsan** [comment]
For further reference I also added the player options configuration in the initial comment.

**Comment by thijstriemstra** [comment]
> 5. Try to stop the webcam and bring everything to the "initial state" such that I can rely on deviceReady(or something similar) when accessing getDevice again.

How are you doing this? You should use `stopDevice`, see https://collab-project.github.io/videojs-record/#/methods

**Comment by bmsan** [comment]
I've tried using the following 3 methods:

```
opt1: 
       player.record().stopDevice();
opt2:
    player.record().stopDevice();
    player.record().reset();
opt3:
    player.record().stopDevice();
    player.record().reset();
    player.reset();
```

**Comment by bmsan** [comment]
The issue was totally on my side and a very stupid mistake. 

I was using the callback registration code from one of the demos and I didn't notice that for the `deviceReady` callback registration `player.one(...)` was called instead of `player.on(...)` so it was called once.
Please note that I was blind enough to also miss the comment `// enumerate devices once`

// The discussion below is a different topic and I can create a different thread if it makes sense to you.
@thijstriemstra All of this made me dig a little bit into videojs-record and I wanted to ask you if it would make sense to you
to add a safeguard against a potential resource leak (which would be caused by users not using properly your library).
More specifically if the user uses improperly videojs-record with external triggers(user defined buttons) and starts the webcam two times two MediaStreams will get created and on stop() only one of them will be released.
``` 
//videojs.record.js
value: function onDeviceReady(stream) {
....
// At this point this.stream could already be initialized,
// if the user didn't properly dispose of it the resource would never be released.
// ( the webcam would remain on after player.record().stopDevice() ).
this.stream = stream;
 ```
So a safeguard could look something like:
```
 if stream_is_initialized(this) {
    this.stream.getTracks().forEach(track => track.stop());
}
```

**Comment by thijstriemstra** [comment]
thanks for that report, can you open a new ticket for that?

**Comment by bmsan** [comment]
Thanks! Created https://github.com/collab-project/videojs-record/issues/561
