### ISSUE TITLE
how to improve the quality of screenshot took by exportImage() function in videojs-record

### ISSUE THREAD

**Issue by MohitVerma786** [collab-project/videojs-record#550]
## Description
i'm trying to grab the screenshot by start recording the creen and using built in exportImage function but the output of the image is so low when i converts the blob into base64

```javascript
// video.js configuration
    this.config = {
      controls: false,
      bigPlayButton: false,
      loop: false,
      width: 640,
      height: 480,
      fluid: false,
      plugins: {
          record: {
              screen: true,
              image:true,
              maxLength: 30,
              displayMilliseconds: false,
              debug: true,
          }
      } 
    };
async getVPDetails(): Promise<any> {
    return await this.player.record().exportImage('image/png', 1);
  }
  takeScreenshot(){
      this.getVPDetails().then(data => {
          var unsafeImageUrl = URL.createObjectURL(data);
          this.imageData = this.sanitizer.bypassSecurityTrustUrl(unsafeImageUrl);
      }, error => {
          console.log(error);
      
      });
  }
```

## Image I'm getting
https://i.stack.imgur.com/D4Q1v.png

## Expected Result
I want maximum quality image

**Comment by thijstriemstra** [comment]
There are no other options, you're already using image/png with full quality. The browsers out there don't provide any better quality options unfortunately.

**Comment by MohitVerma786** [comment]
@thijstriemstra is there any way to grab a single fame of same quality of recoding of video and save it as a image....?
