### ISSUE TITLE
Chrome constraints 

### ISSUE THREAD

**Issue by zang** [collab-project/videojs-record#56]
What's the best way to let browsers use 720p?

Experiment 1 
_video: { mandatory: { minWidth: 1280, minHeight: 720 } }, frameWidth: 1280, frameHeight: 720,_
It works fine on my iMac fine. However, it throws media constrain error on my Mac air. 

Experiment 2
_video: {
  width: { min: 640, ideal: 1280, max: 1280 },
  height: { min: 480, ideal: 720, max: 720 },
}, frameWidth: 1280, frameHeight: 720,_
It always chooses 640x480 although my webcams support 1280x720

Experiment 3
video: { width: { exact: 1280 }, height: { exact: 720 } } , frameWidth: 1280, frameHeight: 720,

Video still recorded in 640x480

**Comment by thijstriemstra** [comment]
What media constraint error do you see on your mac?

**Comment by zang** [comment]
@thijstriemstra I got the following error on Chrome 50, Mac Air

NavigatorUserMediaError {name: "ConstraintNotSatisfiedError", message: "", constraintName: "width"}

**Comment by thijstriemstra** [comment]
@zang what if you include http://webrtc.github.io/adapter/adapter-latest.js before every other js script?

**Comment by zang** [comment]
Thanks, will try.

**Comment by vojka** [comment]
With https://webrtc.github.io/adapter/adapter-latest.js it works on Chrome 49.

**Comment by thijstriemstra** [comment]
Thanks for the feedback @vojka. A pull request adding this info to the media constraints section in the readme is always welcome.

**Comment by zang** [comment]
It doesn't seem to work for me on Chrome 49. Console log:

adapter.js shimming chrome!
constraintName "minHeight"
message ""
name "ConstraintNotSatisfiedError"

Recorder setup as:
record: { audio: true, video: { mandatory: { minWidth: 1280, minHeight: 720 } }, frameWidth: 1280, frameHeight: 720

**Comment by thijstriemstra** [comment]
This [comment](https://github.com/samdutton/simpl/issues/62) suggests the camera doesn't support the resolution but you're saying it's working in Firefox so that can't be the issue then..

**Comment by thijstriemstra** [comment]
Here's a very complete examination of constraints: https://webrtchacks.com/video-constraints-2/

**Comment by zang** [comment]
Thanks, Chrome seems still use the old constraints and all seems ok with setting up maxWidth option.
