### ISSUE TITLE
Safeguard against a potential resource leak(media streams) due to user missuse 

### ISSUE THREAD

**Issue by bmsan** [collab-project/videojs-record#561]
## Description 
Users improperly using videojs-record with external triggers(user defined buttons) might call 
 `player.record().getDevice();` multiple times before trying to use `stopDevice()`.
In this case multiple media streams would get created but only the last one would be freed when calling `stopDevice()`
The implication would be that the webcam would remain on even after `stopDevice()` is called.
 
## When would this situation be encountered?
```
Eg: let's say the user creates an external button "start webcam" which calls getDevice, 
but doesn't handle thoroughly the state of the system to see if it is actually ok to call getDevice. 
Someone visiting the website might press that button multiple times 
(maybe he doesn't notice the the request for video/audio permissions) after the first press.
``` 

## Potential way to add an extra safeguard

Before 
```
//videojs.record.js
value: function onDeviceReady(stream) {
....
// At this point this.stream could already be initialized,
// if the user didn't properly dispose of it the resource would never be released.
// ( the webcam would remain on after player.record().stopDevice() ).
this.stream = stream;
```
With a safeguard things could look something like:
```
//videojs.record.js
value: function onDeviceReady(stream) {
....
 if stream_is_initialized(this) {
    this.stream.getTracks().forEach(track => track.stop());
}
this.stream = stream;
```

**Comment by bmsan** [comment]
Update: I realized that this is actually happening even in one of the existing demos: https://collab-project.github.io/videojs-record/demo/change-video-input.html
On my laptop switching between 2 camera devices faster than they are initialized will end up getting one of the cameras always on.
(I've tested this on Chrome, Firefox and Opera on Windows10)

**Comment by thijstriemstra** [comment]
Looks like we'll have to check for `stream.active`, see https://developer.mozilla.org/en-US/docs/Web/API/MediaStream/active

Can you check if that works @bmsan (and maybe even make a pull request if it does)?

**Comment by bmsan** [comment]
Sure, I'll take a look and report back

**Comment by bmsan** [comment]
I have created #562 
Tested against:  Chrome, Firefox and Opera on Windows10.

Test description: 
- Test1: In change-video-input with 2 webcams connected, change fast the input device two times(before the webstream starts to get streamed). 
- Test2: Call getDevice() multiple times

Expected Test result: 
Calling stopDevice() will close all streams opened in the tests.

**Comment by bmsan** [comment]
@thijstriemstra If you have in your mind other tests that should be done, or if you think the solution might be better done at a different level then in the onDeviceReady Callback, I could try to take a look in my spare time.

**Comment by thijstriemstra** [comment]
having a unit test or two for this change would be nice. basically your tests incorporated in a unit test.

**Comment by bmsan** [comment]
Sure, I'll have a look in my spare time
