### ISSUE TITLE
How to start recording right away?

### ISSUE THREAD

**Issue by therealgilles** [collab-project/videojs-record#563]
When the player appears on the screen, there is a camera/microphone icon to click on and then I need to hit the record button. Is there a way to either bypass the first step or the second step so that I don't have to do two actions before starting to record?

I cannot seem to find any example with this behavior. Thank you for any insight :)

**Comment by thijstriemstra** [comment]
you cannot bypass the browser requirement of asking a user to confirm the webcam/mic can be used. Clicking on that first button can be done programmatically with:

```javascript
player.record().getDevice()
```

Clicking on that second button is the same as:
```javascript
player.record().start()
```
see https://collab-project.github.io/videojs-record/#/methods for more info.

**Comment by therealgilles** [comment]
@thijstriemstra: Thank you for your response. I was looking for this:

```
		player.on('deviceReady', function () {
			console.log('deviceReady')
			player.record().start()
		})
```

which is I think the behavior most users would expect when doing video recording only.
