### ISSUE TITLE
Switch from camera to screen and vice-versa in the same video

### ISSUE THREAD

**Issue by Anil-matcha** [collab-project/videojs-record#565]
## Description
I would want to be able to switch between camera and screen recording in the same video session. But currently I can only do camera recording or screen recording once and can't switch in between while recording

## Steps to reproduce
Create a camera stream, now there is no option to switch to screen recording. I can stop the video and start a new video with screen recording but can't switch in the mid 

### Expected
Would love an option to pause the video, change options and continue recording  

### Actual
Have no option to pause and switch in between

**Comment by thijstriemstra** [comment]
you can try:

```javascript 
player.record().stop();
player.record().loadOptions(newOptions);
player.record().getDevice();
```

**Comment by Anil-matcha** [comment]
Hi @thijstriemstra , thanks for replying. When the stop is called, the recording again starts from beginning and I lose the content from before. Hence it is like a new video recording. Is there any way to just pause, load options and continue so that I can have the whole video even when toggling between screen and camera

**Comment by thijstriemstra** [comment]
> Is there any way to just pause, load options and continue so that I can have the whole video even when toggling between screen and camera

Not on the client side. When a user presses pause you could:

* create a screenshot of the last frame of the video and display that
*  in background send the video to a server
* allow the user to select screen and hide screenshot of video
* record screen sharing session
* at the end, send recording to server and use a tool like ffmpeg to turn 2 videos into 1 video.

If you want to do it all on the clientside you could also try to use the ffmpeg-wasm plugin to make 1 video out of 2.
