### ISSUE TITLE
ffmpeg.wasm plugin: React throws ReferenceError: FFmpeg is not defined

### ISSUE THREAD

**Issue by Grv90** [collab-project/videojs-record#567]
## Description
Briefly describe the issue.

created new react app using create-react-app

Using screen share recording and saveAs works fine but when using plugin to convert it throws this error.

convert plugin using:

```js
const videoJsOptions = {
  controls: true,
  bigPlayButton: false,
  width: 320,
  height: 240,
  fluid: false,
  plugins: {
    record: {
      audio: true,
      screen: true,
      displayMilliseconds: false,
      debug: true,
      convertEngine: "ffmpeg.wasm",
      convertWorkerURL: "../../node_modules/@ffmpeg/core/dist/ffmpeg-core.js",
      // convert recorded data to MP4 (and copy over audio data without encoding)
      convertOptions: [
        "-c:v",
        "libx264",
        "-preset",
        "slow",
        "-crf",
        "22",
        "-c:a",
        "copy",
        "-f",
        "mp4",
      ],
      // specify output mime-type
      pluginLibraryOptions: {
        outputType: "video/mp4",
      },
    },
  },
};
```

My Imports - 

```js
import React, { Component } from "react";

import logo from "./logo.svg";
import "./App.css";
import "video.js/dist/video-js.css";
import "videojs-record/dist/css/videojs.record.css";
import "@ffmpeg/ffmpeg/dist/ffmpeg.min.js";
import videojs from "video.js";
import "webrtc-adapter";
import RecordRTC from "recordrtc";
import Record from "videojs-record/dist/videojs.record.js";
import FFmpegWasmEngine from "videojs-record/dist/plugins/videojs.record.ffmpeg-wasm.js";
```

![image](https://user-images.githubusercontent.com/13903076/114295384-0d8fe380-9af9-11eb-94fe-b8f218d10fa1.png)

**Comment by alanbugeja** [comment]
I have the exact same issue.

**Comment by jub-jan** [comment]
i get that same error in my angular project. any ideas?

**Comment by hex20** [comment]
I'm also having the same issue, anybody got a fix?

**Comment by jub-jan** [comment]
any idea? @thijstriemstra

**Comment by MohannadEhabBarakat** [comment]
any solutions?

**Comment by MohannadEhabBarakat** [comment]
I uninstalled ffmpeg version 0.10.*
 then installed 
"@ffmpeg/core": "^0.8.5",
"@ffmpeg/ffmpeg": "^0.9.8",


it works now fine with react. 
No idea why this worked

**Comment by NAMU1105** [comment]
> I uninstalled ffmpeg version 0.10.*
> then installed
> "@ffmpeg/core": "^0.8.5",
> "@ffmpeg/ffmpeg": "^0.9.8",
> 
> it works now fine with react.
> No idea why this worked

You just saved my day!! Thank you!

**Comment by zmutnik** [comment]
@MohannadEhabBarakat I have the same error using Vue.js. Do you have any ideas why it happens? Downgrading @ffmpeg/core and @ffmpeg/ffmpeg doesn't help me.

**Comment by MohannadEhabBarakat** [comment]
> @MohannadEhabBarakat I have the same error using Vue.js. Do you have any ideas why it happens? Downgrading @ffmpeg/core and @ffmpeg/ffmpeg doesn't help me.

No unfortunately I don't know why it happened

**Comment by ebarooni** [comment]
> I uninstalled ffmpeg version 0.10.*
> then installed
> "@ffmpeg/core": "^0.8.5",
> "@ffmpeg/ffmpeg": "^0.9.8",
> 
> it works now fine with react.
> No idea why this worked

Are there any updates on how to solve this? Doing this doesnt work for me.

**Comment by KalinaAugust** [comment]
Are there any updates on how to solve this?

**Comment by thijstriemstra** [comment]
upcoming videojs-record 4.7.0 has support for ffmpeg.wasm v0.12.x and should hopefully work better with react and other frameworks.

**Comment by jacoblfrandsen** [comment]
I'm getting this same error. 

When Updating to videojs-record 4.7.0 and using:
```
        "@ffmpeg/core": "^0.12.6",
        "@ffmpeg/ffmpeg": "^0.12.10",
        "@ffmpeg/core-mt": "^0.12.6",
        "@ffmpeg/util": "^0.12.1",
```
        
With these as my imports:

```
import 'video.js/dist/video-js.min.css';
import videojs from 'video.js';
import RecordRTC from 'recordrtc';
import Record from 'videojs-record/dist/videojs.record.js';
import 'videojs-record/dist/css/videojs.record.css';
import FFmpegWasmEngine from 'videojs-record/dist/plugins/videojs.record.ffmpeg-wasm.js';

```
        
I get a similar error in the FFmpeg Library:

```
ERROR
FFmpegUtil is not defined
ReferenceError: FFmpegUtil is not defined
    at FFmpegWasmEngine._callee$ (http://localhost:3000/src/index.js:87503:15)
    at tryCatch (http://localhost:3000/src/index.js:87812:16)
    at Generator.<anonymous> (http://localhost:3000/src/index.js:87900:17)
    at Generator.next (http://localhost:3000/src/index.js:87841:21)
    at asyncGeneratorStep (http://localhost:3000/src/index.js:87609:24)
    at _next (http://localhost:3000/src/index.js:87628:9)
    at http://localhost:3000/src/index.js:87633:7
    at new Promise (<anonymous>)
    at FFmpegWasmEngine.<anonymous> (http://localhost:3000/src/index.js:87625:12)
    at FFmpegWasmEngine.convert (http://localhost:3000/src/index.js:87561:25)
```

Which when looking at the previous report bug it is the same but slightly more specific. 


![Screenshot 2024-02-21 at 4 36 07 PM](https://github.com/collab-project/videojs-record/assets/71732814/da7b65c1-d441-477b-a01d-c6b40384a9db)


Has anyone ran into a similar issue with version 4.7.0 of videojs-record. I was thinking about using just ffmpeg.js instead of ffmpeg.wasm but the videojs-record 

"Note: this plugin is deprecated, use the [ffmpeg.wasm](https://collab-project.github.io/videojs-record/#/ffmpeg.wasm) plugin instead.'"


Any suggestions?

**Comment by thijstriemstra** [comment]
> ReferenceError: FFmpegUtil is not defined

The docs at https://collab-project.github.io/videojs-record/#/plugins/ffmpeg.wasm state you need to include:


```html
<script src="@ffmpeg/ffmpeg/dist/umd/ffmpeg.js"></script>
<script src="@ffmpeg/util/dist/umd/index.js"></script>
```

**Comment by skill83** [comment]
I have the same error. i'm using all the last versions of plugin and library. i have my imports like this:
```
import videojs from 'video.js';
import RecordRTC from 'recordrtc/RecordRTC.js';
import 'webrtc-adapter';
import '@ffmpeg/ffmpeg'
import '@ffmpeg/util';
import Record from 'videojs-record/dist/videojs.record.js';
import FFmpegWasmEngine from 'videojs-record/dist/plugins/videojs.record.ffmpeg-wasm.js';
```

you cannot write an import like this:
`import '@ffmpeg/ffmpeg/dist/umd/ffmpeg.js'`
because it will throw you an error! in the package.json of both @ffmpeg/ffmpeg and @ffmpeg/util it is  written 
```
  "name": "@ffmpeg/ffmpeg",
  "version": "0.12.10",
  "description": "FFmpeg WebAssembly version for browser",
  "main": "./dist/umd/ffmpeg.js",
  "types": "./dist/esm/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/esm/index.d.ts",
      "node": "./dist/esm/empty.mjs",
      "default": {
        "import": "./dist/esm/index.js",
        "require": "./dist/umd/ffmpeg.js"
      }
    }
  },
```
and 
```
  "name": "@ffmpeg/util",
  "version": "0.12.1",
  "description": "browser utils for @ffmpeg/*",
  "main": "./dist/cjs/index.js",
  "types": "./dist/cjs/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/cjs/index.d.ts",
      "import": "./dist/esm/index.js",
      "require": "./dist/cjs/index.js"
    }
  },
```

So there is no other way to import them

**Comment by skill83** [comment]
Actually using this two import i solved the issue:

```
import * as FFmpegWASM from '@ffmpeg/ffmpeg'
import * as FFmpegUtil from '@ffmpeg/util';
window.FFmpegUtil = FFmpegUtil
window.FFmpegWASM = FFmpegWASM
```

by the way i have a new issue when he tries to convert:

![Screenshot 2024-03-01 alle 12 47 46](https://github.com/collab-project/videojs-record/assets/656011/c01a2584-8b1d-4268-bba5-53450200c8fa)
