### ISSUE TITLE
Option to delay convert until method called

### ISSUE THREAD

**Issue by MichaelHeydon** [collab-project/videojs-record#568]
As far as I'm aware, there's currently no way delay a media conversion, it just starts as soon as the recording has stopped. Could there be a way to delay the conversion? Say `player.record().convert();` This would allow the user to first review the video prior to converting.

**Comment by thijstriemstra** [comment]
sounds like a good enhancement.

**Comment by MichaelHeydon** [comment]
For anyone looking for this in the meantime, I've just implemented it directly for now. Referencing the examples provided at https://github.com/ffmpegwasm/ffmpeg.wasm and converting `this.player.recordedData`

**Comment by thijstriemstra** [comment]
I'm adding a `convertAuto` option for this that's true by default. Pass false to disable auto convert and manually start converting with a call to the new `convert()` method.

**Comment by MichaelHeydon** [comment]
Thanks for the update @thijstriemstra
