### ISSUE TITLE
Progress control through ts-ebml still function? 

### ISSUE THREAD

**Issue by MichaelHeydon** [collab-project/videojs-record#569]
Does the example here still function? https://collab-project.github.io/videojs-record/demo/video-only-ebml.html
After recording the video UI does still not have a progress control.

**Comment by thijstriemstra** [comment]
@MichaelHeydon the video UI's progress control is always hidden in videojs-record. See #23.

**Comment by MichaelHeydon** [comment]
Thanks, so currently I'd need to sub in another videojs component to enable progress control?

**Comment by thijstriemstra** [comment]
> I'd need to sub in another videojs component

not sure what this means?

**Comment by MichaelHeydon** [comment]
All sorted - once I've recorded a video, use another videojs component to play the recorded data, passing through with: 
`
sources: 
[
	{
		src: URL.createObjectURL(this.recordedData),
		type: this.recordedData.type
	}
]
`
