### ISSUE TITLE
Using VMSG plugin hides controls on deviceReady

### ISSUE THREAD

**Issue by overjoied** [collab-project/videojs-record#574]
## Description
Controls are hidden and disabled even when `options.controls` was set to true. 

## Steps to reproduce
1. Create a new react app with `npx create-react-app`.
2. Then, `npm i videojs-record vmsg` 

### Expected
Controls are visible and enabled so that I can actually record audio-only mp3.

### Actual
I've been trying to use vmsg plugin in order to record audio only in mp3 format. I tried running the  [audio-only-mp3](examples/plugins/audio-only-mp3.html) example and it worked just fine. However, when I implemented it on my project, controls are being hidden and disabled. So I recreated it into another new React app hoping that there's just conflicts with my code, to no avail. If I removed `audioEngine: 'vmsg'` in `options.plugins.record`, controls are visible and enabled but I need the data to be in mp3 format. I don't know where I'm doing wrong. As much as possible, I don't wanna use [ffmpeg.js](https://collab-project.github.io/videojs-record/#/plugins/ffmpeg.js) because it's deprecated.

```
var options = {
    controls: true,
    bigPlayButton: false,
    width: 600,
    height: 300,
    fluid: false,
    plugins: {
        wavesurfer: {
            backend: 'WebAudio',
            waveColor: '#eeefda',
            progressColor: '#FAFCD2',
            displayMilliseconds: true,
            debug: true,
            cursorWidth: 1,
            hideScrollbar: true,
            plugins: [
                WaveSurfer.microphone.create({
                    bufferSize: 4096,
                    numberOfInputChannels: 1,
                    numberOfOutputChannels: 1,
                    constraints: {
                        video: false,
                        audio: true
                    }
                })
            ]
        },
        record: {
            audio: true,
            video: false,
            maxLength: 20,
            debug: true,
            audioEngine: 'vmsg',
            audioWebAssemblyURL: '../../node_modules/vmsg/vmsg.wasm'
        }
    }
}
```

### Error output
N/A

## Additional Information
I followed the videojs-record version from the example.

References: 

- [React - videojs-record implementation](https://collab-project.github.io/videojs-record/#/frameworks/react)
- [Audio Only Usage](https://collab-project.github.io/videojs-record/#/usage)
- [vmsg plugin](https://collab-project.github.io/videojs-record/#/plugins/vmsg)

#### videojs
videojs-record: 4.4.0
vmsg: 0.4.0

I also tried it with: 

vmsg: 0.3.6

#### browsers
Chrome Version 90.0.4430.93
Firefox Version 88.0
Edge Version 90.0.818.51
Safari Version 14.1

#### OSes
macOS Catalina Version 10.15.7

**Comment by thijstriemstra** [comment]
@overjoied can you create a screenshot of the issue?

**Comment by overjoied** [comment]
here: 
Control bar is hidden if I do this: 
```
record: {
    audio: true,
    video: false,
    maxLength: 20,
    debug: true,
    // enable vmsg plugin
    audioEngine: 'vmsg',
    audioWebAssemblyURL: '../../node_modules/vmsg/vmsg.wasm'
    // use the pluginLibraryOptions option to specify optional settings for the
    // vmsg library. For example:
    //pluginLibraryOptions: {
    //    shimURL: '/static/js/wasm-polyfill.js',
    //    pitch: 1
    //}
}
```
![Screen Shot 2021-05-07 at 2 51 46 PM](https://user-images.githubusercontent.com/36223391/117409633-f996a080-af43-11eb-9d12-40805a11f2d0.png)

I want it to be like this: with the control bar. Thank you for your response.
![Screen Shot 2021-05-07 at 2 52 30 PM](https://user-images.githubusercontent.com/36223391/117409767-25b22180-af44-11eb-911d-51d48965d990.png)

**Comment by thijstriemstra** [comment]
If there are no error messages, I'm not sure what to suggest here. Also: it's not working in a third-party framework (React), which I can't start debugging.

**Comment by PratikDev** [comment]
@overjoied have you finally succeeded in solving it? I'm facing the same bug and don't really know what to do as it's not giving any error in the console. it was working fine in my core javascript project, but when I moved my project to React, it stopped working unexpectedly. it's not even capturing any sound in my case
