### ISSUE TITLE
Updated the captured image dimensions based on device width/height

### ISSUE THREAD

**Issue by MichaelHeydon** [collab-project/videojs-record#578]
Using the image example (https://collab-project.github.io/videojs-record/demo/image-only.html) on a phone, it's clear that the image width/height constraints will unlikely match the cameras device dimensions. Once I have the devices width/height, am I able to update the dimensions of the captured video frames to match?

**Comment by thijstriemstra** [comment]
Sorry but not sure what you exactly mean, can you clarify your question?

**Comment by thijstriemstra** [comment]
no feedback, closing.

**Comment by MichaelHeydon** [comment]
Sorry @thijstriemstra, I had moved on from this. But may look at again in the future. So like the attached image: 
![IMG_2787](https://user-images.githubusercontent.com/74880856/131803640-76ee1b0d-1dc2-4539-a206-016d0d004b00.PNG)

Is there a way I can update the video dimensions to avoid the pink borders once the device dimensions are available?
