### ISSUE TITLE
Not working on live

### ISSUE THREAD

**Issue by vipul306** [collab-project/videojs-record#582]
## Description
Using videojs record i have recorded and save file succssfully in local, but when same code I publish on live 

it gives device error **"No Compatible device found"**

Can anybody help on this. ?

**Comment by thijstriemstra** [comment]
With "live" I assume you mean in production. This library needs to be served using https.

**Comment by vipul306** [comment]
> With "live" I assume you mean in production. This library needs to be served using https.

Thijs Triemstra , thanks for the response. 

But in my local machine I have tested it without https , so you mean to say when we move it to live ( production ) it suppose to be serve using https

**Comment by thijstriemstra** [comment]
> o you mean to say when we move it to live ( production ) it suppose to be serve using https

Correctos.

**Comment by vipul306** [comment]
> > o you mean to say when we move it to live ( production ) it suppose to be serve using https
> 
> Correctos.

Let me try that , whatever is result will update you. 

Thanks

**Comment by vipul306** [comment]
**Thijs Triemstra**

One more question, I can check Audio and Video device on my local like they are connected or not . Once go in production , is there any permission need to give for browser ? 

Sorry to bother you once again .

**Comment by thijstriemstra** [comment]
User needs to give permission every time, unless their browser supports saving this preference, like chrome.
