### ISSUE TITLE
Get accurate mimeType prior to recording start. 

### ISSUE THREAD

**Issue by MichaelHeydon** [collab-project/videojs-record#583]
When recording is started, a `Passing following config over MediaRecorder API.` message appears in the console that contains the accurate `mimeType` within the Object. This may obviously vary from that set in the videojs-record options depending on the browser. Is there any way to retrieve this prior to starting the recording?

**Comment by thijstriemstra** [comment]
I think you're looking for the recordrtc mimetype definition:

```js
player.record().engine.engine.mimeType
```

Returns:

```
Object { video: "video/webm", gif: "image/gif" }
```
