### ISSUE TITLE
downloadBlob API doesn't work

### ISSUE THREAD

**Issue by gelxgx** [collab-project/videojs-record#584]
because createObjectURL API doesn't work in high level chrome ,so if use this API,chrome may  thrown An exception

so i write it another way 
use blob to dataURL and creat 'a' element to download this video
```
function readBlobToDownload(blob, name) {
  const file = new FileReader()
  file.readAsDataURL(blob)
  file.onload = function(e) {
    const a = document.createElement('a')
    a.style.display = 'none'
    a.href = e.target.result
    a.download = name || blob.name
    document.body.appendChild(a)
    a.click()
  }
}
```

**Comment by thijstriemstra** [comment]
@gelxgx why does it not work?

> chrome may thrown An exception

what are the error message(s)?

what version of videojs-record? what operating system? why did you ignore the ticket guidelines?

**Comment by thijstriemstra** [comment]
No feedback, closing.
