### ISSUE TITLE
Chrome v49 - no video playback

### ISSUE THREAD

**Issue by JoshHarrington** [collab-project/videojs-record#59]
Hi there,

First off, massive thanks for the plugin.

I've noticed an issue when trying to playback the video on the latest version of Chrome on Mac - Version 49.0.2623.87 (64-bit).

To replicate:

- Ensure you're on Chrome v49 or higher on Mac
- Start recording a video
- Stop the video
- Press the play button
- Instead of playing the video you've just recorded it will just default to the live feed

Errors seen in the console (when running locally):
`Failed to parse SourceMap: http://localhost:2011/assets/js/vendor/videojs-record/videojs.record.min.js.map`
`Failed to parse SourceMap: http://127.0.0.1:8011/js/showdown.js.map`

`Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.`

Hope this helps and that you can replicate this.

Thanks,
Josh

**Comment by thijstriemstra** [comment]
@JoshHarrington I'll take a look at it now but can you also try to reproduce this with one of the online examples (because your report references a `http://127.0.0.1:8011/js/showdown.js.map` which is not related to this plugin), e.g. http://collab-project.github.io/videojs-record/

**Comment by JoshHarrington** [comment]
@thijstriemstra thanks for the quick response.

Yeah I think you're right, I'm guessing there must be something wrong with our setup as I can still use the demo from the github site fine (https://collab-project.github.io/videojs-record/examples/audio-video.html)

If there's anything you can think that we might be doing strangely then that would be a massive help, but I think it's unlikely there's anything wrong with the plugin

Thanks again,
Josh

**Comment by JoshHarrington** [comment]
@thijstriemstra just grabbed the latest js from the repo and seems to be working fine now.

Sorry for the false alarm!
