### ISSUE TITLE
Aspect Ratio Not Changing

### ISSUE THREAD

**Issue by Evaske** [collab-project/videojs-record#591]
## Description
Hi,

I am trying to get it so that the video records from my desktop webcam and the output video is 540 x 720. What is actually output is 640 x 480 (my camera's default ratio). Is there a way to get the result to be recorded and zoomed in so that the outputted video fills the 540x720 size? Ideally without using FFMPEG as I believe that's a massive library?

I am using these options:

```
options: {
  controls: true,
  autoplay: false,
  fluid: false,
  loop: false,
  width: 540,
  height: 720,
  bigPlayButton: true,
  controlBar: {
    ProgressControl: true,
  },
  plugins: {
    record: {
      audio: true,
      video: {
        minWidth: 540,
        minHeight: 720,
      },
      frameHeight: 720,
      frameWidth: 540,
      debug: false,
      maxLength: 60,
    },
  },
```

**Comment by thijstriemstra** [comment]
>  Ideally without using FFMPEG as I believe that's a massive library?

Short answer: no. Unless this setting works for you: https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/aspectRatio

**Comment by thijstriemstra** [comment]
no feedback, closing.
