### ISSUE TITLE
Recording feature not working for me when I start recording

### ISSUE THREAD

**Issue by Trushal0066** [collab-project/videojs-record#593]
## Description
When I start recording using code "player.record().start()" it's give me error like Cannot read property 'record' of undefined. I have given recording option when initialize the video js as below

var options = {
                controls: true,
                width: 4096,
                height: 2160,
                fluid: false,
                bigPlayButton: false,
                controlBar: {
                    volumePanel: false
                },
                plugins: {
                    record: {
                        audio: true,
                        video: true,
                        maxLength: 20,
                        debug: true,
                        timeSlice: 3000
                    }
                }
            };

            // video player ini.
            player = videojs('#id", options, function () { });

**Comment by thijstriemstra** [comment]
@Trushal0066 I don't see your call to `player.record().start()`. Please include code that reproduces the issue.

**Comment by thijstriemstra** [comment]
No feedback, closing.
