### ISSUE TITLE
Unable to access the camera using getDevice() when the firefox window is not active

### ISSUE THREAD

**Issue by pradeepaanumalla** [collab-project/videojs-record#594]
Browser : Firefox 
version : 90.0

I am using video js to start and stop the recoding automatically on the basis of timer.

Generally we are having a requirement to record the user answer's. There will be multiple retakes to record the video.

When user clicks on start then we are calling getDevice() and then start(), when he stops then it will trigger stopDevice().

So after stopping the recording if user doesn't submit the answer then the next retake will start after certain time(ex : 60secs).

So In this autorestart process I am using getDevice() to access the camera , but its resulting in this error

**Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request.**

**Comment by thijstriemstra** [comment]
@pradeepaanumalla thanks for the report. Do you have any more info about this error? A longer stacktrace would be needed to determine where this error is triggered.

**Comment by pradeepaanumalla** [comment]
Yes @thijstriemstra , Can you check this 
![Screenshot from 2021-07-29 15-32-43](https://user-images.githubusercontent.com/37704663/127473038-42715a20-a086-4b8e-928f-f2c6d7bbd349.png)

**Comment by thijstriemstra** [comment]
@pradeepaanumalla can you try with a unminified version of video.js so the stacktrace contains the correct line numbers? You would have to compile your project with dev version of video.js, not video.min.js

**Comment by pradeepaanumalla** [comment]
Hi @thijstriemstra 
Tried using unminified version and got this error
![Screenshot from 2021-08-02 10-46-40](https://user-images.githubusercontent.com/37704663/127807622-5eb41f7c-cd90-4fb9-ae26-c730aec89a90.png)

**Comment by thijstriemstra** [comment]
@pradeepaanumalla you're using a old version of videojs-record: `3.8.0`

Please always test with the latest versions!

**Comment by pradeepaanumalla** [comment]
Hi @thijstriemstra 
I have updated the video js  to 7.14.3 and video js record to 4.5.0 , but I am still facing the issue

**Comment by thijstriemstra** [comment]
no feedback, closing.
