### ISSUE TITLE
ts-ebml plugin: Safari record issue 

### ISSUE THREAD

**Issue by Hideman85** [collab-project/videojs-record#595]
Hi community,

ts-ebml have an issue with safari and that breaks the record.

The issues has been reported on ts-ebml and needs and needs a quick fix for now.
- Please have a look at the original issue https://github.com/legokichi/ts-ebml/issues/33

To whom that are interested in we could bring the support of webm playback to safari via [ogv.js](https://github.com/brion/ogv.js).
I'm wondering if we could do the same for recording so we support one optimal format in all platforms.

Looking forward to the quick fix

**Comment by thijstriemstra** [comment]
> Looking forward to the quick fix

?

**Comment by Hideman85** [comment]
I just meant that there is a quick fix available in the issue I linked to and that would be nice that a release is made with this fix while waiting the fix by the author of ts-ebml.

**Comment by thijstriemstra** [comment]
@Hideman85 if there's a quick fix, please open a pull request.

**Comment by thijstriemstra** [comment]
@Hideman85 can you give pull request #600 a try?

**Comment by rcausey** [comment]
I don't think #600 fixed the issue with Safari, since the error is thrown when `decoder.decode(buffer)` is called. I can reproduce the error when I run the `video-only-ebml.html` demo.

**Comment by endigma** [comment]
This is still broken in my tests
