### ISSUE TITLE
Stop Recording not working

### ISSUE THREAD

**Issue by moumitacn** [collab-project/videojs-record#598]
The recording stop and submit feature in not working Macbook, Iphone , Ipad (IOS devices) for both Safari and chrome platform. 

You can check the below link.
https://911us.us/
--- There you will find "Record Description of Incident" button of red colored.
Step 1 - Click  "Record Description of Incident" button
Step 2 - The recording popup will open, there you can start the recording, it will record, but neither it will stop nor Submit

Version - videojs-record 2.4.1
Non Working OS - IOS

Non-working Platforms : IOS chrome, Safari

**Comment by moumitacn** [comment]
Waiting for your solution and update.

**Comment by arghadip** [comment]
Hello, 

There is any solution? Please sugegst.

**Comment by moumitacn** [comment]
Waiting for your support.

**Comment by thijstriemstra** [comment]
Duplicate of #573
