### ISSUE TITLE
videojs 5.0 support

### ISSUE THREAD

**Issue by Billybobbonnet** [collab-project/videojs-record#6]
I want to switch to 5.0 but I am struggling with their new plug-in management. I will work on it but concerning this plugin, I wanted to check first if you plan to migrate to 5.0. If I manage to do it, do you want a PR?.

**Comment by thijstriemstra** [comment]
Hi @Billybobbonnet, thanks for your feedback. I think it makes sense to support v5 as soon as they make a stable release. We could look into a port before that and maybe work on a separate branch until then. Once it's released we can move v4 to a stable branch and put v5 implementation on the master/trunk. So yea, feel free to poke at it, PRs are always welcome.

**Comment by Billybobbonnet** [comment]
Ok. I'll keep in touch. Thanks for your fast answer.

**Comment by Billybobbonnet** [comment]
I looked a bit more into it. Here are some info on the task:
  - `videojs.Component.extend` is deprecated. It has been replaced with `videojs.extends` function. It should be called like this (see https://github.com/videojs/video.js/pull/2078):
``` javascript
var VjsButton = videojs.getComponent('Button');
var MyNewButton = videojs.extends(VjsButton, {
  constructor: function() {
    VjsButton.call(this, player, options);
  }, // notice the comma
  otherFunc: function() {
    // do something
  }
});
``` 
  - The plugin code should be wrapped into the videojs  `ready` event (see https://github.com/videojs/video.js/wiki/5.0-Change-Details#initialization)

I gave it a few tries, and failed. I don't know if I did it wrong or if it is too early to try it. So I will not dive in this yet because I don't feel confident enough in my chances to achieve it fast enough and I must prioritize other topics.

I will probably come back on this in one month or two.

**Comment by thijstriemstra** [comment]
Also note that https://github.com/collab-project/videojs-wavesurfer is an optional dependency for videojs-record that also needs to be ported.

**Comment by thijstriemstra** [comment]
Looks like video.js 5.0 is ready: https://github.com/videojs/video.js/commit/872459837b21c1e3d05fa86df4022f5a2b17ea1c

**Comment by thijstriemstra** [comment]
Before porting videojs-record I want to port videojs-wavesurfer because videojs-record depends on it in audio mode. See https://github.com/collab-project/videojs-wavesurfer/issues/5.

**Comment by Billybobbonnet** [comment]
I heavily modified videojs-record to suit my needs. I work on a video analysis tool. I skipped the webRTC part and merged it with a custom version of the videojs plugin [rangeslider"](https://github.com/danielcebrian/rangeslider-videojs). To make it short, the plugin "records" a sub-part of the video (rangeslider displays the "chunk") and allow pseudo video editing.

For this project, I also have modified and included several other plugins (video shortcuts, hd source switch, etc.). This is then a big (huge?) work to update the whole stuff to v5.0, not to mention that I am not confident about my success chances :laughing: 

Concerning videojs-wavesurfer, I plan to use it too but didn't put efforts into its integration so far (pre 5.0). I would welcome any help to port it but I cannot undertake the porting by myself in my situation.

Also, I can send you by email the modified code of your plugin if you want me to. I wish I could make a PR or publish it as a different plugin but I am a little overworked at the moment. It still could be an option in the upcoming months since I plan to publish my code as open-source.

**Comment by thijstriemstra** [comment]
videojs-wavesurfer basically is ready and ported to v5, only need to merge it to master. It was not a lot of work and I think porting videojs-record won't be a problem either.

**Comment by thijstriemstra** [comment]
Well, the port to video.js 5 is ready for testing (@Billybobonet?): https://github.com/collab-project/videojs-record/archive/videojs5.zip
If there are no problems I'll merge it to master in a day or two and release 1.0.0.

**Comment by Billybobbonnet** [comment]
Great news! I will take a look at it this weekend. Congrats for the port :)

2015-10-14 17:21 GMT+02:00 Thijs Triemstra <notifications@github.com>:

**Comment by Billybobbonnet** [comment]
I have partially updated my player, including your plugin in a modified version. I still have to add wavesurfer but everything works great so far. Good job on the port.
I will try to port the rangeslider plugin and merge it with videojs-record this week. The goal is to achieve a video pseudo editing plugin: you "extract" chunks of an existing video using your plugin buttons (so I'm not actually recording, just indexing the start/stop + thumbnails) and play/edit them with the rangeslider. You are welcome to have a look if you want to.

**Comment by thijstriemstra** [comment]
Sounds exciting man :) Looking forward to a PR..!
