### ISSUE TITLE
Recording crash over 3 mins on 720p

### ISSUE THREAD

**Issue by zang** [collab-project/videojs-record#60]
Resolution 720p, on Chrome 49 stable iMac. Page crashes when I click on the finish button.

**Comment by thijstriemstra** [comment]
@zang can you include the video.js config so I can give it a try?

**Comment by zang** [comment]
Here you go: 

var player = videojs('myVideo', { controls: true, loop: false, plugins: { record: { audio: true, video: { mandatory: { minWidth: 1280, minHeight: 720, maxWidth: 1280, maxHeight: 720 } },  maxLength: 600 } } });

Tried on the following page and works fine for long recording but apparently it's 480p as I don't see any option to switch to 720p. :)

**Comment by zang** [comment]
Testing Machine:
iMac OS X
2.7 GHz Intel Core i5
8 GB 1600 MHz DDR3

**Comment by thijstriemstra** [comment]
> Tried on the following page and works fine for long recording but apparently it's 480p as I don't see any option to switch to 720p. :)

What page?

**Comment by zang** [comment]
https://www.webrtc-experiment.com/RecordRTC/MRecordRTC/

**Comment by thijstriemstra** [comment]
@zang with chrome 49 on OSX I've tried with the default settings (320x240) and this created a video/webm -> 74.1 MB file for 9:10 minutes. When I record more than 9:30 the browser crashes, even with 320x240. Need to figure out how to view the crash log.

**Comment by thijstriemstra** [comment]
I've logged a crash report here: https://bugs.chromium.org/p/chromium/issues/detail?id=595442

**Comment by zang** [comment]
Thanks @thijstriemstra 
I just recorded a 5-min 720p on Firefox (98mb) and it works. So, I think it's a Chrome issue. 

@muaz-khan are you aware of this issue? I vaguely remember you have an example of 60-min recording. If so, how did you do it?

**Comment by thijstriemstra** [comment]
FYI a Blob in Chrome cannot be bigger than 500MB at the moment according to [this bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=375297) but we're not hitting that limit yet are we?

**Comment by thijstriemstra** [comment]
@muaz-khan on Chromium I see an actual error and it seems related to RecordRTC: https://bugs.chromium.org/p/chromium/issues/detail?id=595442#c1

**Comment by thijstriemstra** [comment]
@muaz-khan added a change related to this issue it seems (https://github.com/muaz-khan/RecordRTC/commit/b1e63b06ce3d19828849ab53f1174288f528d925).

**Comment by zang** [comment]
Thanks @thijstriemstra , and I will try.

**Comment by thijstriemstra** [comment]
I just tried again in Chrome stable 49 and created video/webm -> 173 MB for 10:10 minutes and I didn't get a crash. Tested on:

<img width="208" alt="screen shot 2016-03-22 at 19 39 31" src="https://cloud.githubusercontent.com/assets/305679/13963484/d89602f6-f065-11e5-909a-1803450fde49.png">

**Comment by zang** [comment]
Tested on my machine and it works perfectly. (Closing this ticket)

**Comment by thijstriemstra** [comment]
Chrome 51 introduces async blob construction that should be able to work around this problem. See https://bit.ly/BlobStorageRefactorPreso
