### ISSUE TITLE
Pause and resume recording

### ISSUE THREAD

**Issue by zang** [collab-project/videojs-record#61]
Question : Is it possible to press a button to pause/resume recording?

**Comment by thijstriemstra** [comment]
Not yet. Back then this wasnt part of recordrtc yet. PR welcome!

**Comment by thijstriemstra** [comment]
https://github.com/muaz-khan/RecordRTC/blob/master/dev/MRecordRTC.js will also need an update since there is no pause/resume functionality implemented yet.

**Comment by thijstriemstra** [comment]
I've opened https://github.com/muaz-khan/RecordRTC/pull/128. Once this lands and gets released it can be implemented in this plugin.

**Comment by erikdonohoo** [comment]
Our company will need this. I'm happy to do the work and open a PR if someone can point me in the right direction.  There are a few things that are currently open issues here that we would like.  I'm happy to help contribute more to the project.

**Comment by thijstriemstra** [comment]
@erikdonohoo thanks! point any questions you have at me.

**Comment by manishchauhanquovantis** [comment]
Can we now pause and resume recording ? If yes how can we  use it.

**Comment by thijstriemstra** [comment]
@manishchauhanquovantis I've added a `pause` and `resume` method in the master branch, can you test that?

You can use it like:

```javascript
player.recorder.pause();
player.recorder.resume();
```

**Comment by thijstriemstra** [comment]
Should be fixed with the upcoming 1.6.0 release. Pause/resume during a video recording seems to work fine on Ubuntu 16.04 Chrome (57.0.2987.37) but on Firefox 51 there was an issue with the stream timestamp increasing despite the `pause()` call. Haven't tested on other platforms yet.

**Comment by thijstriemstra** [comment]
https://github.com/muaz-khan/RecordRTC/issues/190 also looks related.
