### ISSUE TITLE
Audio only without wavesurfer?

### ISSUE THREAD

**Issue by oobie11** [collab-project/videojs-record#612]
I'm using StimulusJS and trying to use Videojs-record to record audio only using a custom button that calls a stimulus action to get the users microphone. 
It seems that setting the options to 

`audio : true,
video: false`

makes it so you have to use wavesurfer. 
When I try, `player.record().getDevice()` from my stimulus action, it does not work and this error gets thrown `TypeError: this.surfer is undefined`. 
Doing the same when setting the options to record audio/video or a users screen works fine though.

I think I have everything imported correctly per the installation instructions and the example source for "audio only". 

```
import videojs from 'video.js';
import { RecordRTC } from 'recordrtc';
import WaveSurfer from 'wavesurfer.js';
import MicrophonePlugin from 'wavesurfer.js/dist/plugin/wavesurfer.microphone.js';
WaveSurfer.microphone = MicrophonePlugin;
import 'videojs-wavesurfer/dist/videojs.wavesurfer.js';
import Record from 'videojs-record/dist/videojs.record.js'
``` 
I'm not sure what I am doing wrong here when it pertains to audio only.

It seems like the issue Is coming from the wavesurfer plugin, is there a way to disable the wavesurfer functionality?

Thanks

**Comment by thijstriemstra** [comment]
Going to https://collab-project.github.io/videojs-record/demo/audio-only.html, opening a browser console, and entering `player.record().getDevice()` works fine. 

Print the wavesurfer version nr to check if it's properly loaded:

```js
// create player
var player = videojs('myAudio', options, function() {
    // print version information at startup
    var msg = 'Using video.js ' + videojs.VERSION +
        ' with videojs-record ' + videojs.getPluginVersion('record') +
        ', videojs-wavesurfer ' + videojs.getPluginVersion('wavesurfer') +
        ', wavesurfer.js ' + WaveSurfer.VERSION + ' and recordrtc ' +
        RecordRTC.version;
    videojs.log(msg);
});
```

Looks like a build issue on your side.

> It seems like the issue Is coming from the wavesurfer plugin, is there a way to disable the wavesurfer functionality?

No.

**Comment by oobie11** [comment]
Thank you, you were right. It was my issue. 
For anyone that stumbles upon this that is using StimulusJs, The problem I was running in to was that I was trying to set the player options and build the player on activation of my Stimulus action, so after the controller was loaded. This was causing `WaveSurfer.microphone.create()` to not initialize.
I solved the issue by moving the options to the stimulus `connect()` action so the player is built when the Stimulus controller loads. Then in my action, I call `player.record().getDevice()` and all works perfectly.
