### ISSUE TITLE
VIDEOJS: WARN: Player "my-id" is already initialised. Options will not be applied.

### ISSUE THREAD

**Issue by angelolustosa** [collab-project/videojs-record#62]
When I close window that contains video with "my-id", show me this warning. I know  that I close player before open new window with new player and fix this warning, but I can't doing. Can help me?

`var me =  this,
			player = videojs("videoExame", {
		    controls: true,
		    width: 415,
		    height: 306,
		    plugins: {
		        record: {
		            audio: true,
		            video: true,
		            maxLength: 1000,
		            debug: true
		        }
		    }
		});`

`<div id="gravar" >' +
					  //'<h2>Gravar Video:</h2>' +
					  '<video id="videoExame" class="video-js vjs-default-skin" style="float: left;"></video>'+
					'</div>'`

**Comment by thijstriemstra** [comment]
It looks like you need to call `destroy` on the player when you close your modal window, see https://github.com/collab-project/videojs-record#options.

**Comment by thijstriemstra** [comment]
@angelolustosa closing because no feedback.
