### ISSUE TITLE
Toggle Video on/off Dynamically  not working

### ISSUE THREAD

**Issue by yu0307** [collab-project/videojs-record#635]
## Description
When trying to toggle between video+audio and audio only using the following snippet, it seems Video.js is having issue determine surfer and throw "surfer" undefined error.  

## Steps to reproduce
Initialize the component as follows:
```
config:{
                controls: false,
                loop: false,
                fluid: true,
                controlBar: {
                    deviceButton: false,
                    pipToggle: false
                },
                plugins: {
                    record: { 
                        image: false,
                        audio: true,
                        video: true,
                        maxLength: 30,
                        displayMilliseconds: true,
                        debug: true
                    },
                    wavesurfer: { 
                        backend: 'WebAudio',
                        waveColor: '#c2ebff',
                        progressColor: 'black',
                        debug: true,
                        cursorWidth: 2,
                        displayMilliseconds: true,
                        hideScrollbar: true,
                        plugins: [
                            // enable microphone plugin
                            WaveSurfer.microphone.create({
                                bufferSize: 4096,
                                numberOfInputChannels: 1,
                                numberOfOutputChannels: 1,
                                constraints: {
                                    video: false,
                                    audio: true
                                }
                            })
                        ]
                    }
                }
            }
```
```
methods:{
        toggleMedia(mediaType){
            this.player.record().reset();
            this.player.record().loadOptions({
                video:(mediaType==='VIDEO')
            });
        }
}
```

### Expected
should load the new config correctly and init the control accordingly

### Actual
error thrown "Cannot read properties of undefined (reading 'surfer')"
resulted in videojs.record.js
```
if (this.getRecordType() === _recordMode.AUDIO_ONLY) {
  ##this.surfer.surfer.microphone.stopDevice();
  return;
}
```

### Error output
Cannot read properties of undefined (reading 'surfer')

PS: if you init with audio only everything works fine.

**Comment by thijstriemstra** [comment]
@yu0307 you cannot use audio + video with the videojs-wavesurfer plugin, it's not supported. Change it to audio only:

```js
image: false,
audio: true,
video: false
```

**Comment by yu0307** [comment]
I actually got it to work, with the following changes:
```
toggleMedia(mediaType){
            this.ready=false;
            this.recording=false;
            this.removeMedia();
            this.player.record().reset();
            if(mediaType!=='VIDEO'){
                this.player.record().loadOptions({
                    video:(mediaType==='VIDEO')
                });
            }
            this.mediaMode=this.player.record().getRecordType();
            this.player.record().setupUI();
            this.startDevice();
        }
```
watch: {
        videoDevice(newVideoDevice, oldVideoDevice) {
            if(this.record.recordVideo === Object(this.record.recordVideo)){
                this.record.recordVideo.deviceId = {exact: newVideoDevice.value};
            }else if (this.record.recordVideo === true) {
                this.record.recordVideo = {
                    deviceId: {exact: newVideoDevice.value}
                };
            }
            this.record.stopDevice();
            return newVideoDevice;
        },
        audioDevice(newAudioDevice, oldAudioDevice) {
            if (this.record.recordAudio === Object(this.record.recordAudio)) {
                this.record.recordAudio.deviceId = {exact: newAudioDevice.value};
            } else if (this.record.recordAudio === true) {
                this.record.recordAudio = {
                    deviceId: {exact: newAudioDevice.value}
                };
            }
            switch (this.record.getRecordType()) {
                case 'audio_only':
                    this.record.surfer.surfer.microphone.constraints = {
                        video: false,
                        audio: this.record.recordAudio
                    };
                    break;
            }
            this.record.stopDevice();
            return newAudioDevice;
        }
    }
```
