### ISSUE TITLE
501 Not Implemented

### ISSUE THREAD

**Issue by prathibhatvm** [collab-project/videojs-record#637]
While running videojs it returns 501 Not Implemented.

**Comment by prathibhatvm** [comment]
It shows, Video successfully uploaded but no video found.

<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Audio/Video Example - Record Plugin for Video.js</title>
        
        
        <link href="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.0.0/video-js.min.css" rel="stylesheet">

        
        <link href="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/4.5.0/css/videojs.record.min.css" rel="stylesheet">

        <style>
        /* change player background color */
        #myVideo {
            background-color: #9ab87a;
        }
        </style>
    </head>
    <body>
        
        <video id="myVideo" class="video-js vjs-default-skin"></video>
        
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.0.0/video.min.js"></script>

        
        <script src="RecordRTC.js"></script>
        <script src="adapter.js"></script>
        
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/4.5.0/videojs.record.min.js"></script>
        <script>
        var videoMaxLengthInSeconds = 120;

        // Inialize the video player
        var player = videojs("myVideo", {
            controls: true,
            width: 720,
            height: 480,
            fluid: false,
            plugins: {
                record: {
                    audio: true,
                    video: true,
                    maxLength: videoMaxLengthInSeconds,
                    debug: true,
                    videoMimeType: "video/webm;codecs=H264"
                }
            }
        }, function(){
            // print version information at startup
            videojs.log(
                'Using video.js', videojs.VERSION,
                'with videojs-record', videojs.getPluginVersion('record'),
                'and recordrtc', RecordRTC.version
            );
        });

        // error handling for getUserMedia
        player.on('deviceError', function() {
            console.log('device error:', player.deviceErrorCode);
        });

        // Handle error events of the video player
        player.on('error', function(error) {
            console.log('error:', error);
        });

        // user clicked the record button and started recording !
        player.on('startRecord', function() {
            console.log('started recording! Do whatever you need to');
        });

        // user completed recording and stream is available
        // Upload the Blob to your server or download it locally !
        //player.on('finishRecord', function() {

            // the blob object contains the recorded data that
            // can be downloaded by the user, stored on server etc.
          //  var videoBlob = player.recordedData.video;

            //console.log('finished recording: ', videoBlob);
        //});
		
		// user completed recording and stream is available
		player.on('finishRecord', function() 
		{
			//player.record().saveAs({'video': player.recordedData.name});
			//console.log('finished recording: ', player.recordedData);
			// the blob object contains the recorded data that
			// can be downloaded by the user, stored on server etc.
			console.log('finished recording: ', player.recordedData.video);

			// Create an instance of FormData and append the video parameter that
			// will be interpreted in the server as a file
			var formData = new FormData();
			formData.append('video', player.recordedData.video);
			console.log(formData);
    
			//var videoBlob = player.recordedData.video;
	
			// Execute the ajax request, in this case we have a very simple PHP script
			// that accepts and save the uploaded "video" file
			xhr('https://10.176.16.170/static/upload-video.php', formData, function (fName) {
				console.log("Video succesfully uploaded !");
			});

			// Helper function to send 
			function xhr(url, data, callback) 
			{
				var request = new XMLHttpRequest();
				request.onreadystatechange = function () 
				{
					if (request.readyState == 4) 
						if (request.status == 200)
						{
							console.log("success");
							callback(location.href + request.responseText);
						}
						else
							console.log(request.responseText); 
				};
				request.open('GET',url);
				request.send(data);
			}
		});	
		</script>
	</body>
</html>

**Comment by prathibhatvm** [comment]
upload-video.html

<!DOCTYPE html>
<html>
<body>
<?php
if(isset($_FILES["video"])){
    // Define a name for the file
    $fileName = "myvideo.webm";

    // In this case the current directory of the PHP script
    $uploadDirectory = './'. $fileName;
    
    // Move the file to your server
    if (!move_uploaded_file($_FILES["video"]["tmp_name"], $uploadDirectory)) {
        echo("Couldn't upload video !");
    }
}else{
    echo "No file uploaded";
}
?>
</body>
</html>

**Comment by thijstriemstra** [comment]
> running videojs it returns 501 Not Implemented.

Where does it say this? can you make a screenshot? I have a feeling this is a PHP issue I can't help you with.

**Comment by thijstriemstra** [comment]
no feedback, closing.
