### ISSUE TITLE
ffmpeg.wasm : Error: Could not load ffmpeg.wasm plugin

### ISSUE THREAD

**Issue by diplesh123** [collab-project/videojs-record#639]
## Description
![image](https://user-images.githubusercontent.com/72154919/153813239-13a10663-0b81-4a0d-95d9-33c65e33897e.png)

## Steps to reproduce
with videojs we can record video with webm extension. While to convert video into mp4 in angular project with ffmpeg.wasm
I got the above issue.

step-1 : npm install --save @ffmpeg/ffmpeg @ffmpeg/core
step-2 : put this <script>  into index.html <script src="@ffmpeg/ffmpeg/dist/ffmpeg.min.js"></script>
step-3 : Tried with this to import FFmpegWasmEngine from 'videojs-record/dist/plugins/videojs.record.ffmpeg-wasm.js'; at TS file & also tried without this
step-4 : used record: {
    audio: true,
    video: true,
    maxLength: 20,
    debug: true,
    // enable ffmpeg.wasm plugin
    convertEngine: 'ffmpeg.wasm',
    convertWorkerURL: '../../node_modules/@ffmpeg/core/dist/ffmpeg-core.js',
    // convert recorded data to MP4 (and copy over audio data without encoding)
    convertOptions: ['-c:v', 'libx264', '-preset', 'slow', '-crf', '22', '-c:a', 'copy', '-f', 'mp4'],
    // specify output mime-type
    pluginLibraryOptions: {
        outputType: 'video/mp4'
    }
}

## Results
Get this error
![image](https://user-images.githubusercontent.com/72154919/153813239-13a10663-0b81-4a0d-95d9-33c65e33897e.png)

### Expected
To open the camera & start recording & save in mp4 format

### Actual
Getting error in deviceError event

### Error output
Get this error
![image](https://user-images.githubusercontent.com/72154919/153813239-13a10663-0b81-4a0d-95d9-33c65e33897e.png)

## Additional Information
Please include any additional information necessary here. Including the following:
#### browsers
chrome

#### OSes
Linux

**Comment by dionjwa** [comment]
The underling issue is likely described here: https://web.dev/cross-origin-isolation-guide/

**Comment by thijstriemstra** [comment]
The ffmpeg.wasm plugin was updated to support v0.12.x, please try videojs-record 4.7.0 (or newer) once it's released.
