### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by javiqnk** [collab-project/videojs-record#642]
## Description
When uploading a file it is not saved correctly.
The file is saved without the name and extension.

Code: 
```
player.on('finishRecord', function () {
            // the blob object contains the recorded data that
            // can be downloaded by the user, stored on server etc.
            console.log('finished recording:', player.recordedData);

            var data = player.recordedData;
            var serverUrl = '/upload';
            var formData = new FormData();
            formData.append('file', data, data.name);

            console.log('uploading recording:', data.name);

            fetch(serverUrl, {
                method: 'POST',
                body: formData
            }).then(
                success => console.log('recording upload complete.')
            ).catch(
                error => console.error('an upload error occurred!')
            );
        });
```

Console Log:
uploading recording: 1647719609986.mkv
recording upload complete.

Server Log:
saving uploaded file...
filename: undefined
saved file.

Uploads:
![image](https://user-images.githubusercontent.com/31355032/159136626-438b9d1b-cfe0-424b-9f15-014791d9dcab.png)

**Comment by thijstriemstra** [comment]
What you do on the backend, how you save it etc, is up to you. As you can see the file is 203 kb, and not corrupted, so you'll need to handle the file extension on whatever backend you're using.
