### ISSUE TITLE
VIDEOJS: ERROR: TypeError: this.stream is undefined

### ISSUE THREAD

**Issue by VedantMadane** [collab-project/videojs-record#647]
## Description
VIDEOJS: ERROR: TypeError: this.stream is undefined
    muteTracks videojs.record.js:4221
    stop videojs.record.js:3860
    dispose videojs.record.js:4118
    dispatcher video.es.js:2310
    trigger video.es.js:2446
    trigger$1 video.es.js:3387
    dispose video.es.js:22444
    beforeDestroy Registration.vue:3493
    VueJS 29
    reload index.js:244
    reload index.js:242
    tryWrap index.js:119
    <anonymous> Registration.vue:29
    vue VueJS
    __webpack_require__ app.js:833
    hotApplyInternal app.js:729
    hotApply app.js:391
    hotUpdateDownloaded app.js:366
    promise callback*hotUpdateDownloaded app.js:365
    hotAddUpdateChunk app.js:341
    webpackHotUpdateCallback app.js:37
    <anonymous> view-RegistrationManagement-Registration-vue.642ee6f6cdbf71ab6d5f.hot-update.js:1
[video.es.js:228](webpack:///node_modules/video.js/dist/video.es.js?f0e2)
    LogByTypeFactory video.es.js:228
    error video.es.js:416
    dispatcher video.es.js:2312
    trigger video.es.js:2446
    trigger$1 video.es.js:3387
    dispose video.es.js:22444
    beforeDestroy Registration.vue:3493
    VueJS 29
    reload index.js:244
    reload index.js:242
    tryWrap index.js:119
    <anonymous> Registration.vue:29
    vue VueJS
    __webpack_require__ app.js:833
    hotApplyInternal app.js:729
    hotApply app.js:391
    hotUpdateDownloaded app.js:366
    (Async: promise callback)
    hotUpdateDownloaded app.js:365
    hotAddUpdateChunk app.js:341
    webpackHotUpdateCallback app.js:37
    <anonymous> view-RegistrationManagement-Registration-vue.642ee6f6cdbf71ab6d5f.hot-update.js:1

**Comment by thijstriemstra** [comment]
there is no example code, no description, no version/operating system info as described in the ticket instructions. Please add those and re-open.
