### ISSUE TITLE
Cannot set properties of undefined (setting 'muted')

### ISSUE THREAD

**Issue by vitorcogo** [collab-project/videojs-record#648]
## Description
When call to start record, this message appears.

## Steps to reproduce
- Start record

### Expected
Starts record

### Actual
Black screen

### Error output
`erro TypeError: Cannot set properties of undefined (setting 'muted')
    at Record.startVideoPreview (videojs.record.js:3396:1)
    at Record.start (videojs.record.js:2879:1)
    at executeListenerWithErrorHandling (core.js:21819:1)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:21861:1)
    at HTMLButtonElement.<anonymous> (platform-browser.js:976:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:402:1)
    at Object.onInvokeTask (core.js:41645:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:401:1)`

#### videojs
7.11.4
#### browsers
Chrome 101.0.4951.54
#### OSes
Windows 10

**Comment by snow-sprite** [comment]
> ## Description
> When call to start record, this message appears.
> 
> ## Steps to reproduce
> * Start record
> 
> ## Results
> ### Expected
> Starts record
> 
> ### Actual
> Black screen
> 
> ### Error output
> `erro TypeError: Cannot set properties of undefined (setting 'muted') at Record.startVideoPreview (videojs.record.js:3396:1) at Record.start (videojs.record.js:2879:1) at executeListenerWithErrorHandling (core.js:21819:1) at wrapListenerIn_markDirtyAndPreventDefault (core.js:21861:1) at HTMLButtonElement.<anonymous> (platform-browser.js:976:1) at ZoneDelegate.invokeTask (zone-evergreen.js:402:1) at Object.onInvokeTask (core.js:41645:1) at ZoneDelegate.invokeTask (zone-evergreen.js:401:1)`
> 
> ## Additional Information
> ### versions
> #### videojs
> 7.11.4
> 
> #### browsers
> Chrome 101.0.4951.54
> 
> #### OSes
> Windows 10

Have you solved this problem? I also have this problem😫

**Comment by Kulgar** [comment]
Ok, I found the problem: I had no recording device "ready". 
This was because I wasn't using localhost (or 127.0.0.1 or https). Browser automatically blocks recording device authorization if we are not on a "safe" website. 

I switched from my local app IP to localhost and it now works properly.
