### ISSUE TITLE
setAudioInput broken?

### ISSUE THREAD

**Issue by pork1977** [collab-project/videojs-record#649]
Hi,

It looks like the **setAudioOutput(device_id)** is broken as it's giving a "player is not defined" (even though I don't reference it as player) error in the console whenever I try it using the code below..

```
 // get data
    var videoRecorder = instance.data.videoRecorder.record();
    var device_id = properties.device_id;

    if (device_id) {
        videoRecorder.setAudioOutput(device_id);
    }
```

I use the above in a similar way for changing the audioInput and videoIput devices which produce no errors, they work perfectly. I just can't figure out what's causing the above.

![image](https://user-images.githubusercontent.com/29090134/170091616-3fda33d4-b488-4b26-a179-fde8924354ba.png)

Using the demo page also produces an error
https://collab-project.github.io/videojs-record/demo/change-audio-output.html

I'm just wondering if this is indeed a bug?
I'm currently trying with the latest 4.5 release, hoping the info above is enough and if it is a bug can be resolved in 4.6 when it's released :)

**Comment by thijstriemstra** [comment]
@pork1977 can you reproduce this with the example https://github.com/collab-project/videojs-record/blob/master/examples/change-audio-input.html?

**Comment by thijstriemstra** [comment]
no feedback, closing.
