### ISSUE TITLE
need to execute code before `deviceReady` event

### ISSUE THREAD

**Issue by straycoders** [collab-project/videojs-record#658]
How can I execute codes just before `deviceReady` event is fired? If any, what other events triggered before it?

**Comment by thijstriemstra** [comment]
There are no other events besides `ready` I think.

**Comment by straycoders** [comment]
@thijstriemstra, thanks for your response. If there are no other events, what about adding a new one? Say, an event that is fired right after the `browser-requirement (dialog) check` is done but, before `deviceReady` is fired. 

For example: `player.on('permissionState',fn){ }`

I think its presence would be nice and very helpful.

**Comment by thijstriemstra** [comment]
> an event that is fired right after the browser-requirement (dialog) check is done

Sounds good but last time I checked there is not such a cross-browser event, but please investigate.

**Comment by straycoders** [comment]
I've done that with `videojs-record.js` during my free time a while ago. Even until `video.js` . But I prefer to start from your side. Unfortunately currently I'm running on deadline and that needs special time to focus. I'll be back with new findings, hopefully.
Thank you for your time and attention.
