### ISSUE TITLE
Re-register events

### ISSUE THREAD

**Issue by jjones3535a** [collab-project/videojs-record#66]
I am using -> player.recorder.destroy();  and then rebuilding my player on a page.  However, when I do this my player events:

player.on('deviceError',
player.on('deviceReady'
player.on('startRecord',

no longer fire.  Is there a way to re-register those events on the page?

**Comment by thijstriemstra** [comment]
That would be a bug, can you create an example that reproduces this?

**Comment by thijstriemstra** [comment]
@jjones3535a closing because of missing feedback.
