### ISSUE TITLE
Problem with rendering the video component

### ISSUE THREAD

**Issue by viku3150** [collab-project/videojs-record#665]
Hi I am getting the entire information and an HTML rendering of the modal window to configure, can someone help sort this out
![image](https://user-images.githubusercontent.com/61621763/203101118-8659ef45-50b1-4382-9f77-87bfcae931d3.png)

**Comment by thijstriemstra** [comment]
@viku3150 looks like you didn't (properly) include the required videojs-record and video.js css files so the styling looks screwed up.

**Comment by thijstriemstra** [comment]
no feedback, closing.
