### ISSUE TITLE
Can't tweek the parameters enough for my specific setting

### ISSUE THREAD

**Issue by gui-rossi** [collab-project/videojs-record#669]
Hello, I'm trying to make the lib work for audio-only recordings of: **11025 Hz, 8 bits and 1 channel**, is it supported? I've already tried with MediaStreamRecorder and StereoAudioRecorder - I always get "sample-rate must be under range 22050 and 96000" and my audios seem to slow down as I decrease the frequency. Any advices on how I can record audios with this specific setting and in normal speed? (artifacts and noise in the audio are expected)

**Comment by thijstriemstra** [comment]
> "sample-rate must be under range 22050 and 96000"

This is a limitation of RecordRTC, a library this project uses. See https://stackoverflow.com/questions/26301771/webrtc-issue-when-using-recordrtc

A user there mentions you should modify RecordRTC and change these hardcoded values there.
