### ISSUE TITLE
Timeslice/Timestamp video doesn't have duration when upload to AWS s3 multipart upload

### ISSUE THREAD

**Issue by StephenVinuya** [collab-project/videojs-record#675]
## Description
I'm working on an application, where we upload parts of video that are being recorded on video.js-record every n seconds timestamp.
The problem is the video duration is always 0 with no end time specified when I played the video and it will just continuously play till I reach the end of the video.

I don't know how to integrate the **ts-ebml.js** plugin in this scenario, cause the **finishConvert** doesn't fire on every **timestamp** event

## Steps to reproduce
Upload the timestamp **recordedData** to AWS s3 multipart upload.

### Expected
The video end time when watching the video should be there

### Actual
See image, there's no duration/end time specified, and progressbar of the video is always at the end part.
![image](https://user-images.githubusercontent.com/115604140/218370555-f17eaf00-015a-463c-94d0-9572fc8bb5fa.png)

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
video.js 7.2.0
 video.js record 4.6.0
#### browsers
Chrome, firefox, safari
#### OSes
Windows 10

**Comment by HolyshitOvO** [comment]
facing same issue

**Comment by thijstriemstra** [comment]
You can use the ts-ebml plugin to inject duration: https://collab-project.github.io/videojs-record/#/plugins/ts-ebml
