### ISSUE TITLE
Videojs-record with Browserify

### ISSUE THREAD

**Issue by Technopathic** [collab-project/videojs-record#68]
Hi, I'm pretty new to VideoJS/VideoJS-record and was wondering if it's possible to get this working on the client-side using Browserify? And if so, could I have a basic example?

**Comment by thijstriemstra** [comment]
hi @Technopathic I've not used browserify before but I believe @alsar has, maybe he can give some tips.

**Comment by atsuzu** [comment]
I would also like to have a guide on how to use Browserify with this if possible :)

**Comment by thijstriemstra** [comment]
Having a browserify (test) grunt task wouldn't hurt so we can see if it builds properly. I'm personally (still) using r.js.

**Comment by atsuzu** [comment]
I tried using Browserify with this just now actually and encountered a problem.  I am a complete beginner with Browserify, so I may have done something wrong.

Steps I took (for video and audio): 
1.  npm installed on video.js, recordrtc, and videojs.record.
2.  run browserify on videojs.record.js to create a bundle.js
3.  Included the bundle.js like so:
```
  <link href="http://vjs.zencdn.net/5.8.7/video-js.css" rel="stylesheet">
  <link href="node_modules/videojs-record/src/css/videojs.record.css" rel="stylesheet">

  <script src="http://vjs.zencdn.net/5.8.7/video.min.js"></script>
  <script src="https://webrtcexperiment-webrtc.netdna-ssl.com/RecordRTC.js"></script>

  <script src="bundle.js"></script>
```

4.  I put all of this into MAMP, and started MAMP server.

I then got an error saying: 
VIDEOJS: ERROR: Unable to find plugin: record

I copied and pasted the example that you provided for the html file.

How would I approach this problem?

Thanks in advance.

**Comment by thijstriemstra** [comment]
@atsuzu can you paste the contents of the bundle in a gist (https://gist.github.com/) or something so we can take a look?

**Comment by atsuzu** [comment]
@thijstriemstra  Sure thing!  I used MAMP to load my website on localhost and worked without problem without using browserify.  So I think the setup should be fine.  The bundle.js is crazy long but here it is.  :)

https://gist.github.com/atsuzu/78a88892551c0b64eba82ea36778e5cb

**Comment by thijstriemstra** [comment]
Hmm the videojs-record code is in there.. Can you try implementing the steps you took into a grunt file (using something like https://github.com/jmreidy/grunt-browserify) so we can add this to the videojs-record grunt file for testing?

**Comment by atsuzu** [comment]
I've never actually used grunt before, and so it might take a while to add the testing.  However, I can explain step by step what I did on here though if that's okay?

**Comment by thijstriemstra** [comment]
I suppose that's ok but it might take longer to debug this.

**Comment by thijstriemstra** [comment]
@atsuzu here's a good example: https://github.com/jmreidy/grunt-browserify/tree/master/examples/basic

**Comment by atsuzu** [comment]
Thanks,

Step 1:
Download  and install MAMP

Step 2:
put index.html in MAMP/htdocs directory.

Step 3:
npm install video.js
npm install recordrtc
npm install videojs-record

Step 4: 
Create a main.js with just the following content:
`var videojsrecord = require("videojs-record");`

Step 5:
browserify main.js > bundle.js

Step 6:
Start server with MAMP

Step 7:
Go to localhost:8888

Step 8:
When you inspect element on chrome, within the console section you will see the 
`VIDEOJS: ERROR: Unable to find plugin: record`

So after installing all of the files, you would have within the MAMP/htdoc directory:
index.html
main.js
bundle.js
/node_modules/recordrtc
/node_modules/video.js
/node_modules/videojs-record

**Comment by atsuzu** [comment]
@thijstriemstra Thanks, I'll go through and will try to create the grunt file as soon as I can.  :)

**Comment by thijstriemstra** [comment]
> Step 4:
Create a main.js with just the following content:
var videojsrecord = require("videojs-record");

I would probably try this instead:

```javascript
var videojs = require("videojs"); // or require("video.js")
var player = videojs("myVideo",
{
    // video.js options
    controls: true,
    loop: false,
    width: 320,
    height: 240,
    plugins: {
        // videojs-record plugin options
        record: {
            image: false,
            audio: false,
            video: true,
            maxLength: 5,
            debug: true
        }
    }
});
```

**Comment by atsuzu** [comment]
So I took that portion out of the index.html and inserted it in main.js.  
I then get the following issue:

`video.min.js:22 Uncaught TypeError: The element or ID supplied is not valid. (videojs)`
and
`VIDEOJS: ERROR: Unable to find plugin: record`

**Comment by thijstriemstra** [comment]
@atsuzu looks like there's not a video element on your page? See https://github.com/collab-project/videojs-record/blob/master/examples/video-only.html#L25.

**Comment by atsuzu** [comment]
That's odd... I see the video tag on my index.html

https://gist.github.com/atsuzu/988e8e1251157ec9e3764aa08935bc1e#file-index-html-L25

**Comment by thijstriemstra** [comment]
@atsuzu right but the script etc is still there (https://gist.github.com/atsuzu/988e8e1251157ec9e3764aa08935bc1e#file-index-html-L27)? Move everything inside <script> to your main.js.

**Comment by atsuzu** [comment]
@thijstriemstra yes you're right.  I must have misunderstood how browserify worked with this.
So I updated the files with the script contents moved to move.js, and I regenerated the files using browserify main.js > bundle.js
Now I get just this error:
`Uncaught TypeError: The element or ID supplied is not valid. (videojs)`

**Comment by atsuzu** [comment]
@thijstriemstra Actually, I think I got it to work.
I had to do two things.
1.  Move the bundle.js include to the bottom of the index.html
2.  
```
<script src="http://vjs.zencdn.net/5.8.7/video.min.js"></script>
<script src="https://webrtcexperiment-webrtc.netdna-ssl.com/RecordRTC.js"></script>
```
These two files were not included by the bundle.

So after adding those two changes, the recorder was able to successfully record! 
Thank you very much!! :)

**Comment by thijstriemstra** [comment]
That's good to hear @atsuzu. I've created a wiki (https://github.com/collab-project/videojs-record/wiki) and it would be cool if you could these instructions to a new browserify wiki page so it can help @Technopathic etc.

**Comment by atsuzu** [comment]
@thijstriemstra Done.  I hope it helps :)

**Comment by thijstriemstra** [comment]
@atsuzu thanks, ive added some links and cleanup to the page, closing this ticket, please refer to that page @Technopathic.

**Comment by alsar** [comment]
@atsuzu @Technopathic @thijstriemstra 

I've read the wiki: https://github.com/collab-project/videojs-record/wiki/Browserify
You don't need to include `video.min.js`. But you have to include `https://webrtcexperiment-webrtc.netdna-ssl.com/RecordRTC.js` as it does not support Browserify.

So in your index.html at the end of the body tag you just have to add:

```html
<script src="https://webrtcexperiment-webrtc.netdna-ssl.com/RecordRTC.js"></script>
<script src="bundle.js"></script>
```

In your main.js you add:

```js

        videojs = require('video.js');
        require('videojs-record');

        var player = videojs("myVideo", {
                controls: true,
                loop: false,
                width: 320,
                height: 240,
                plugins: {
                    record: {
                        image: false,
                        audio: true,
                        video: true,
                        maxLength: 5,
                        debug: true
                    }
                }
            });

```

This works for me. I hope it helps.

**Comment by thijstriemstra** [comment]
Thanks for the feedback @alsar, feel free to update the wiki page ;)
