### ISSUE TITLE
Record Camera and Screen into Single WebM. 

### ISSUE THREAD

**Issue by shivakantshukla55** [collab-project/videojs-record#680]
## Description
How to record camera video and screen in single webM. This feature is provided by recordRTC but my question is how to use it with videojs-record plugin? I am using it in React framework.

## Expected output 
just like this demo from recordRTC: [demo](https://www.webrtc-experiment.com/RecordRTC/simple-demos/video-plus-screen-recording.html)

## Additional Information
I am using videojs version 8.0.4

**Comment by thijstriemstra** [comment]
This is not supported at the moment.

**Comment by thijstriemstra** [comment]
marking as duplicate of #428
