### ISSUE TITLE
Not able to enable Portrait Mode 

### ISSUE THREAD

**Issue by aliumair-CD** [collab-project/videojs-record#696]
## Description
Is there any way to enable portrait mode using videojs-record
## Steps to reproduce
I was using aspect ratio to make it enable portrait mode by implement aspect ratio as 9:16 
### But code was not working in chrome on Android and IOs
Please describe what you expected to see.

### Actual
But code was not working in chrome on Android and IOs
### Error output
Errors come on screen when I rotate my screen and press record button

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
what browser(s) are affected? Make sure to test with all third-party browser **extensions disabled**.
#### OSes
what platforms (operating systems and devices) are affected?

**Comment by thijstriemstra** [comment]
Always include code snippets and the version information in a bug report.
