### ISSUE TITLE
ffmpeg.wasm plugin needs upgrading to 0.12+

### ISSUE THREAD

**Issue by michi88** [collab-project/videojs-record#697]
## Description
The API has changed from 0.12+. Examples are also not working as it uses the latest ffmpeg version (`//unpkg.com/@ffmpeg/core/dist/ffmpeg-core.js` results in `Cannot find "/dist/ffmpeg-core.js" in @ffmpeg/core@0.12.3`) .

see: https://ffmpegwasm.netlify.app/docs/migration

## Steps to reproduce
https://collab-project.github.io/videojs-record/demo/video-only-ffmpegwasm.html

### Error output
ReferenceError: FFmpeg is not defined

Let me know if you'd like a PR.

Thanks for your work on the plugin!

**Comment by dparker2** [comment]
Various demos simply do not work because of using latest unpkg links.

**Comment by thijstriemstra** [comment]
> Various demos simply do not work because of using latest unpkg links. Audio specific ones using wavesurfer has the same issue

I'll take a look at it.
