### ISSUE TITLE
Can't record mp4 file on Google Chrome.

### ISSUE THREAD

**Issue by gavinhar** [collab-project/videojs-record#699]
## Description

I cannot record a video in h264 format on Google Chrome.

## Steps to reproduce

Use these options to record a video on Google Chrome

```
let options = {
    // video.js options
    controls: true,
    controlBar: {
	// hide fullscreen and volume controls
	fullscreenToggle: false,
	volumePanel: false,
    },
    
    loop: false,
    fluid: false,
    width: 320,
    height: 240,
    plugins: {
	// videojs-record plugin options
	record: {
		videoMimeType: 'video/webm;codecs=h264',

		image: false,
		audio: true,
		video: true,
		maxLength: 60,
		displayMilliseconds: false,
		debug: true,
	},
    },
};
```

Console logs will show "video/x-matroska;codecs=avc1,opus -> 117 KB" or similar.

### Expected

"video/x-matroska;codecs=h265,aac" or similar and video output in webm/h264 format.

### Actual

Console logs will show "video/x-matroska;codecs=avc1,opus -> 117 KB" or similar.  And output is in mkv format.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:

videojs 8.6.0
videojs-record 4.6.0

macOS 14.0

Chrome 118.0.5993.70

Using `videoMimeType: 'video/webm;codecs=vp8'` works as expected

**Comment by thijstriemstra** [comment]
It depends on the formats your browser supports. Can you run this and paste or screenshot the output here?

```js
const types = [
  "video/webm",
  "audio/webm",
  "video/webm;codecs=vp8",
  "video/webm;codecs=daala",
  "video/webm;codecs=h264",
  "video/x-matroska;codecs=h265,aac",
  "audio/webm;codecs=opus",
  "video/mpeg",
];

for (const type of types) {
  console.log(
    `Is ${type} supported? ${
      MediaRecorder.isTypeSupported(type) ? "Maybe!" : "Nope :("
    }`,
  );
}
```
