### ISSUE TITLE
Demos using wavesurfer error with 404

### ISSUE THREAD

**Issue by dparker2** [collab-project/videojs-record#703]
## Description

The demos linked in the docs that use the wavesurfer package do not work, such as this one: https://collab-project.github.io/videojs-record/demo/enumerate-devices.html

In the console, there is an error showing a 404 when fetching `https://unpkg.com/wavesurfer.js@7.7.2/dist/plugin/wavesurfer.microphone.min.js`.

## Steps to reproduce
1. Go to https://collab-project.github.io/videojs-record/demo/enumerate-devices.html
2. See the error in console
3. Notice the demo does not work

### Expected
Demo should work

### Actual
Demo does not work

### Error output
```
GET https://unpkg.com/wavesurfer.js@7.7.2/dist/plugin/wavesurfer.microphone.min.js net::ERR_ABORTED 404 (Not Found)
enumerate-devices.html:57 Uncaught TypeError: Cannot read properties of undefined (reading 'create')
    at enumerate-devices.html:57:39
```

**Comment by thijstriemstra** [comment]
thanks, for the report, should be fixed now.
