### ISSUE TITLE
how to save video in php

### ISSUE THREAD

**Issue by sabardotnet** [collab-project/videojs-record#72]
console.log('finished recording: ', player.recordedData);

how to save player.recordedData in php ?

**Comment by thijstriemstra** [comment]
@sabardotnet this is in the documentation: "Check the [jquery.fileupload](https://github.com/collab-project/videojs-record/blob/master/examples/upload/jquery.fileupload.html) or [Fine Uploader](https://github.com/collab-project/videojs-record/blob/master/examples/upload/fine-uploader.html)
examples on how to upload the data to a server."
