### ISSUE TITLE
Is there a way to clear the recorded video and restart the player?

### ISSUE THREAD

**Issue by jimklo** [collab-project/videojs-record#73]
Is there a way to reset the video recorder and restart after the user has recorded a video?

**Comment by thijstriemstra** [comment]
No not yet, PR welcome!

**Comment by thijstriemstra** [comment]
@jimklo I've added a `reset` method, please give it a try. Closing this ticket, but add your feedback here and I'll reopen it if necessary.

**Comment by ignl** [comment]
I was wondering about the same. For some reason reset didn't work for me, but after some search I found this ticket and saw that it was closed only few days ago so figured my npm install is too old and  just downloaded from github and now it works fine. Thanks and great job!

**Comment by thijstriemstra** [comment]
@ignl thanks for letting me know, I'll push a new release this week.
