### ISSUE TITLE
Loading previously recorded video from Base64 value?

### ISSUE THREAD

**Issue by AdamHess** [collab-project/videojs-record#74]
Is there a way to load in base64 encoded video and then record over it? 

I'd like a user to be able to land on the page, view what they recorded for this page in the past and then record over it. 

 I can get the record over it part down, but I can't quite load in their video again. 

I tried 

```
<video> 
    <source src="{{Base64DataHere}}"> 
</video>
```

But I get an error because it tries to load in from the source rather than webcam when trying to initialize recording device.

**Comment by thijstriemstra** [comment]
@AdamHess you should convert your base64 data and create a new Javascript Blob file. Take that Blob's URL and create an instance programmatically.

```javascript
$('body').append('<video id="myVideo" class="video-js vjs-default-skin"></video>');

var player = videojs("myVideo",
{
    controls: true,
    width: 320,
    height: 240,
    controlBar: {
        volumeMenuButton: false
    }
});

player.on('ready', function(){
    player.src(myBlobURL);
    player.play();
});
```
