### ISSUE TITLE
Empty record data on chrome

### ISSUE THREAD

**Issue by adrianug** [collab-project/videojs-record#75]
I following this simple step to recording my video 

JS 
```js
var player = videojs('video', {
    controls: true,
    loop: false,
    width: 334,
    height: 251,
    plugins: {
        record: {
            audio: true,
            video: true,
            maxLength: 60,
            debug: false
        }
    }
});

player.on('deviceError', function()
{
    console.log('device error:', player.deviceErrorCode);
});

player.on('startRecord', function()
{
    console.log('started recording!');
});

player.on('finishRecord', function()
{
    var data = new FormData();

    data.append('video-filename', 'video-filename.webm');
    data.append('video-blob', player.recordedData);

    console.log(data);
    console.log(player.recordedData);

    $.ajax({
        type: 'POST',
        url: '/api/upload/video',
        data: data,
        dataType: 'json',
        processData: false,
        contentType: false
    }).done(function(data) {
        if (data.code == 200) {
            return window.location.href = '/share'
        };

        console.log(data);
    });
});
```

Work fine in firefox, but has empty data in chrome. . 

![image](https://cloud.githubusercontent.com/assets/17444732/15291675/54e76a52-1ba9-11e6-8d4b-29f7de4346f7.png)

![image](https://cloud.githubusercontent.com/assets/17444732/15292125/c1d9f286-1bab-11e6-8a47-0cde16ee06b7.png)

So, what did i miss ?

Chrome 50.0.2661.102
Firefox 46.0.1
Latest version of RecordRTC.js & videojs.record.js

**Comment by adrianug** [comment]
Test using blob

```js
var blob = new Blob([player.recordedData]);
``` 

![image](https://cloud.githubusercontent.com/assets/17444732/15297064/7d316896-1bc2-11e6-823a-331e9fa81df7.png)

`console.log(blob.size);` = 15

And sure, working fine in firefox

**Comment by thijstriemstra** [comment]
@adrianug in older versions of the Chrome browser you would need to use recordedData.audio and recordedData.video and stitch these 2 blobs together on the server-side using something like FFmpeg. With recent Chrome browsers >= 49 (inc. the one you're using) a single blob is created and stored into `recordedData`. What is the `Video field is required`?

**Comment by thijstriemstra** [comment]
Also, before uploading etc, can you reproduce this issue with the simplest example, eg. https://collab-project.github.io/videojs-record/examples/audio-video.html?

**Comment by adrianug** [comment]
`Video field is required` is response from ajax post because when post from chrome, `$_FILES` is empty

Both firefox and chrome has correct data in `blob:https%3A//site.com/4ec97744-994a-4f5e-8c1b-a9fd3ecfa8d8`

But, when i try using `new FormData();` to post data with ajax, `player.recordedData` is missing in chrome

```js
var data = new FormData();
data.append('video-filename', 'video-filename.webm');
data.append('video-blob', player.recordedData);
```
And wrong size when using `new Blob();`

```js
var blob = new Blob([player.recordedData]);
console.log(blob.size);
```

Sadly, everything works fine in firefox

**Comment by ncaneldiee** [comment]
Solved with `new Blob([player.recordedData.video], { type: 'video/webm' });` in chrome and `new Blob([player.recordedData], { type: 'video/webm' });` in firefox

**Comment by adrianug** [comment]
Solved with `new Blob([player.recordedData.video], { type: 'video/webm' });` in chrome and `new Blob([player.recordedData], { type: 'video/webm' });` in firefox

**Comment by thijstriemstra** [comment]
> Still, i dont understand why different, player.recordedData.video in chrome and just player.recordedData in firefox

It's something (left over) from RecordRTC.js, take a look at that source code if you really want to know ;)
