### ISSUE TITLE
Can options be changed dynamically?

### ISSUE THREAD

**Issue by jyounger** [collab-project/videojs-record#76]
Can options be changed dynamically? For example, can I turn audio off with javascript and then record video only? Or, can I choose a different width and height?

Thanks! Already using videos-record. It's quite good.

**Comment by thijstriemstra** [comment]
@jyounger #73 proposes a similar thing, I was thinking of a `reset` method there, but what you're proposing also depends on having that functionality present in recordrtc and wavesurfer.js. If you could take a look at these libraries and manage to change their options on the fly in an example, let me know,  and technically we should be able to do it in videojs-record as well.

**Comment by thijstriemstra** [comment]
@jyounger I added a new `loadOptions` in https://github.com/collab-project/videojs-record/commit/3426e600db26e1a139c3d963e87be6543512da09#diff-493b5c61507553acbf7af34be47e0c3cR367. You can try to override these settings and call it `loadOptions` again (and any other methods like `load` after that) and see what happens.. I haven't tested it yet.

**Comment by jyounger** [comment]
Thanks! I'll test it today and post the results.

**Comment by thijstriemstra** [comment]
@jyounger any news?

**Comment by thijstriemstra** [comment]
Closing, no feedback, please open a new ticket if something's not working.

**Comment by kimhongn89** [comment]
hi @thijstriemstra,
what function can i call after call loadOptions().
it looks like load() function is not appropriate

**Comment by tomasdev** [comment]
@kimhongn89 it should be `.getDevice()`

**Comment by thijstriemstra** [comment]
It's possible to specify new options since 2.3.2:

```javascript
player.record().loadOptions({
  video: {
    facingMode: 'environment'
  }
});
```
