### ISSUE TITLE
Need way to control bitrate of video.

### ISSUE THREAD

**Issue by AdamHess** [collab-project/videojs-record#77]
frameWidth and Height do not control the video quality recorded. 

recordRTC seems to indicate the bitrate should be 60kbs/s but with my hardware/configuration it a 3 second clip is closer to 130kbs leading to HUGE files for 20-30seconds of recording.

**Comment by thijstriemstra** [comment]
@AdamHess can you show the player and plugin configuration?

**Comment by thijstriemstra** [comment]
No feedback, closing.

**Comment by vrajroham** [comment]
@thijstriemstra Same question again! Can I change video bitrate of underlying RecordRTC library so that it will help to reduce the video size. 

I don't have example but you can see example here. https://www.webrtc-experiment.com/RecordRTC/
