### ISSUE TITLE
Recording video then changing source

### ISSUE THREAD

**Issue by maxpaj** [collab-project/videojs-record#78]
Hi,

I'm having a little bit of trouble with first recording a video then playing another video by changing the source of the player. First, the duration display when playing the second video doesn't work. Second, when that video is done playing, the play button plays the first recorded video again. I think the expected behaviour is that the second video should play again.

Is there any way to work around this?

**Comment by thijstriemstra** [comment]
@maxpaj I suggest you use a separate video.js player for playback.
