### ISSUE TITLE
Handle rear/front camera

### ISSUE THREAD

**Issue by abhaydas78** [collab-project/videojs-record#79]
## Description
How to handle rear and front camera?

**Comment by abhaydas78** [comment]
Can anyone help here???

**Comment by thijstriemstra** [comment]
This is an opensource project and asking questions that way is perceived rude. You could also simply google it: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Front_and_back_camera

**Comment by abhaydas78** [comment]
Hi Thijstriemstra...my apologies. Didn't wanted to be rude. What I wanted to know was, how to set these constraints in the player initialization?

Regards,
Abhay

**Comment by thijstriemstra** [comment]
I haven't tested it but from the link I posted it seems this should do it:

```javascript
var constraints = { video: { facingMode: (front? "user" : "environment") } };
```
