### ISSUE TITLE
Compress wave audio using Libvorbis 

### ISSUE THREAD

**Issue by v3ss0n** [collab-project/videojs-record#8]
Wav is very big.
Before we discovered videojs , we implemented compression of wav using http://garciat.com/libvorbis.js/ inside browser. It works very well. 
Now we are using  videojs-record due to it records both video and audio at the same time . But sizes of audio is huge and looking a way to compress it using libvorbis. Libvorbis compress stream directly.
http://garciat.com/libvorbis.js/demos/microphone-recorder.html
Can you give us some guide where to look? We will contribute.

**Comment by thijstriemstra** [comment]
This sounds like a really good idea. I'm on a holiday now so I won't be able to help you now but next week I'll try to get back to you.

**Comment by v3ss0n** [comment]
Ok i will find a way in the mean time.

**Comment by v3ss0n** [comment]
this is not enabled yet right? tested and record in wav.

**Comment by thijstriemstra** [comment]
It's not enabled yet, adding some settings for that now. With current master you have to make sure to place the js libs at these paths: https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L140

And enable the libvorbis engine here: https://github.com/collab-project/videojs-record/blob/master/src/js/videojs.record.js#L439

Thanks for testing!

**Comment by v3ss0n** [comment]
ok , going to try that out

**Comment by thijstriemstra** [comment]
There's a demo now (https://github.com/collab-project/videojs-record/blob/master/examples/audio-only-ogg.html) but the worker path is still hardcoded, will add a setting for that later today. I'll close this ticket when all is done.

**Comment by v3ss0n** [comment]
that is so awesome. thanks alot.

**Comment by v3ss0n** [comment]
testing soon

**Comment by thijstriemstra** [comment]
@v3ss0n everything should be in place now, if you see any issues, open a new ticket, thanks.

**Comment by v3ss0n** [comment]
Audio recording example in Audio Only works!
But at Audi-video example isChrome is become null and trows error. Forces setting isChrome to True but
that makes it not showing video, it cant get videoblob url 
`Request URL:http://localhost:8000/examples/null
Request Method:GET
Status Code:404 File not found`

**Comment by v3ss0n** [comment]
ok creating issue
