### ISSUE TITLE
Getting error while uploading the recorded file. using script in examples.

### ISSUE THREAD

**Issue by achyuth8121** [collab-project/videojs-record#80]
## Description
File Upload not working

## Results
jquery.min.js:5 POST http://localhost/jQuery-File-Upload/server/php/ 404 (Not Found)
### Expected
Need to upload the recorded file to a path.

### Actual
Getting below errors.
1) jquery.min.js:5 POST http://localhost/jQuery-File-Upload/server/php/ 404 (Not Found)
2) undefined:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

### Error output
1) jquery.min.js:5 POST http://localhost/jQuery-File-Upload/server/php/ 404 (Not Found)
2) undefined:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
I have tried in chrome
#### OSes
On mac OS

**Comment by achyuth8121** [comment]
Please help me on how to fix this.

**Comment by thijstriemstra** [comment]
This is a jQuery-File-Upload related issue, please ask for help there. Here's the documentation for the basic PHP setup I used: https://github.com/blueimp/jQuery-File-Upload/wiki/Setup#using-jquery-file-upload-ui-version-on-php-websites
