### ISSUE TITLE
Videos generated are not playing second time in FireFox untill refresh

### ISSUE THREAD

**Issue by achyuth8121** [collab-project/videojs-record#81]
## Description
Videos generated are not playing second time in FireFox untill refresh
## Steps to reproduce
Record a video and save in some path, now in added the src for video tag and tried to play the video. For the very first time the video played good and when we try to replay clicking the play button it does not play and buffer circle was shown.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with?
#### browsers
FireFox
#### OSes
Mac OS

**Comment by thijstriemstra** [comment]
@achyuth8121 can you show me an example that reproduces this issue? Also include the Firefox and OSX versions please.

**Comment by achyuth8121** [comment]
Fireofx version : 47.0.1
Mac OSX Version 10.9.5

Attached is the sample audio-video recorded file.
[SampleGeneratedVideo.zip](https://github.com/collab-project/videojs-record/files/363973/SampleGeneratedVideo.zip)


Below is the code i am using for playing the recorded video. (We need to specify the path of the video saved in src).

<video  id='videoPlayer' width="320" height="240" controls >
	<source src="" type="video/webm"/>
</video>


I have attached a screen shot of the buffering circle.

![screen shot 2016-07-14 at 19 52 12](https://cloud.githubusercontent.com/assets/20276210/16842833/8051b630-49fc-11e6-84cd-610414815ba0.png)

Thanks in Advance.

**Comment by ignl** [comment]
Yes I have this problem too. Once webm is saved and then served in src of video tag, Firefox for some reason cannot replay it. I tried same setup with another webm sample and it was working, so something is wrong with recorded webm. This is reproducible on https://www.webrtc-experiment.com/RecordRTC/ (once recorded and in another tab video will play only once), so this is RecordRTC problem and not videojs-record related.

**Comment by ignl** [comment]
Created ticket in recordrtc, I think this ticket can be closed: https://github.com/muaz-khan/RecordRTC/issues/145

**Comment by ignl** [comment]
This issue is now solved on Firefox 48

**Comment by thijstriemstra** [comment]
Thanks for update. Any reference to ticket,/changeset for that?

**Comment by ignl** [comment]
This one I think:
https://bugzilla.mozilla.org/show_bug.cgi?id=657791

**Comment by thijstriemstra** [comment]
@ignl would be good to have a table in the documentation describing known and fixed issues per browser like this one.. ;)

**Comment by ignl** [comment]
Maybe it's better to move documentation to the wiki as it's easier for anyone to add notes etc?

**Comment by thijstriemstra** [comment]
@ignl with github you can edit repository files just as editing a wiki page.

**Comment by ignl** [comment]
Yeah I don't have much experience with that but as I understand I fork whole repo then need to create pull request or smth like that? Too complex for a few lines of documentation change. Wiki is better for that :)

**Comment by thijstriemstra** [comment]
@ignl no, you browse to the file you want to edit and then press the 'edit' button and inside the browser you can make edit the document. Press save and it will make a fork and PR for you.

**Comment by ignl** [comment]
OK
