### ISSUE TITLE
Video recording not working on chrome/firefox on iPad

### ISSUE THREAD

**Issue by achyuth8121** [collab-project/videojs-record#82]
## Description
Video recording not working on chrome/firefox on iPad

## Steps to reproduce
Open below link and try to record video on iPad and it wont let me record the video
https://collab-project.github.io/videojs-record/examples/audio-video.html

### Expected
Should record the video on iPad and ios devices

### Actual
Video recording not working on iPad

#### videojs
what version of videojs does this occur with?
#### browsers
Latest firefox and chrome
#### OSes
iOs 9.3.2

**Comment by achyuth8121** [comment]
Thanks in Advance. :(

**Comment by ignl** [comment]
If I am not mistaken apple forces everyone to use webkit on mobile devices so all the browsers are basically the same and webm and recording is not supported by apple webkit.

**Comment by thijstriemstra** [comment]
Is it possible to get the console output, curious what error it's throwing. But like @ignl said, it's not supported on any iPad/iOS browser at the moment (see http://iswebrtcreadyyet.com). You can track it's progress here: https://bugs.webkit.org/show_bug.cgi?id=124288. So it's a known issue I can't work around unfortunately.

**Comment by tomasdev** [comment]
It should be working now, right?

**Comment by thijstriemstra** [comment]
@tomasdev yes, safari is problematic though.
