### ISSUE TITLE
Firefox: the media playback was aborted due to corruption problem

### ISSUE THREAD

**Issue by ignl** [collab-project/videojs-record#83]
## Description
Trying to record with firefox results in: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support"

## Steps to reproduce
I can reproduce this on: https://collab-project.github.io/videojs-record/examples/audio-video.html with Firefox (Chrome is fine). This one: https://simpl.info/mediarecorder/ works. My project which uses newest version of libs also has this problem, however it worked sometimes before (it was unpredictable).

## Additional Information
Please include any additional information necessary here. Including the following:
"recordrtc": "^5.3.8",
"video.js": "^5.10.4",
"videojs-record": "^1.4.0"

#### browsers
Firefox 47.0

#### OSes
Windows 10

**Comment by ignl** [comment]
Ok after computer (firefox only was not enough) restart example seems to be working. However I can still reproduce it by pressing record, then stop, then play, then record again (while play haven't finished yet) then stop. Yesterday I was getting error every single record, but it was probably because I was testing my app and was doing a lot of different tests on recording on firefox and after a while it just stopped working at all (including example). Maybe this reproducible error will give some hints because error is identical and chrome does not have it.

**Comment by thijstriemstra** [comment]
I suspect it's a RecordRTC issue. Do you have a stacktrace of the error?

**Comment by ignl** [comment]
It's reproducible on https://collab-project.github.io/videojs-record/examples/audio-video.html with action sequence I described. After a lot of tests today firefox recording stopped working again for me. Error is the same as in reproducible example: "The media playback was aborted due to a corruption problem or because the media used features your browser did not support". Maybe they are related. I don't see any javascript errors in console.

**Comment by thijstriemstra** [comment]
@ignl you have time to test PR #90?

**Comment by ignl** [comment]
Ok I will check it tomorrow.

**Comment by ignl** [comment]
OK I didn't test PR because I could not reproduce it on example page anymore. Also I have updated my project versions of video.js and recordrtc (to 5.40 from 5.38) and could not also reproduce it. However on my project it was rather unpredictable so will have to do some more tests but right now it seems that newer versions fixed the problem. Oh and also updated firefox to 48.02. So I am not sure what exactly fixed it.
