### ISSUE TITLE
The end of the video is cut if recording until auto stop

### ISSUE THREAD

**Issue by ignl** [collab-project/videojs-record#84]
## Description
Record for all allowed time. Very tiny amount of the video at the end is cut off. Maybe a second or even less. On my project for a 15s video sometimes almost 2s.

## Steps to reproduce
It is visible on the example (audio/video). When replaying recorded video it stops at 9s (not sure if always but I get that). 

## Additional Information
Both chrome and firefox seems to be affected.

**Comment by thijstriemstra** [comment]
@ignl can you reproduce this with a pure RecordRTC-only example?

**Comment by ignl** [comment]
This is more like a countdown issue. In webrtc sample you have to manually stop recording (https://www.webrtc-experiment.com/RecordRTC/) which works ok for chrome (and cuts a lot maybe 2-3s for firefox). Videojs-record seems to work ok for me when you stop manually however using countdown it seems to stop just a liiittttle bit too early. It's subtle but noticeable.

**Comment by thijstriemstra** [comment]
Maybe https://github.com/videojs/video.js/issues/3369 is also related.

**Comment by ignl** [comment]
Yeah it's very likely. It also seems that it is OK now after I updated to new version of video.js. Ticket is not closed but maybe they already solved that problem.

**Comment by thijstriemstra** [comment]
@ignl what version of video.js are you using now?
