### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by canpoyrazoglu** [collab-project/videojs-record#85]
I am considering to use the library, and I've tried to fire up the demo. (tried both audio and audio + video). All I'm getting is this:

<img width="340" alt="screen shot 2016-08-02 at 12 12 08" src="https://cloud.githubusercontent.com/assets/4348413/17323318/6435422a-58aa-11e6-85bc-342c8cb9676b.png">

I can click it but nothing happens. Why? (I am on Safari 9.1.2)

**Comment by ignl** [comment]
Safari does not support video recording.

**Comment by thijstriemstra** [comment]
@ignl is right, if you open the web inspector or console in the browser you'll see an error message because Safari doesn't support it.

**Comment by httpamit** [comment]
I have same issue. Can we provide support for Safari Browser using flash?

**Comment by thijstriemstra** [comment]
see #106 for the flash question.
