### ISSUE TITLE
How to stop the recording from JS and get the recorder data?

### ISSUE THREAD

**Issue by THPubs** [collab-project/videojs-record#86]
I tried to call the `stop` and the `deviceStop` functions. It does stop the recording but if I try to get the recorded data like this `player.recordedData` it returns undefined. Any idea how to fix this?

**Comment by thijstriemstra** [comment]
@THPubs see https://github.com/collab-project/videojs-record#get-recorded-data

**Comment by THPubs** [comment]
@thijstriemstra Thanks. But if I try to stop the recording using js functions like `player.recorder.stop()`, The `player.on('finishRecord', function()` won't fire and `player.recordedData` returns undefined.

**Comment by thijstriemstra** [comment]
@THPubs can you paste your code on a https://gist.github.com?

**Comment by THPubs** [comment]
Sure. Here's how I initiate the player :

    const videoBoxWidth = $('#video-box').width()
    const videoBoxHeight = videoBoxWidth * 0.5625

    const player = videojs("myVideo",
      {
        // video.js options
        controls: true,
        loop: false,
        width: videoBoxWidth,
        height: videoBoxHeight,
        plugins: {
        // videojs-record plugin options
          record: {
            image: false,
            audio: false,
            video: true,
            maxLength: 5,
            debug: true
          }
        }
      }
    );

    player.on('stopRecord', () => {
      console.log('finished recording: ', player.recordedData);
    });

Then I tried to run the above mentioned functions from the console and they didn't fire the `stopRecord` event. I tried to run `player.recordedData` in the console and it also returns undefined.

**Comment by THPubs** [comment]
@thijstriemstra Very sorry! I just fixed the issue! Looks like I'm not starting the recording. You have to click the record button twice :-)

**Comment by thijstriemstra** [comment]
Yes clicking the player starts the camera/microphone. Use `getDevice` to do this programatically.

**Comment by THPubs** [comment]
Perfect thanks!

**Comment by pixelpointtechnology** [comment]
hey I want to use facingMode in record parameter
