### ISSUE TITLE
Having problem getting the recorded data from the demo

### ISSUE THREAD

**Issue by kelvinblade** [collab-project/videojs-record#87]
I tried the demo online and I also tried it locally. 

Video shows, press records, it starts. 

When it ends, I get Stopped recording video stream RecordRTC.js:100 but it doesn't seem to be firing console.log('finished recording: ', player.recordedData);

I am using chrome 52 on a macbook air.

i am using this demo:
https://github.com/collab-project/videojs-record/blob/master/examples/audio-video.html

i am having the same problem using the example as well:
https://collab-project.github.io/videojs-record/examples/audio-video.html

update:

i tried it on firefox and it worked both online and locally.
i tried to do audio: false and it worked on chrome.
i thought video/audio was support for chrome 47+?

**Comment by thijstriemstra** [comment]
@kelvinblade what version of video.js, wavesurfer.js and videojs-wavesurfer?

**Comment by kelvinblade** [comment]
i am using the cdn which is 5.8

i am not using wavesurfer.js and videojs-wavesurfer

**Comment by kelvinblade** [comment]
i am using this demo:
https://github.com/collab-project/videojs-record/blob/master/examples/audio-video.html

i am having the same problem using the example as well:
https://collab-project.github.io/videojs-record/examples/audio-video.html

**Comment by thijstriemstra** [comment]
I cannot reproduce this with Chrome/52.0.2743.116 on latest OSX. The event handler is called and creates a blob. When I save that blob and use ffmpeg's `ffprobe` tool it shows both audio and video:

```
Input #0, matroska,webm, from '/Users/foo/Downloads/bar.webm':
  Metadata:
    encoder         : Chrome
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Audio: opus, 48000 Hz, mono, fltp (default)
    Stream #0:1(eng): Video: vp8, yuv420p, 640x480, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
```

**Comment by thijstriemstra** [comment]
Closing due to lack of feedback.
