### ISSUE TITLE
Unable to run example audio-video.html locally

### ISSUE THREAD

**Issue by chirag-jog** [collab-project/videojs-record#89]
## Description
I am trying to run the audio-video.html on my local macbook. I get the following error:

`Not allowed to load local resource: blob:null/87fe6221-142a-4f82-af80-b97a8a44839b
video.min.js:20 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. i {code: 4, message: "The media could not be loaded, either because the …rk failed or because the format is not supported."}e @ video.min.js:20h.error @ video.min.js:20b.error @ video.min.js:17b.handleTechError_ @ video.min.js:17e @ video.min.js:20e @ video.min.js:20d.dispatcher.d.dispatcher @ video.min.js:20`
## Steps to reproduce
Cloned the videojs-record
used bower to resolve all dependencies
fixed the js/css references in the audio-video.html file
Load the html file in the browser

### Expected
Expected the audio-video.html file to work as the actual hosted example (which works fine!).
### Actual.
As reported above

### Error output
As reported above
![screen shot 2016-09-07 at 3 42 01 pm](https://cloud.githubusercontent.com/assets/1052219/18308320/a6810938-7511-11e6-9788-bfaa44262bbb.png)

## Additional Information
Please include any additional information necessary here. Including the following:
#### OSes
what platforms (operating systems and devices) are affected?
OSX 10.11.6

**Comment by ignl** [comment]
Few ideas. Try to set breakpoint on player.on('finishRecord', function() and check what does player.recordedData return. Also do you have access to PC? Could you try to do same setup?
Btw is deployed version working fine for you?

**Comment by thijstriemstra** [comment]
getUserMedia stuff needs to be run from a webserver. Please reopen if you can reproduce this with a RecordRTC example.
