### ISSUE TITLE
Export sound wave as an image

### ISSUE THREAD

**Issue by sur3d** [collab-project/videojs-record#91]
Hi,

I love you project guys, it really helped my out!
I'd like to know if there is any way to export the recorded sound wave as an image

Thanks!

**Comment by thijstriemstra** [comment]
This sounds like a useful feature, I'll add one.

**Comment by sur3d** [comment]
Thanks so much!
I'd love to help, but I'm not quite exactly sure where to start from.
There is no render logic in video-record, right? As far as I understand it's all done in wavesurfer.
Do you have an idea/advice as per where to start?

**Comment by thijstriemstra** [comment]
@sur3d videojs-record uses videojs-wavesurfer for the waveform rendering. videojs-wavesurfer uses wavesurfer.js for the waveform rendering. I think videojs-wavesurfer needs an `exportImage` method that exports an image from the wavesurfer.js `canvas` that can be called in this plugin, videojs-record.

**Comment by thijstriemstra** [comment]
@sur3d I've opened https://github.com/katspaugh/wavesurfer.js/issues/822 as a starting point, feel free to open a PR there, anywhere.

**Comment by thijstriemstra** [comment]
Added `exportImage` to wavesurfer.js with https://github.com/katspaugh/wavesurfer.js/pull/823

**Comment by thijstriemstra** [comment]
Added `exportImage` to videojs-wavesurfer with https://github.com/collab-project/videojs-wavesurfer/commit/b0283c47d147e85e665a7a3029e48e129a196788 (in the upcoming 1.2.4 release).

**Comment by thijstriemstra** [comment]
@sur3d Update wavesurfer.js and videojs-wavesurfer and use the `exportImage` method from videojs-wavesurfer like this:

```javascript
var imageData = player.recorder.surfer.exportImage();
myImg.src = imageData;
```
