### ISSUE TITLE
Recorded video need in .mp4 format

### ISSUE THREAD

**Issue by Banwari1990** [collab-project/videojs-record#92]
Hi,

Is it possible to get the recorded video in to .mp4 format instead of .webm format.

Thanks.

**Comment by thijstriemstra** [comment]
There's [this solution](https://www.webrtc-experiment.com/ffmpeg/merging-wav-and-webm-into-mp4.html) using ffmpeg.js but that isn't optimal. But it also looks like, at least Firefox, can record as mp4, according to [this example](https://github.com/muaz-khan/RecordRTC#record-audiovideo-in-firefox). I just tested this in Firefox 49 on Ubuntu and it did create a mp4 file:

```
started recording video stream
Using recorderType: MediaStreamRecorder
Passing following config over MediaRecorder API. Object { type: "video", mimeType: "video/mp4", initCallback: null }
Initialized recorderType: MediaStreamRecorder for output-type: video
Stopped recording video stream
video/mp4 -> 5.25 MB
```
I'll add an option to change the mimeType.

**Comment by thijstriemstra** [comment]
Also tested on Chrome 54 / Ubuntu 16.04 and it also produced an MP4 file. ffprobe details:

```
Input #0, matroska,webm, from 'recordrtc-chrome54.mp4':
  Metadata:
    encoder         : Chrome
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Audio: opus, 48000 Hz, mono, fltp (default)
    Stream #0:1(eng): Video: vp8, yuv420p, 640x480, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 1k tbc (default)
```

Duration is not available it seems though.. but it plays in VLC.

**Comment by thijstriemstra** [comment]
This is probably on hold until https://github.com/muaz-khan/RecordRTC/issues/97 is resolved.

**Comment by thijstriemstra** [comment]
A full list of supported mime-types in Chrome is listed [here](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/fast/mediarecorder/MediaRecorder-isTypeSupported.html). Just tested the mime type `video/webm;codecs=H264` and it created a H264 clip. Output of ffprobe:

```
Input #0, matroska,webm, from 'index.mp4':
  Metadata:
    encoder         : Chrome
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: h264 (Constrained Baseline), yuv420p, 640x480, SAR 1:1 DAR 4:3, 30 fps, 30 tbr, 1k tbn, 2k tbc (default)
```

**Comment by thijstriemstra** [comment]
Added `audioMimeType` and `videoMimeType` settings for H264 support in next release.

**Comment by smakinson** [comment]
I've added:

`videoMimeType: 'video/webm;codecs=H264'`

under plugins.record. Is that all that is required? I haven't installed ffprobe, but should quicktime play the file I get from:

`player.record().saveAs({'video': 'my-video-file-name.mp4'})`

**Comment by thijstriemstra** [comment]
@smakinson should be enough, please open a new ticket if you see any issues.
