### ISSUE TITLE
Save as dialog

### ISSUE THREAD

**Issue by ConnectedReasoning** [collab-project/videojs-record#97]
## Description

I don't see any methods to save
## Steps to reproduce

navigate to video-only.html record and then stop
## Results

dfsdf
### Expected

I expect to find information necessary to save video
### Actual

There is no documentation about how to save video
### Error output

If there are any errors at all, please include them here.
## Additional Information

Nothing to add
### versions

Current
#### videojs

The current
#### browsers

Chrome
#### OSes

Mac

**Comment by thijstriemstra** [comment]
I guess you want to see a link where you can download the recorded video? You can also right-click the video and save it from there.

**Comment by thijstriemstra** [comment]
Closing because there's no further feedback.

**Comment by clavish** [comment]
I have similar question. How to save video? (not upload) When user stops recording then its able to click on "save to disk". Any ideas? Thank you!

**Comment by clavish** [comment]
I have similar question. How to save video? (not upload to server) When user stops recording then its able to click on "save to disk". Any ideas? Thank you!

**Comment by thijstriemstra** [comment]
@clavish remember it's already saved to disk in a temporary location.

That being said, use this to show a save as dialog when the user finished recording for example:

```javascript
// user completed recording and stream is available
player.on('finishRecord', function()
{
    player.recorder.engine.engine.save({
        // file extension will be automatically added
        video: 'video-file-name',
        // audio: 'audio-file-name'
    });
});
```
This is not a really nice API so I'll re-open this ticket and add something better.

**Comment by ConnectedReasoning** [comment]
I extended a sample to offer a download option. I will add to this soon

**Comment by clavish** [comment]
@thijstriemstra thank you, works great now :+1:

**Comment by thijstriemstra** [comment]
thanks for the feedback @clavish. In upcoming 1.6 it should be as simple as `player.recorder.saveAs(nameObj)`, see https://github.com/collab-project/videojs-record#save-data.

**Comment by aleksey-lav** [comment]
and how to saveAs already converted video by ffmpeg ?

**Comment by thijstriemstra** [comment]
> and how to saveAs already converted video by ffmpeg ?

Please open a new ticket with a specific request.
