### ISSUE TITLE
clicking on video returns a re

### ISSUE THREAD

**Issue by ConnectedReasoning** [collab-project/videojs-record#98]
## Description

Clickingon video returns error "ReferenceError() video.min.js 6359
## Steps to reproduce

run the site with simple node server. VideoOnly screen comes up with mic logo. Clicking on logo does not bring up video, only error message
### Expected

I expected to get a permision request to access video
### Actual

ReferenceError() video.min.js 6359
### Error output

ReferenceError() video.min.js 6359
## Additional Information

Please include any additional information necessary here. Including the following:
#### videojs

The latest as of oct 22 2016
#### browsers

unknown -client reported will update asap
#### OSes

unknown -client reported will update asap

**Comment by thijstriemstra** [comment]
@ConnectedReasoning can you use a non-minified version of video.js and report the stacktrace of this error? Can you reproduce this with the github example site?

**Comment by thijstriemstra** [comment]
@ConnectedReasoning any news? Please open a new ticket with instructions from my previous comment if it's still an issue.
