### ISSUE TITLE
Duration display showing incorrect values when switching between recording and watching video

### ISSUE THREAD

**Issue by maxpaj** [collab-project/videojs-record#99]
## Description
I've observed that the duration display is showing incorrect values when switching between recording video and watching video. 

## Steps to reproduce
First scenario:
1. Record video (record button)
2. Watch the video (auto plays) (duration displayed correctly)
3. Watch it again (play button)
The max duration is now displayed as "-:--:--". Towards the very end of the video the duration is displayed correctly again. Probably related to how duration metadata is missing from webm when recorded with RecordRTC? https://github.com/collab-project/videojs-record/issues/31

Second scenario:
1. Record video (record button)
2. Play a MP4 video using player.src = [{ type: "video/mp4", src: "source.mp4" }]
The max duration is correct, but the current time stops counting when it reaches the max duration of the recorded video. So if my recorded video is 5 seconds and the MP4 video is 15 seconds, when playing the MP4 the current time will get stuck at 5/15 seconds even though the video keeps playing.

### Expected
First scenario: Expected to see the actual recording max duration instead of "-:--:--"
Second scenario: Expected to see the actual current time instead of it getting stuck

### Actual
First scenario: I see "-:--:--" as max duration
Second scenario: I see time getting stuck at 5/15 seconds

## Additional Information
I've noticed that webm format files recorded with RecordRTC do not display the correct max duration no matter if they are recorded with videojs-record or played with videojs.
#### videojs
Video.js 5.11.9
#### videojs-record
videojs-record v1.5.0
#### browsers
Chrome Version 54.0.2840.87 m (64-bit)
#### OSes
Windows 10 64-bit

**Comment by thijstriemstra** [comment]
Thanks for this detailed report. It's a known issue and it should be fixed.

**Comment by thijstriemstra** [comment]
@maxpaj is this still an issue?

**Comment by maxpaj** [comment]
I think this may be fixed with the config
`videoMimeType: 'video/webm;codecs=vp9',`

**Comment by thijstriemstra** [comment]
Thanks for the feedback. if you could verify this, it would be very useful so we can close this one.

**Comment by maxpaj** [comment]
Yup, it's definitely working now. You can close it :)

**Comment by thijstriemstra** [comment]
Thx for the feedback.
